### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by samuela**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
@samuela Could you please sign the CLA?

**Comment by samuela** [comment]
@meteorcloudy signed!

**Comment by meteorcloudy** [comment]
@samuela Thanks, can you reply "I signed it!"? So the bot would be able to check your CLA. :)

**Comment by samuela** [comment]
I signed it!

**Comment by meteorcloudy** [comment]
@samuela LGTM, thank you!  I'll import this change.

**Pull request closed without merging**
