### PR TITLE
Update to JDK 10 javac

### PR DESCRIPTION
**Pull request by cushon**
This reverts commit 12dcd35ef7a26d690589b0fbefb1f20090cbfe15.

### CODE REVIEW

**Comment by eaftan** [comment]
LGTM

**Comment by iirina** [comment]
Thanks for this PR Liam!

Some files (e.g. `bazel-singlejar_deploy.jar`, `java_compiler.jar`) are removed, is it intentional?

As much as I would love to upgrade to javac 10 I suggest we hold on a bit longer. I'm working on setting up some guidelines and processes for versioning the java tools in relation to java releases. I would wait a few days until we reach consensus on those before going ahead and upgrading javac.

**Comment by iirina** [comment]
I see now the PR was merged in 3d47f74f6688480ad3fb390ba97ed96cc28cc8a0. Please in the future mention the commit(s) where the PR is merged and the close it.

**Comment by cushon** [comment]
> Some files (e.g. bazel-singlejar_deploy.jar, java_compiler.jar) are removed, is it intentional?

I don't think they were removed. The github diff view shows that the files got slightly smaller in red text, maybe that's what you saw?

> Please in the future mention the commit(s) where the PR is merged and the close it.

Thanks, I filed b/127486068 to update the documented merge process for PRs.

**Pull request closed without merging**
