### PR TITLE
Try to remove instrumentation api

### PR DESCRIPTION
**Pull request by meteorcloudy**
The maven page shows instrumentation-api is from
https://github.com/google/instrumentation-java,
but that repo has become
https://github.com/census-instrumentation/opencensus-java,
which is another dependency we have (opencensus-api)

instrumentation-api looks obsolete and should be removed.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
I am not 100% sure we can remove this dependency, but let's see if it will break anything

**Comment by meteorcloudy** [comment]
FYI @olekw

**Comment by meisterT** [comment]
I checked and while it was necessary back then, it doesn't appear to be necessary anymore, since the file `tools/grpcz/census.proto` doesn't exist any more.

**Comment by meteorcloudy** [comment]
Nice, thanks!

**Comment by meteorcloudy** [comment]
> since the file tools/grpcz/census.proto doesn't exist any more.

Do we still need opencensus-api as a runtime dependency?

**Comment by meisterT** [comment]
> Do we still need opencensus-api as a runtime dependency?

Sorry, I don't know.

**Comment by meteorcloudy** [comment]
No problem, I can check that

**Comment by meteorcloudy** [comment]
Merged at https://github.com/bazelbuild/bazel/commit/13effb9bd881b89822a7d8f6e9b26aa4e13e2b90

**Comment by meteorcloudy** [comment]
We cannot remove opencensus-api as a runtime dependency, check https://github.com/bazelbuild/bazel/pull/11289

**Pull request closed without merging**
