### PR TITLE
Fix Bash rlocation failure with stricter Bash options

### PR DESCRIPTION
**Pull request by fmeum**
When run in the context of the bazel-skylib unit test setup, the new repo mapping logic in the Bash runfiles library failed due to a non-matching grep in a pipe. Fix this by using a wrapper around grep throughout that does not exit with exit code 1 if there is no match.

Fixes https://github.com/bazelbuild/bazel-skylib/pull/411#issuecomment-1312475310

### CODE REVIEW

**Comment by fmeum** [comment]
@c-parsons as you set up the unit test framework in bazel-skylib: I haven't been able to reproduce the failure of `$(grep ... | ...)` that I see over in bazel-skylib's unit tests when the `grep` doesn't match anything here in `runfiles_test.sh`. Even with `set -o errexit`, `set -e`, set -o pipefail` I don't get this behavior. Do you know how I could enable it so that this fix has test coverage?

**Comment by fmeum** [comment]
@shs96c Could you verify that this fixes the issue you are seeing? Some tests still fail, but I believe that may be due to https://github.com/bazelbuild/bazel/issues/16746.

**Comment by shs96c** [comment]
That does appear to fix the problem.

**Comment by fmeum** [comment]
@bazel-io flag

**Review by Wyverald — APPROVED** [review]

**Comment by Wyverald** [comment]
@bazel-io fork 6.0.0

**Pull request closed without merging**
