### PR TITLE
Intern repository mapping entries

### PR DESCRIPTION
**Pull request by fmeum**
All repositories generated by a module extension have the same repository mapping entries. Without interning, if a module extension generates N repositories, each such repository would have its own copy with (more than) N entries, resulting in overall memory usage quadratic in N.

We intern the entries, not the `RepositoryMapping` itself, since the latter also includes the owner repo, which differs between extension repos.

Output of `bazel info used-heap-size-after-gc` after running a build with a synthetic module extension generating N + 1 repos and requesting all of them:

```
before
N=100:     32MB
N=1000:    77MB
N=3000:   371MB
N=5000:   961MB
N=10000: 3614MB

after
N=100:     32MB
N=1000:    44MB
N=3000:    71MB
N=5000:    91MB
N=10000:  158MB
```

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald What do you think,, should this go into a patch release together with https://github.com/bazelbuild/bazel/pull/19245?

**Comment by fmeum** [comment]
@bazel-io flag

**Review by Wyverald — APPROVED** [review]
nice, thank you for the investigation and prompt fix!

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
@fmeum Oops. I accidentally clicked on the "Update branch", which resulted in extra commit (merge commit). Do you mind "git reset hard" or something to get rid of that commit in your branch? So sorry about that  :(

@bazelbuild/triage

**Comment by iancha1992** [comment]
@fmeum I accidentally clicked on "Update branch", causing a merge commit to be made. Can you please reset to the original commit? My apologies.

cc: @bazelbuild/triage

**Comment by meteorcloudy** [comment]
@iancha1992 I think you are still able to import the PR, you can fix the GIT_AUTHORS manually, I can help review ;)

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
