### PR TITLE
Extend attr with label_dict

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
Started extending `attr` with an additional `label_dict`.

This requires a bit of groundwork in the Skylark type handling.
~~Currently most code should be in place but it still crashes so not finished.~~

@damienmg Can you perhaps point me to the place where I should add unit tests for this?

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by iirina** [comment]
Hi Andreas,

Did you discuss this change on bazel-dev beforehand?

**Comment by abergmeier-dsfishlabs** [comment]
@iirina Nope.

**Comment by iirina** [comment]
Can you please do so?

**Comment by abergmeier-dsfishlabs** [comment]
Ok.

**Comment by michajlo** [comment]
Does this work with the assorted query formats? In particular I'm interested in ProtoOutputFormatter, I think you also need to add support to AttributeFormatter/I don't see it in any of the changed files.

**Comment by abergmeier-dsfishlabs** [comment]
@michajlo Ah, good catch, thanks.

**Comment by abergmeier-dsfishlabs** [comment]
Ok, tests are in now. Anything else?

**Comment by laszlocsomor** [comment]
@laurentlb , @dslomov : ping

**Comment by abergmeier-dsfishlabs** [comment]
FYI: Submitted that to Gerrit: https://bazel-review.googlesource.com/#/c/8031/

**Comment by laszlocsomor** [comment]
Awesome, thank you!

Both @dslomov and @laurentlb are currently away on business travel, so they are most likely unable to review this change this week. Sorry about that! I'll add @vladmos for another set of eyes, but @laurentlb should see this change too before we import it.

To follow up on https://github.com/bazelbuild/bazel/pull/2208#issuecomment-265725774, did you discuss this on the mailing list?

**Comment by abergmeier-dsfishlabs** [comment]
> To follow up on #2208 (comment), did you discuss this on the mailing list?

See here: https://groups.google.com/forum/#!topic/bazel-dev/h6DF4Zks3U0

**Comment by laszlocsomor** [comment]
@abergmeier-dsfishlabs : Thanks! This discussions doesn't seem to be resolved. I'll CC more people on the thread.

**Comment by mhlopko** [comment]
Closing due to inactivity, feel free to reopen.

**Pull request closed without merging**
