### PR TITLE
Polishing

### PR DESCRIPTION
**Pull request by jbduncan**
This is a follow-on to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-dev/Q2owiR-e86s/ugrVUhn7AwAJ to introduce more usages of Java 8 idioms and other "cleanups", with the intention of making the code base easier to maintain.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
Looks like there is no class signatures or method signatures changed in this commit, right @jbduncan ?
@damienmg Can you review this?

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by jbduncan** [comment]
@meteorcloudy I certainly did my best to either not affect any class or method signatures, or at least to affect them in such a way that they still behave the same (e.g. converting inner `public static enum` classes to inner `public enum`s). :)

@damienmg You're very welcome. :)

It occurs to me that ci.bazel.io failed, but it's not immediately obvious to me what's the cause of the failure. :thinking:

**Comment by damienmg** [comment]
The test failure are all discard_graph_tests. Weirdly enough it seems like we do not have any XML files generation for that test failure. Anyway that change is good to go.

**Comment by jbduncan** [comment]
@damienmg SGTM! :+1:

**Comment by jbduncan** [comment]
Great to see this merged in! Many thanks for reviewing this @damienmg. :)

**Pull request closed without merging**
