### PR TITLE
Add OpenSUSE support

### PR DESCRIPTION
**Pull request by Hui-Zhi**
Add OpenSUSE support for installation.

### CODE REVIEW

**Comment by philwo** [comment]
https://software.opensuse.org/package/bazel shows that the last version they package is Bazel 0.22.0. I don't think we should add official looking documentation to our own website for these packages unless they are better maintained, or alternatively we should make it very clear that we do not maintain these packages.

**Comment by Hui-Zhi** [comment]
@philwo I will ask SUSE R&D team to update Bazel version.

**Comment by Hui-Zhi** [comment]
@philwo SUSE R&D team has built bazel 2.0 here: https://build.opensuse.org/request/show/761595,
and it will take a few days to have it here: https://software.opensuse.org/package/bazel, also I will refine the steps for instruction later.

**Comment by Hui-Zhi** [comment]
@philwo I have updated the installation guide, and the latest version has been built at https://build.opensuse.org/request/show/761595. It will be available at after an SUSE internal review: https://software.opensuse.org/package/bazel

Please review this.

**Comment by jin** [comment]
Could you please add a note at the top of the instructions that the Bazel team does not maintain openSUSE support, and add a point of contact to the maintainers?

**Comment by Hui-Zhi** [comment]
@jin I have added a note for this, but there's no need to add maintainers, users just need to file a ticket at bugzilla.opensuse.org then SUSE maintainers will take care of it.

**Comment by philwo** [comment]
Thank you! I'll import this change.

**Pull request closed without merging**
