### PR TITLE
Add auth support for proxy downloads

### LINKED ISSUE #587: tensorflow building issue on ubuntu 14.04: Accessing remote repository through a proxy
As (https://github.com/tensorflow/tensorflow/issues/67) is declared as Bazel issue I'm writing here. So I'm having the same issue with the original post. As mentioned in the original post, by manually wget and placing the jpeg library the error message about jpeg has gone. However there are still many error messages, and by trying multiple times the error message seems to change but always fails with downloading something. These are the variations.

Variation 1:
`
ERROR: /home/name/work/tensorflow/tensorflow/core/platform/default/build_config/BUILD:36:1: no such package '@re2//': https://github.com/google/re2.git: cannot open git-upload-pack and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
`

Variation 2:
`
ERROR: /home/name/work/tensorflow/tensorflow/core/platform/default/build_config/BUILD:36:1: no such package '@png_archive//': Error downloading from https://storage.googleapis.com/libpng-public-archive/libpng-1.2.53.tar.gz to /home/name/.cache/bazel/_bazel_name/894ee6ce07893c5c665fe600d592867f/external/png_archive: Error downloading https://storage.googleapis.com/libpng-public-archive/libpng-1.2.53.tar.gz to /home/name/.cache/bazel/_bazel_name/894ee6ce07893c5c665fe600d592867f/external/png_archive/libpng-1.2.53.tar.gz: storage.googleapis.com and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
`

Variation 3:
`
ERROR: /home/name/work/tensorflow/tensorflow/tensorflow.bzl:224:3: no such package '@gemmlowp//': https://github.com/google/gemmlowp.git: cannot open git-upload-pack and referenced by '//tensorflow/core:kernels'.
`

### PR DESCRIPTION
**Pull request by kchodorow**
Should fix #587.

RELNOTES: Support for downloading remote resources through proxies by setting HTTP_PROXY (or HTTPS_PROXY).

### CODE REVIEW

**Comment by kchodorow** [comment]
> Shouldn't no password be a valid case?

I couldn't find documentation about it.  Does Java need to even know about the username if the password isn't set?

**Comment by damienmg** [comment]
I have no idea. Well I guess it does not hurt to throw an error there.

**Comment by damienmg** [comment]
LGTM. Should I import it or will you do it?

**Comment by kchodorow** [comment]
Thanks, I'll do it.

**Comment by damienmg** [comment]
Was imported

**Comment by plattenschieber** [comment]
No password is indeed a valid case. I'm using it everywhere (apt-get, git, ...).

**Comment by mcelhennyi** [comment]
Does bazel support auth? I cant seem to get my auth required prox-ied computer to work, but my non auth prox-ied VM works?

**Pull request closed without merging**
