### PR TITLE
A few FilesystemValueChecker improvements.

### PR DESCRIPTION
**Pull request by benjaminp**
- Pass possibly-modified keys around as a Collection rather than an Iterable.
- Remove an atomic that counted the possibly-modified keys.
- Use a lambda in getDiff.

### CODE REVIEW

**Comment by laurentlb** [comment]
What's the status of this? Should it be merged?

**Comment by jin** [comment]
For primary reviewers, please read go/import-bazel-pr (internal link) for import instructions.

**Comment by ulfjack** [comment]
Looks reasonable to me. @benjaminp, did you see any improvements with this change?

**Comment by benjaminp** [comment]
> Looks reasonable to me. @benjaminp, did you see any improvements with this change?

The context of this change was that I was trying to make a more complex modification to `FileSystemValueChecker`. Part of the way through that I noticed the change would be very large, so I split this out. I don't think Bazel users will find this change wildly beneficial, but at least the world has one less thread-local atomic variable.

**Comment by ulfjack** [comment]
IMO, this can be merged. @philwo, maybe you could import it and send it to Eric or Nathan as an internal review? It might make sense to mention that this is a preparatory change - I'm definitely interested in what @benjaminp is cooking up.

**Pull request closed without merging**
