### PR TITLE
Added HttpContentDecompressor to HttpBlobStore download pipeline

### PR DESCRIPTION
**Pull request by excitoon**
This patch enables accepting compressed data from remote cache.

### CODE REVIEW

**Comment by ishikhman** [comment]
Hey @excitoon, would that be possible to add a test for this change?

**Comment by excitoon** [comment]
Hi @ishikhman , I don't know if you asked about possibility, but I made this test. It is the first Python test of remote functionality, and I hope it will start a good practice of making such tests in Python. This code runs on both 2 and 3 Pythons and checks Bazel can accept gzip encoding of data.

**Comment by excitoon** [comment]
@buchgr @ishikhman Is there a chance it can appear in 0.28?

**Comment by ishikhman** [comment]
> @buchgr @ishikhman Is there a chance it can appear in 0.28?

sorry that it took so long, but I guess we missed the 0.28 already :( 
We'll have a look next week.

**Comment by excitoon** [comment]
I've resolved conflicts, hope to merge it soon.

**Comment by excitoon** [comment]
@buchgr @ishikhman Is there a chance it can appear in 0.30?

**Comment by ulfjack** [comment]
Both of them have left the project. Unfortunately, the code has changed *again* and the patch no longer applied. I'm very sorry.

**Comment by aiuto** [comment]
@excitoon Is this still worth doing?
@ola-rozenfeld is there any chance you can look at this ancient PR if @excitoon syncs and tests pass again?

**Comment by ulfjack** [comment]
It is probably worth doing, IMO. I can help with reviews; the current patch seems pretty straightforward.

**Comment by excitoon** [comment]
@aiuto It certainly is. It allows to save lots of traffic when linker accesses object files.

**Comment by aiuto** [comment]
@excitoon Can you resolve the merge?
@ulfjack Can you review?
When it is ready to go, assign it to me and I will do the import-merge

**Comment by jgavris** [comment]
I don't mean to hijack this thread, but for users of GCP as their HTTP cache, which doesn't do compressive transcoding on download, any recommendations? @excitoon are you using a content store that compresses on download?

**Comment by excitoon** [comment]
@aiuto I will do it by tomorrow

**Comment by excitoon** [comment]
@jgavris what do you mean? Would you like to save space on storage (which is what transcoding about) or network traffic? In order to utilize decompressive transcoding one would need to tune upload pipeline a little bit (probably set proper headers and compress the output).

**Comment by excitoon** [comment]
```$ bazel test //src/test/py/bazel:bazel_remote_cache_decompression_test
//src/test/py/bazel:bazel_remote_cache_decompression_test                PASSED in 9.3s
```

**Comment by excitoon** [comment]
@ulfjack @aiuto @ola-rozenfeld Is there a chance it can appear in 3.3? 😊

**Comment by excitoon** [comment]
I've got a problem on Darwin:
```
WARNING: Reading from Remote Cache:
Operation not permitted: localhost/127.0.0.1:52020
```

How would I allow Bazel to access a test server on local machine?

**Comment by ulfjack** [comment]
ISTR that the Mac sandbox disallows localhost traffic - not sure there's anything you can do besides disabling the test on mac or disabling sandboxing (with the "no-sandbox" tag).

**Comment by ulfjack** [comment]
I'd expect this to land in 3.3 given that it's supposed to be cut in ~a week.

**Comment by excitoon** [comment]
.

**Comment by aiuto** [comment]
@excitoon You beat the birthday cake!

**Pull request closed without merging**
