### PR TITLE
Directly check and disallow for Repository references in glob arguments.

### PR DESCRIPTION
**Pull request by abergmeier**
Also added remark to documentation.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
@abergmeier: we cannot accept contribution without CLA, could you sign the CLA? Thanks!

**Comment by abergmeier** [comment]
@damienmg might take some time till our bureaucracy is through. Sorry.

**Comment by damienmg** [comment]
Ok no problem, thanks for the update!

**Comment by abergmeier** [comment]
Closing for now. Will reopen once our company has gotten the paperwork done.

**Pull request closed without merging**
