### PR TITLE
[7.1.0] Update java_tools v13.4 / rules_java 7.4.0

### PR DESCRIPTION
**Pull request by iancha1992**
PR: https://github.com/bazelbuild/bazel/pull/21222
Commit: https://github.com/bazelbuild/bazel/commit/d51f9487ea8441379cb36dde1480911e7c6cecee

### CODE REVIEW

**Comment by iancha1992** [comment]
cc: @keertk

**Comment by iancha1992** [comment]
@hvadehra looks like the checks are failing. Can you please check?

cc: @bazelbuild/triage

**Comment by hvadehra** [comment]
I think we also need https://github.com/bazelbuild/bazel/pull/19361

**Comment by iancha1992** [comment]
> I think we also need #19361

Sure. Trying again. Thanks

**Comment by keertk** [comment]
@hvadehra finally ready! Please approve?

**Review by hvadehra — APPROVED** [review]

**Pull request merged**
