### PR TITLE
Handle symlinks and root_symlinks in Runfiles

### LINKED ISSUE #18249: --remote_download_toplevel does not download symlink targets of runfiles
### Description of the bug:

`--remote_download_toplevel` downloads the runfiles associated with any outputs explicitly listed on the command line, and (on Linux) constructs a runfiles tree of symlinks for them.
Unfortunately, if the runfiles is constructed with `symlinks=` or `root_symlinks=` that refer to File objects _not_ in the `files=` depset of the runfiles, this process fails and the target of the symlink is not downloaded, which results in a broken symlink in the resulting runfiles tree.

This is important for us because we use root_symlinks to relocate files to keep our PYTHONPATH smaller. This works file when not using --remote_download_toplevel.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`rules.bzl`
```starlark
def _symlink_rule_impl(ctx):
    file = ctx.actions.declare_file("file.txt")
    executable = ctx.actions.declare_file("executable")

    ctx.actions.run_shell(
        outputs = [file],
        command = "echo 'Hello World!' > " + file.path,
    )
    ctx.actions.write(executable, "cat symlink.txt")
    return [DefaultInfo(
        runfiles = ctx.runfiles(
            symlinks = {"symlink.txt": file},
        ),
        executable = executable,
    )]

symlink_rule = rule(
    implementation = _symlink_rule_impl,
    executable = True,
    attrs = {},
)
```

`BUILD`
```starlark
load(":rules.bzl", "symlink_rule")

symlink_rule(name = "symlink")
```

Reproduction steps:
1. `bazel run //:symlink --remote_download_toplevel --disk_cache /tmp/cache`
2. `bazel clean`
3. `bazel run //:symlink --remote_download_toplevel --disk_cache /tmp/cache`

### Which operating system are you running Bazel on?

Ubuntu 18.04

### What is the output of `bazel info release`?

release 6.1.2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

This seems to reproduce both on Bazel 5.x and the latest 7.0.0-pre*

### PR DESCRIPTION
**Pull request by coeuvre**
Fixes #18249.

### CODE REVIEW

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.0

**Comment by iancha1992** [comment]
@coeuvre @brentleyjones 
Cherry-pick was attempted for this PR into the release-6.3.0 branch. However, it looks like the "RemoteOutputChecker.java" (src/main/java/com/google/devtools/build/lib/remote/RemoteOutputChecker.java) file doesn't exist in the release-6.3.0 branch (but it did get merged and exist in the MASTER branch), so it seems like additional commits needs to be cherry-picked first for the release branch. Could you please submit a PR or let us know what commits to include?

**Comment by coeuvre** [comment]
I think it's almost impossible to cherry pick this change into 6.3.0 due to the missing of `RemoteOuputChecker`.

**Comment by iancha1992** [comment]
> I think it's almost impossible to cherry pick this change into 6.3.0 due to the missing of `RemoteOuputChecker`.

cc: @Wyverald @meteorcloudy

**Pull request closed without merging**
