### PR TITLE
Improve error message for concurrent modifications

### PR DESCRIPTION
**Pull request by tbaing**
Improve the error message logged when concurrent modifications
occur and --experimental_guard_against_concurrent_changes is set.

### CODE REVIEW

**Review by coeuvre — APPROVED** [review]
Thanks!

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by kshyanashree** [comment]
@bazel-io fork 6.1.0

**Comment by kshyanashree** [comment]
Hi @tbaing! Could you please sign the CLA with the Email you used?  https://github.com/bazelbuild/bazel/pull/17323/checks?check_run_id=10886732089 Thanks!

**Pull request closed without merging**
