### PR TITLE
Upgrade grpc-java to 1.47.0 and remove 1.45.1

### PR DESCRIPTION
**Pull request by comius**
This is needed to upgrade protobuf, see `java_generator.cpp`.

### CODE REVIEW

**Comment by comius** [comment]
Tested with: https://github.com/bazelbuild/bazel/pull/17094

**Review by meteorcloudy — APPROVED** [review]
Thanks! It looks like the 1.47.0 jars were checked in a long time ago, but never used.. https://github.com/bazelbuild/bazel/pull/15814

**Comment by comius** [comment]
@sgowroji this needs a github merge

**Comment by sgowroji** [comment]
Merged at e1bfe1d8c32f0b98d9a0f61e8592e6f523ca0388

**Pull request closed without merging**
