### PR TITLE
Supported Git LFS

### PR DESCRIPTION
**Pull request by excavador**
On my work I need to use the external dependency to repository with LFS files 
https://git-lfs.github.com/

Without my commit I receive raw LFS pointer instead of files (LFS pointers - text files which describe how to download LFS object).

With my commit repository is cloning correctly.

Little annoying fact - I see no progress about downloading LFS files, while in shell on everyday git use  I see it.

I am very sorry If something is wrong - I definitely not a Java programmer.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by katre** [comment]
We are in the process of removing the native git rules, which use jgit, and urging people to use the Skylark git rules, which use the git command from your local system.

To use the Skylark rules, just add this line to your WORKSPACE before you call git_repository:
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
```

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by excavador** [comment]
@katre thank you for your answer!

Yes, I saw the rules and try to patch their first, but I did not know the trick with 
```
load('@bazel_tools//tools/build_defs/repo:git.bzl', 'git_repository')
```

I ready to do patch in skylark rule.

Can you please give me adise?
So, for use LFS from git command-line we need to install it https://github.com/git-lfs/git-lfs/wiki/Installation

1. Which git uses bazel - own or system?
2. What the "right" way to install LFS for this get?

Thank you again,
Best regards, Oleg Tsarev

**Comment by katre** [comment]
If you add the load() statement from above to your WORKSPACE, git_repository will call the system git command-line program, so there is no need to patch anything. Please try it and see how it works for you.

**Comment by excavador** [comment]
```If you add the load() statement from above to your WORKSPACE, git_repository will call the system git command-line program, so there is no need to patch anything. Please try it and see how it works for you.
```
I pretty sure it would work. My question related to bazel contribution, I want to provide patch for all bazel users.
My three questions above about this feature (of course, If bazel team agree with my feature proposal)

**Comment by excavador** [comment]
So, seems like, I need lfs support in system git, and "init_lfs: True" can failure external repository fetch according to missed git-lfs in the system git.

Is it ok or bazel has some internal requirements to cases like this?

**Comment by excavador** [comment]
@katre so now I got what you mean

It works, without any patch.
Thanks!

**Pull request closed without merging**
