### PR TITLE
Add Starlark API for ProtoSource

### PR DESCRIPTION
**Pull request by Yannic**

### CODE REVIEW

**Comment by jin** [comment]
What is this PR about? Are there prior discussions? It would help to have a description.

**Review by comius — APPROVED** [review]

**Review by comius — CHANGES_REQUESTED** [review]
Is there a particular motivation for this?
Can you please update PR description.

**Comment by comius** [comment]
> Is there a particular motivation for this?
> Can you please update PR description.

@Yannic ping

**Comment by comius** [comment]
No answers to pings and PR went stale.

**Pull request closed without merging**
