### PR TITLE
Add worker assertions resource_processing_integration_test

### PR DESCRIPTION
**Pull request by Bencodes**
Adding a few assertions to the worker and multiplex worker tests to ensure that the expected workers are in fact coming up.

### CODE REVIEW

**Comment by Bencodes** [comment]
@ted-xie mind taking a look at this?

**Comment by ted-xie** [comment]
LGTM, we'll import this.

**Review by ted-xie — APPROVED** [review]

**Comment by sgowroji** [comment]
Hello @Bencodes, Above PR is awaiting to merge. Could you please resolve the conflicts. Thanks!

**Comment by sgowroji** [comment]
Hello @Bencodes, Could you please resolve the above conflict files. Above PR is awaiting to import. Thanks!

**Comment by Bencodes** [comment]
@ted-xie I think something may have regressed here causing multiplex workers to no longer work, and these tests no longer pass against master even with all the Android related multiplex flags enabled.

**Comment by ted-xie** [comment]
@Bencodes Coincidentally, I was just looking at this yesterday and noticed the same thing. I'm working on a fix right now.

**Comment by ted-xie** [comment]
@Bencodes I merged the fix for multiplexed workers. Could you rebase your PR branch? Once all the presubmit tests pass, we can try importing this again.

**Comment by Bencodes** [comment]
@ted-xie rebased and updated the tests to use the correct flag. This should be ready to merge.

**Comment by ted-xie** [comment]
@Bencodes This PR has been merged; thank you! I'll cherry-pick this change and bf94d9d96964323a20822ace2e94e11780eba623 into 6.1.0.

**Pull request closed without merging**
