### PR TITLE
Enable C/C++ remote tests on macOS

### PR DESCRIPTION
**Pull request by fmeum**
Also ensure that the remote worker doesn't fail executions when the spawn fails, but instead sends back the result of the unsuccessful execution.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @tjqg I'm working on this now, but it will require further changes (e.g. https://github.com/bazelbuild/bazel/pull/23089).

**Comment by fmeum** [comment]
FYI @keith

**Comment by fmeum** [comment]
@tjgq I have been able to drop the apple_support patch thanks to a release containing the fix, this is now ready for review.

**Review by coeuvre — APPROVED** [review]
Thanks for the PR!

**Pull request closed without merging**
