### PR TITLE
Windows: remove incompatible_windows_style_arg_escaping

### PR DESCRIPTION
**Pull request by laszlocsomor**
In this PR:

- Removed the
  `--incompatible_windows_style_arg_escaping` flag
  and all code for its "false" case.  The flag is
  flipped to true.

- In WindowsProcessesTest, the
  testDoesNotQuoteArgWithDoubleQuote method is
  replaced by testQuotesArgWithDoubleQuote, i.e.
  the test logic is reversed. The new test shows
  the correct behavior, the old test was wrong.

See https://github.com/bazelbuild/bazel/issues/7122
See https://github.com/bazelbuild/bazel/issues/7454

RELNOTES[INC]: The --incompatible_windows_style_arg_escaping flag is flipped to "true", and the "false" case unsupported. Bazel no longer accepts this flag.

### CODE REVIEW

**Comment by dkelmer** [comment]
Just making sure, this doesn't affect the 0.25 rehearse, right?

**Comment by laszlocsomor** [comment]
No, it won't affect 0.25. The flag is still supported at the baseline commit: https://github.com/bazelbuild/bazel/blob/03662462941953dad23af88693804b8b1d4430b9/src/main/java/com/google/devtools/build/lib/runtime/BlazeServerStartupOptions.java#L469-L470

Alas merging this PR is blocked on https://github.com/bazelbuild/bazel/issues/8005 which breaks `//src/test/shell/integration:test_test`.

**Comment by dkelmer** [comment]
Thanks for clarifying 😊

**Comment by jin** [comment]
Has this been imported? What's the status of this PR? It looks like #8005 is closed.

**Comment by laszlocsomor** [comment]
It was never merged.
I'm running presubmit tests to try and merge it.

**Pull request closed without merging**
