### PR TITLE
runfiles: rlocation() checks if arg is normalized

### PR DESCRIPTION
**Pull request by laszlocsomor**
rlocation() now validates that the path argument
is normalized, i.e. contains none of:
- current directory references (".")
- uplevel references ("..")
- double slash ("//")

This helps avoiding a bug similar to https://github.com/bazelbuild/bazel/pull/5083.

See https://github.com/bazelbuild/bazel/pull/4460

Change-Id: Ia73fa2df1eae86fc7084162c24e144129672742d

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Do you think if it's an option to normalize the given path in `rloacation` instead of throwing an error?

**Comment by laszlocsomor** [comment]
Yes. Do you think that's a better idea?

**Comment by laszlocsomor** [comment]
I agree it's more convenient but I'd prefer to keep the runfiles libraries simple. WDYT?

**Comment by meteorcloudy** [comment]
That's right, normalizing in bash script doesn't seem to be very easy.

**Pull request closed without merging**
