### PR TITLE
Update RE third party code.

### PR DESCRIPTION
**Pull request by rubensf**
This does come with a slight breaking change in
digest_function->digest_functions on CacheCapabilities.

### CODE REVIEW

**Comment by atetubou** [comment]
fix build?

**Comment by aiuto** [comment]
Thanks for the PR, but it obviously does not build. It is also in third_party, which changes the merge process.
I'll keep this open as a place for discussion.

**Comment by rubensf** [comment]
Google instructions for contributing to bazel explicitly say to send third_party changes separately from main code changes... Which seems impossible here :)

I was hoping someone would tell me what to do otherwise.

**Comment by aiuto** [comment]
Right. We can figure out a plan in this PR (or maybe open a distinct issue).
My hunch is that we have to update Bazel so the update will happen,
then we can do the third_party update.

**Comment by coeuvre** [comment]
Discussed with @philwo today. We need some hacks for this case.

**Pull request closed without merging**
