### PR TITLE
upgrade the centos6.7 to centos6 (current)

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
Also use the scl-rh repository for devtoolset-3 instead of my devtoolset-2 unmaintained repository :P.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
Can you sign the CLA or we would not be able to merge your change?

**Comment by truatpasteurdotfr** [comment]
I have request a "go" from my corporate lawyer department, and still awaiting for an answer :(

**Comment by damienmg** [comment]
Ok no problem, thanks for the heads-up!

**Comment by iirina** [comment]
@truatpasteurdotfr any update on this?

**Comment by truatpasteurdotfr** [comment]
sorry, no :( they are still working on it :(

**Comment by iirina** [comment]
OK, no problem. :)

**Comment by mhlopko** [comment]
Friendly ping, any update on this? Thanks!

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
test this please

**Comment by damienmg** [comment]
Closing since the CLA is not yet signed and no activity for 20 days.

**Pull request closed without merging**
