### PR TITLE
Windows: Use vswhere to locate latest Visual C++ installation

### PR DESCRIPTION
**Pull request by gjasny**
Starting with Visual Studio 15.2 vswhere.exe is installed into
`%ProgramFiles(x86)%\Microsoft Visual Studio\Installer`.

We locate the latest non-prerelease version which has the
Desktop development with C++ workload installed.

Closes: #10772

### CODE REVIEW

**Comment by gjasny** [comment]
When nothing matches `vswhere` does not error out but happily returns nothing. I need to run some more tests today and refine the query and error handling

**Comment by gjasny** [comment]
The build error looks unrelated.

**Comment by meteorcloudy** [comment]
@gjasny Thanks for the contribution!
This CL looks good, should we wait for https://github.com/bazelbuild/bazel/pull/10807 to be merged first?

**Comment by gjasny** [comment]
> This CL looks good, should we wait for #10807 to be merged first?

I'd merge this one before. The environment variable lookup problems do not influence this PR (more than before). I guess most users have their "Program Files" folder on the C-drive anyways.

**Pull request closed without merging**
