### PR TITLE
Starlark: validate Method signature at MethodDescription construction

### PR DESCRIPTION
**Pull request by stepancheg**
Kind of type checking: no need to call a function to check its
signature is correct.

### CODE REVIEW

**Comment by laurentlb** [comment]
That's a bunch of new code. How is it useful?

**Comment by stepancheg** [comment]
> How is it useful?

It is useful when starlark library is used without the StarlarkMethodProcessor, which validates signatures at build time: this diff does the same validation as the annotation processor but at instantiation time.

Yesterday I did not know about the annotation processor, TIL. With the annotation processor, the value is this commit is smaller, but it is still useful.

**Comment by laurentlb** [comment]
I'll wait for @alandonovan on this. At the moment, Starlark is not intended to be used outside of Bazel (the API is not stable). It might be easier for us to ignore this use-case for the time being, until we're able to provide a stable API.

**Comment by laurentlb** [comment]
@alandonovan

**Comment by stepancheg** [comment]
> Is the annotation processor difficult to use?

Kind of difficult, while there is no standalone starlark dist. Currently, we just dump all the sources in one folder and compile them.

But that's not how Starlark is meant to be used, let's drop this PR.

**Pull request closed without merging**
