### PR TITLE
Adding JUnit example to docs

### PR DESCRIPTION
**Pull request by KilimAnnejaro**
In working through the Bazel documentation for a new job, I found the process for testing with Bazel to be somewhat complicated and annoying to figure out. Since testing is essential to great software, I thought adding the process for building tests to the starter tutorial made a lot of sense. If there's anything I can do to make this documentation better, please let me know--thanks!

Resolves https://github.com/bazelbuild/bazel/issues/14431.

### CODE REVIEW

**Comment by aiuto** [comment]
Thanks for trying to improve the docs. But let's not add this here. As rule  definitions move out of native bazel and in to starlark based rules, the tutorials should shift as well. 
Can you find a place for it in https://github.com/bazelbuild/examples/tree/main/java-tutorial ?
That way you can have a complete example which can eventually be executable and run in CI.

**Comment by KilimAnnejaro** [comment]
@aiuto does https://github.com/bazelbuild/examples/pull/232 work for you?

**Comment by aiuto** [comment]
Yes. That's exactly the idea.  Sorry for the late reply.  Holiday
season and end of year things.

I reassigned to @jin, who knows more about maven than the rest of us.

**Comment by aiuto** [comment]
This is superceded by https://github.com/bazelbuild/examples/pull/232

**Pull request closed without merging**
