### PR TITLE
added buildozer command to strict deps fix message

### LINKED ISSUE #3285: Print buildozer command for "add the following deps" message
Right now we print something like:

```
** Please add the following dependencies:
  //:C  to //:A
```

Now that buildozer is open sourced, it would be nice to give people a one-liner to run.

### PR DESCRIPTION
**Pull request by ittaiz**
fixes #3285 
kept the existing message in case someone is parsing this text

### CODE REVIEW

**Comment by ittaiz** [comment]
@damienmg I can't understand where to find the failures? The new jenkins UI is somewhat of a conundrum to me :(

**Comment by damienmg** [comment]
http://ci.bazel.io/blue/organizations/jenkins/PR%2Fbazel-tests/detail/bazel-tests/104/tests shows the list of test for which we have a XML file but all the test I see are also failing at HEAD (on each platform there is a shell test that is the bazel output).


Also need to restart jenkins because there is a change I rolled-back that make the UI more confusing

**Comment by ittaiz** [comment]
I see. What can we do?

**Comment by ittaiz** [comment]
cc @iirina since we discussed this issue

**Comment by ittaiz** [comment]
Great, thanks!
Can I expect this in HEAD tomorrow?

**Comment by iirina** [comment]
@ittaiz Yes

**Pull request closed without merging**
