### PR TITLE
debian package: Relax JDK dependency to suggests

### LINKED ISSUE #6412: Debian package should only suggest JDK instead of depending on it
Right now the published Debian / Ubuntu package declares a (hard) dependency to a Java SDK. But the bazel version included in the `deb` file is already a standalone one that comes with a bundled Java runtime.

Would you accept a PR which downgrades the `Depends` to a `Suggests`? The [Debian Policy](https://www.debian.org/doc/debian-policy/ch-relationships.html) describes `Suggests` as:

> This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

Thanks,
Gregor

### PR DESCRIPTION
**Pull request by gjasny**
The Bazel binary comes with a pre-bundled JRE/JDK so the hard
dependency on a JDK could be relaxed to a suggestion.

Closes #6412.

### CODE REVIEW

**Comment by gjasny** [comment]
I'm confused right now what's right and wrong. Is the Debian package supposed to embed the JDK? 

Currently it does but the code suggests that's not intentional because `scripts/packages/debian:bazel-bin` has the following `srcs`:
```
    srcs = [
        "//scripts/packages:without-jdk/bazel",
        "//scripts/packages:without-jdk/bazel-real",
    ],
```

Maybe the `rename-bazel-bin-without-jdk` genrule in `scripts/packages` should be fixed instead (which would render this PR just wrong):

```diff
diff --git a/scripts/packages/BUILD b/scripts/packages/BUILD
index ace087ce2a..c759065567 100644
--- a/scripts/packages/BUILD
+++ b/scripts/packages/BUILD
@@ -93,7 +93,7 @@ genrule(
 
 genrule(
     name = "rename-bazel-bin-without-jdk",
-    srcs = ["//src:bazel"],
+    srcs = ["//src:bazel_nojdk"],
     outs = ["without-jdk/bazel-real"],
     cmd = "mkdir -p $$(dirname $@); cp $< $@",
 )
```

Please advise. Personally I'd like the `bazel.deb` to be self-contained due to all the hassle with Oracle JDK on Ubuntu Xenial (licensing, download issues, etc.)

**Comment by philwo** [comment]
> I'm confused right now what's right and wrong. Is the Debian package supposed to embed the JDK?

Oh, wow :D That's messed up. Yes, it's supposed to embed it and your PR looks good. The whole "without-jdk" thing should instead be "with-jdk" (which is now the default).

If you'd like to clean that up, I'd happily review it in this PR, otherwise I can also just merge your change and will see that I clean it up later.

**Comment by gjasny** [comment]
Hi @philwo, could you please review the 2nd cleanup patch and merge? It would be nice if the change could land in 0.20.0. Thanks!

**Comment by philwo** [comment]
Sorry for the delay. I'm merging this now!

**Pull request closed without merging**
