### PR TITLE
Allow ignored directories with wildcards to be specified in the REPO.bazel file.

### PR DESCRIPTION
**Pull request by lberki**

### CODE REVIEW

**Comment by lberki** [comment]
Sigh. It does, but then there is a very similar cycle:

1. `WORKSPACE` 
2. `BzlLoadValue`
3. `PackageLookupValue`
4. `IgnoredPackagePrefixesValue`
5. `RepoFileValue`
6. `RepositoryMappingValue` for the repository in which the .bzl file is in
7. `//external`
8. `WORKSPACE`

And since there are in fact labels in `REPO.bazel`, the `RepoFileValue` -> `RepositoryMappingValue` dependency edge is legitimate. Sure, this doesn't happen with `--enable_workspace` because then the 6. -> 7. edge doesn't exist, but that doesn't help while the WORKSPACE file is still a thing.

I can imagine one fix, which is to store unconverted labels in `RepoFileValue.packageArgs()` and instead convert them in either `PackageFunction` or a separate `SkyFunction` so that it doesn't need to be re-done in every  package. This would probably require some acrobatics, though, to avoid making error reporting worse.

**Comment by fmeum** [comment]
Since WORKSPACE is going away anyway, how about gating this new feature behind `--noenable_workspace`? We could still cherry-pick it into Bazel 8.

**Comment by lberki** [comment]
I'd much rather not gate this behind the removal of WORKSPACE, since that is still a risky thing in my book (less risky than a year ago, but still not a done deal).

But, I think I have fix. Let me just run some presubmits and report back probably tomorrow...

**Comment by lberki** [comment]
Closing this in favor of https://github.com/bazelbuild/bazel/pull/24032 ..

**Pull request closed without merging**
