### PR TITLE
Fix Who's Using Bazel? link in docs footer

### LINKED ISSUE #14621: 'Who's using Bazel' in about footer of docs.bazel.build links to obsolete GitHub wiki
### Description of the problem / feature request:

The [Who's using Bazel](https://github.com/bazelbuild/bazel/wiki/Bazel-Users) link in the footer of the [docs.bazel.build](https://docs.bazel.build/) (i.e. [Test encyclopaedia](https://docs.bazel.build/versions/main/test-encyclopedia.html)) links to https://github.com/bazelbuild/bazel/wiki/Bazel-Users which redirects to the obsolete https://github.com/bazelbuild/bazel/wiki/

The same 'Who's using Bazel' link on the main bazel.build links to https://bazel.build/users.html

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Browse to [docs.bazel.build](https://docs.bazel.build/), scroll to the bottom of the page, click "Who's using Bazel?"

### PR DESCRIPTION
**Pull request by joshuagl**
fixes #14621

### CODE REVIEW

**Comment by aiuto** [comment]
I think this page page is not used. It comes from bazel-website now. 
I'll check on that and probably close this CL later.

**Comment by aiuto** [comment]
Agggh.   We have two copies.  That is wrong. 
Let's figure out how to fix this so we don't need to sync them. The one in bazel-website should take precedence.  This footer is completely out of date.

**Review by aiuto — APPROVED** [review]
I'll merge this to clear out the PR, but this duplicate footer has to go.

**Comment by joshuagl** [comment]
Got it. Thanks. CLA is now signed 👍

**Review by aiuto — APPROVED** [review]

**Comment by aiuto** [comment]
Passing this to @fweikert, since the location of the page is moving and changes to this one might get lost.

**Comment by fweikert** [comment]
This issue was fixed in https://github.com/bazelbuild/bazel/commit/3d37dc2ccbca01e6192cd9421a785e8ee08973b1 for the legacy site.

**Pull request closed without merging**
