### PR TITLE
Update bundled gRPC to 1.18.0 and nanopb to 0.3.6

### LINKED ISSUE #2804: Update C++ gRPC from 0.13.0
0.13.0 is truly ancient and unsupported, so it should be updated to something more recent. It'd also probably help us get rid of the Windows patch. Furthermore, it might also help with the issue whereupon a gRPC thread is still alive when we fork the server and prevents the fork from succeeding.

This probably also requires an update to protobuf.

The Java gRPC library should also be given a closer look.

### PR DESCRIPTION
**Pull request by tetromino**
And take the opportunity to align third_party/grpc/BUILD closer with
gRPC upstream's BUILD file to make importing easier next time.

Fixes #2804.

### CODE REVIEW

**Comment by tetromino** [comment]
Nanopb 0.3.6 is what the gRPC upstream currently bundles with their code. I thought we should use the same for consistency.

**Comment by kwasimensah** [comment]
A couple of non-blocking questions about how these deps are currently set up

1) How are there not ODR issues with Bazel and GRPC using possibly different versions of protobuf?

2) Isn't there also a code bloat/longer build times from having two different versions of it linked in? This is a desktop app so I don't think anyone truly cares but it seems unnecessary.

**Comment by tetromino** [comment]
@kwasimensah - the bundled third_party/grpc should be using the same third_party/protobuf and third_party/nanopb as the other of c++ code in bazel. At least, that's how the modified third_party/grpc/BUILD file is set up.

**Comment by tetromino** [comment]
Updating to split third_party/ and tools/ changes into separate commits as required by review processes. (And changing the grpc_cpp_plugin label - unfortunately, deviating from gRPC upstream - to make this order of commits possible.)

**Comment by tetromino** [comment]
Commits got applied but in the wrong order due to review process complications; I do apologize for breaking master for 3 commits (458ab037, 62675105, 4c3aeb0e).

All should be ok now.

**Pull request closed without merging**
