### PR TITLE
ByteStreamBuildEventArtifactUploader: Treat test directory outputs like other directory outputs.

### PR DESCRIPTION
**Pull request by benjaminp**
Fixes https://github.com/bazelbuild/bazel/issues/19847.

### CODE REVIEW

**Review by tjgq — APPROVED** [review]
Thanks, I think this does the job of preventing the BEP error until a more principled fix is possible. (We should expand the directory into individual files in the BEP like we do for other tree artifacts, but that's not as easily done.)

**Comment by benjaminp** [comment]
Indeed, it seems `ByteStreamBuildEventArtifactUploader` today just drops any kind of directory on the floor.

**Comment by tjgq** [comment]
> Indeed, it seems `ByteStreamBuildEventArtifactUploader` today just drops any kind of directory on the floor.

Not every directory IIRC: if a non-test action produces a tree artifact output, the files inside the tree should individually appear in the `ActionExecutedEvent` for that action, and in the `TargetCompleteEvent` for the action's owner. But test actions have their own `TestAttempt` and `TestSummary` events, which don't do the same. Source directories will also not get automatically expanded wherever they appear in the BEP.

**Comment by benjaminp** [comment]
Ah, I see what you mean. Other important places expand the directories before they reach the BEP uploader.

**Comment by tjgq** [comment]
@bazel-io fork 7.0.0

**Pull request closed without merging**
