### PR TITLE
No longer eagerly fetch labels in repo rule attributes

### PR DESCRIPTION
**Pull request by fmeum**
Eager fetching of all labels listed in repo rule attributes was introduced as a performance optimization to avoid costly restarts. 

Now that restarts are gone by default, this is no longer a benefit as it can cause unnecessary fetches and also create cycles where there wouldn't be any without this behavior (e.g. when two repos write each others labels into a file without resolving them).

Work towards #19055

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Comment by fmeum** [comment]
I fixed and deleted tests.

**Comment by dzbarsky** [comment]
We still have restarts for extensions, right? If an extension instantiates a repo rule, how does this affect it?

**Comment by fmeum** [comment]
> We still have restarts for extensions, right? If an extension instantiates a repo rule, how does this affect it?

We still have restarts for extensions, but their label attributes have never been fetched eagerly. Since repo rules are run lazily when needed, not inline when called by an extension, they will always be free of restarts even with this change.

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

**Comment by fmeum** [comment]
Sorry about that, I simply didn't realize that the implicit dependency may be relevant as more than a scheduling optimization. 

Please use `watch` (or one of the methods with a `watch` parameter) instead of `path`, as the latter no longer implicitly watches labels in Bazel 8 - this time behind an incompatible flag since we grasped the potential impact.

**Pull request closed without merging**
