### PR TITLE
Add additional_compiler_inputs support to local_defines/defines

### LINKED ISSUE #23885: cc_library.additional_compiler_inputs should be subject to `$(location ...)` substitution
### Description of the feature request:

Consider the following situation. I'm trying to compile libfst from https://github.com/gtkwave/gtkwave/tree/master/lib/libfst

Now, someone had the great idea to do `#include FST_CONFIG_INCLUDE` in fstapi.c here:  https://github.com/gtkwave/gtkwave/blob/master/lib/libfst/fstapi.c#L41

This, of course, conflicts with bazel's idea about file placement.  I added the file `config.h`, but it wouldn't go into either `srcs` or `hdrs` of the target `:libfst` below:

```
  1 cc_library(                                                                                                                               
  2     name = "libfst",                                                                                                                      
  3     srcs = [ "@libfst//:all_c"],                                                                                                          
  4     hdrs = [ "@libfst//:all_h",],                                                                                                         
  5     deps = [                                                                                                                              
  6     ¦   "//third_party/libjudy",                                                                                                          
  7     ],                                                                                                                                    
  8     defines = [                                                                                                                           
  9     ¦   'FST_CONFIG_INCLUDE=\\"third_party/libfst/config.h\\"',                                                                           
 10     ],                                                                                                                                    
 11     additional_compiler_inputs = [                                                                                                        
 12     ¦   ":config",                                                                                                                        
 13     ]
 14                                                                                                                                           
 15
 16 filegroup(                                                                                                                                
 17     name = "config",                                                                                                                      
 18     srcs = [ "config.h" ],                                                                                                                
 19 )                                                                                                                     
 14 )     
```

I wanted to define `FST_CONFIG_INCLUDE=\\"$(location :config)\\"`, but this would not do because `additional_compiler_inputs` is not subject to `$(location ...) ` substitution apparently. Placing the file elsewhere, e.g. in deps would allow it, but since deps requires `CCInfo` or some such, then I can't place the filegroup there. The `:config` target can not be a `cc_library` since that leads to:

```
ERROR: /home/fmil/tmp/bazel_delib/third_party/libfst/BUILD.bazel:1:11: in cc_library rule //third_party/libfst:libfst: label '//third_party/libfst:config' in $(location) expression expands to no files
```

### Which category does this issue belong to?

_No response_

### What underlying problem are you trying to solve with this feature?

I want to refer to a `$(location)` in a `cc_library.defines`.

### Which operating system are you running Bazel on?

Linux. I don't think that maters.

### What is the output of `bazel info release`?

╰─>$ bazel info release release 7.3.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/bazelbuild/bazel/issues/23885

### CODE REVIEW

**Review by kernhanda — APPROVED** [review]

**Comment by keith** [comment]
I'm less sure about `defines` here, I think `local_defines` is very reasonable though, general thoughts?

**Comment by fmeum** [comment]
> I'm less sure about `defines` here, I think `local_defines` is very reasonable though, general thoughts?

`local_defines` seems reasonable to me, but I would suggest disabling expansion for `defines`. There is no way to add files to downstream compilation actions, so it also wouldn't make sense to emit paths into them.

**Comment by keith** [comment]
yea makes sense, done

**Review by fmeum — APPROVED** [review]

**Review by oquenchil — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Comment by fmeum** [comment]
@oquenchil Should this receive the "awaiting-merge" label or are you importing it yourself?

**Comment by satyanandak** [comment]
Hi @oquenchil @pzembrod ,  Since I can see that this PR has been approved, Please let us know whether gTech team should proceed with importing it. Thanks!"

**Comment by fmeum** [comment]
@pzembrod Friendly ping

**Comment by fmeum** [comment]
@oquenchil @pzembrod Friendly ping, I need this for further path mapping work and it has already been approved.

**Comment by iancha1992** [comment]
@oquenchil or @pzembrod could you please review this one? Thanks!

**Review by pzembrod — APPROVED** [review]
Big apologies for missing this for so long!

**Comment by fmeum** [comment]
@bazel-io fork 8.0.0

**Review by ortstadtthomas91-coder — APPROVED** [review]

**Pull request closed without merging**
