### PR TITLE
Add tests for nested set collision handling in the compact execution log

### PR DESCRIPTION
**Pull request by fmeum**
In a pathological case relying on reference equal `SymlinkEntry` instances, the compact and expanded execution log can differ. Such cases can only be constructed with `--nobuild_runfile_manifests`, which is deemed acceptable.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @tjgq for after you return

**Comment by fmeum** [comment]
@meisterT I found this while working on a consuming application, but I would personally consider it too much of an edge case to fix as it would require a more verbose proto representation.

**Review by meisterT — APPROVED** [review]

**Comment by iancha1992** [comment]
@fmeum I can't make the call on the conflict with the `execRoot` variable. Could you please resolve the conflict?

**Comment by fmeum** [comment]
@iancha1992 I resolved it

**Pull request closed without merging**
