### PR TITLE
Flip incompatible_use_host_features to true

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by keith** [comment]
@oquenchil do you think we'll want to do this before 7.0, or between 7.0 and 8.0?

**Comment by oquenchil** [comment]
I think we can do before 7.0

**Comment by katre** [comment]
Is this still waiting for a review? And, if so, will you be reviewing @oquenchil?

**Comment by keith** [comment]
yea waiting on whenever you want to flip

**Comment by oquenchil** [comment]
@jyknight can this be flipped already?

**Comment by jyknight** [comment]
I have no objection. (And Google already enabled the flag internally.)

**Review by oquenchil — APPROVED** [review]

**Comment by keith** [comment]
@oquenchil thanks for the review! can you land?

**Pull request closed without merging**
