### PR TITLE
Zipalign the incremental APK before install

### PR DESCRIPTION
**Pull request by Bencodes**
This addresses https://github.com/bazelbuild/bazel/issues/13050 which prevents the incremental APK from being installed on Android 11 devices due to the fact that the contents of the APK are not aligned on a 4-byte boundary.

### CODE REVIEW

**Comment by Bencodes** [comment]
@ahumesky mind taking a look at this so we can get it cherry picked into the 4.2.0 release?

**Comment by Bencodes** [comment]
Split APK installs are also broken https://github.com/bazelbuild/bazel/pull/13718

**Comment by ahumesky** [comment]
Thanks, I'll start the import on this fix

**Comment by ahumesky** [comment]
Unfortunately this change is failing an internal test, and in somewhat surprising way, so it might take a little while to debug.
And same for https://github.com/bazelbuild/bazel/pull/13718

**Comment by Bencodes** [comment]
@ahumesky have you been able to root cause that internal test failure?

**Pull request closed without merging**
