### PR TITLE
added self-signed TLS certificates for remote cache tests via TLS

### PR DESCRIPTION
**Pull request by ishikhman**
part of #7999

### CODE REVIEW

**Comment by aiuto** [comment]
Why is this third_party? Did you actually take the certs from the gRPC site or did you generate them using their technique? If you generated them, they should just part of our source tree.

**Comment by ishikhman** [comment]
> Why is this third_party? Did you actually take the certs from the gRPC site or did you generate them using their technique? If you generated them, they should just part of our source tree.

Right, like you said, they are generated using the instructions from gRPC examples repo. Jakob told me that it belongs to the third_party anyways. @buchgr ?

**Comment by buchgr** [comment]
I am fine with putting them into the source tree as well. Put them in src/test/testdata maybe?

**Comment by ishikhman** [comment]
Great, closing this PR and moving certs back to the source tree. Thanks @buchgr, @aiuto

**Pull request closed without merging**
