### PR TITLE
Fix message generation of `ActionExecutionException`

### PR DESCRIPTION
**Pull request by fmeum**
This fixes an issue introduced by commit f95b80d166eb46ba4e4c0fb4b998f6e12206ee17, which resulted in certain exception message being printed twice.

### CODE REVIEW

**Comment by fmeum** [comment]
@meteorcloudy Modifying exception messages may have been naive. I noticed that this ended up duplicating messages in other places, e.g. the one emitted by the `TEST_SHARD_STATUS_FILE` check.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 6.2.0

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Pull request closed without merging**
