### PR TITLE
[credentialhelper] Update flag doc to point to more convenient usage instructions

### PR DESCRIPTION
**Pull request by Yannic**
Arguably, we should have a dedicated page for this on `bazel.build`, but until we have that, this post seems like a better source for users than the original design doc.

### CODE REVIEW

**Comment by tjgq** [comment]
@bazel-io fork 7.1.0

**Review by tjgq — APPROVED** [review]

**Review by tjgq — CHANGES_REQUESTED** [review]
While the blog post clarifies how to *use* a credential helper, it doesn't describe how to *write* one. But I agree that the proposal isn't the right artifact to link to. How about we also link to https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md?

**Comment by Yannic** [comment]
> While the blog post clarifies how to _use_ a credential helper, it doesn't describe how to _write_ one. But I agree that the proposal isn't the right artifact to link to. How about we also link to https://github.com/EngFlow/credential-helper-spec/blob/main/spec.md?

SG, done. PTAL

**Review by tjgq — APPROVED** [review]

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
