### PR TITLE
Enhance documentation search experience (adding DocSearch)

### PR DESCRIPTION
**Pull request by s-pace**
bazelbuild/bazel#4600

It will enhance the search experience, you can have a look on the quick preview:
http://bazel-preview.surge.sh/

[Reference about DocSearch](https://community.algolia.com/docsearch/)

### CODE REVIEW

**Comment by s-pace** [comment]
cc @laurentlb  @jin @spomorski

**Comment by laurentlb** [comment]
cc @jhfield

**Comment by s-pace** [comment]
Happy to help in any way

**Comment by s-pace** [comment]
👋 @jhfield and @laurentlb 

Do you need any help on this one? 

Happy to have any feedback

**Comment by s-pace** [comment]
I have improved the showcase https://docsearch-bazel.netlify.com

Feel free to ping me if you need anything?

**Comment by jin** [comment]
@s-pace thanks for prototyping it and creating this pull request. I don't think we'll be merging this for now, but we may revisit it in the future.

**Pull request closed without merging**
