### PR TITLE
Properly escape GitHub repository download URL for git_repository w/ sha256

### PR DESCRIPTION
**Pull request by akira-baruah**
Addresses #3661

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
Jenkins: test this please.

**Comment by mhlopko** [comment]
Can this be merged?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
Thank for the ping I forgot it. I'll merge it tomorrow morning.

**Comment by damienmg** [comment]
importing right now, sorry I forgot about it.

**Comment by akira-baruah** [comment]
@dslomov do you happen to know what about these changes broke the `rules_docker` repo as described in the rollback commit?

I built `bazel` at commit 0a63dadf4eafbae1730f88644b0c537fb1c16d5c (which was rolled back) and used that version to run both `bazel build //...` and `bazel test //...` successfully in the `rules_docker` repo at commit 59431b85f0f1ecf4be99bdcc11f599b8916f9f9f (current HEAD).

I'll look at the error logs a bit more to see if I can write a fix.

**Comment by dslomov** [comment]
https://ci.bazel.io/blue/organizations/jenkins/Global%2Frules_docker/detail/rules_docker/243/pipeline/ is the CI failure.
I was able to reproduce this locally on Linux and bisected the failure to 0a63dad.
My repro steps were `bazel clean --expunge && bazel build //...` under rules_docker checkout.

**Comment by akira-baruah** [comment]
Thanks for the repro details @dslomov !

I was able to repro the issue and I think I've found the source of the bug. I'll explain in the original issue #3661 and submit a new PR.

**Pull request closed without merging**
