### PR TITLE
Use rules_jvm_external to fetch turbine

### PR DESCRIPTION
**Pull request by cushon**
Instead of checking in a precompiled jar, following the example of https://github.com/bazelbuild/bazel/pull/17112

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]
Awesome, thanks!

**Comment by meteorcloudy** [comment]
@iancha1992 Can you first import the non-third party change, then the third party change?

**Comment by Pavank1992** [comment]
Hi @cushon, Could you please help us in resolving the conflict?

**Comment by cushon** [comment]
> Hi @cushon, Could you please help us in resolving the conflict?

Done

**Comment by meteorcloudy** [comment]
Reopen until the third party change is also merged.

**Comment by fmeum** [comment]
The third_party change wasn't merged correctly and was reverted as part of the following commit: https://github.com/bazelbuild/bazel/commit/2482322fedb463e0bbecd29c5e8e6d0f087ed884

This currently breaks CI on master.

**Comment by meteorcloudy** [comment]
This is now merged and the breakage has been fixed.

**Pull request closed without merging**
