### PR TITLE
Move Java runfiles library out of Bazel

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@hvadehra The CI failures on this PR look like they shouldn't be related to my changes, did something else change?

**Comment by hvadehra** [comment]
Should go through in https://github.com/bazelbuild/bazel/pull/24391

**Review by hvadehra — APPROVED** [review]

**Comment by hvadehra** [comment]
@fmeum resolve conflicts please?

**Comment by hvadehra** [comment]
As it turns out, this is not so easy to import. There is a divergence between the internal BUILD files and one's being changed here.

Also the (deleted) files are still used internally, and simply pointing them to the internal `rules_java` copy doesn't work since we made those bazel only. Changing the latter is going to involve some complex copybara, at the very least for the tests.

@meteorcloudy Thoughts?

**Comment by meteorcloudy** [comment]
Hmm, eventually we do want to use the runfiles library from rules_java both internally and externally, right? If this is not going to make it for Bazel 8, we should probably spend some time on untangling the copybara setup?

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
(for 8.1.0)

**Comment by iancha1992** [comment]
@bazel-io fork 8.1.0

**Comment by fmeum** [comment]
> It is off topic, but can we also kill JAVA_RUNFILES during the process? There is a TODO to kill it but nobody did it yet.

Yes, we should, but that affects all runfiles libraries as well as Bazel itself. I would say that getting rid of `RUNFILES_MANIFEST_ONLY` has higher priority though.

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 8.1.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.1.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.1.0rc1`. Thanks!

**Pull request closed without merging**
