### PR TITLE
Add feature definition for `static_link_cpp_runtimes` in unix cc toolchain config

### PR DESCRIPTION
**Pull request by yuzhy8701**
`static_link_cpp_runtimes` is one of the well-known features - which is required if you want to link in non-default toolchain libs. However the default unix toolchain does not define it at all.

This PR adds a simple definition of this feature. The added feature is disabled by default to avoid negative impacts, and can be enabled on demand.

### CODE REVIEW

**Review by oquenchil — APPROVED** [review]

**Comment by sgowroji** [comment]
Hi @yuzhy8701, Could you please fix the above buildkite checks. As the PR is awaiting to merge. Thanks!

**Comment by yuzhy8701** [comment]
The test failures are complaining not finding python:

```
AssertionError: Could not find python binary: python
```

I don't think they are related to my change - more like an infra issue.

I can rebase the changes and try again.

**Comment by kishorenc** [comment]
Will this PR fix https://github.com/bazelbuild/bazel/issues/14342?

**Comment by yuzhy8701** [comment]
> Will this PR fix #14342?

No. This PR only defines the feature, but does not add the `-static-libstdc++` flag. So users would still need to define flags in the linkopts as if the feature is not enabled. Actually, I think this feature should be renamed, since all it provides by default is linking the libs you provide in `static|dynamic_runtime_libs`.

**Pull request closed without merging**
