### PR TITLE
make included gflags library py3 compatible

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
Use the print() function from future and use the "as" syntax for catching exceptions

One quick and dirty solution for #3124

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by katre** [comment]
Jenkins, test this please.

**Comment by meteorcloudy** [comment]
LGTM, I'll import this.

**Comment by meteorcloudy** [comment]
@ahumesky @katre Do you also think it's OK to merge this change? If so, I'll push to oss.

**Comment by katre** [comment]
The changes look good. Do we have a general policy about changes in third_party? Should third_party always match the upstream project's release, or are patches such as this fine?

**Comment by meteorcloudy** [comment]
AFAIK, it's not required to match the upstream release, @laszlocsomor did some change to protobuf to make it build with MSVC. But I think it's better to keep the difference as small as possible, so @MarkusTeufelberger  Can you also send a PR to https://github.com/gflags/gflags?

**Comment by MarkusTeufelberger** [comment]
No, because that's not the correct project. ;-)

https://github.com/google/python-gflags is the actual upstream, and it is far beyond the vendored version in Bazel. As far as I see they already added Python3 support a while ago.

**Comment by meteorcloudy** [comment]
@MarkusTeufelberger I see, thanks! I think we can just merge this change.

**Comment by meteorcloudy** [comment]
Pushed. Thanks for the PR!

**Comment by MarkusTeufelberger** [comment]
Update in #3124 - https://bazel-review.googlesource.com/c/8250/ seems to solve this in a much nicer way (no internal fork), please check it out. :-)

**Pull request closed without merging**
