### PR TITLE
Find `libtool` when using `BAZEL_USE_CPP_ONLY_TOOLCHAIN`.

### PR DESCRIPTION
**Pull request by uri-canva**
Instead of hardcoding `/usr/bin/libtool` which requires Xcode / Xcode CLT installed, which `BAZEL_USE_CPP_ONLY_TOOLCHAIN` is meant to avoid.

Related to https://github.com/bazelbuild/bazel/issues/16009.

### CODE REVIEW

**Review by oquenchil — APPROVED** [review]
LGTM. Thank you!

**Comment by oquenchil** [comment]
Failing on Windows, can you take a look: https://buildkite.com/bazel/google-bazel-presubmit/builds/61941#01851b5c-fbda-413a-a1c6-0b4b8dde0ed2 ?

**Comment by oquenchil** [comment]
Never mind, broken at head it seems.

**Comment by kshyanashree** [comment]
@bazel-io fork 6.1.0

**Pull request closed without merging**
