### PR TITLE
add ".dll.a"

### PR DESCRIPTION
**Pull request by kekxv**
update `INTERFACE_SHARED_LIBRARY`.
Need to connect `dll.a` when use `mingw`.

### CODE REVIEW

**Review by comius — CHANGES_REQUESTED** [review]
Tests are not passing. Please also provide reference to the issue / why the change is needed.

**Comment by kekxv** [comment]
> Tests are not passing. Please also provide reference to the issue / why the change is needed.

@comius  

cmake build shared dynamic will get dll.a when use mingw on linux.

Tests are not passing Because previous commit could not pass.

**Comment by comius** [comment]
> cmake build shared dynamic will get dll.a when use mingw on linux.

@oquenchil are there any concerns extending this?

> Tests are not passing Because previous commit could not pass.

Please rebase and push your changes.

**Comment by kekxv** [comment]
> > cmake build shared dynamic will get dll.a when use mingw on linux.
> 
> @oquenchil are there any concerns extending this?
> 
> > Tests are not passing Because previous commit could not pass.
> 
> Please rebase and push your changes.

ok

**Comment by kekxv** [comment]
@comius  https://github.com/bazelbuild/bazel/pull/13836

**Pull request closed without merging**
