### PR TITLE
`alwayslink` documentation fix.

### PR DESCRIPTION
**Pull request by excitoon**
See https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.alwayslink .

### CODE REVIEW

**Comment by excitoon** [comment]
@meteorcloudy You may want to know about this.

**Comment by excitoon** [comment]
@irengrig Why is it WIP? This is a complete fix from my point of view. It may worth checking if there are such things in other place though.

**Comment by meteorcloudy** [comment]
@excitoon Sorry for the delay here, I'm importing this change right now.

**Comment by irengrig** [comment]
@excitoon it means that the PR is already in work ("work in progress"). As @meteorcloudy was already taking care of it, I marked the PR.

**Pull request closed without merging**
