### PR TITLE
Use proper logging for "Reading 'startup' options" message

### LINKED ISSUE #2530: Can't suppress "Reading 'startup' options" print
The following line of code prints directly to `stderr`, completely circumventing the standard logger levels. 
Please replace this with the usual `BAZEL_LOG(INFO) << ` as used above in the same `Parse` function.

https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/option_processor.cc#L163

### PR DESCRIPTION
**Pull request by kersson**
Fixes #2530 and may help with #2279.

Setting up the CLA with my company in parallel.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by kersson** [comment]
We're having trouble getting our corporate CLA signed.  Our Authorized Signer never received the email with the link to electronically sign and when I try to resubmit it says "It looks like you've already signed this CLA" (see screenshot below).  Who can we contact to resolve this issue?

screen shot 2017-04-24 at 1 14 17 pm

**Comment by damienmg** [comment]
Sorry for the delay

**Comment by kersson** [comment]
CLA should be all set. Thanks!

**Comment by willnorris** [comment]
It [still needs to be reviewed by legal on our side](https://cla.developers.google.com/about#start-contributing), so just a bit longer.

**Comment by lberki** [comment]
Looks good!

**Comment by lberki** [comment]
Actually, no, I spoke too early :( We deemed these messages internally useful even if logging is switched off (which is most of the time), so we left them here.

@cvcal has a bit more context on this, so forwarding this code review to her.

**Comment by lberki** [comment]
..or I would, if she was set up properly. Then bumping the pull request back to @damienmg  so that he can put her in the Bazel org and assign the issue to her.

**Comment by kersson** [comment]
@lberki how do you turn logging on at this point in the startup so this message would be visible? Interested to hear more context on this issue. Sounds like this issue gets at a deeper flaw if the normal logging system had to be bypassed, making it difficult/impossible to fully control the output of this tool.

**Comment by cvcal** [comment]
Here's some context, let me know if it doesn't fully answer your question.

To turn on logging, main.cc needs to pass in a log handler to blaze::main(), instead of the current nullptr. src/main/cpp/util/bazel_log_handler.cc works for this, and handles log statements by printing them to a file, once SetLogfileDirectory is called, or dumping the buffer to stderr at client close. It was done this way to allow the log file to go into output_base, which the client doesn't immediately know. 

Unfortunately, this is not turned on by default because of a number of remaining concerns, notably that having 1 log file per output base could be a problem if there are multiple clients with the same user & workspace, since they would be trying to log to the same file. There are ways to fix this, but instead of rolling our own, we were waiting for some other changes that would make this logging framework essentially obsolete. Personally, I would be happy to make BAZEL_LOG just print to stderr for all log statements, and have it on by default for Bazel, but users would complain about the terminal spam, and there isn't a good way for them to modulate the verbosity, so that isn't a good option. We have verbosity controls for the java code, and requiring a different flag for the client is not very helpful, so ideally, all log statements from the client would be redirected to the proper file for debugging, and the client would be silent on the terminal (except for errors/fatal logs).

The more this comes up, the more I think I should probably remove the BAZEL_LOG code entirely, it's confusing in its current state...

**Comment by damienmg** [comment]
@cvcal is now in the org, assigning it to her :)

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by cvcal** [comment]
I don't think this is mergeable as is, until BAZEL_LOG is activated or replaced. As much as possible, the bazel client shouldn't be in the job of printing any information to the command line, because of the implied double verbosity flag interface I mentioned above.

For this specific log message, and the two bugs you mentioned, the server should be given this information and print it out under the same verbosity control as the rest of the terminal output, and we have a pending change internally to make this happen. If it wasn't for the BAZEL_LOG problem, this would be fine as a temporary fix until the server change made it obsolete, but unfortunately that isn't the case. Thanks @kersson, sorry for the delay and confusion!

**Pull request closed without merging**
