### PR TITLE
Switch proguard over to 6.2.2

### PR DESCRIPTION
**Pull request by Bencodes**
Pulling this out #12509 so that it's easier to merge and sync

This will need to be rebased after https://github.com/bazelbuild/bazel/pull/12909 is merged.

### CODE REVIEW

**Comment by Bencodes** [comment]
@ahumesky @philwo can you take a look at this?

**Comment by ahumesky** [comment]
@philwo is out of office for the rest of the week, @meteorcloudy can you take a look?

**Review by meteorcloudy — CHANGES_REQUESTED** [review]
Looks good, can you rebase the branch to fix the tests?

**Comment by Bencodes** [comment]
Should be good to go once CI passes.

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
