### PR TITLE
Adding toolchain support for j2objc protos

### PR DESCRIPTION
**Pull request by mikelikespie**
Ran into an issue where it wasn't possible to add protos to blacklist for j2objc toolchain and was getting duplicate symbols for the descriptor protos.

This change should make it consistent with the other proto rules which use a toolchain. Was able to remove bespoke and uncustomizable proto blacklist for j2objc.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mikelikespie** [comment]
@googlebot I work for Square, Inc. which has a corp. CLA signed.

**Comment by philwo** [comment]
@calpeyser Friendly ping - could you please review this pull request? :)

**Comment by calpeyser** [comment]
@mikelikespie I'm sorry for the extensive delays on this PR.

The issue is that this change needs testing.  We have some internal tests for j2objc, which we are working on open-sourcing.

**Comment by mikelikespie** [comment]
@calpeyser Thanks! btw, this PR is related (but not assigned to you) https://github.com/bazelbuild/bazel/pull/4058

**Comment by mikelikespie** [comment]
@calpeyser Sorry to bother you, but is there any update on possibly getting this reviewed (and possibly #4058)? We're trying to use this j2objc/protos for a project, and having to use (and maintain) a forked version of bazel has a decent cost/added risk for us. Let me know if there's anything we can do to facilitate getting these patches upstream.

Thanks! Mike

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by calpeyser** [comment]
Hey @mikelikespie - I'm very sorry about the wait.  We're working on sorting out some differences between the j2objc implementation internally vs. externally.  Once we're through with that, we should be able to open source some test cases, which will allow this change to be completed.

**Comment by laszlocsomor** [comment]
ping @calpeyser @c-parsons

**Comment by c-parsons** [comment]
Apologies - was out on vacation last week. Will take a look today or tomorrow.

**Comment by lfpino** [comment]
Hi @c-parsons @calpeyser, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by mikelikespie** [comment]
@lfpino We (at square) would really like this patch to get merged still. Please let me know if there's anything we can do else to get it through the finish line.

**Comment by mikelikespie** [comment]
@calpeyser thanks! no worries. Just pushed an update w/ merge conflicts resolved

**Comment by calpeyser** [comment]
Can an admin please merge?

**Comment by laszlocsomor** [comment]
@calpeyser : FYI, you should be an admin too. If that's not true, let @philwo know.

**Comment by calpeyser** [comment]
(Actually we should wait a moment before merging - we have a quick bug fix to do first)

**Comment by c-parsons** [comment]
Yep, finally got this pushed through internally :) Sorry for the delay, and let me know if there's anything else I can do to help.

**Comment by mikelikespie** [comment]
@c-parsons Thanks! I don't see the change for this PR on master, just want to make sure closing this didn't get confused with #4793 . (I keep getting confused myself)

**Pull request closed without merging**
