### PR TITLE
[WIP] Replace HOST transition with EXEC transition for Starlark rules.

### PR DESCRIPTION
**Pull request by susinmotion**
PiperOrigin-RevId: 415128765
Change-Id: Iec1a69149b41444f090ec04d24fdbdd4ca0a81bf

### CODE REVIEW

**Comment by sgowroji** [comment]
Hello @susinmotion,  This PR is in draft, Do we have any update on this?. Thanks!

**Comment by susinmotion** [comment]
This was a draft for testing. The code was committed in https://github.com/bazelbuild/bazel/commit/6e6c4cf1bd6edaa15ecc4417cd0be70581181def

**Comment by sgowroji** [comment]
@susinmotion  So can we close this PR now?

**Comment by susinmotion** [comment]
Yes.

**Pull request closed without merging**
