### PR TITLE
Windows: native test wrapper can run simple tests

### PR DESCRIPTION
**Pull request by laszlocsomor**
The Bash-less test wrapper can now run simple
tests, indicate passing or failing as needed, and
print the test's output.

There's still more work to make the test wrapper
feature-compatible with test-setup.sh, but this
commit already makes good progress.

See https://github.com/bazelbuild/bazel/issues/5508

Change-Id: If5fb473d09323969db34ee381f1b54354fb6a97d

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Looks like //src/test/shell/bazel:bazel_bootstrap_distfile_test is failing due to this change.

**Comment by laszlocsomor** [comment]
PTAL. Should be fixed now.

**Comment by laszlocsomor** [comment]
Thanks! The import pipeline will automatically rebase it.

**Comment by meteorcloudy** [comment]
Sounds good

**Pull request closed without merging**
