### PR TITLE
Change pkg_tar behavior to keep current permissions of files

### LINKED ISSUE #2925: Problems with pkg_tar file permissions
### Description of the problem / feature request / question:

`pkg_tar` is unable to preserve the mode of files being packaged and makes everything executable by default. The following should be fixed:

- [ ] The default mode should be `None`, not `"0555"`. Making *everything* executable *by default* is just **wrong**. (Implies not passing `--mode` to `build_tar.py` in such case.)
- [ ] When no `--mode` is passed to `build_tar.py`, the *actual* permissions of the original file (at least on platforms that support POSIX permissions) should be used. (Currently, there is a simple check that forces the mode to either `0644` or `0755`.)
- [ ] Ability to specify symbolic modes (e.g. 'u+w'), as supported by `tar`, would be nice.
- [ ] Ability to preserve/set XATTRs and/or ACLs would be nice too.

### Environment info
* Operating System: Fedora 25
* Bazel version (output of `bazel info release`): 0.4.5- (@non-git) compiled from `bazel-0.4.5-dist.zip` (sha256 2b737be42678)

### PR DESCRIPTION
**Pull request by zlalanne**
Changes the default behavior of pkg_tar to not modify file permissions before
putting the files in an archive unless requested. Now by default pkg_tar will
keep the current permissions on a file unless the user specifies a mode.

This fixes #2925.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by zlalanne** [comment]
I signed it!

**Comment by damienmg** [comment]
Jenkins: test this please.

This looks reasonable to me.

**Comment by damienmg** [comment]
jenkins retest this please.

**Comment by damienmg** [comment]
Bootstrapping fails on darwin because wrapped_clang does not have the x mode now...

**Comment by zlalanne** [comment]
jenkins retest this please.

**Comment by mattmoor** [comment]
@damienmg Do we have any testing of the impact of this on `rules_docker`?  I suspect this could be breaking to some users.

**Comment by damienmg** [comment]
Don't we have the dep in internal testing? 

The docker test where still there and did not broke, they got removed this morning though.

[jenkins] test this please

**Comment by mattmoor** [comment]
@damienmg We haven't unforked `build_tar.py` in `rules_docker` because it takes a Bazel release cycle before the upstreamed changes are available. :(

**Comment by zlalanne** [comment]
Anything I can do here? Having trouble understanding what failed? Seems like something related to freebsd?

**Comment by damienmg** [comment]
So the distribution artifact does not add +x flag to tools/cpp/clang_wrapper (or something like that) and so it fails to executed where it is used (freebsd and darwin). Just set tools/cpp/clang_wrapper should fix the issue.

**Comment by zlalanne** [comment]
Can this get tested again?

**Comment by damienmg** [comment]
jenkins: test this please

**Comment by damienmg** [comment]
jenkins: retest this please

**Comment by damienmg** [comment]
FTR it passes all our tests internally so it should be merged in the following days. Sorry for taking so long.

**Comment by zlalanne** [comment]
Thanks, I definitely still need this so let me know if I can do anything. Everything seems to pass when I run bazel test locally but not sure if I was doing something wrong

**Comment by damienmg** [comment]
An update: this needs to fix some project internally, so it will take some time before I can get to it.

**Comment by mhlopko** [comment]
Friendly ping @damienmg, are internal changes done?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
No, see cl/168508781

**Comment by zlalanne** [comment]
Any update on this?

**Comment by damienmg** [comment]
Hello,

Unfortunately I had no time to do the work yet. We have the Bazel Conference next week so it is unlikely I can do that in the following weeks.

Sorry for such delays.

I had one thought that could make the import simple: have an option to build_tar (on by default) that maintains the old permission settings (pkg_tar would deactivate that). The problems is with the interaction with rules_docker, but if default behavior of build_tar doesn't change, it should be possible to import it directly.

**Comment by damienmg** [comment]
Reassigning to Marcel as I am leaving the Bazel team.

**Comment by zlalanne** [comment]
I'm still interested in this and can do the work. Like suggested above, maybe we can change the functionality of the "mode" parameter so that if it sees the work "keep" it will keep the current permissions on the filesystem. It won't be the default but can be opt-in. That way the docker rules arn't broken and the default behavior doesn't change.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by davidstanke** [comment]
ping @mhlopko -- what's the next step here?

**Comment by ulfjack** [comment]
We don't rerun actions if only the file system permissions change, making this change a bit risky. I'd recommend to have the default be 0555 and providing a mode to keep the fs permissions, as suggested above, with a big warning that Bazel does not rebuild on permissions-only changes.

**Comment by laszlocsomor** [comment]
@ulfjack  and @zlalanne : please advise what we should do with this PR -- merge, rework, or abandon?

**Comment by zlalanne** [comment]
Maybe we can abandon this one. I've started to just use the "mode" parameter in pkg_tar explicitly to set exact permissions for all files I'm packaging.

**Comment by mhlopko** [comment]
Ok, thank you for your contribution!

**Comment by cmoore3** [comment]
The current `mode` implementation is not intuitive.  It's disappointing to see the change get worked so far only to be closed.

If pkg extraction under Bazel needs a particular set of permissions, it can (and probably already does) do that part.  The tarball should grab the permissions as they are by default--but at least having the option to do that would be sufficient.

My use case is that I'm using `pkg_tar` to put files into a `container_image` and then doing various checks on the imported files to gather feedback for developers.  Feedback like "This source file should not be executable."  Unfortunately, that test is not something I can do inside the container (without writing a custom rule).

**Pull request closed without merging**
