### PR TITLE
java_lite_proto_library: respect ProtoLangToolchainProvider.forbiddenProtos()

### LINKED ISSUE #13928: lang_proto_toolchain behaving inconsistently for javalite vs java toolchains RE: blacklisted_protos
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, or a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

I'm attempting to use the `blacklisted_protos` argument of `lang_proto_toolchain` and getting inconsistent behavior between java and javalite toolchain definitions.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

The diff we've made is here:
https://github.com/protocolbuffers/protobuf/pull/8942

we've been testing dupes with this reproducer: https://github.com/eikemeier/proto-java
Simply pull this PR, and use `local_repository` in the WORKSPACE of this reproducer to get our results.

For java_proto_library we get no dupe warnings, but for java_lite_proto_library we're getting dupe warnings for `@com_google_protobuf//:timestamp_proto`.

We _were_ seeing that as well in main, but properly configuring `blacklisted_protos` fixed java but not lite for some reason.

### What operating system are you running Bazel on?

MacOS

### What's the output of `bazel info release`?

release 4.0.0

###  Have you found anything relevant by searching the web?

Nope.

### PR DESCRIPTION
**Pull request by Yannic**
Fixes #13928

### CODE REVIEW

**Comment by Yannic** [comment]
@comius PTAL

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
Wow one liner. Nice work, thanks!

**Review by comius — CHANGES_REQUESTED** [review]
There's a NPE, it should be easy to fix:
Caused by: java.lang.NullPointerException
	at com.google.devtools.build.lib.rules.java.proto.JavaProtoAspectCommon.shouldGenerateCode(JavaProtoAspectCommon.java:210)
	at com.google.devtools.build.lib.rules.java.proto.JavaLiteProtoAspect$Impl.addProviders(JavaLiteProtoAspect.java:173)
	at com.google.devtools.build.lib.rules.java.proto.JavaLiteProtoAspect.create(JavaLiteProtoAspect.java:95)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createAspect(ConfiguredTargetFactory.java:558)
	at com.google.devtools.build.lib.skyframe.AspectFunction.createAspect(AspectFunction.java:893)
	at com.google.devtools.build.lib.skyframe.AspectFunction.compute(AspectFunction.java:490)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:560)

**Comment by Yannic** [comment]
Fixed. Looks like tests aren't open sourced :(

**Comment by comius** [comment]
> Fixed. Looks like tests aren't open sourced :(

That's true. We're working on open sourcing them. It should happen next year.

**Review by comius — APPROVED** [review]

**Pull request closed without merging**
