### PR TITLE
Fix choco integrity check

### PR DESCRIPTION
**Pull request by petemounce**
This causes a hard-fail. I'm attempting to publish a fixed package now, but chocolatey.org is failing with a `502 Bad Gateway`. I'm talking to the chocolatey team in their gitter now.

I'll update here once I've been able to push.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by petemounce** [comment]
@dslomov please wait, there's a problem.

**Comment by petemounce** [comment]
OK - published to https://chocolatey.org/packages/bazel/0.4.5.20170330

**Comment by dslomov** [comment]
Oops, I think I merged the wrong version. Please resubmit the changes in another PR

**Pull request closed without merging**
