### PR TITLE
Bump python-gflags to 3.1.0, take two.

### PR DESCRIPTION
**Pull request by spxtr**
[c/8250](https://bazel-review.googlesource.com/c/8250/) caused [a breakage](http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD,PLATFORM_NAME=windows-x86_64/870/console) on windows. I don't have a windows machine to test this on, so I'll have to lean on Jenkins. Also, changing to GitHub because I am way more familiar with this interface than with Gerrit.

### CODE REVIEW

**Comment by spxtr** [comment]
@damienmg PTAL. I still see lots of failures from android tests, but I'm not sure that those are related to this PR. The windows test that failed to build before is now passing, I think. It's hard to tell what with all the java/android failures.

**Comment by damienmg** [comment]
Ok the failure seems genuine, added the android support experts to look at it and advise.

**Comment by aj-michael** [comment]
The problem is in the jenkins log:

```
no such package '@bazel_tools//third_party/py/six': BUILD file not found on package path and referenced by '@bazel_tools//third_party/py/gflags:gflags'
```

We bundle gflags with bazel into the @bazel_tools repository, but we do not currently do that for six. This CL adds a dep from gflags to six, so we need to bundle six as well. You need to update //src:embedded_tools to have a dep on //third_party/py/six:srcs.

**Comment by damienmg** [comment]
Humm this has to be done as a separate PR because 3rd party and non 3rd party code are like 2 repository for us.

**Comment by spxtr** [comment]
retest this please

**Comment by damienmg** [comment]
Test failure does looks unrelated, good to merge tomorrow, hopefully we do not encounter any more hurdle inside Google.

**Comment by spxtr** [comment]
Thanks :)

**Comment by spxtr** [comment]
@damienmg any update?

**Comment by damienmg** [comment]
Sorry I have been fighting fire the whole week, did not got around to
import it yet.

**Comment by spxtr** [comment]
No worries.

**Comment by damienmg** [comment]
Sorry I haven't got time to deal with it, trying to finish things before going on holidays. Reassigning to @aj-michael. I know they are some concern about version mistchmatch between the version of gflags in google and gflags 3, but so far it is not a problem.

**Comment by dslomov** [comment]
retest this please

**Comment by dslomov** [comment]
CI looks good

**Comment by aj-michael** [comment]
Sorry for the delay, I just realized this was assigned to me and I do not have much time this week.

This change looks fine for Bazel, however, internally we still use the older gflags and I suspect it will not be easy to migrate. I am not sure what the teams thoughts are on trying to keep Bazel compatible with both versions, especially since I suspect the reason to update it in Bazel is to use new features, which will then break internal Bazel.

**Comment by spxtr** [comment]
The reason for using it in Bazel is actually just that the newer version supports python 3. It's not really for any new features.

**Comment by dslomov** [comment]
I'll merge this

**Pull request closed without merging**
