### PR TITLE
Pass the name of the classpath manifest jar to JacocoCoverageRunner

### LINKED ISSUE #21268: [Java] Coverage not collected for some manifest jars
### Description of the bug:

When the classpath of a test is over the [CLASSPATH_LIMIT](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L395), Bazel will create a [manifest jar](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L344) that contains a manifest with an entry of the classpath.

The [JacocoCoverageRunner](https://cs.opensource.google/bazel/bazel/+/release-6.2.1:src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverageRunner.java;l=363) accounts for this and will undo the process to find the classpath during coverage collection. However, one of the checks [(urls.length == 1)](https://cs.opensource.google/bazel/bazel/+/release-6.2.1:src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverageRunner.java;l=368) assumes that the manifest jar is the only jar on the classpath.

If a test has a jar in its `data`, it can also be added to the classpath after the manifest jar. Since the length of the array is greater than 1, the logic is skipped and the coverage collection file is empty.

We were able to resolve this by adding a [patch](https://github.com/uber-common/bazel/commit/701f15ee14a8304164bc6b4cf25afa84bb1daeb7) to our fork, but the solution depends on the naming convention of the manifest jar from the stub template and also the ordering of the classpath, which may not be the most robust/futureproof solution. I wanted to raise this issue in case Bazel team had a better way to resolve it.

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Created reproduction: https://github.com/ckilian867/bazel-coverage-bug 

See README for details

### Which operating system are you running Bazel on?

PRETTY_NAME="Debian GNU/Linux 10 (buster)"  NAME="Debian GNU/Linux"  VERSION_ID="10"  VERSION="10 (buster)"  VERSION_CODENAME=buster  ID=debian  HOME_URL="https://www.debian.org/"  SUPPORT_URL="https://www.debian.org/support"  BUG_REPORT_URL="https://bugs.debian.org/"

### What is the output of `bazel info release`?

$ bazel info release release 7.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

```text
$ git remote get-url origin; git rev-parse HEAD
https://github.com/ckilian867/bazel-coverage-bug.git
a1570f38065822f548cd279eb7e3bf75257d8a59
```
```


### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.


_No response_

### Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11847

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by c-mita**
When the java classpath exceeds the limit, we create a manifest JAR
and pass that on the classpath. JacocoCoverageRunner knows how to
extract information from this JAR. But if another JAR ends up on that
classpath, it confuses the coverage runner which is expecting only a
single jar in this case.

This changes the java_stub_template file to export the name of the
created manifest jar so the coverage runner can extract it.

We also change the template file so the relevant exports don't occur
in the middle of a larger function.

It's possible this is somewhat overengineered and that we could
always rely on the manifest jar always being the first one discovered
by the coverage runner, but it is not totally obvious to me that that
will always be true.

Fixes #21268

### CODE REVIEW

**Comment by c-mita** [comment]
Do we need to handle version-skew between Bazel and java_tools? If so, we may need to add a bit more logic to JacocoCoverageRunner?

**Comment by hvadehra** [comment]
> Do we need to handle version-skew between Bazel and java_tools? If so, we may need to add a bit more logic to JacocoCoverageRunner?

Yes, I think we need to. java_tools / rules_java upgrades happen more frequently than bazel upgrades.

**Comment by c-mita** [comment]
> > Do we need to handle version-skew between Bazel and java_tools? If so, we may need to add a bit more logic to JacocoCoverageRunner?
> 
> Yes, I think we need to. java_tools / rules_java upgrades happen more frequently than bazel upgrades.

Done.

It's not a tested path since the Bazel shell tests always use a fresh build, but I have verified that it should work.

**Comment by hvadehra** [comment]
Just a quick clarification before I properly review, my understanding is this change is currently doing two things:

1. Export the manifest jar path from the stub template and start using that in JacocoCoverageRunner if set.
2. If the above does not apply (i.e. for Bazel versions not including this change), stop assuming there is only one URL and try to identify the jar from the first URL.

Why are we doing (2)? If we think that fixes things, then we don't need (1). My concern is we're subtly altering behavior for currently released Bazel on a java_tools upgrade. Can we not just do (1) and cherry pick that into 7.1?

**Comment by c-mita** [comment]
> Just a quick clarification before I properly review, my understanding is this change is currently doing two things:
> 
> 1. Export the manifest jar path from the stub template and start using that in JacocoCoverageRunner if set.
> 2. If the above does not apply (i.e. for Bazel versions not including this change), stop assuming there is only one URL and try to identify the jar from the first URL.
> 
> Why are we doing (2)? If we think that fixes things, then we don't need (1). My concern is we're subtly altering behavior for currently released Bazel on a java_tools upgrade. Can we not just do (1) and cherry pick that into 7.1?

Whilst I may suspect that 2. fixes things in all cases, I cannot prove it. Hence 1.

Just doing 1. breaks things if java_tools is ahead of Blaze, since we're looking for an environment variable that isn't being set and ignoring the one that is. If that's not a problem then 2. is not needed, which is what I originally asked.

**Comment by hvadehra** [comment]
Sorry, I guess I misunderstood your question about version skew. I meant that in `JacocoCoverageRunner` we can't assume the new variable will be available/exported. 

Assuming we can get this into 7.1, I think it's safer to leave the old behavior as is if the variable isn't set. This should be acceptable as after all, this is long standing (buggy) behavior and not a regression as such. WDYT?

**Comment by c-mita** [comment]
I don't really get the rationale for that and it doesn't simplify the logic at all. The diff is simply:

```
@@ -380,7 +380,7 @@ public class JacocoCoverageRunner {
         System.err.println("Classpath JAR " + wrappedJar + " not provided");
         return null;
       }
-    } else if (jarIsWrapped && urls[0].getPath().endsWith("-classpath.jar")) {
+    } else if (jarIsWrapped && urls.length == 1) {
       classPathUrl = urls[0];
     }
     if (classPathUrl != null) {
```

Regardless, I've done it.

**Review by hvadehra — CHANGES_REQUESTED** [review]
Lets not disable the tests. For the new test case that currently only works for java_tools built at HEAD, maybe exit early if `JAVA_TOOLS == 'released"`?

Also maybe add a TODO to clean up the legacy logic in `java_stub_template.txt` when we update to a new java_tools version that includes this change?

**Comment by c-mita** [comment]
> Lets not disable the tests. For the new test case that currently only works for java_tools built at HEAD, maybe exit early if `JAVA_TOOLS == 'released"`?
> 
> Also maybe add a TODO to clean up the legacy logic in `java_stub_template.txt` when we update to a new java_tools version that includes this change?

Good point on the test; done.

**Review by hvadehra — APPROVED** [review]

**Comment by hvadehra** [comment]
@bazel-io fork 7.1.0

**Pull request closed without merging**
