### PR TITLE
Add Autocomplete Integration to IDE Docs

### PR DESCRIPTION
**Pull request by cpsauer**
This doc lists ways of integrating various IDEs with Bazel. I'm hoping to add an entry for integrating autocomplete systems in IDEs with Bazel. 

[After a bunch of requests from Bazel users, we released our tool that uses aquery to enable clangd-based autocomplete across a wide variety of editors.]

Thanks for your consideration!
Chris
(ex-googler)

### CODE REVIEW

**Comment by aiuto** [comment]
@floriographygoth @hicksjoseph   What do you think about moving this literature about IDE integrations out of the versioned documentation and into the bazel.build web site.

**Comment by cpsauer** [comment]
Seems like a good (if possibly broader and separable) question!

**Comment by cpsauer** [comment]
Hey guys! Sorry to bump, but any chance I could ask for your help in getting this in?
(Pinging only because it's been a couple weeks.)

**Comment by aiuto** [comment]
It's been a few holiday weeks for most people on the team. We'll be ramping back up to work shortly.

**Comment by cpsauer** [comment]
Totally! Happy holidays to all of you :)

**Comment by cpsauer** [comment]
Hey, all. Just following back up. Anything I can do to help on this? I know you guys are busy.

**Comment by aiuto** [comment]
I think we can just accept this for now and move it to the right place and
or fix it later.
I'll work on refactoring the docs so we can move this to
bazelbuild/bazel-website as a distinct project.

I have no way to actually review the content or not. I could look for a
proper reviewer.

**Comment by aiuto** [comment]
@jin:   You edited this page more recently than most of us. Do you have any thoughts? I can do the merge if you LGTM.

**Comment by cpsauer** [comment]
[Thanks so much guys.]

**Comment by jin** [comment]
Seems like a better home for this would be www.bazel.build (or generally, a better way for discover projects in the ecosystem not unlike awesome-bazel). But I don't think we should block this contributions on that -- the page was meant to collect all tools and rules related to IDE, anyway.

**Review by jin — APPROVED** [review]

**Comment by aiuto** [comment]
> Seems like a better home for this would be [www.bazel.build](http://www.bazel.build) (or generally, a better way for discover projects in the ecosystem not unlike awesome-bazel). But I don't think we should block this contributions on that -- the page was meant to collect all tools and rules related to IDE, anyway.

Yes. www.bazel.build is the better place. That needs a reorganization. to allow better sidebar navigation. We're trying to coordinate that with the docs team, who are moving it all to a new serving infrastructure and layout.

**Review by aiuto — APPROVED** [review]

**Comment by cpsauer** [comment]
Sweet! Thanks so much, guys--for this and the awesomeness that is Bazel.

**Pull request closed without merging**
