### PR TITLE
Use local_termination_grace_seconds when testing LinuxSandbox availability

### LINKED ISSUE #18071: linux-sandbox is not available occasionally since Bazel 6.0.0
### Description of the bug:

We noticed that Bazel occasionally (about 5% in our env) fails due to `linux-sandbox` not being available.
```
ERROR: 'linux-sandbox' was requested for default strategies but no strategy with that identifier was registered. Valid values are: [processwrapper-sandbox, standalone, remote, worker, sandboxed, local]
```
It seems that recently a 1s timeout was introduced in checking if `linux-sandbox` available #15414, which might be too tight under load.

In our setup, we disable all other weaker sandboxes for hermeticity, which makes this fail reliably and easy to notice. I suspect this is happening on more environments, but people haven't noticed because of`processwrapper-sandbox` fallback.

CC @meisterT 

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

run Bazel >=6.0.0 with `--spawn_strategy=worker,linux-sandbox` under a heavy load many times.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

_No response_

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by tsawada**
A 1s timeout was introduced in checking whether LinuxSandbox is available, to prevent a complete hangup on broken systems. However, it turned out that it occasionally results in misjudging that linux-sandbox being not available.
`local_termination_grace_seconds` defaults to 15s, which hopefully gives more headroom and configurability in various setups.

Fixes #18071

### CODE REVIEW

**Comment by tsawada** [comment]
CC @meisterT

**Comment by meisterT** [comment]
cc @larsrc-google 

This whole situation sounds like a dilemma to me. Perhaps we need to take a step back and think about other ways to detect whether sandboxing is available?

**Comment by tsawada** [comment]
IMHO, some form of timeout is necessary to prevent complete freezes even when we use other ways to detect sandboxes, but simply it should have large enough headroom so that it'd never affect the normal execution paths on properly setup environments.

**Comment by tsawada** [comment]
I agree there could be a way and that'd be cleaner, but this 1s timeout is currently blocking us from upgrading to v6.0+, and I believe this is affecting more users (by occasionally falling back to weaker sandboxes).
Would it be possible to merge this for now? If you think 30s is excessive, maybe even 10s would make the situation better for us.

**Comment by larsrc-google** [comment]
Actually, let's just do the 30s and see if it saves you. It's pretty rare that the check actually hangs and needs the timeout (https://github.com/bazelbuild/bazel/issues/15373 is the only case we know of). That said, @sluongng's advice on the bug is valid - your system is in a bad shape if running a no-op command takes >1s. One could argue that the 1s timeout works as a warning that something else needs to be fixed, it's just a pretty obscure warning.

**Review by larsrc-google — APPROVED** [review]

**Comment by sluongng** [comment]
This might cause Bazel to start up taking up to 30 seconds to complete though.

At the very least, switch to use `local_termination_grace_seconds` value would make it configurable.

**Comment by sluongng** [comment]
My opinion is that this is one of those "user is holding it wrong (because the tool is hard to hold)" kinda case.

I object to merging the change as is and I would urge the author to follow my comments at https://github.com/bazelbuild/bazel/issues/18071.

For this change to merge, I would prefer if we (a) allow the value to be configurable and (b) leave the default value as-is.
The flag key should be either `local_termination_grace_seconds` or a new key that's close to it as the functionality of the 2 flags is somewhat similar: wait for timeout and kill the sandbox.

**Comment by larsrc-google** [comment]
`local_termination_grace_seconds` is not unreasonable here. The difference between its default and this PR is relatively small. I'll send in a change for that.

**Comment by tsawada** [comment]
@larsrc-google PTAL
Edited the PR title and description. Lmk if this should be another PR.

**Comment by tsawada** [comment]
@larsrc-google ping 😃

**Review by larsrc-google — APPROVED** [review]

**Comment by tsawada** [comment]
@larsrc-google @sgowroji Thanks! It'd be great if this is taken / backported into 6.x releases. Please let me know if there's anything else I should do.

**Comment by sgowroji** [comment]
Hi @larsrc-google, , Since I can see that this PR has been approved, please let me know whether I should proceed with importing it.Thanks!

**Comment by larsrc-google** [comment]
Yes, please import it, and if possible backport to the latest 6.X release.

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.0

**Comment by iancha1992** [comment]
@larsrc-google @sluongng @tsawada 
There is a merge conflict when the cherry-pick to release-6.3.0 was attempted (from src/main/java/com/google/devtools/build/lib/sandbox/BUILD). Could you please submit a PR or let us know what commits to include?

**Comment by tsawada** [comment]
@iancha1992  For release-6.3.0 we only need to cherry-pick 5cac33f3f5d8591a971ce3b6400832279c798a17 . Please skip 39b7d6d42ec0684dd52fbbddf2745646e567e01a

**Pull request closed without merging**
