### PR TITLE
[6.0.0]Implement getDirectoryEntries and readdir for RemoteActionFileSystem.

### PR DESCRIPTION
**Pull request by kshyanashree**
So spawns can read content of directires within action exuection.

Part of https://github.com/bazelbuild/bazel/pull/16556.

PiperOrigin-RevId: 486918859
Change-Id: Ida86e4c927093d26f7f96d2f0c2aa0d1d74cc8a4

### CODE REVIEW

**Comment by coeuvre** [comment]
It seems that there are conflicts when doing the cherry-pick. Can you please cherry-pick https://github.com/bazelbuild/bazel/commit/0a23d46976c3fc999d44fbd1e37732ec2442d485 first?

**Comment by kshyanashree** [comment]
> It seems that there are conflicts when doing the cherry-pick. Can you please cherry-pick [0a23d46](https://github.com/bazelbuild/bazel/commit/0a23d46976c3fc999d44fbd1e37732ec2442d485) first?

Yeah sure! Here is the cherry-picked PR [16722](https://github.com/bazelbuild/bazel/pull/16722). Thanks!

**Comment by coeuvre** [comment]
https://github.com/bazelbuild/bazel/pull/16722 is merged, please rebase. Thanks!

**Comment by kshyanashree** [comment]
Apologizing for accidentally closing this PR. Here is the link of new PR: https://github.com/bazelbuild/bazel/pull/16738. Please review it. Thanks!

**Pull request closed without merging**
