### PR TITLE
Add patch for protobuf 21.7

### PR DESCRIPTION
**Pull request by comius**
Remove old patches and unused aliases.

This PR/patch needs to be merged, before protobuf can be upgraded.

### CODE REVIEW

**Comment by comius** [comment]
Tested with: https://github.com/bazelbuild/bazel/pull/17094

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by comius** [comment]
@sgowroji this needs a github merge

**Comment by sgowroji** [comment]
Hi @comius, Could you please Squash above PR commits into one. Thanks!

**Comment by comius** [comment]
> Hi @comius, Could you please Squash above PR commits into one. Thanks!

Done.

**Comment by sgowroji** [comment]
Merged at 087cb8ba91c7ae350ffd5a7cf339bbda07b120c2

**Pull request closed without merging**
