### PR TITLE
file_test: fix for Windows

### PR DESCRIPTION
**Pull request by laszlocsomor**
Rewrite the file_test rule in
@bazel_tools//tools/build_rules:test_rules.bzl to
use ctx.actions.run_shell instead of running a
shell script.

This way Bazel (on Windows) knows how to run the
code.

See https://github.com/bazelbuild/bazel/issues/6122

Change-Id: I159e5dd8f058f8581a4ce7a5f06242bce16374eb

### CODE REVIEW

**Comment by laszlocsomor** [comment]
PR still needs unit tests. I'll add those later. No review solicited yet.

**Comment by ulfjack** [comment]
Looks fine. What's the plan for testing?

**Comment by laszlocsomor** [comment]
[`//tools/build_rules:test_rules_test`](https://github.com/bazelbuild/bazel/blob/d90ff8e581c91b64672f9bc7cf9e8e7dc63d899d/tools/build_rules/BUILD#L19) should keep passing, which it does.

**Comment by laszlocsomor** [comment]
Ideally we'd test this with release Bazel, i.e. instantiate `file_test` rules for mock input files and assert whether they pass or fail. Alas there's no way to expect a `*_test` rule to fail, i.e. if an expected-to-fail `file_test` would fail, it would fail the "bazel test" run or CI run it was part of.

**Comment by laszlocsomor** [comment]
> Looks fine. What's the plan for testing?

Oh, I guess you mean in the context of: https://github.com/bazelbuild/bazel/pull/6320#issuecomment-427372788

I commented that before adding `//tools/build_rules:test_rules_test`.

**Pull request closed without merging**
