### PR TITLE
Fix singlejar & ijar builds and add tests.

### PR DESCRIPTION
**Pull request by iirina**

### CODE REVIEW

**Comment by iirina** [comment]
@meteorcloudy  I added the tests here and fixed them for the other platforms.

**Comment by meteorcloudy** [comment]
Oh, nice! The tests are also passing on Windows. Does this mean if we build the toolchain again, it will work for RBE on Windows?

**Comment by iirina** [comment]
The tests are disabled on Windows right now:

```
 if "$is_windows"; then
    echo "Skipping test on Windows." && return
 fi
```

I'll submit this and you can rebase your PR afterwards.

**Comment by meteorcloudy** [comment]
Ah... I see. Thanks!

**Pull request closed without merging**
