### PR TITLE
[WIP] Improved swift & module support

### PR DESCRIPTION
**Pull request by mikelikespie**
Looking for feedback. Need to clean up a lot and add tests. Also doesn't completely work yet.

Also IJ reformatted a bunch of stuff I need to revert.

Current state of this is that swift modules still can't resolve their dependencies 

e.g.

```
Frameworks/RxSwift/RxCocoa/Common/CLLocationManager+Rx.swift:11:8: error: cannot load underlying module for 'RxSwift'
import RxSwift
       ^
Target //Frameworks:RxCocoa failed to build
```

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
Please resolve the conflicts. :)

**Comment by damienmg** [comment]
Hi there, this is a large change and already conflicts have emerged. Maybe open up discussion on bazel-dev@?

Also pinging @c-parsons so he can bring the good persons to discuss that change (and assigning)

**Comment by mikelikespie** [comment]
@damienmg thanks for the feedback. I'm planning on breaking this up into separate atomic PRs soon. I updated the conflicts (and whitespace noise). Also started a conversation with @c-parsons as suggested.

Thanks!

**Comment by damienmg** [comment]
Assigning to Chris as he willl do the follow-up so next sheriff knows someone is following that work

**Comment by laszlocsomor** [comment]
Gentle ping @mikelikespie : would you still like to get this change in?
Similarly soft ping @c-parsons : is there any ongoing discussion about this PR? Can we close it?

**Comment by mikelikespie** [comment]
@laszlocsomor sorry for letting this linger. Gonna close this since I think most of it is obsolete.

**Pull request closed without merging**
