### PR TITLE
Fixes test breakage on darwin

### LINKED ISSUE #1343: bazel_app_test is broken on darwin
http://ci.bazel.io/job/bazel-tests/BAZEL_VERSION=HEAD-jdk7,PLATFORM_NAME=darwin-x86_64/34/console

Possibly caused by 6d07acbfb9a45e58d9f2dcc95758cb9add1ad2b5 or 696a4a7e8bb96a3a1955730130f8da2a755a5356
@dmishe Please take a look. :)

### PR DESCRIPTION
**Pull request by dmishe**
Fixes #1343 due to missing iOS SDK version.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by dmishe** [comment]
@c-parsons FYI

**Comment by meteorcloudy** [comment]
Jenkins: test this please

**Pull request closed without merging**
