### PR TITLE
Use boolean expressions to define filters

### PR DESCRIPTION
**Pull request by emusand**
Python boolean expression syntax can now be used to express filters in
--test_tag_filters and --build_tag_filters.

Example:
bazel test ... --test_tag_filters="tag1 and (tag2 or not tag3)"

### CODE REVIEW

**Comment by emusand** [comment]
This is a new PR for the same change in https://github.com/bazelbuild/bazel/pull/11900. The author of the original PR, @ehkloaj, was a summer intern at our company, and the Google CLA check failed as his account recently was removed.

See the original PR for more information about this change.

**Review by meisterT — COMMENTED** [review]
The new file (TagFilter.java) needs the same license header (with updated copyright year) that we have in other files.

**Comment by emusand** [comment]
Thank you for finding the mistake! I have added the license header to TagFilter.java now.

**Comment by tetromino** [comment]
Interesting decision to not quote the tag names! I assumed at first that it would be certain to break lots of things, but in practice I've found only a handful of instances of [Starlark keywords](https://github.com/bazelbuild/starlark/blob/master/spec.md#lexical-elements) being as tag names in Google's monorepo, and I think we can fix those.

So it should be ok.

**Comment by meisterT** [comment]
Hi @emusand, @Kal-Elx,

We are sorry, but after careful consideration we have decided to not merge this PR.

We appreciate the problem you're trying to solve. The challenge we see is keeping Bazel's wider API clear and consistent. The existing --*_tag syntax already has non-trivial uses and documentation references (outside of Bazel). This means extra challenges for migration sequencing, forking the documentation, and sustained migration ownership. If we don't tackle those issues thoroughly, it will lead to new API complexity, even if your specific syntax is clear.

So this isn't about the quality of your technical contribution, but larger project management issues.

As a workaround, you would need to combine bazel query, some postprocessing and bazel test.

Apologies for the late decision which we should have made much sooner.

**Pull request closed without merging**
