### PR TITLE
Fix spelling errors in site docs

### PR DESCRIPTION
**Pull request by akira-baruah**
I used [GNU Aspell](http://aspell.net/) to quickly look through markdown files in `site/docs/` for typos. Still involved a bit of manual checking, but ultimately found a handful of spelling errors.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
PR #3896 already fixes `dependnecies -> dependencies`, so commit 61337262ec3ff7207ccb435a23594891b6b6160e of this PR #3944 may be omitted.

**Comment by buchgr** [comment]
Please merge everything in one commit

**Comment by akira-baruah** [comment]
@buchgr I've rebased the changes into a single commit.

**Comment by buchgr** [comment]
It's still 3 commits. Can you just make one please?

**Comment by akira-baruah** [comment]
@buchgr This branch is rebased to master. One commit now. :) Please let me know if you'd like me to change anything else.

**Pull request closed without merging**
