### PR TITLE
Add https://github.com/google/jarjar to third_party

### PR DESCRIPTION
**Pull request by cushon**
This is based on the original jarjar sources, with updates
to support JDK 9.

I added it to a different packages (third_party/jarjar vs.
third_party/java/jarjar) because Bazel uses the first 'java/'
component of the path as the resource root.

Change-Id: Icdf10b1a71edf4e59f5524c1e169000b9f090ed9

### CODE REVIEW

**Comment by cushon** [comment]
@ittaiz are you interested specifically in a jarjar rule, similar to johnynek/bazel_jar_jar? Or is there additional work you'd like to see done on jarjar? I am not working on those things, but it sounds like a reasonable feature request.

**Comment by ittaiz** [comment]
specifically a jarjar rule. 
IDK of additional work needed.
Just something that is easy to do on maven but less on bazel.
Where do you think should I open such a FR?

**Comment by cushon** [comment]
I'm not sure what the best place would be, but if you start a thread or open a bug on bazelbuild/bazel someone can probably direct you.

**Comment by philwo** [comment]
Merged in https://github.com/bazelbuild/bazel/commit/c7e7232c8a58d3bdf8f7423645521a8b94c81bbd!

**Pull request closed without merging**
