### PR TITLE
Implement `SelectorValue#{equals,hashCode}`

### PR DESCRIPTION
**Pull request by fmeum**
This allows Starlark unit tests to verify that certain `select` expressions are equal.

### CODE REVIEW

**Comment by fmeum** [comment]
@brandjon Friendly ping

**Comment by fmeum** [comment]
@tetromino Do you have time to review this PR?

**Comment by fmeum** [comment]
@brandjon Friendly ping

**Review by tetromino — CHANGES_REQUESTED** [review]
Overall, LGTM. Your PR fixes a real inconsistency, which I think was a bug - for some reason we had value equality semantics for SelectorList, but reference equality semantics for SelectorValue.

But please add a test - probably in BuildTypeTest.java - for the new equality semantics. Maybe something like

```java
  @Test
  public void testSelectorValue_equals() {
    new EqualsTester()
        .addEqualityGroup(
            new SelectorValue(ImmutableMap.of("a", 1, "b", 2), ""),
            new SelectorValue(ImmutableMap.of("b", 2, "a", 1), ""))
        .addEqualityGroup(new SelectorValue(ImmutableMap.of("a", 1, "b", 2), "Match failed"))
        .addEqualityGroup(new SelectorValue(ImmutableMap.of("a", 1, "c", 2), ""))
        .addEqualityGroup(new SelectorValue(ImmutableMap.of("a", 1, "b", 3), ""))
        .testEquals();
  }
```

**Comment by fmeum** [comment]
@tetromino Thanks for the comments.

**Comment by fmeum** [comment]
@tetromino Friendly ping

**Review by tetromino — APPROVED** [review]
LGTM, sorry for overlooking this!

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

**Pull request closed without merging**
