### PR TITLE
Revert "Make http_archive honor $HOME/.netrc"

### PR DESCRIPTION
**Pull request by katre**
This reverts commit c26e3396cb341e173b4be5c780cafac3ec386df5.

Work on #9327.

### CODE REVIEW

**Comment by katre** [comment]
This attempts to mitigate #9327 so that 0.29.1 (#9293) can be released. Once that is done the code can be restored and fixed.

**Comment by katre** [comment]
I cannot reproduce the actual issue, can @keith or @davido please verify this fixes the problem?

**Comment by keith** [comment]
I can confirm this fixes the issue for me

**Comment by davido** [comment]
I can confirm, that after applying this revert, the line in ~/.netrc:

```
machine github.com login foo password bar
```

is ignored, and `bazel-dev build headless` in gerrit just works.

**Comment by katre** [comment]
Dropping this PR since the issue was fixed separately.

**Pull request closed without merging**
