### PR TITLE
Add test for Unicode console output

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io fork 8.0.0

**Comment by fmeum** [comment]
`echo "äöüÄÖÜß🌱" | grep -F "äöüÄÖÜß🌱"` fails in MSYS2 bash, which caused the test to fail on Windows. I am now converting both the pattern and the log file contents to hex and grepping that instead.

**Comment by fmeum** [comment]
@tjgq This is ready for review now, but does require the reland of the Unicode commit.

**Comment by fmeum** [comment]
@tjgq I rebased onto master.

**Review by tjgq — APPROVED** [review]

**Pull request closed without merging**
