### PR TITLE
Update implementation of fail()

### PR DESCRIPTION
**Pull request by Quarz0**
See: https://github.com/bazelbuild/starlark/issues/47, https://github.com/google/starlark-go/blob/master/doc/spec.md#fail

### CODE REVIEW

**Comment by laurentlb** [comment]
The annoying part is that there's migration to do. Following the incompatible change policy isn't very useful: we're breaking only the code that's failing. :)

Still, we can think of a migration path.
Buildifier can warn against the keyword arguments in `fail`.
We could also warn against extra positional arguments for some time, and then allow them in 2/3 months.

Assigning to @vladmos to help with that.

**Comment by laurentlb** [comment]
What do you think, @vladmos?

**Comment by vladmos** [comment]
Sorry for the late reply. I think the change makes sense, but perhaps we need to support both `*args` and `attr` during the migration period (however I don't think `attr` is widely used). That will also be an incompatible change, e.g. the behavior of `fail(msg, my_attr)` will be changed, but I don't think it's a critical change.

**Comment by meisterT** [comment]
What's the status of this PR?

**Comment by aiuto** [comment]
ping

**Pull request closed without merging**
