### PR TITLE
Teach ijar about dynamic constants.

### PR DESCRIPTION
**Pull request by benjaminp**
https://github.com/bazelbuild/bazel/issues/18360

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io flag

**Review by cushon — APPROVED** [review]

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.0

**Comment by iancha1992** [comment]
Third party changes merged at: https://github.com/bazelbuild/bazel/commit/37c80e849e4a56da7abc5cb05431f9cce8841c1e

**Comment by benjaminp** [comment]
@iancha1992 Thank you for merging. However, there's some kind of extra-special procedure for importing ijar changes. It doesn't seem that was followed in this case, causing the changes to be reverted by the next change (651c45108dcb9d27737194511d47fa104b0b199e).

**Comment by meteorcloudy** [comment]
@cushon Can you help importing this PR again?

**Pull request closed without merging**
