### PR TITLE
WIP: Enable //src/test/shell/bazel:bazel_test_test on Windows

### PR DESCRIPTION
**Pull request by meteorcloudy**

### CODE REVIEW

**Comment by meisterT** [comment]
What's the state of this PR?

**Comment by meteorcloudy** [comment]
Still need some fixes for the tests to work on Windows. I was distracted to other work, sorry. Will come back when I have time.

**Comment by sventiffe** [comment]
What is the state of this PR?

**Comment by meteorcloudy** [comment]
Closing for now since I don't think I'll find any time working on this in near future.

**Pull request closed without merging**
