### PR TITLE
[7.2.0] Cherry-picks of JDK 21 related changes

### PR DESCRIPTION
**Pull request by Wyverald**
Original commits:
* 239b89a6e0d6fd36808533a622481e89230a96f0
* 707d06573107666e0ad631778a7a1e87f4d486a2
* b532a462b9c234bcbd7a8ccf3ed70aa554b34032
* e3bd7252724b666e115b8ea7811b9d74e8550afd
* 5dc617039018daa49f7ed90cded9fa99e23fcd90
* 982b9ade343014667c6d44d3720d83eeb6ac2a37
* 40824e1813445fd05a97152a95ed704ef731577b
* 594bd121b46cea736a0e8584fa0878c231c2a55f
* 849da31ab182c49ff86994661d03fc141f83495f
* 11498b5bf62d1cebf4404fa5dcab3c547ef8b540
* 55ec5eac24069dd57a0ee42e397e8c9f1831d18e
* ad8ea5aed2c97c4dbbe577fb69adbd51746f6a51
* 6f47024266407789bb781a2c2ddb96916247ec47
* 8024a753cfa933d6eb77ce9ed06e50d40bd20cbc
* 3798b550db3dd21fcd0d7a851a45011b0482e9d8
* 6783339e3fd21655b7fa3be2daedde4491ae0348
* 59cf396d7d1a1a35c01a99bcaae742d76d872c5b

### CODE REVIEW

**Review by iancha1992 — APPROVED** [review]

**Comment by Wyverald** [comment]
I'm not sure how to get rid of the remaining failures. Maybe I missed an important cherry-pick?

cc @meteorcloudy @coeuvre @zhengwei143 @fmeum @cushon -- in case any of you have an idea what to do with the failures.

**Comment by cushon** [comment]
I'm not sure why this is only showing up for Bazel 7.2, but I think the fix is to update the version of ASM

The failure I see is:

```
Executing tests from //src/java_tools/import_deps_checker/javatests/com/google/devtools/build/importdeps:library_interface_missing_golden_test
...
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
...
	at com.google.devtools.build.importdeps.ImportDepsChecker.lambda$check$0(ImportDepsChecker.java:88)
```

Class file version 65 support was added to ASM in https://gitlab.ow2.org/asm/asm/-/commit/dd57050b0a34b92ff37295c8b9710bd43e3e173e, which was released in ASM 9.5

It looks like Bazel might still be depending on ASM 9.2 (unless ImportDepsChecker is getting ASM from somewhere else?): https://github.com/bazelbuild/bazel/blob/1253b5eb5534f75ff8d5ad7ca79ac654d2cc6be1/MODULE.bazel#L161-L165

**Comment by Wyverald** [comment]
> I'm not sure why this is only showing up for Bazel 7.2

Indeed -- I double-checked and these tests are currently running on master (postsubmit, at least -- [example](https://buildkite.com/bazel/bazel-bazel/builds/27430#018ea04f-81e5-4e0c-beae-392657ffbc2a)). I'll try updating asm but there's probably something wrong elsewhere.

**Comment by Wyverald** [comment]
oh, fun. We're actually still using bundled jars for `asm`, which were updated in https://github.com/bazelbuild/bazel/commit/c03f3736919ff645a84e4b3a76efc5235574bd92

Will cherry-pick that and report back.

**Comment by Wyverald** [comment]
Thanks, @cushon! That was it :) Getting close to all green now.

**Comment by Wyverald** [comment]
huh, not sure what happened with the merge queue there -- it merged before the checks passed. I'll send a follow-up PR.

**Pull request merged**
