### PR TITLE
Path map executable paths

### PR DESCRIPTION
**Pull request by fmeum**
In `CommandLines`, the very first argument of the first command line is always a path to an executable. As such, it should be path mapped, even when it is a string. This wasn't the case for `SpawnAction`'s created via `ctx.actions.run(executable = <some string>)`.

Work towards #6526
Work towards #22366

### CODE REVIEW

**Comment by fmeum** [comment]
Marking this as draft as the idea is flawed: It's possible that the user wants the executable to be looked up in path.

**Comment by fmeum** [comment]
@justinhorvitz Friendly ping

**Comment by justinhorvitz** [comment]
Is this change only necessary due to the optimization detailed at https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/analysis/actions/SpawnAction.java;l=979-982;drc=d32202b20f82c17f75ee204d505b08f2160640f5? That comes from https://github.com/bazelbuild/bazel/commit/d18702c7b0be423ed55d11ddb75d0af5a667182a, for which the internal description mentions a trivial memory savings. Maybe it's not worth it? @comius

**Comment by fmeum** [comment]
Not just because of that: There is plenty of starlark API that doesn't provide access to an `Artifact`, but just the path of an executable. For example, C++ tool paths and the `java` binary can only be specified as strings but may still need to be mapped.

**Comment by justinhorvitz** [comment]
Thanks, it's much easier to justify this change then.

**Review by justinhorvitz — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Comment by iancha1992** [comment]
@justinhorvitz @fmeum Just a friendly reminder, the 7.3.0RC1 is scheduled for next Monday, July 29th. Thanks!

**Pull request closed without merging**
