### PR TITLE
Fix bazel build with java 9

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
@cushon I've uploaded Java 9 fixes for bazel build in new PR.

**Comment by cushon** [comment]
@buchgr someone on Bazel team should review this, maybe @iirina?

**Comment by cushon** [comment]
* forking grpc is problematic, either that change needs to be made in upstream grpc or we need to work around it for Bazel.
* can you remove the checker framework changes now that there's a separate PR for them?

Also - I'm not sure what Bazel team's plans are for building with JDK 9. Instead of selecting on `--java_toolchain`, they may just cut over to depend on JDK 9 at some point. Building Bazel on JDK 9 doesn't block running with JDK 9 as a LHS-host_javabase. @iirina WDYT?

**Comment by cushon** [comment]
* forking grpc is problematic, either that change needs to be made in upstream grpc or we need to work around it for Bazel.
* can you remove the checker framework changes now that there's a separate PR for them?

Also - I'm not sure what Bazel team's plans are for building with JDK 9. Instead of selecting on `--java_toolchain`, they may just cut over to depend on JDK 9 at some point. Building Bazel on JDK 9 doesn't block running with JDK 9 as a LHS-host_javabase. @iirina WDYT?

**Comment by davido** [comment]
> forking grpc is problematic, either that change needs to be made in upstream grpc or we need to work around it for Bazel.

As a good open source citizen, I've uploaded the same PR upstream and started the discussion on the issues linked to my commit.

> can you remove the checker framework changes now that there's a separate PR for them?

That's the way how GitHub handles depending PRs: stacked PR. I created the this PR from branch fix-build-java-9, that is based on the branch where i changed checker framework. Once another change is merged I will rebase this PR on top of master.

I wish I could use Gerrit Code Review. Unfortunately current Bazel CI pipeline doesn't support Gerrit ;-(

**Comment by lfpino** [comment]
Hi @iirina and @cushon, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by cushon** [comment]
This change is a combination of #4795, grpc/grpc-java#3633, and a partial fix for an issue that will be addressed as part of ongoing work on #3410.

The fist two parts are being reviewed separately. I'll keep the last one in mind for #3410, but I'm not sure yet that's the way we want to handle JDK 9-specific JVM opts.

**Pull request closed without merging**
