### PR TITLE
[worker] Move WorkerProtocolImpl into its own package

### PR DESCRIPTION
**Pull request by Yannic**
Splitting it out of the main worker package makes re-using the code
for other implementations for dispatching requests to workers (e.g.,
for remote persistent workers, #10091) easier.

### CODE REVIEW

**Comment by Yannic** [comment]
@larsrc-google PTAL

**Comment by Yannic** [comment]
Ping?

**Comment by Yannic** [comment]
ping?

**Comment by Yannic** [comment]
@wilwell can you help getting this merged please?

**Review by wilwell — APPROVED** [review]
LGTM. @larsrc-google please review these changes too.

**Comment by larsrc-google** [comment]
Why do you need to split it into an entirely separate package, rather than just into a separate target?

**Comment by Yannic** [comment]
> Why do you need to split it into an entirely separate package, rather than just into a separate target?

Having it in a dedicated package makes it clearer that this is its own unit. I prefer the package solution, but I'm not strictly against just making it its own target. Please let me know what you think

**Comment by larsrc-google** [comment]
Now a separate target.

**Pull request closed without merging**
