### PR TITLE
Declare credential helpers to be a stable feature.

### PR DESCRIPTION
**Pull request by tjgq**

### CODE REVIEW

**Comment by tjgq** [comment]
@yannic I think we're ready to declare credential helpers to be stable. Please let me know if you have any remaining concerns!

**Review by coeuvre — APPROVED** [review]
Great!

**Review by meteorcloudy — APPROVED** [review]
🎉 Do we need to backport this (and maybe other changes) to 6.3.0?

**Review by Yannic — APPROVED** [review]
Let's do it!

**Comment by tjgq** [comment]
@bazel-io fork 6.3.0

**Pull request closed without merging**
