### PR TITLE
And mnemonic and label to remote metadata

### PR DESCRIPTION
**Pull request by illicitonion**
This reflects https://github.com/bazelbuild/remote-apis/pull/186

### CODE REVIEW

**Comment by coeuvre** [comment]
Thanks for the PR!

For reasons, we cannot merge a PR containing both third_party and non-third_party changes. Can you please split this into two PRs? (One for updating REAPI and another one for adding additional metadata)

**Comment by illicitonion** [comment]
I split off https://github.com/bazelbuild/bazel/pull/13133 for just the proto change, now that it's merged upstream :) Thanks!

**Comment by EdSchouten** [comment]
Cc @coeuvre @philwo

**Review by coeuvre — APPROVED** [review]
#13133 is merged. Please rebase and I will merge this.

**Comment by illicitonion** [comment]
Rebased :) Thanks!

**Comment by coeuvre** [comment]
Waiting for bazelbuild/remote-apis#186 to be imported. Once that's done, this should be merged automatically.

**Comment by philwo** [comment]
@coeuvre It seems like the linked change was already merged:

image

Is there something left to do?

**Comment by coeuvre** [comment]
Yes. We use internal version of REAPI internally. The linked change need to be imported to the internal REAPI first so we can import this change. (b/182107620)

**Comment by EdSchouten** [comment]
(Friendly ping :-) )

**Pull request closed without merging**
