### PR TITLE
Improve mechanism to distribute precompiled jars (e.g. for bootstrapping)

### PR DESCRIPTION
**Pull request by Yannic**
This change adds a new directory `derived/jars` to `bazel-distfile.{tar,zip}` that contains jars that we can't (or don't want to) build during bootstrapping (e.g. the Protobuf runtime).
Delaying the compilation of these jars until we create the distfile archive removes the need to check-in these precompiled jars.

This should allow us to replace some of the checked-in third-party repositories with `http_archive`.

### CODE REVIEW

**Comment by Yannic** [comment]
@philwo I think this could be split into a third-party and a non-third-party commit without breaking CI.

@lberki fyi^

**Comment by philwo** [comment]
@Yannic Thanks! If you can easily split this up into two separate PRs, I'll make sure to get them in asap. :)

**Comment by Yannic** [comment]
@philwo Thank you! Third_party parts are in https://github.com/bazelbuild/bazel/pull/10703 now.

**Comment by philwo** [comment]
Merging this now.

**Pull request closed without merging**
