### PR TITLE
Upgrade zlib to 1.3.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by meteorcloudy** [comment]
I think I'm hitting https://github.com/bazelbuild/bazel/issues/17956 again with Xcode 14.3 after upgrading to zlib 1.3.

Maybe need to apply https://github.com/meteorcloudy/bazel/commit/62ea9dd5f99b6782621b790cd0b637e4c802d1d6 again or https://github.com/bazelbuild/bazel/issues/17956#issuecomment-1497684969

**Comment by meteorcloudy** [comment]
Using
```
    copts = select({
        "@platforms//os:windows": [],
        "//conditions:default": [
            "-Wno-deprecated-non-prototype",
            "-Wno-unused-variable",
            "-Wno-implicit-function-declaration",
        ],
    }),
```
fixes the issue

**Comment by iancha1992** [comment]
Third party changes merged at https://github.com/bazelbuild/bazel/commit/b29649fbdc983cd62a58b9b09ef699867e7c5b69

**Pull request closed without merging**
