### PR TITLE
Add `protobuf` dep to `bazel_tools`

### LINKED ISSUE #23907: [8.0.0rc1] `no such package '@@[unknown repo 'protobuf' requested from @@_builtins]//bazel/private'`
### Description of the bug:

With Bazel 8.0.0rc1, I get the following error when using proto toolchains:

```
ERROR: no such package '@@[unknown repo 'protobuf' requested from @@_builtins]//bazel/private': The repository '@@[unknown repo 'protobuf' requested from @@_builtins]' could not be resolved: No repository visible as '@protobuf' from repository '@@_builtins'
ERROR: /Users/fmeum/git/with_cfg.bzl/docs/BUILD.bazel:14:21: While resolving toolchains for target //docs:protoc_java_toolchain (415c165): com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package '@@[unknown repo 'protobuf' requested from @@_builtins]//bazel/private': The repository '@@[unknown repo 'protobuf' requested from @@_builtins]' could not be resolved: No repository visible as '@protobuf' from repository '@@_builtins'
```

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
git clone https://github.com/fmeum/with_cfg.bzl
git checkout 19b8eb6035ace755b1783f270ddfb17bc1b268b3
USE_BAZEL_VERSION=8.0.0rc1 bazel test //...
```

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

release 8.0.0rc1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

_No response_

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

Bazelisk points to:
https://github.com/bazelbuild/bazel/commit/07af430eafcc7afb47d17d0b395a0020d08ed598

This commit removed the `protobuf` dep from `bazel_tools`:
https://github.com/bazelbuild/bazel/commit/f36b8a390d750eaca5875af90666b866d9e94031

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by fmeum**
This is needed to resolve the protobuf autoload.

Fixes #23907

### CODE REVIEW

**Comment by fmeum** [comment]
@meteorcloudy Updating the default lockfile no longer works on my machine (macOS) due to rules_rust repo rules failing:
```

**Comment by meteorcloudy** [comment]
Yes, we need some patches to remove rules_rust from protobuf 29.0, this has been agreed on with the protobuf team. @comius @Wyverald are tracking the progress.

**Comment by Wyverald** [comment]
protobuf 29.0 will not ship with a dependency on rules_rust: https://github.com/protocolbuffers/protobuf/pull/18650

**Comment by ted-xie** [comment]
Protobuf 29.0-rc2 was just cut this week. Could we try this PR again?

**Comment by Wyverald** [comment]
it's actually still not clear to me what the plan is here.

I think @comius has implemented autoloads in such a way that `protobuf` is no longer needed to be a dependency of `bazel_tools` (Bazel will 'autoload' as long as protobuf is _somewhere_ in the dep graph), but I'm not sure how well that works in practice.

I'm trying to get https://github.com/bazelbuild/bazel/pull/24088 submitted so that we can test with Bazel 8.0.0rc2, hopefully early next week.

**Comment by Wyverald** [comment]
This is obsolete.

**Pull request closed without merging**
