### PR TITLE
Do not kill Android persistent workers if the response has warnings

### PR DESCRIPTION
**Pull request by jin**
The Android manifest merging action will log warnings to standard out. This is bad for the persistent worker protocol, since it uses stdout for communication. The manifest merging action is also called by other busybox tools, so omitting ManifestMerger and AndroidManifestMerger mnemonics from --persistent_android_resource_processor doesn't work.

Add a --logWarning boolean flag to the busybox tools. If --persistent_android_resource_processor or --internal_persistent_busybox_tools is enabled, stop logging warnings in manifest merging actions. 

Also re-enable manifest merging actions in --persistent_android_resource_processor.

Fixes https://github.com/bazelbuild/bazel/issues/8505

### CODE REVIEW

**Comment by jin** [comment]
FYI @cgruber

**Comment by nkoroste** [comment]
@jin can you rebase this PR? there are too many conflicts that I need to resolve before I can test this PR again

**Comment by cgruber** [comment]
@restingbull - this is relevant.

**Comment by jin** [comment]
Rebased.

**Comment by nkoroste** [comment]
:champagne:

**Pull request closed without merging**
