### PR TITLE
Windows test-script debugging

### PR DESCRIPTION
**Pull request by briandealwis**
This PR is the same as #10665 but with some extra logging in `tools/test/windows/tw.cc` and `tools/test/test-setup.sh`. It indicates that the attempt to re-build Bazel with the built-Bazel is not picking up the changed test wrapper as these logging changes should show up in the test logs.

### CODE REVIEW

**Comment by aiuto** [comment]
@sdtwigg  since you are working on testing tools, you might be interested in taking a look at this.

**Comment by briandealwis** [comment]
@sdtwigg this PR is the same as #10665 but with some extra logging in `tools/test/windows/tw.cc` (and `tools/test/test-setup.sh`).  I believe these logging changes should show up in the test logs, but there is nothing there.  It seems the attempt to build Bazel with the built Bazel is not picking up the changed test wrapper? 🤷‍♂

**Comment by philwo** [comment]
What's the status of this PR?

**Comment by meteorcloudy** [comment]
Unfortunately, I don't have time to help on this, so will close this one and the related PR for now.

**Pull request closed without merging**
