### PR TITLE
[7.5.0] Retry the cleanup of downloadAndExtract

### PR DESCRIPTION
**Pull request by bazel-io**
This helps the HTTP downloader better cope with filesystems where unlink is non-atomic.

Closes #24295.

PiperOrigin-RevId: 697920434
Change-Id: I91b4dbf07a2efdca07c0310e15aac5f4d89c4091

Commit https://github.com/bazelbuild/bazel/commit/99a27f6d4709516b6210ea4457259f12dd3666ee

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Please backport https://github.com/bazelbuild/bazel/commit/be2186fbe76ea52b9c146a5f01780a0171384ac8 and https://github.com/bazelbuild/bazel/commit/9b027c88051797ada7350098ef190191b953014a to fix the windows failures.

**Comment by sthornington** [comment]
The moment this is merged I'm going to switch our bazelisk to it!  :)

**Comment by sthornington** [comment]
🎉

**Comment by sthornington** [comment]
I created https://github.com/bazelbuild/bazel/issues/24728 in case that helps with some automation, but I can't set the release or milestone so probably it doesn't help... @iancha1992

**Comment by sthornington** [comment]
Got a clean CI hash for bazelisk, early Christmas present. Thanks everyone that helped with this.

**Pull request merged**
