### PR TITLE
Add removeprefix/removesuffix to Starlark strings

### PR DESCRIPTION
**Pull request by fmeum**
Implements https://github.com/bazelbuild/starlark/issues/185 in Java Starlark.

Closes #14824.

PiperOrigin-RevId: 430556229

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald In general, do you want cherry-pick commits to add `RELNOTES`? Also, if possible, you might want to disable code owners for non-master branches, as otherwise reviewers will get pinged for all these cherry picks.

**Comment by Wyverald** [comment]
> In general, do you want cherry-pick commits to add RELNOTES?

It's probably fine since most minor releases get release notes from entire commit messages, instead of relnotes. The number of cherry-pick commits in a minor release is very manageable. So let's so "no" for now.

> Also, if possible, you might want to disable code owners for non-master branches, as otherwise reviewers will get pinged for all these cherry picks.

I can't find a setting that does that. Please let me know if I'm missing something!

**Comment by fmeum** [comment]
@Wyverald You would have to delete the `CODEOWNERS` on the release branch or, even better, replace its content with a wildcard that always assigns the current release manager. See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location for the details.

**Comment by Wyverald** [comment]
Hmm, this idea has been brought up before. I guess we should just replace `CODEOWNERS` with the release manager wildcard as the first commit in each `release-X` branch. There shouldn't be any downsides. Thanks for the suggestion!

**Pull request merged**
