### PR TITLE
Use definition location for StarlarkRuleFunction.export errors.

### PR DESCRIPTION
**Pull request by benjaminp**
StarlarkRuleFunction.getLocation() always returns BUILTIN.

### CODE REVIEW

**Comment by benjaminp** [comment]
@gregestren, @juliexxia this PR makes it easier to figure out where the problem is with transition allowlist errors occur.

**Comment by juliexxia** [comment]
Awesome thank you!

**Comment by laurentlb** [comment]
Have you tried using `Starlark.errorf`?
In many cases, it's no longer needed to set the location explicitly (cc @alandonovan)

**Comment by benjaminp** [comment]
This change is in a `StarlarkExportable.export` implementation, which bubbles into the closure in `BzlLoadFunction.execAndExport` rather than the Starlark interpreter. Probably that interface could be fixed up, but that's a separate change.

**Comment by alandonovan** [comment]
This change seems fine. I plan to abolish the Location parameter to EvalException eventually, but it requires a series of changes. The Location is used only when the exception is thrown and caught in Java code without passing through Starlark calls; in other words, parts of Bazel (ab)use EvalException as a String+Location pair for local error reporting. All such places should either (a) pass an EventHandler down from the (current) catch to the throw, or (b) locally use a private exception that has Location+String.

Unfortunately the changes will require the introduction of several `catch(EvalException){throw LocationError}` statements because so many low-level operators (e.g. Sequence.cast) report their failures as EvalException (sans stack). The challenge is to find the natural seams (or restructure) to minimize the need for them.

**Pull request closed without merging**
