### PR TITLE
Force Objective C to always load all symbols from dependent libraries

### PR DESCRIPTION
**Pull request by petewarden**
These changes are required to enable iOS Blaze building, which we need for TensorFlow. From discussions with the Bazel team this is the cleanest approach that will currently work.

### CODE REVIEW

**Comment by davidzchen** [comment]
+@dmaclach

**Comment by calpeyser** [comment]
We've been thinking about adding this specifically for the case of ios_test, to allow the test to rely on symbols in dependencies of the binary under test without having to depend on them itself.

Can you clarify to me (perhaps reference me to the discussion) why this is necessary for all compile actions?

**Comment by damienmg** [comment]
@calpeyser can we close this one? Was it resolved?

**Comment by calpeyser** [comment]
Yes, this was resolved - we've implemented the linkopts attribute on objc_* targets with link steps as an alternative to this change.

Feel free to close.

**Pull request closed without merging**
