### PR TITLE
Update GoogleTest to 1.10.0

### PR DESCRIPTION
**Pull request by Yannic**
This includes fixes for `--incompatible_load_{cc,python}_rules_from_bzl`.

### CODE REVIEW

**Comment by Yannic** [comment]
@aehlig Friendly ping?

**Comment by jin** [comment]
Re-assigning to @lberki.

**Comment by meisterT** [comment]
What version of googletest is this?

**Comment by Yannic** [comment]
@meisterT gtest doesn't have a recent release. It's a similarly random commit like we had before (with fixes for `--incompatible_*`).

**Comment by Yannic** [comment]
gtest 1.10 has just been [released](https://groups.google.com/d/msg/googletestframework/_fpwymiTLeI/X2o1p2ajAQAJ). I'll update this PR accordingly.

**Comment by Yannic** [comment]
Updated to 1.10.0. ptal.

**Comment by hlopko** [comment]
Thank you! Importing.

**Pull request closed without merging**
