### PR TITLE
[WIP] Custom TLS Certificates for HTTP Cache

### PR DESCRIPTION
**Pull request by ahirreddy**
This PR adds 3 flags that enable support for custom TLS certificates when interacting with the HTTP cache. The high level goals is to allow for the use of custom CA chains and client authenticated TLS.

Both of the following flags are necessary to support client authenticated TLS.
- `--http_cache_tls_certificate`: The X.509 TLS client certificate
- `--http_cache_tls_key`: The PKCS8 PEM private key

The following flag is necessary to support trusting a custom authority
- `--http_cache_tls_certificate_authority`: Specify the trusted certificates used to verify the remote endpoint for HTTP Caching. This file must be an X.509 PEM certificate collection.

These flags are added to the `AuthAndTLSOptions` class, and is threaded through to the Netty SSLContext in `HttpBlobStore`.

TODO:
- [ ]: Fix test compilation and add a test case

### CODE REVIEW

**Comment by ahirreddy** [comment]
I was wondering what the best way to test this would be? I can generate some certificates and use those in a test case. Should I just check in the certs?

**Comment by buchgr** [comment]
Hey @ahirreddy, 

we already have `--tls_` flags in `AuthAndTLSOptions`. Do you think that we could use the same flags for HTTP and gRPC caching clients?

Also, can you sign our CLA please? :-)

Thanks!

**Comment by buchgr** [comment]
@ahirreddy as for tests, it's fine to check in certificates that you generated yourself. Please include the exact steps on how you generated these certificates in comments or a readme.

**Comment by ahirreddy** [comment]
@buchgr Sure, I can fold the two flags back together. I think I’ll still have to add flags, as I don’t think the existing set supports client authentication. I’m just waiting for sign off to sign the CLA as I am contributing this on behalf of my company, Databricks. Thanks for the response and the testing advice!

**Comment by buchgr** [comment]
Closing this due to inactivity. Please re-open if this is still of interest.

**Pull request closed without merging**
