### PR TITLE
Bump minimum supported macOS versions to 10.13

### PR DESCRIPTION
**Pull request by illicitonion**
As per https://developer.apple.com/support/xcode/ Xcode from 14.0 no longer supports targeting 10.9, and attempting to do so may fail in obscure ways.

10.13 is still 5+ years old, so we retain coverage for a reasonable range on macOS versions.

### CODE REVIEW

**Review by brentleyjones — APPROVED** [review]

**Comment by keith** [comment]
just to verify this doesn't produce any new build warnings for deprecated APIs or anything right? also note that these binaries even with this will likely still run on older versions, they just might crash depending on macOS changes, so these values don't matter that much

**Comment by illicitonion** [comment]
> just to verify this doesn't produce any new build warnings for deprecated APIs or anything right?

Yes, I've built all of the files built with the affected codepaths and there were no warnings (or errors).

**Review by keith — APPROVED** [review]

**Comment by illicitonion** [comment]
@bazel-io flag

**Comment by kshyanashree** [comment]
@bazel-io fork 6.1.0

**Comment by keertk** [comment]
@bazel-io fork 4.2.4

**Pull request closed without merging**
