### PR TITLE
Update the remote java tools archive to include the right permissions.

### PR DESCRIPTION
**Pull request by iirina**

### CODE REVIEW

**Comment by iirina** [comment]
I already pushed the new archive to mirror bazel. I'll import the third_party change separately after the review.

**Comment by iirina** [comment]
The binaries under `third_party/java/java_tools` already have write access but that was lost when generating the .tar.gz (the `pkg_tar` rule has a `mode` field that defaults to 055 which I missed before).

> Oh, it's a .tar.gz! 

Yes. The remotejdk is a zip archive.

**Comment by lberki** [comment]
Why the inconsistency?

**Comment by iirina** [comment]
remotejdk is also a tar.gz for the other platforms and a zip for windows. For remote_java_tools we only have one archive, the tar.gz.

**Comment by iirina** [comment]
third_party changes pushed in ae744f3bc1329714a60cd9765e83ac493274d33b

**Pull request closed without merging**
