### PR TITLE
Rollforward of commit 4162cc54ba0b128b616c0bd05b65bf9ad5e66f2e.

### LINKED ISSUE #10484: proto_lang_toolchain and blacklisted_protos with ProtoInfo not propagated correctly
### Description of the problem / feature request:

With protobuf's `proto_lang_toolchain`, after this change https://github.com/protocolbuffers/protobuf/commit/7b28278c7d4f4175e70aef2f89d304696eb85ae3 it seems the `blacklisted_protos` are no longer working correctly and removing that field has no effect on the build.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

See https://github.com/protocolbuffers/protobuf/issues/7046 for a repro case

### What operating system are you running Bazel on?

macOS

### What's the output of `bazel info release`?

release 1.2.0 (I also tried with 2.0.0 with no change)

### Have you found anything relevant by searching the web?

The protobuf commit linked above referenced this bazel change https://github.com/bazelbuild/bazel/commit/a5ee2c4d979441e663cf53b2ace4daa05e5033d8

I'm also wondering if the issue is with protobuf's use of `strip_import_prefix` on the `proto_library` targets they define: https://github.com/protocolbuffers/protobuf/commit/a03d332aca5d33c5d4b2cd25037c9e37d57eff02

### PR DESCRIPTION
**Pull request by Yannic**
proto_lang_toolchain: Add original sources of ProtoInfo to blacklistedProtos

This fixes the problem reported in #10588

Fixes #10484

### CODE REVIEW

**Comment by Yannic** [comment]
cc @meteorcloudy

**Comment by meteorcloudy** [comment]
@Yannic Thanks for the fix!
I'm now running a downstream test for this change at:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1353

Can you also add a test to prevent the regression?

**Comment by meteorcloudy** [comment]
The downstream looks good!

**Comment by Yannic** [comment]
@meteorcloudy Thanks! Test already added https://github.com/bazelbuild/bazel/pull/10592/files#diff-5fa14f4d43ed29b5b81abeaa02ff11b5R161

**Comment by meteorcloudy** [comment]
Perfect! I'll merge this PR

**Pull request closed without merging**
