### PR TITLE
Update def_parser

### PR DESCRIPTION
**Pull request by meteorcloudy**
- Updated def_parser.cc from https://raw.githubusercontent.com/Kitware/CMake/76db09fd750dbb6929366b7a4664f210bcf71d66/Source/bindexplib.cxx
- Updated def_parser.patch to adapt for Bazel usages.

This update includes important changes like https://github.com/Kitware/CMake/commit/f513781bc51e99ceb003ac11c93639bb09e05cf4

### CODE REVIEW

**Comment by learning-to-play** [comment]
Used `613e462d165f82d2bd8bb03487123d91dabcce8f` in .bazelverion and then ran `bazel test` which led to error
```
> bazel test pybind:pybind_py_test
2024/01/15 22:16:19 Using unreleased version at commit 613e462d165f82d2bd8bb03487123d91dabcce8f
2024/01/15 22:16:19 Downloading https://storage.googleapis.com/bazel-builds/artifacts/windows/613e462d165f82d2bd8bb03487123d91dabcce8f/bazel..
.
2024/01/15 22:16:19 could not download Bazel: HTTP GET https://storage.googleapis.com/bazel-builds/artifacts/windows/613e462d165f82d2bd8bb0348
7123d91dabcce8f/bazel failed with error 404
```
It seems using commits in .bazelversion only works for submitted commits. To confirm I used a recently submitted commit `cddec1247571f1cda9939ffb7546e089e528c76e` and it worked as expected
```
> bazel test pybind:pybind_py_test
2024/01/15 22:19:50 Using unreleased version at commit cddec1247571f1cda9939ffb7546e089e528c76e
INFO: Analyzed target //pybind:pybind_py_test (73 packages loaded, 411 targets configured).
...
```

**Comment by meteorcloudy** [comment]
Parsing the first_library.obj does output the symbols.
```
pcloudy@bazel-windows-playground:~/workdir/symbol-locations (main)
$ ../bazel/bazel-bin/third_party/def_parser/def_parser.exe pybind_copy.gen.def pybind_copy bazel-out/x64_windows-opt/bin/pybind/_objs/first_library/first_library.ob
j
pcloudy@bazel-windows-playground:~/workdir/symbol-locations (main)
$ cat pybind_copy.gen.def
LIBRARY pybind_copy
EXPORTS
        ?first_func@@YAHH@Z
```

**Comment by meteorcloudy** [comment]
I think you were parsing the wrong object file. The `first_function` is defined in first_library.cc instead of pybind_copy.cc, therefore you need to parse the object file of first_library.cc. 

`dumpbin` did dump the name of the function as an external symbol, but the def_parser only parses symbols actually defined in the object file.

**Review by oquenchil — APPROVED** [review]

**Comment by learning-to-play** [comment]
Thank you @meteorcloudy ! I actually need to parse a list of symbols that are external, that is, will need to be exported by other objects and linked dynamically (I want to use it to automatically create a `DEF` file and export those symbols from the other objects). Isn't that possible at all with `def_parser`? If so, is `dumpbin` a good option to use?

**Comment by learning-to-play** [comment]
Sounds good, thank you!

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0

**Pull request closed without merging**
