### PR TITLE
Use CallCredentialsProvider and refresh credentials when needed for GrpcCacheClient and GrpcRemoteExecutor

### PR DESCRIPTION
**Pull request by coeuvre**
Follow up on #12106, this PR make changes to `GrpcCacheClient` and `GrpcRemoteExecutor` to use `CallCredentialsProvider` and refresh credentials when needed to avoid unauthenticated error during a long remote build.

### CODE REVIEW

**Comment by coeuvre** [comment]
cc @ulfjack

**Comment by ulfjack** [comment]
Looks reasonable. I like that it actually simplifies the code in parts, and also that it now properly retries after credential refresh. I think another improvement might be to use a Retrier implementation for the credential refresh. I think that would simplify the call sites. (Feel free to ignore or defer this last proposal.)

**Comment by coeuvre** [comment]
> I think another improvement might be to use a Retrier implementation for the credential refresh.

Thanks for your suggestion, I like this idea! Will refactor the code in another PR soon.

**Comment by katre** [comment]
Is this likely to submit before October 1? It was flagged to be in the 3.7 release (#12188), and I'd like to figure out if I need to delay cutting RC1 or plan to make an RC2.

**Comment by philwo** [comment]
This is already in internal code review (see cl/334286851). Please wait with cutting rc1 until it's submitted, but I think we can get this in tomorrow.

**Pull request closed without merging**
