### PR TITLE
Use --depth=1 on git clone for git_repository skylark rules

### PR DESCRIPTION
**Pull request by edbaunton**
Fixes https://github.com/bazelbuild/bazel/issues/4359

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by edbaunton** [comment]
Ah, have just discovered the tests at https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/skylark_git_repository_test.sh so will be updating those.

**Comment by aehlig** [comment]
Partly implemented in 6496b1d1d25025f33406b1eaf9949cab126f08bd (using --depth=1
for tags, and supporting shallow_since for specified commit tags).


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by edbaunton** [comment]
Closing this.

**Pull request closed without merging**
