### PR TITLE
Update rules.md

### PR DESCRIPTION
**Pull request by Vertexwahn**
xcode rules do not exist anymore

### CODE REVIEW

**Comment by keith** [comment]
Hrm these rules definitely still exist and are in use. Maybe their docs disappearing (or moving?) is a bug?

Here's xcode_config: https://github.com/bazelbuild/bazel/blob/d533996b2c8eabaa8e796f3aad57bca13878f460/src/main/java/com/google/devtools/build/lib/rules/apple/XcodeConfigRule.java#L30

Here's xcode_version https://github.com/bazelbuild/bazel/blob/d533996b2c8eabaa8e796f3aad57bca13878f460/src/main/java/com/google/devtools/build/lib/rules/apple/XcodeVersionRule.java#L27

**Comment by gregestren** [comment]
I assume this is related to the recent website refresh?

**Comment by gregestren** [comment]
Looks like the links resolve now. Can I get a second opinion?

**Comment by keith** [comment]
yep looks like the links work now from https://bazel.build/rules?hl=en

**Pull request closed without merging**
