### PR TITLE
Fix precompiled lib symlinks missing in runfiles of cc_shared_library

### PR DESCRIPTION
**Pull request by Flamefire**
26d882f92943587d39460320694b17865ea74f91 was intended to remove unnecessary files from runfiles However it also removes (some?) required symlinks from runfiles. E.g. libtensorflow_cc.so.2.13.0 is present in the runfiles but `libtensorflow_cc.so.2` is not leading to failures as programs are linked to the latter. See https://github.com/tensorflow/tensorflow/issues/60326

Use the same logic used in other places preferring `resolved_symlink_dynamic_library` over `dynamic_library`.

### CODE REVIEW

**Comment by Flamefire** [comment]
It looks like `//src/main/starlark/tests/builtins_bzl:cc_builtin_tests` is failing on CI but can't see what exactly fails. However that might as well be an issue with the test which 26d882f92943587d39460320694b17865ea74f91 seems to have changed to only testing actually created files against a list of "expected" files while the issue intended to be fixed here is to add an expected file which was not created before. That might explain the failure

**Comment by oquenchil** [comment]
> It looks like `//src/main/starlark/tests/builtins_bzl:cc_builtin_tests` is failing on CI but can't see what exactly fails and I can't find how to run this test locally. However that might as well be an issue with the test which [26d882f](https://github.com/bazelbuild/bazel/commit/26d882f92943587d39460320694b17865ea74f91) seems to have changed to only testing actually created files against a list of "expected" files while the issue intended to be fixed here is to add an expected file which was not created before. That might explain the failure
> 
> I'd argue that is an oversight in the test as right now the test would pass when NO files were being created at all which likely isn't the intention.

Yes, please modify the test to account for these new files.

Just run:
```
bazel test //src/main/starlark/tests/builtins_bzl:cc_builtin_tests
```

The test to modify is [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl;drc=ba5c74038ed3ae633a9bf8346c88b01e1931992e;l=181https://cs.opensource.google/bazel/bazel/+/master:src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/starlark_tests.bzl;drc=ba5c74038ed3ae633a9bf8346c88b01e1931992e;l=181)

**Comment by Flamefire** [comment]
I ran the test on my machine and printed the expected and actual files, i.e. `target[DefaultInfo].default_runfiles.files.to_list()` and `expected_basenames` via

```
        all_files = target[DefaultInfo].default_runfiles.files.to_list()
        env.expect.where(
            detail = runfile.path + " not found in expected basenames:\n"
                    + "\n".join(expected_basenames)
                    + "\n All files:\n"
                    + "\n".join([f.path for f in all_files])
        ).that_bool(found_basename).equals(True)
```

bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libdirect_so_file.so not found in expected basenames:
```
libfoo_so.so
libbar_so.so
libdiff_pkg_so.so
libprivate_lib_so.so
Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary_Slibfoo_Uso.so
Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary_Slibbar_Uso.so
Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary3_Slibdiff_Upkg_Uso.so
Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/renamed_so_file_copy.so
Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/libdirect_so_file.so
 All files:
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libfoo_so.so
bazel-out/k8-fastbuild/bin/_solib_k8/_Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/libfoo_so.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libbar_so.so
bazel-out/k8-fastbuild/bin/_solib_k8/_Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/libbar_so.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library3/libdiff_pkg_so.so
bazel-out/k8-fastbuild/bin/_solib_k8/_Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary3/libdiff_pkg_so.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libprivate_lib_so.so
bazel-out/k8-fastbuild/bin/_solib_k8/_Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/libprivate_lib_so.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/renamed_so_file_copy.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libdirect_so_file.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/python_test
src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/python_test.py
bazel-out/k8-fastbuild/bin/external/bazel_tools/tools/python/py3wrapper.sh
```

Given this I'd expect the first failure in `renamed_so_file_copy.so` and am surprised by the first failure of `libdirect_so_file.so`

Anyway what this PR changes is replacing
```
bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Ssrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary_Cfoo___Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/renamed_so_file_copy.so
bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Ssrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary_Cprebuilt___Usrc_Smain_Sstarlark_Stests_Sbuiltins_Ubzl_Scc_Scc_Ushared_Ulibrary_Stest_Ucc_Ushared_Ulibrary/libdirect_so_file.so
```
by
```
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/libdirect_so_file.so
bazel-out/k8-fastbuild/bin/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/renamed_so_file_copy.so
```

I adapted the test accordingly and enhanced it to not only check for superflous files but also for missing files.

I see `renamed_so_file_copy.so` listed in `srcs` at https://github.com/bazelbuild/bazel/blob/80235380833c61bc47dd14efb8fe1c395e17316a/src/main/starlark/tests/builtins_bzl/cc/cc_shared_library/test_cc_shared_library/BUILD.builtin_test#L149 which is similar to the situation in TF where the missing lib is also listed in `srcs`: https://github.com/tensorflow/tensorflow/blob/be88ba0aefb1b778c2c0d0d896a342a70579740c/tensorflow/tensorflow.bzl#L2415-L2420

So I'd say this is indeed a valid fix and the enhanced test covers it. But as I don't know the intention behind using those mangled paths in `_solib_k8` please double check and if this turns out to be the wrong approach please coordinate with the TF team on how that build can be fixed

**Review by oquenchil — APPROVED** [review]

**Comment by Pavank1992** [comment]
Hi @Flamefire, it seems there is a failure on buildkite, could you please take a look and fix the error: https://buildkite.com/bazel/google-bazel-presubmit/builds/71675#018ab151-4f5a-4b35-9f1e-521a873e023b

**Comment by Flamefire** [comment]
> Hi @Flamefire, it seems there is a failure on buildkite, could you please take a look and fix the error: https://buildkite.com/bazel/google-bazel-presubmit/builds/71675#018ab151-4f5a-4b35-9f1e-521a873e023b

@Pavank1992 From the linked log I cannot see why that test on that system failed.
I ran `bazel test --flaky_test_attempts=1 //src/test/py/bazel:bzlmod_query_test` locally and it passed.

**Pull request closed without merging**
