### PR TITLE
Use @io_bazel to reference Bazel sources from local repositories.

### PR DESCRIPTION
**Pull request by jmillikin-stripe**
Fixes https://github.com/bazelbuild/bazel/issues/4285

cc @dslomov

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by dslomov** [comment]
Sorry I had some issues with our internal tooling trying to merge this. Will look now.

**Comment by dslomov** [comment]
Being imported now

**Comment by dslomov** [comment]
Sorry, I have no luck with importing this. Will try again today

**Comment by philwo** [comment]
Any news?

**Comment by jmillikin-stripe** [comment]
It looks like the original commit was imported, then rolled back and re-imported without this chunk of `third_party/googleapis/BUILD`:

```diff
-    visibility = ["@//src:__pkg__"],
+    visibility = ["@io_bazel//src:__pkg__"],
```

@dslomov was there a problem in applying that chunk? Is there anything I can do to help? That is the last remaining use of `@//` in the Bazel repo.

**Comment by philwo** [comment]
@ulfjack FYI, sounds like this might have been caused by the visibility exporter thingy you built?

**Comment by ulfjack** [comment]
@philwo, I don't think so. We don't export third_party, but instead merge it from the other place. What probably happened was that the import script reverted this part because it's under third_party - it's not currently possible to do changes to third_party and non-third_party in a single commit.

**Comment by philwo** [comment]
@ulfjack Perfect, thanks. I'll commit a fix for this.

**Comment by dslomov** [comment]
Sorry for the late reply for that. With this change:
```
diff --git a/third_party/googleapis/BUILD b/third_party/googleapis/BUILD
index 05784ef2c4..accc873a42 100644
--- a/third_party/googleapis/BUILD
+++ b/third_party/googleapis/BUILD
@@ -44,7 +44,7 @@ filegroup(
       ":google_devtools_remoteexecution_v1test_remote_execution_java_grpc_srcs",
       ":google_watch_v1_java_grpc_srcs",
     ],
-    visibility = ["@//src:__pkg__"],
+    visibility = ["@io_bazel//src:__pkg__"],
 )
 
 java_proto_library(
```
building `//scripts/packages` fails:
```
$ bazel build //scripts/packages
ERROR: <redacted>/bazel/src/BUILD:372:1: Target '@googleapis//:dist_jars' is not visible from target '//src:derived_java_srcs'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//scripts/packages:packages' failed; build aborted: Analysis of target '//src:derived_java_srcs' failed; build aborted
INFO: Elapsed time: 0.360s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by jmillikin-stripe** [comment]
`bazel build //scripts/packages` succeeds on my local machine (MacOS, Bazel 0.10) using `visibility = ["@io_bazel//src:__pkg__"]`. Does the Bazel you ran there have any non-public patches?

**Comment by dslomov** [comment]
no non-public patches. I'll investigate

**Comment by philwo** [comment]
`//scripts/packages` is a filegroup whose contents depend on the OS you're running the build on. This fails on Linux with the error that @dslomov saw, but works fine on macOS, which explains why @jmillikin-stripe didn't see anything wrong.

I agree that it looks like a bug to me.

**Comment by jmillikin-stripe** [comment]
Thanks for the tip on the OS-specific filegroup. Verified that `bazel build //src:derived_java_srcs` fails on MacOS. Interestingly, `bazel build @io_bazel//src:derived_java_srcs` succeeds. Here's a minimal reproduction:

```python
# ./WORKSPACE
workspace(name="test_bazel_visibility")

# ./files_b/BUILD
filegroup(name="srcs", srcs=["//files_a:srcs"])

# ./files_a/BUILD
filegroup(name="srcs", visibility=["@test_bazel_visibility//files_b:__pkg__"])
```
```
$ bazel build //files_b:srcs
ERROR: src/bazel-visibility/files_b/BUILD:1:1: Target '//files_a:srcs' is not visible from target '//files_b:srcs'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: Analysis of target '//files_b:srcs' failed; build aborted: Analysis of target '//files_b:srcs' failed; build aborted
INFO: Elapsed time: 0.167s
FAILED: Build did NOT complete successfully (1 packages loaded)

$ bazel build @test_bazel_visibility//files_b:srcs
INFO: Analysed target @test_bazel_visibility//files_b:srcs (1 packages loaded).
INFO: Found 1 target...
Target @test_bazel_visibility//files_b:srcs up-to-date (nothing to build)
INFO: Elapsed time: 0.189s, Critical Path: 0.01s
INFO: Build completed successfully, 1 total action
```

**Comment by jmillikin-stripe** [comment]
Filed https://github.com/bazelbuild/bazel/issues/4678 for the visibility issue.

**Comment by laszlocsomor** [comment]
ping -- any updates? can we import this PR?

**Comment by lfpino** [comment]
Hi all, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by irengrig** [comment]
This pull request was actually merged by commit: https://github.com/bazelbuild/bazel/commit/a59e60e4fba191b8793254c38485f781f790a607

I see no rolling back commits: [https://github.com/bazelbuild/bazel/blame/master/third_party/googleapis/BUILD](https://github.com/bazelbuild/bazel/blame/master/third_party/googleapis/BUILD)
[https://github.com/bazelbuild/bazel/blame/master/third_party/grpc/build_def.bzl](https://github.com/bazelbuild/bazel/blame/master/third_party/grpc/build_def.bzl)
[https://github.com/bazelbuild/bazel/blame/master/third_party/protobuf/3.6.0/BUILD](https://github.com/bazelbuild/bazel/blame/master/third_party/protobuf/3.6.0/BUILD)

Closing this.

**Pull request closed without merging**
