### PR TITLE
Add # support for LabelValidator as discussed in #2006

### PR DESCRIPTION
**Pull request by wsxiaoys**
As suggested by @damienmg in #2006 send this out to run it with internal test.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by wsxiaoys** [comment]
I'm a Googler so I don't need to sign CLA.

**Comment by aehlig** [comment]
over to @damienmg who apparently made the suggestion.

Please note that, as the account is not registered with the google oranisation,
we have no means to verify the claim "I'm a Googler".

**Comment by wsxiaoys** [comment]
I updated my information and commits and seems cla check automatically passed.

**Comment by damienmg** [comment]
Oops sorry, I forgot to import it yesterday.

Yes using your @google.com email for the author in the commit fix it (which you should do if you are employed by google).

**Comment by wsxiaoys** [comment]
Great, thank you. Does it break anything?

**Comment by wsxiaoys** [comment]
ping?

**Comment by damienmg** [comment]
Sorry I sent the change to @lberki for review but he seemed to have missed
it. Our tests have passed so far

**Comment by lberki** [comment]
Let's see what happens. We generally prefer patches through Gerrit, but it's a tiny simple one so I can just patch it in manually and run it through our internal test battery.

**Pull request closed without merging**
