### PR TITLE
Log one file per command if --experimental_workspace_rules_log_file is a directory

### PR DESCRIPTION
**Pull request by gonzojive**
This is helpful for keeping track of all workspace events across multiple runs of bazel for the https://github.com/gonzojive/bazelgopackagesdriver project. Without this behavior, every bazel invocation needs to be customized to specify the path of the output.

I would probably prefer to have a different flag rather than detecting whether the output location is a directory. Please let me know if you agree.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
My feeling is adding a `--experimental_workspace_rules_log_file` is better, but on the other hand, we do want as few flags as possible in Bazel. Can you figure out a way to work this around instead of changing Bazel?

**Comment by gonzojive** [comment]
> My feeling is adding a `--experimental_workspace_rules_log_file` is better, but on the other hand, we do want as few flags as possible in Bazel. Can you figure out a way to work this around instead of changing Bazel?

1) I assume you mean `--experimental_workspace_rules_log_dir` (distinct from the existing `experimental_workspace_rules_log_file` flag).

2) What about using variable substitution to allow a value like "/tmp/workspace_log_${command_id}.log" for  the `--experimental_workspace_rules_log_dir` flag? Is there a standard string templating syntax used in other parts of the project that could be used here for consistency? That would alleviate the need for the flag and provide the functionality I desire.

I can work around this... but the proposal is a 5 line change vs the workaround, which will require writing a wrapper for the bazel binary.

**Comment by meteorcloudy** [comment]
> I assume you mean --experimental_workspace_rules_log_dir (distinct from the existing experimental_workspace_rules_log_file flag).

Ah, yes, sorry for the mistake, fixed.

> What about using variable substitution to allow a value like "/tmp/workspace_log_${command_id}.log" for the --experimental_workspace_rules_log_dir flag? Is there a standard string templating syntax used in other parts of the project that could be used here for consistency? That would alleviate the need for the flag and provide the functionality I desire.

I don't think we currently support such syntax.

> I can work around this... but the proposal is a 5 line change vs the workaround, which will require writing a wrapper for the bazel binary.

This isn't just a 5 line change. It's the Bazel team who will need to maintain or clean up this in the future. Also if we allow using a dir for the workspace debug log, what about flags for other log files, it's hard to justify why we need to special case this one but not others.

**Comment by gonzojive** [comment]
> > I assume you mean --experimental_workspace_rules_log_dir (distinct from the existing experimental_workspace_rules_log_file flag).
> 
> Ah, yes, sorry for the mistake, fixed.
> 
> > What about using variable substitution to allow a value like "/tmp/workspace_log_${command_id}.log" for the --experimental_workspace_rules_log_dir flag? Is there a standard string templating syntax used in other parts of the project that could be used here for consistency? That would alleviate the need for the flag and provide the functionality I desire.
> 
> I don't think we currently support such syntax.

I updated the pull request to support `{{command_id}}` substitution in all of these flags. The idea behind using `{{x}}` instead of `${x}`  is to make it sufficiently different from bash substitution that it's apparent something else is going on to an unfamiliar user.

> 
> > I can work around this... but the proposal is a 5 line change vs the workaround, which will require writing a wrapper for the bazel binary.
> 
> This isn't just a 5 line change. It's the Bazel team who will need to maintain or clean up this in the future. Also if we allow using a dir for the workspace debug log, what about flags for other log files, it's hard to justify why we need to special case this one but not others.

I understand. I was hoping to find a solution with a minimal maintenance burden.

**Comment by meteorcloudy** [comment]
@gonzojive Thanks for this PR, I understand it's a nice thing to have for you. But I checked this flag is an experimental feature that's currently unmaintained. I strongly prefer to not add more complexity to Bazel while there are simple work arounds.

**Comment by gonzojive** [comment]
That's fine. I understand wanting to keep the codebase easy to understand. I'll work around this by wrapping the bazel binary a la bazelisk.

The PR affects non-experimental flags as well. The main complexity is the introduction of a templating syntax. The ability to put templated strings in configuration files and flags is pretty valuable in some cases. I am thinking of VS Code's configuration files, for instance - often the configuration values can include strings like ${workspaceDir}.

**Pull request closed without merging**
