### PR TITLE
[WIP] Git repository rule cache

### LINKED ISSUE #5116: Should git_repository use repository cache?
### Description of the problem / feature request:

have `new_git_repository` rules use the `repository_cache`

### Feature requests: what underlying problem are you trying to solve with this feature?

I'd like to be able to reuse external git dependencies like one can reuse new_http_archive

### PR DESCRIPTION
**Pull request by ittaiz**
fixes #5116 still WIP
Main open question which we'd love @aehlig's thoughts about is how to decide where to clone this?
Ideally it should be controlled by `--repository_cache`'s value and just add a new key type (`git`?) which this code clones under it. WDYT?
If this sounds like a good idea we'd really appreciate pointers on how to access the command line flag's value from the repository rule.

thank you @aoded and @eyalmalron for your work on this

### CODE REVIEW

**Comment by ittaiz** [comment]
@aoded is a Wix employee and Wix has signed the corporate CLA.

**Comment by edbaunton** [comment]
If you clone from the cache (on the same filesystem) I believe git will automatically create hardlinks for you https://git-scm.com/docs/git-clone

**Comment by ittaiz** [comment]
@aehlig can we get your feedback about this? Also, how do you recommend we handle the path?
I have a bit of hope of getting this before 0.17.0 RC1 is cut (probably next few days)

**Comment by Globegitter** [comment]
Ah nice @edbaunton the docs do talk about hard linking but only when the `--local` flag is provided. So should this flag maybe be passed in also?

**Comment by ittaiz** [comment]
@aehlig ping

**Comment by aehlig** [comment]
> @aehlig ping

I didn't realize you already wanted a review for a pull request marked "Work in progress".

In any case, the concern I already mentioned in direct communication is still
valid: sharding the git cache by name(!) of the repository contradicts the general
idea of our repository caches being conent-addressable. This also is unnecessary,
as git already stores everything in a content-adressable way.

Also, hard-coding cache paths is not a ready-to-merge solution. Using an appropriate
environement variable (and falling back to not caching, if unset) is a solution for
the time being, till #6016 is done.

-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by VolodymyrPolishchuk** [comment]
> @aehlig ping
> I didn't realize you already wanted a review for a pull request marked "Work in progress". In any case, the concern I already mentioned in direct communication is still valid: sharding the git cache by name(!) of the repository contradicts the general idea of our repository caches being conent-addressable. This also is unnecessary, as git already stores everything in a content-adressable way. Also, hard-coding cache paths is not a ready-to-merge solution. Using an appropriate environement variable (and falling back to not caching, if unset) is a solution for the time being, till #6016 is done.
> […](#)
> -- Klaus Aehlig Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen Registergericht und -nummer: Hamburg, HRB 86891 Sitz der Gesellschaft: Hamburg Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

Hi Klaus! 
we are working on improvement of this PR to align with bazel's vision of local cache. 
Afaiu, if we clone multiple repositories into temp directory, we may encounter naming collisions, since repositories end up being folders of the same name as repository, am i correct?

**Comment by unapiedra** [comment]
Thank you @aehlig  for the nice collaboration today at the hackathon. My branch can be found [here](https://github.com/unapiedra/bazel/tree/feature/git_repo_rule_cache). 

I've written what is definitely still missing inside the commit.

**Comment by meisterT** [comment]
What's the status of this PR? Can we close it in favor of @siedentop 's changes?

**Pull request closed without merging**
