### PR TITLE
Identify isolated extensions by exported name

### PR DESCRIPTION
**Pull request by fmeum**
Instead of making a running counter and the `dev_dependency` bit the
identifier of an isolated module extension usage within a module file,
use the exported name of the usage. This still results in a stable name
even with `--ignore_dev_dependency` flips, but makes the canonical
repository name more recognizable and allows for less verbose buildozer
fixup commands.

### CODE REVIEW

**Comment by fmeum** [comment]
Stacked on https://github.com/bazelbuild/bazel/pull/18829

**Comment by fmeum** [comment]
@Wyverald I rebased onto master.

**Comment by fmeum** [comment]
@bazel-io flag

**Review by Wyverald — APPROVED** [review]

**Comment by iancha1992** [comment]
@bazel-io fork 6.3.0

**Comment by iancha1992** [comment]
@fmeum @Wyverald looks like there's a conflict when attemting a cherry-pick to release-6.3.0.

1) src/main/java/com/google/devtools/build/lib/bazel/bzlmod/BazelDepGraphFunction.java
"bestName" variable should not be:
String bestName = nonEmptyRepoPart + "~" + id.getExtensionName();

Instead, should be somewhat looks like below: 
String bestName =
          id.getIsolationKey()
              .map(
                  namespace ->
                      String.format(  [some code] )

Can you please take a look and let us know which commit to push in order to resolve this? Thanks!           

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
It's safe to just use the longer snippet you pasted.

**Comment by keertk** [comment]
@fmeum @Wyverald we're not able to get this into rc1 (to go out shortly) unfortunately - there are still some failures in https://github.com/bazelbuild/bazel/pull/18923.

Please let us know if this cherry-pick is required and we can create another release candidate in the coming days. Thanks!

**Comment by fmeum** [comment]
See https://github.com/bazelbuild/bazel/pull/18923#issuecomment-1633865452, a previous cherry-pick ended up partially reverting an earlier one.

**Pull request closed without merging**
