### PR TITLE
Add thin_lto to NDK CC toolchain features

### PR DESCRIPTION
**Pull request by keith**
This is a direct copy of the unix toolchain thin_lto setup

Related: https://github.com/bazelbuild/bazel/issues/13287

### CODE REVIEW

**Comment by jgavris** [comment]
Thanks @keith as always!

**Comment by keith** [comment]
Looks like CI has an older version of the NDK than I was testing, I guess we might also have to force on lld in this case, which I found to be a bit of an issue with rules_foreign_cc in my testing, but might just need to be fixed there

**Comment by jgavris** [comment]
Is there any test coverage for NDK 19 in CI (especially on macOS, since most of our mobile devs have Apple laptops)? Looking at the Buildkite pipeline I don't have a lot of confidence.

**Comment by cpsauer** [comment]
Hey all! Was setting up the new NDK toolchain (https://github.com/bazelbuild/rules_android_ndk) and noticed it has a thin_lto feature built in. Maybe that obsoletes this?

**Comment by keith** [comment]
dropping for new ndk rules

**Pull request closed without merging**
