### PR TITLE
[6.0.0] [remote] Respect whether the server supports action cache updates

### PR DESCRIPTION
**Pull request by Yannic**
Only a subset of users may be allowed to update the action cache (e.g., only CI but not devs).

Today, there are 2 ways to achive the desired behavior:
  - `GetCapabilities` returning that all users are allowed to update, and `UpdateActionResult` returning an error that Bazel prints and ignores, or
  - have the users that are not allowed to update the action cache set `--remote_upload_local_results=false`.

Why don't we instead respect whether the remote cache supports uploading action results?

Note that this requires support from the remote system to fully work (i.e., it needs to return `update_enabled = false` for users that don't have permission). Otherwise, Bazel's behavior will be the same as before this change: failed `UpdateActionResult` do not cause the build to fail. The only change this introduces is that Bazel will no longer error if `--remote_upload_local_results=true` and `GetCapabilities` returning `update_enabled = false`.

Closes #16624.

PiperOrigin-RevId: 486901751
Change-Id: I0991f6891e21711df1e23ae0998a8bc95e2389bc

### CODE REVIEW

**Comment by Yannic** [comment]
@meteorcloudy @kshyanashree PTAL

**Comment by meteorcloudy** [comment]
@coeuvre Please LGTM if this looks good to be cherry-picked for 6.0 ;)

**Review by coeuvre — APPROVED** [review]
Yes, it's safe to cherry-pick this into 6.0.

**Comment by meteorcloudy** [comment]
@Yannic Can you rebase?

**Comment by Yannic** [comment]
thanks! done

**Pull request merged**
