### PR TITLE
Pass stdin through test-setup.sh

### PR DESCRIPTION
**Pull request by DavidANeil**
stdin was not being passed through to the test script.
ibazel depends on being able to write to stdin to notify test runner
scripts that there are updates.
Test runners were previously unable to read the messages from stdin
because the stream was closed.

### CODE REVIEW

**Comment by DavidANeil** [comment]
Full disclosure: I don't really know bash, and I may have missed some places, or changed places where it isn't needed.

**Comment by jmmv** [comment]
So this is actually trying to propagate stdin to the *test*, right?

I'm surprised this is necessary at all because the stdin should be automatically inherited by subprocesses:

```
$ cat >test.sh <<EOF
#!/bin/sh
sed -e 's,^,inherited: ,'
EOF
$ echo foo | sh test.sh
inherited: foo
```

Could you add an integration test to demonstrate what this changes?

**Comment by DavidANeil** [comment]
I believe stdin has to be explicitly redirected because the test is being run as async/background.
I will test adding the redirection only to the two lines that run in the background and see if it works as expected with ibazel.
I will also begin work on some integration tests.

**Comment by Globegitter** [comment]
Yep if processes are started in the background via `&` they do not get stdin passed through automatically. You can find an issue here: https://github.com/bazelbuild/bazel-watcher/issues/184 and this should be the repro: https://github.com/Globegitter/bazel-watch-test-repro

**Comment by DavidANeil** [comment]
I am having a hard time trying to find how to write a test for this behavior.
I would love some help in getting started on it.

**Comment by iirina** [comment]
@jmmv can you take another look?

**Comment by DavidANeil** [comment]
I have recently finished a large project and have time to come back to this.  If someone could say "look at file `x` and make a test for this that looks like that" I should be able to get this ready to merged quickly.

For what it's worth, we have been using a cherry-pick of this branch on our fork internally since this PR was opened and everything looks great.

**Comment by laszlocsomor** [comment]
@DavidANeil : Could you please demonstrate a minimal scenario this PR fixes? I thought this PR is supposed to forward Bazel's stdin to the test so `echo hello | bazel test //foo:bar` would pass "hello" to the test's stdin, but that doesn't seem to happen.

**Comment by DavidANeil** [comment]
I'm not sure how Bazel handles stdin internally, but I do know that for iBazel, this change allows iBazel to communicate on stdin with the test runner.

Without this change, stdin would be closed almost immediately on the test runner.

See https://github.com/bazelbuild/bazel-watcher/issues/184

**Comment by JaredNeil** [comment]
I don't believe it will (or should) work for `bazel test`, since the stdin would not be part of the cache key. It should, however pass the stdin through when you `bazel run` a `_test` target.

For example: 
`read.sh`:
```
#!/bin/bash
n=1
echo "BEGIN"
while read p; do
  echo $((n++)) $p
done
echo "END"
```
`BUILD.bazel`:
```
sh_test(
    name = "read",
    srcs = ["read.sh"],
)
```
Running:
```
$ echo -e "one\ntwo\nthree" | bazel run :read
WARNING: Option 'direct_run' is deprecated
INFO: Invocation ID: f4cb4a02-02ad-4e1e-9ffb-441ada86155a
INFO: Analysed target //:read (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:read up-to-date:
  bazel-bin/read
INFO: Elapsed time: 0.194s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:read
-----------------------------------------------------------------------------
BEGIN
1 one
2 two
3 three
END
```

**Comment by laszlocsomor** [comment]
> I'm not sure how Bazel handles stdin internally, but I do know that for iBazel, this change allows iBazel to communicate on stdin with the test runner.

Could you maybe tell more about how you came upon this bugfix? That might help revealing what's happening in Bazel.

> I don't believe it will (or should) work for `bazel test`, since the stdin would not be part of the cache key. It should, however pass the stdin through when you `bazel run` a `_test` target.

Agreed. I tried the patch with `bazel test` and couldn't pass input through stdin. (I didn't try `bazel run`.)

However, `bazel run`'ing a test target in general seems odd, I wonder what purpose `bazel test` fails to fulfill. Again, it'd be very helpful to see an example with Bazel (not iBazel) to understand exactly what's fixed here, because I can't in good conscience approve of this change without understanding what it fixes.

I'll be away next week so let me loop in @jmmv again.

**Comment by DavidANeil** [comment]
We use `test` for headless and `run` for browser/debugger testing.
I'll let @JaredNeil answer how we arrived at this, as this was literally day one for me in the Bazel codebase.

**Comment by DavidANeil** [comment]
I'd also like to note that there are 6 code paths that invoke the test from within this wrapper script, the 2 modified in this commit were the only 2 that didn't already pass stdin through.

**Comment by JaredNeil** [comment]
Debugging tests is annoying if you use `bazel test` because you have to set the `--test_timeout` to some arbitrarily high number, and if you don't set it high enough, it'll kill your process while you're still trying to debug something. For this reason, we have been using `bazel run` whenever we want to debug a test.

After ibazel detects changes and re-builds a target that you have `bazel run`, it normally kills the subprocess and re-starts it, but for some things like a dev server or test runner we don't actually need to restart the whole process because most of the time it's just the data (code to be served to the browser) that has changed, not the process's code. So ibazel has an option to just send a message to the subprocess on stdin, notifying it of the completed build, so it can reload the data without restarting the whole process.

We came across this issue when we noticed that those messages were getting swallowed by the `test-setup.sh`. As far as I can tell, `test-setup.sh` is meant to be transparent, and as @DavidANeil mentioned, it is in 4 of the 6 code paths. This change just makes that 6 of 6. Consistency is my only non-ibazel argument for this change. If have an `x_binary` and `x_test` and `bazel run` them both, stdin is forwarded to one, but not the other. That's inconsistent.

For us, this change means we can `ibazel run :some_js_test`, and it will launch chrome and run the tests. And then if you make a change to the test code, ibazel will rebuild and signal the test runner to reload the browser and rerun the new test code. This all happens without closing the browser, so you don't lose all of your breakpoints, or have windows flashing out of and into existence. This in-browser hot-reload workflow is very common in the JS ecosystem and we really don't want to go back to the old, slow way of re-launching the whole test runner and Chrome processes after every change.

**Comment by kornholi** [comment]
Yeah, interactively debugging tests under `bazel run` is the goal here. For example, pytest can be invoked with `--pdb` to drop into a debugger after the first failure, and it would be nice to `bazel run :test -- --pdb`. Easily replicating the test environment isn't always straightforward, and sometimes our users have resorted to (incorrectly) running tests from `bazel-bin`...

Envoy similarly worked around this issue to run tests under gdb, see https://github.com/envoyproxy/envoy/blob/master/tools/gen_gdb_wrapper_script.py#L3-L6 and https://github.com/envoyproxy/envoy/blob/master/tools/bazel-test-gdb. Although I agree that stdin should not be connected for `bazel test`, only `bazel run`.

**Comment by laszlocsomor** [comment]
Thank you all for the explanation.
I filed a bug to track this on Windows: https://github.com/bazelbuild/bazel/issues/9344

I added tests for this PR, please copy them over (run_test.sh and test_test.sh):  https://github.com/bazelbuild/bazel/compare/master...laszlocsomor:gh8322

**Comment by laszlocsomor** [comment]
I imported and rebased this PR and ran the tests, all is good: https://buildkite.com/bazel/google-bazel-presubmit/builds/24360

**Pull request closed without merging**
