### PR TITLE
Remove superfluous bazel_toolchains patch (part 2)

### PR DESCRIPTION
**Pull request by philsc**
This is a follow-up to 4e2a330d3699a89191728161834663daf12d891a.

Now that the `target_compatible_with` attribute no longer applies to
repository rules, this patch is superfluous.

### CODE REVIEW

**Comment by philsc** [comment]
@katre , this is part 2 of the patch deletion.

**Comment by katre** [comment]
I am on vacation today and will take a look tomorrow.

**Comment by katre** [comment]
I can merge this, but @gregestren can you also check that this is safe before I do so?

**Comment by katre** [comment]
Greg is out til next week, unassigning him.

**Review by katre — APPROVED** [review]

**Comment by katre** [comment]
I will go ahead and merge this today.

**Pull request closed without merging**
