### PR TITLE
Update to Error Prone 2.5.1

### PR DESCRIPTION
**Pull request by cushon**
RELNOTES[INC]: Update to Error Prone 2.5.1 (https://github.com/google/error-prone/releases/tag/v2.5.1)

### CODE REVIEW

**Review by comius — APPROVED** [review]
Please also add `RELNOTES[INC]: ` tag to PR description. There were some issues in the past upgrading error prone, see https://github.com/bazelbuild/bazel/issues/11769. But this can now be handled better with java_tools releases.

**Comment by cushon** [comment]
> Please also add RELNOTES[INC]: tag to PR description.

Done.

(To confirm, do I need to do anything to merge this?)

**Comment by comius** [comment]
> > Please also add RELNOTES[INC]: tag to PR description.
> 
> Done.
> 
> (To confirm, do I need to do anything to merge this?)

I'll import it.

**Comment by philwo** [comment]
Yes, I can merge this today.

**Comment by philwo** [comment]
Turns out I can't merge this today, because I can't reach my workstation via SSH. 😅 I'll try again tomorrow morning.

**Comment by philwo** [comment]
@cushon @comius I'm sorry, I forgot to merge this :( It seems like this is still applicable and 2.5.1 is still the latest version, so I went ahead and merged it now.

**Comment by cushon** [comment]
Thanks @philwo!

It looks like it was merged as 1ec75002589529dafbe54a67da62928db2a56b9c.

**Pull request closed without merging**
