### PR TITLE
Point rule reference link to correct subsection

### PR DESCRIPTION
**Pull request by amalkurup89**
Description

Correcting an href link to point to correct subsection on the child html page

Motive

To help current and future users of this repository

### CODE REVIEW

**Comment by amalkurup89** [comment]
@googlebot I signed it!

**Comment by amalkurup89** [comment]
@googlebot I signed it!

**Comment by gregestren** [comment]
I could see an argument either way.

It's true this change jumps straight to the rule list itself. But the whole page is a "rule reference" that includes common functionality that's still relevant to using rules.

What do you think?

**Comment by philwo** [comment]
What's the status of this PR?

**Comment by gregestren** [comment]
There was some recent debate about whether we should even have this page. @floriographygoth is best qualified to further triage.

Thanks, @amalkurup89 , for your interest and patience in this.

**Comment by aiuto** [comment]
Closing because it is 9 months stale.

**Pull request closed without merging**
