### PR TITLE
Add remotejdk archives for Java 19.

### PR DESCRIPTION
**Pull request by benjaminp**
Azul doesn't provide ARM Windows archives for JDK 19, so that architecture is omitted.

Java 18 archives are removed because it is an old non-LTS release.

### CODE REVIEW

**Comment by benjaminp** [comment]
Only having the latest LTS release makes sense to me, but do you want me to drop 18 in this PR, too?

**Review by cushon — APPROVED** [review]

**Comment by meisterT** [comment]
cc @coeuvre

**Comment by Wyverald** [comment]
Should the same change be made in rules_java?

**Comment by benjaminp** [comment]
Is rules_java useful for anything? I had the impression rules_java and rules_cc were on the backburner at least until starlarkification is complete.

**Comment by comius** [comment]
> Is rules_java useful for anything? I had the impression rules_java and rules_cc were on the backburner at least until starlarkification is complete.

Yes, it's used by bzlmod already as a dependency in MODULE.tools: https://github.com/bazelbuild/bazel/blob/master/src/MODULE.tools#L4

When using bzlmod, this is where the default configuration comes from.

We will start using it more a more throughout this year (moving @bazel_tools/tools/jdk, Java rules and providers into it), until it becomes a requirement for Java rules.

**Pull request closed without merging**
