### PR TITLE
[7.2.0] Add a new `include()` directive to MODULE.bazel files 

### PR DESCRIPTION
**Pull request by Wyverald**
This new directive allows the root module to divide its `MODULE.bazel` into multiple segments. This directive can only be used by root modules; only files in the main repo may be included; variable bindings are only visible in the file they occur in, not in any included or including files. See the docs for `include()` (in `ModuleFileGlobals.java`) for more details.

RELNOTES: Added a new `include()` directive to `MODULE.bazel` files, which allows the root module file to be divided into multiple segments.

PiperOrigin-RevId: 627034184
Change-Id: Ifc2f616cf0791445daeeac9ca5ec4478e83382aa

### CODE REVIEW

**Review by iancha1992 — APPROVED** [review]

**Comment by peakschris** [comment]
@wyverald, thanks so much for this great feature!

I'm trying this out using latest on release-7.2.0, and when I change one of the included x.MODULE.bazel files, the change isn't being picked up in the build, unless I delete MODULE.bazel.lock.

Should I create an issue?

**Comment by Wyverald** [comment]
no, this is working as intended -- with @fmeum's work on #20369 (also shipping in 7.2.0), we'll _always_ run module resolution and hence pick up your changes to included files.

**Comment by peakschris** [comment]
Great, thank you, I'll track #20369 and update to it once available.

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!

**Pull request merged**
