### PR TITLE
Allow specifying target and exec constrains in remote_java_repository

### PR DESCRIPTION
**Pull request by menny**
This is a continuation of https://github.com/bazelbuild/bazel/commit/27fe30bb7cc1fdea7c60d7f73774149c0dd21457
This is useful for setting constraints on java toolchains.

### CODE REVIEW

**Comment by katre** [comment]
Please update the description to say _what_ can now use target and exec constraints, I was very confused until I read the code.

**Comment by menny** [comment]
I was looking at the [commit](https://github.com/bazelbuild/bazel/commit/d5559c16ac008b86345fbbade5d600181a2fce6f) that changed `exec_compatible_with` to `target_compatible_with` and I wonder if we need to change the usages back to `exec_compatible_with` in the [jdk workspace template](https://github.com/bazelbuild/bazel/blob/d5559c16ac008b86345fbbade5d600181a2fce6f/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE.tmpl). WDYT?

**Comment by menny** [comment]
The setup that failed for us is this:
- we build on a Linux-x86_64 machine. Our JDK is setup using `remote_java_repository`.
- we are building an Android app with C++ library.
- for each android CPU type, we have a different `platform`.

Our JDKs are with these `compatible_with`:
- Linux: ["@platforms//os:linux", "@platforms//cpu:x86_64"]
- mac Intel: ["@platforms//os:macos", "@platforms//cpu:x86_64"]
- mac Apple Silicon: ["@platforms//os:macos", "@platforms//cpu:aarch64"]
- Windows: ["@platforms//os:windows", "@platforms//cpu:x86_64"]

Our command line to build the app with arm64 variant will look something like this:
```
bazelisk build //src/main/java/com/app:app --platforms=@client-core//other/bazel/platform:android-arm64
```

This will fail with bazel 6.2 since our JDKs are not _target_ compatible with the specified `platforms` argument.

**Comment by menny** [comment]
Switching from `target_compatible_with` to `exec_compatible_with` solves our problem. My rationale was that the Java compiler produces byte-code artifacts that are cross-platform, but the binaries in the JDK package are specified to the host (`exec`).

**Comment by hvadehra** [comment]
The file changed here have been moved out of bazel and now resides in `@rules_java`. If this is still an issue with Bazel 7, please consider opening a PR in that repo.

**Pull request closed without merging**
