### PR TITLE
Remove references to python/private in third_party

### PR DESCRIPTION
**Pull request by comius**

### CODE REVIEW

**Review by rickeylev — APPROVED** [review]

**Comment by comius** [comment]
This needs a github merge.

**Comment by rickeylev** [comment]
Are you asking me to do so? I don't have permission.

**Comment by sgowroji** [comment]
Merged at 4e739d30431a31b5ab67187d29299809ac6c277a

**Comment by comius** [comment]
> Are you asking me to do so? I don't have permission.

No. I don't have permission either. Those were just instructions for gtech.

Thanks @sgowroji!

**Pull request closed without merging**
