### PR TITLE
[4.2.0 Cherry-pick] Fixes crashes due to an overly optimistic class cast (#13240)

### PR DESCRIPTION
**Pull request by larsrc-google**
Cherrypick of 2c3cff5. No relnotes.

### CODE REVIEW

**Comment by katre** [comment]
Looks like there's another commit required to make RootType public, do you know what it might be?

**Comment by larsrc-google** [comment]
RootType? What RootType?

**Comment by katre** [comment]
```
src/test/java/com/google/devtools/build/lib/dynamic/DynamicSpawnStrategyUnitTest.java:103: error: RootType is not public in ArtifactRoot; cannot be accessed from outside package
--
  | rootDir = ArtifactRoot.asDerivedRoot(execDir, RootType.Output, "root");
  | ^
```

**Comment by larsrc-google** [comment]
I think those failures are due to the other commits, not this particular
change.

-Lars

**Comment by larsrc-google** [comment]
Need to merge this with other commits in a more organized manner.

**Pull request closed without merging**
