### PR TITLE
[6.1.0]Only fetch @remote_coverage_tools when collecting coverage

### LINKED ISSUE #15088: `cc_test` rules trigger remote JDK download (~200 MB)
### Description of the problem / feature request:

`cc_test` rules trigger remote JDK download (~200 MB), which is undesirable when operating under constraints on storage capacity and/or network capacity. https://en.wikipedia.org/wiki/Principle_of_least_astonishment also applies.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
$ rm -rf $HOME/.cache/bazel
$ git clone https://github.com/google/re2.git
$ cd re2
$ bazel build //:all --experimental_repository_resolved_file=resolved.bzl
$ grep openjdk resolved.bzl
$ bazel query 'somepath(//:all, @remote_coverage_tools//:all)'
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

```
release 5.0.0
```

### PR DESCRIPTION
**Pull request by kshyanashree**
Before this change, every test rule had an implicit dependency on `@bazel_tools//tools/test:coverage_report_generator`, even though this tool is only used when collecting coverage.

This is fixed by moving it to `CoverageOptions` and using the late-bound default resolver to only create a dependency if coverage is enabled.

Also adds `CoverageOptions` to the set of options classes trimmed by `--trim_test_configuration` so that, as before, changing `--coverage_report_generator` doesn't cause non-test rules to be reanalyzed. This behavior now extends to `--coverage_output_generator`.

Fixes #15088

Closes #16995.

PiperOrigin-RevId: 498949871
Change-Id: I2440fae2655bbb701e918ee2aa7acb008d8f97ed

### CODE REVIEW

**Review by comius — APPROVED** [review]

**Comment by kshyanashree** [comment]
Hello @fmeum, Above presubmits checks are getting failed. Could you please fix those failures? Thanks!

**Comment by fmeum** [comment]
@kshyanashree This is a known flake, could you rerun the pipeline?

**Comment by kshyanashree** [comment]
> @kshyanashree This is a known flake, could you rerun the pipeline?

I did it before but still it was failing. Now it’s not showing me the option to reran the particular build.

**Comment by fmeum** [comment]
@kshyanashree CI is green now, but there are conflicts. I resolved them over at https://github.com/bazelbuild/bazel/pull/17512.

**Comment by fmeum** [comment]
@kshyanashree https://github.com/bazelbuild/bazel/pull/17513 should reduce the flakiness of the release branch on Windows.

**Comment by meteorcloudy** [comment]
@keertk Do you remember why we need https://github.com/bazelbuild/bazel/pull/17287/commits/f7e91ab1cb0b66ebfcbfe467e224cb3f689b64bf? This PR is basically the same cherry pick as https://github.com/bazelbuild/bazel/pull/17512 with that additional commit.

**Comment by keertk** [comment]
To close this out - there's a difference between what's [here](https://github.com/bazelbuild/bazel/pull/17287/files) (`//third_party:jsr305_checked_in`) vs what's in the copybara [commit](https://github.com/bazelbuild/bazel/commit/4d188a9beaf3b003d2cb3409000424acf5fd82b7) (`//third_party:jsr305`).
We'll make the update to match the copybara commit for RC2.

**Pull request merged**
