### PR TITLE
REST Cache - Add option for authorization header

### PR DESCRIPTION
**Pull request by justinwp**
I am not a Java person :)

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by hhclam** [comment]
Is this supposed to handle kerberos authentication? What's the use case?

I'm a bit concern that this is not a generic solution as the auth token might need to updated during build depending on the authentication system.

**Comment by justinwp** [comment]
How is that different from the passing basic auth through the remote_rest_cache parameter? This is incredibly generic and the only way to handle changing tokens is probably to use a fully featured client for oauth/kerberos/other.

**Comment by hhclam** [comment]
What's the backend you're using and how often do you need to update the token?

**Comment by buchgr** [comment]
thanks @justinwp . Are you using this with basic auth?

**Comment by philwo** [comment]
@justinwp Could you please let us know if you'd still like this patch in? If yes, can you please rebase it and add a test? Thanks :)

**Comment by softprops** [comment]
The release version currently support basic auth as a feature of http clients ability to parse auth out of a urls but is not ideal. Can someone confirm if  this change resolves https://github.com/bazelbuild/bazel/issues/4209

**Comment by buchgr** [comment]
Closing this for now. Please fill free to re-open if there's interest again. Thanks!

**Pull request closed without merging**
