### PR TITLE
Add worker assertions to test_java_8_android_binary_worker_strategy

### PR DESCRIPTION
**Pull request by Bencodes**
Adding more worker assertions for desugaring to prevent future regressions.

### CODE REVIEW

**Comment by ted-xie** [comment]
Thanks, this is some really nice forward-looking work!

**Comment by Bencodes** [comment]
I think it might be broke for similar reasons, but here's a test for multiplex workers as well. https://github.com/bazelbuild/bazel/pull/17351

**Comment by sgowroji** [comment]
Hi @Bencodes, Above PR is awaiting to merge, Could you please fix the above buildkite  errors. Thanks!

**Comment by ted-xie** [comment]
@sgowroji I'll take a look at the failing tests. They are actually exposing underlying issues in Bazel.

**Comment by Bencodes** [comment]
@ted-xie @sgowroji going to close this PR in favor of https://github.com/bazelbuild/bazel/pull/17351 which has all the fixes in place for workers and multiplex workers.

**Pull request closed without merging**
