### PR TITLE
Add ability to add runfiles to tar

### PR DESCRIPTION
**Pull request by c4urself**

### CODE REVIEW

**Comment by c4urself** [comment]
I signed it!

**Comment by c4urself** [comment]
This is essentially a continuation of the thread found here: https://github.com/bazelbuild/bazel/pull/2687

I looked into this because I want to tar & deb a `py_binary` rule. Without the runfiles, the `pkg_tar` rule does the wrong thing, it adds the executable and nothing else while the `py_binary` executable relies on the runfiles being there; without them things don't work. I looked at an alternative in `par_binary` (subpar) because that creates one "zip" with everything in it, but that particular rule doesn't work with `py_library` rules with C-extensions (which I need). So I tried implementing the changes in this PR, retrofitting them to the latest HEAD. A couple of observations:

* it seems like `default_runfiles` and `data_runfiles` are identical for my builds, can anyone shed light on what the difference is?
* simply adding the `default_runfiles` if there are any does **not** work for my case because, at least for `py_binary`, all the files need to be in a specific place for the PYTHONPATH hackery that happens in the entrypoint executable (of `py_binary`) to work properly. In particular, the `__main__` directory is missing entirely and I don't see it in the `default_runfiles` attribute at all.

**Comment by vsbus** [comment]
Hey there! Is there any ETA on merging this PR? Looking forward for it :)

**Comment by jin** [comment]
@aehlig Not sure who owns the pkg rules now, ptal or reassign, thanks!

**Comment by aehlig** [comment]
>  Not sure who owns the pkg rules now

No one really...

**Pull request closed without merging**
