### PR TITLE
Enable using workspace_name in CROSSTOOL template

### PR DESCRIPTION
**Pull request by abergmeier**
This way we can reference hermetic libraries.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
How are you going to use it? Can we find another way to do it?
//cc @mhlopko

**Comment by abergmeier** [comment]
> Can we find another way to do it?

Will want to specify paths to binaries in repos like `external/foo/clang++`. Not that much a fan of `-B` - I'd rather have the correct paths to begin with.

**Comment by mhlopko** [comment]
Sorry Andreas could you elaborate I don't follow. You want to reference external packages from the crosstool? The commit doesn't make much sense to me, you're adding a variable to the template expansion, but you don't actually use that variable in the CROSSTOOL.tpl. What were you trying to achieve?

**Comment by abergmeier** [comment]
> You want to reference external packages from the crosstool?

I do. But I just encountered a more elegant way of doing that. So cratch that commit :)

**Comment by mhlopko** [comment]
:)

**Pull request closed without merging**
