### PR TITLE
Polishing

### PR DESCRIPTION
**Pull request by jbduncan**
This is another follow-on to https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-dev/Q2owiR-e86s/ugrVUhn7AwAJ to introduce a number of cleanups, such as conversions to more modern Java idioms and applying fixes for some apparently applicable IntelliJ IDEA code inspections, to make the code base more maintainable.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by buchgr** [comment]
I don't think this should be merged. It pollutes the git history and has a chance of introducing bugs. The benefit seems non-existent to me.

**Comment by jbduncan** [comment]
Hi @buchgr, thanks for taking a look at this!

I just wondered if you could clarify for me what it is about this PR that you think is no good? I ask as I would like to get a feel for what sorts of changes are considered acceptable and which aren't, so that I can produce PRs which are more likely to be beneficial to the project and get merged in like https://github.com/bazelbuild/bazel/pull/3623.

**Comment by buchgr** [comment]
Jonathan, 

> I just wondered if you could clarify for me what it is about this PR that you think is no good? I ask as I would like to get a feel for what sorts of changes are considered acceptable and which aren't

I feel like you kind of know. It's been discussed to a great extend in the mailing list thread you point to in your commit message. I personally would not have merged #3623 and pointing to such commits to justify future changes is not a good strategy.

Now, I think it's great that you want to contribute to Bazel, but I think we could utilize everyones time the best if we focused on fixing bugs and adding features. If the code gets cleaned up in the process - even better!  If you are interested, I am more than happy to help finding bugs/feature requests that you might be interested in working on and helping out with guidance and reviews. And so is everyone else on the Bazel team. Just let us know :-).

Jakob

**Comment by jbduncan** [comment]
Hi @buchgr! Many thanks for taking the time to respond.

Your explanation sounds totally fair to me. I do realise now that I pushed my luck given what was discussed on the mailing list thread I linked to and the Bazel team's stance on preferring bug fixes/feature requests, so thank you for responding so patiently.

I would be very happy to leave this PR and #3711 to one side and to take up on your offer to find bugs/feature requests that I might be interested in! :)

> Now, I think it's great that you want to contribute to Bazel, but I think we could utilize everyones time the best if we focused on fixing bugs and adding features. If the code gets cleaned up in the process - even better!

Thanks, I'll keep this in mind. :)

Cheers!

**Comment by buchgr** [comment]
@jbduncan feel free to take on bugs you are interested in (add a comment that you are working on this) or to ping bazel-discuss or me personally (buchgr@) to discuss things you could work on.

**Comment by jbduncan** [comment]
Hi @buchgr, it actually occurs to me that I'm rather busy with IRL things and my free time is divided amongst other open source projects ATM, so I'm sorry to say I'll have to decline your very kind offer for now, but I would be very happy to ping bazel-discuss for advice or pointers once I'm ready. :)

**Comment by buchgr** [comment]
You are always welcome :-)!

**Pull request closed without merging**
