### PR TITLE
Allow native repository rules to declare toolchains they want

### PR DESCRIPTION
**Pull request by katre**
registered.

### CODE REVIEW

**Comment by juliexxia** [comment]
Do we expect different rule classes to want to declare toolchains with different functionality?

**Comment by katre** [comment]
Only repository rules will want to register toolchains. The `register_toolchains` function just takes a string (which should be a valid target pattern, but that's checked later). There's no actual functionality possible in this stage.

**Comment by juliexxia** [comment]
Right right that makes sense to me, I was just wondering why we need to pass a function to RuleClass instead of the toolchains themselves if we expect what we want to pull out of RuleClass to always be the same - if that makes sense?

**Comment by katre** [comment]
Oh, the function is what allows the rule to specify the actual name. using the repository name.

See https://github.com/bazelbuild/bazel/commit/6ac6bef8a0da746c0a711f165e1e3170e7d95d30#diff-688f3bda2aede4d7ff4b19e9e61bb840R55 for the example of this being used.

**Comment by juliexxia** [comment]
Oh oh I understand, it's android_respository_rule related functionality so we don't want to embed it into ruleclass. gotcha!

**Comment by katre** [comment]
Any further comments?

**Pull request closed without merging**
