### PR TITLE
Let native Turbine image find `ct.sym` with non-hermetic `java_runtime`

### PR DESCRIPTION
**Pull request by fmeum**
Work towards #21604

### CODE REVIEW

**Comment by fmeum** [comment]
CC @coeuvre 

I haven't managed to write a test for this (it fails with a different error in Turbine), but verified that this fixes the reproducer.

**Review by coeuvre — APPROVED** [review]
Thanks for the fix!

**Comment by fmeum** [comment]
@bazel-io fork 7.2.0

**Comment by coeuvre** [comment]
@meteorcloudy can we also include this fix in 7.1.0? The risk should be pretty low.

**Comment by hvadehra** [comment]
It would be really nice to have a test, given how non-localized the involved interactions are (bazel, rules_java, java_tools, etc). Otherwise, LGTM to me as an isolated improvement[^1] (and we can always try adding a test in a followup). 

[^1]: I don't think this is the correct resolution to https://github.com/bazelbuild/bazel/issues/21604 but I'll discuss more about that there.

**Review by hvadehra — APPROVED** [review]
Approving, @fmeum if adding a test is too problematic, please let me know and we can merge this anyways.

**Comment by meteorcloudy** [comment]
@coeuvre We just cut rc2 for 7.1.0 and were hoping it would be the last rc. Maybe we can backport this change along with all other JDK 21 changes all together in 7.2.0?

**Comment by coeuvre** [comment]
SG!

**Comment by coeuvre** [comment]
@bazel-io fork 7.1.1

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.1.1 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.1.1rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.1.1rc1. Thanks!

**Pull request closed without merging**
