### PR TITLE
Fix --host_features with multiple transitions

### PR DESCRIPTION
**Pull request by keith**
Fixes https://github.com/bazelbuild/bazel/issues/13839#issuecomment-1448208320

### CODE REVIEW

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 6.1.0

**Comment by keertk** [comment]
Hi @keith @brentleyjones we're actually planning to do the final release for 6.1 tomorrow so won't be able to include this fix.
cc @Wyverald

**Comment by brentleyjones** [comment]
Hmm, can it be included in that cut? `--host_feature` was added in 6.1, so it would be bad for it to be broken like this.

**Comment by keertk** [comment]
Ok, we'll create a new release candidate tomorrow and include this one.

**Review by Wyverald — APPROVED** [review]

**Comment by keith** [comment]
As far as I'm concerned this can make a future 6.x release instead of delaying this one. Especially since it's off by default and this bug is an edge case

**Comment by brentleyjones** [comment]
We've has release with changes that weren't in an RC first. That's all I'm recommending for this very small change. I don't think it needs another RC.

**Pull request closed without merging**
