### PR TITLE
Moved `static_link_msvcrt` to Starlark.

### LINKED ISSUE #7578: `implies: ...` does not stack well with `static_link_msvcrt`
### Description of the problem / feature request:

Hi. I can not enable `static_link_msvcrt` from another feature:

```
    imply_static_link_msvcrt_feature = feature(
        name = "imply_static_link_msvcrt",
        implies = ["static_link_msvcrt"]
    )
```

When I do:
```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cpp"],
    features = ["imply_static_link_msvcrt"],
    linkopts = ["-DEFAULTLIB:libcmt.lib", "-WX"] # Ensuring static_link_msvcrt is enabled.
)
```
linker says that:
```
LINK : warning LNK4098: defaultlib 'msvcrt.lib' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : error LNK1218: warning treated as error; no output file generated
```

Second thing is that if I use non-existent feature, it is silently ignored by Bazel. I feel that that is not right.

See https://github.com/excitoon/bazel-issues/tree/master/imply-static-link-msvcrt

### What operating system are you running Bazel on?

Windows 10 x64

### What's the output of `bazel info release`?

Build label: 0.23.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Feb 26 17:40:30 2019 (1551202830)
Build timestamp: 1551202830
Build timestamp as int: 1551202830

### PR DESCRIPTION
**Pull request by excitoon**
I guess that can fix #7578 and [remove few mentions of Windows](https://en.wikipedia.org/wiki/Microsoft_litigation) from Bazel code.

Can you please check if it can be merged?

### CODE REVIEW

**Comment by excitoon** [comment]
Can you please restart Trusty Tahr?

**Comment by excitoon** [comment]
@meteorcloudy By the way, as Windows expert, can you review this? ^_^

**Comment by excitoon** [comment]
@meteorcloudy No problem with refactoring but actually it came from a real problem (#7578).

**Comment by meteorcloudy** [comment]
I see, then thanks for the fix!

**Comment by meteorcloudy** [comment]
@excitoon Removing the related code in Java code is an incompatible change if users are using an old version of CROSSTOOL file. For example, https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL.tpl#L1128

Can you guard this change behind an incompatible flag? 
See the instruction here: https://bazel.build/breaking-changes-guide.html

**Comment by hlopko** [comment]
Hi @excitoon, this is a great cleanup with unfortunate side effect. I think it's worth enduring through the incompatible change process. Thanks!

**Comment by excitoon** [comment]
@meteorcloudy Yeah I'll do it.

**Comment by excitoon** [comment]
I guess the mechanical change is impossible because I remove 4 features, `dynamic_link_msvcrt_debug`, `dynamic_link_msvcrt_no_debug`, `static_link_msvcrt_debug`, `static_link_msvcrt_no_debug` (theoretically people can misuse them, avoiding features).

**Comment by excitoon** [comment]
@meteorcloudy @hlopko As we break something here, can we go with an advanced plan resulting in rename of `static_link_msvcrt` -> `static_link_libc` additionally:
1) Add a new feature named `static_link_libc` with Starlark logic, which shall also depend on `static_link_msvcrt`.
2) Add incompatible flag removing `static_link_msvcrt` logic and a deprecation warning in Java code.
3) Remove incompatible flag, `static_link_msvcrt` and clean up `static_link_libc`.
I would like to make it in such way in order to: 1) keep Starlark logic clean during moving period; 2) select more or less name for a feature.

**Comment by hlopko** [comment]
Hi @excitoon, what's the status of this effort? The incompatible change still has some FIXMEs, and this change was not updated to define the incompatible flag. I hope you're not blocked by us.

**Comment by hlopko** [comment]
Friendly ping.

**Comment by aiuto** [comment]
Friendly ping.

**Comment by ulfjack** [comment]
Closing due to age. Please reopen if you have updates.

**Pull request closed without merging**
