### PR TITLE
Add a random number to action temp dir

### PR DESCRIPTION
**Pull request by snnn**
Fix for #4035

@laszlocsomor

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by laszlocsomor** [comment]
\o/

**Comment by laszlocsomor** [comment]
LGTM, I'll import it right now.

**Comment by snnn** [comment]
Hi @laszlocsomor 

Let me close it.  I believe you have a better solution for this issue.

**Comment by laszlocsomor** [comment]
Let me reopen it.

My comment on #4035 (https://github.com/bazelbuild/bazel/issues/4035#issuecomment-345607119) was meant for this PR, I just added it to the bug thread by mistake.

That said, I still need to investigate why some of the internal tests broke.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by laszlocsomor** [comment]
Found and fixed the culprit, it was an internal test asserting the temp directory's name with a regex. I'm submitting the change and it'll be pushed to GitHub as soon as submitted.

**Comment by snnn** [comment]
Great! Thank you

**Pull request closed without merging**
