### PR TITLE
bazel syntax: Implement indexed local variables

### PR DESCRIPTION
**Pull request by stepancheg**
Speed-up Starlark evaluation by replacing by-name access with
by-index access for local scope variables.

`LexicalFrame` variables is now represented as a pair of:
* `Object[] locals`
* `Map<String, Integer>` when by name access is needed

`ValidationEnvironment` now assigns a variable index for each local
variable.

Similar optimization is possible for `GlobalFrame`, but it's harder
to implement because the global frame is much more complicated. It is
also not that important for global scope.

Tested with this command:

```
bazel build //src/main/java/com/google/devtools/starlark:Starlark && \
time bazel run //src/main/java/com/google/devtools/starlark:Starlark -- `pwd`/bubble_sort.sky
```

where `bubble_sort.sky` is:

```
def bubble_sort(array):
    array = list(array)
    for i in range(len(array)):
        for j in range((len(array) - i) - 1):
            if array[j] > array[j + 1]:
                array[j], array[j + 1] = array[j + 1], array[j]
    return array

def bench():
    for i in range(1000):
        for j in range(1000):
            if [2, 3, 4, 5, 6, 7, 9] != bubble_sort([9, 3, 5, 4, 7, 2, 6]):
                fail()

bench()
print("$")
```

The program runs in about 18 seconds with this patch and in about 19
seconds without it (hard to say more precisely because of high
variability).

**Note**, github does not have stacked reviews, have a look at top commit only please,
the ones below are #9440, #9445.

**Note**, [similar change in starlark-rust](https://github.com/google/starlark-rust/commit/8b5c6a628389a1c61c6d7b7739c8e85310844178).

@adonovan ?

### CODE REVIEW

**Comment by stepancheg** [comment]
... or @alandonovan

**Comment by alandonovan** [comment]
Hi Stepan, thanks for your PR. I'm not sure if you've noticed, but I've been submitting a stream of changes to this package over the past month to lock down its public API so that I can completely reimplement the structure of the environment much more efficiently and cleanly---and then eventually compile the AST. (I have ported the go.starlark.net compiler to Java already; the hard part is making a hole of the right shape for it to drop into.)

Progress is painfully slow, but it is happening. I'm sorry to dampen the enthusiasm of an external contributor, but honestly the most helpful thing you could do right now would be not to make any changes to the syntax package, especially StarlarkThread, StarlarkFile, and Eval.

cheers
alan

**Comment by stepancheg** [comment]
@alandonovan no worries. My concern is Starlark performance, which is currently suboptimal.

The question is:
* will changes you are planning to do improve performance? (I have no idea what's so special about Go Starlark compiler)
* what's ETA if you have it?

**Comment by alandonovan** [comment]
I hope they will make the interpreter about 10x faster. I hope to be done before the end of the year, but we shall see.

**Pull request closed without merging**
