### PR TITLE
Fix missing line breaks.

### PR DESCRIPTION
**Pull request by chaoren**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by chaoren** [comment]
Done. PTAL.

**Comment by kchodorow** [comment]
Bah, that didn't actually work (it didn't format the paragraphs as "children" of the list items).  Maybe just separate it with a "-", e.g., title - desc?

**Comment by chaoren** [comment]
Done. I don't see anything wrong with the paragraphs (extra whitespace?), but I guess '-' works too.

**Pull request closed without merging**
