### PR TITLE
Add Android NDK r23 support

### PR DESCRIPTION
**Pull request by freedomtan**
Address  https://github.com/bazelbuild/bazel/issues/12889

It seems there are at least 2 major issues so that we cannot reuse NDK r19 based code,
- deprecation of ${NDK_ROOT}/{platforms,sysroot}
- removal of GNU toolchain

With this patch, I was able to build TensorFlow Lite's `benchmark_model` with:

```
bazel build --config android_{arm,arm64,x86,x86_64} //tensorflow/lite/tools/benchmark:benchmark_model --copt=-nostdinc++
```
I didn't figure out how to get rid of `--copt=-nostdinc++` though.

### CODE REVIEW

**Comment by ahumesky** [comment]
Thanks @freedomtan, I'll have a look at this tomorrow. In the meantime, I'll ask around about `--copt=-nostdinc++` to see if anyone has an idea.

Also, looks like there are a couple test failures in testInvalidNdkSourceProperties and testUnsupportedNdkVersion. These tests should probably be made to be more flexible, but it's probably easiest for you to just modify the expected message.

**Comment by ahumesky** [comment]
Sure no problem, the tests are here:

https://github.com/bazelbuild/bazel/blob/0f2c599582c73d93f8605bdd21cf16c945108571/src/test/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryTest.java#L137

https://github.com/bazelbuild/bazel/blob/0f2c599582c73d93f8605bdd21cf16c945108571/src/test/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryTest.java#L163

https://github.com/bazelbuild/bazel/blob/0f2c599582c73d93f8605bdd21cf16c945108571/src/test/java/com/google/devtools/build/lib/bazel/rules/android/AndroidNdkRepositoryTest.java#L191

Looks like the expected message just needs to be updated (or the test made more flexible)

**Comment by ahumesky** [comment]
I'm trying to build the tensorflow target with your change, and did the following:

```
~$ git clone https://github.com/freedomtan/bazel.git bazel-freedomtan
~$ cd bazel-freedomtan
~/bazel-freedomtan$ bazel build src/bazel

~/bazel-freedomtan$ cd
~$ git clone https://github.com/tensorflow/tensorflow.git
~$ cd tensorflow

modify tensorflow/workspace2.bzl to a newer apple rules version:

    tf_http_archive(
        name = "build_bazel_rules_apple",
        ....
    )

to 

    load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
    ....

        http_archive(
            name = "build_bazel_rules_apple",
            sha256 = "0052d452af7742c8f3a4e0929763388a66403de363775db7e90adecb2ba4944b",
            urls = [
               "https://github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz",
            ],
        )


~/tensorflow$ ~/bazel-freedomtan/bazel-bin/src/bazel build --config android_x86 //tensorflow/lite/tools/benchmark:benchmark_model --copt=-nostdinc++
```

And I get a lot of errors like 

```
ERROR: /usr/local/google/home/ahumesky/.cache/bazel/_bazel_ahumesky/57c7ae6c96b17d246e4ff6628926e3bc/external/fft2d/BUILD.bazel:27:11: Compiling fftsg.c failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86-4.9/prebuilt/linux-x86_64 -target i686-none-linux-android -fPIC ... (remaining 38 arguments skipped)
In file included from external/fft2d/fftsg.c:641:
In file included from external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/math.h:301:
In file included from external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include/stdlib.h:20:
external/androidndk/ndk/sources/android/support/include/stdlib.h:31:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
```

Are there other steps I need to do to get the tensorflow benchmark building?
Thanks!

**Comment by EwoutH** [comment]
Any updates on the status of this PR?

**Comment by freedomtan** [comment]
> Any updates on the status of this PR?

pleae see comment from @ahumesky 
https://github.com/bazelbuild/bazel/issues/12889#issuecomment-960010432

**Comment by Bencodes** [comment]
Can this issue be closed now that there's https://github.com/bazelbuild/rules_android_ndk which supports 25b?

**Comment by ahumesky** [comment]
yes, let's converge future work onto https://github.com/bazelbuild/rules_android_ndk

**Pull request closed without merging**
