### PR TITLE
[Cherrypick 4.2.0] Worker cherrypicks

### PR DESCRIPTION
**Pull request by larsrc-google**
Cherrypick request for 4.2.0 (#13558 )

A string of cherrypicks needed to pick fixes 5e352af, 9dc95af, and 779d660 in particular.

### CODE REVIEW

**Comment by larsrc-google** [comment]
@tetromino I cherry-picked two of your changes (cl/346790610 and cl/355641836) to make a clean series of picks. Can you verify that picking those two in isolation won't cause other problems?
@janakdr Same for cl/380833502.

**Comment by janakdr** [comment]
LGTM

**Review by meisterT — APPROVED** [review]

**Comment by katre** [comment]
Overriding CLAbot: 4fda22e47fa60433c8b99c5205c2fd8ea8b3cd74 was in fact authored by a googler.

**Comment by katre** [comment]
Please rebase onto the latest release-4.2.0-patches branch so I can merge.

**Comment by katre** [comment]
CLA is still fine.

**Pull request merged**
