### PR TITLE
Delete BaselineCoverageResult

### PR DESCRIPTION
**Pull request by fmeum**
This event predates BEP and hinders Starlarkification of baseline coverage actions.

### CODE REVIEW

**Review by c-mita — APPROVED** [review]
AFAICT this is only used in an internal class for a deprecated system (replaced by the BEP).

Baseline coverage is undeveloped so this should not be missed.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
(for 8.1.0)

**Comment by iancha1992** [comment]
@bazel-io fork 8.1.0

**Pull request closed without merging**
