### PR TITLE
Test that cc_binary can specify -stdlib=libc++

### PR DESCRIPTION
**Pull request by fmeum**
cc_binary can successfully specify -stdlib=libc++ as copt and linkopt as of f1531dc2 when the compiler is clang. This commit adds a test for this.

@oquenchil This is the test that I should have already included in #13666.

### CODE REVIEW

**Comment by fmeum** [comment]
Is it possible that the tests fail because they haven't picked up https://github.com/bazelbuild/bazel/commit/f1531dc2ebfb2db721a94f6f19081fa89af536da yet? The failure message seems to indicate that is the case.

**Review by oquenchil — CHANGES_REQUESTED** [review]
Thank you!

Could you please add this test as part of cc_integration_test.sh instead of adding it in a separate file?

**Comment by fmeum** [comment]
> Thank you!
> 
> Could you please add this test as part of cc_integration_test.sh instead of adding it in a separate file?

Done. However, this PR is blocked on https://github.com/bazelbuild/continuous-integration/pull/1212 as the Bazel CI images do not have libc++ installed.

**Comment by oquenchil** [comment]
Ah understood. Can you please ping this again when the blocker is resolved?

**Comment by philwo** [comment]
There's a different error now: `clang: error: invalid linker name in argument '-fuse-ld=/usr/bin/ld.gold'` - but maybe that's fixed by rebasing the PR?

**Pull request closed without merging**
