### PR TITLE
Add --incompatible_use_platforms_repo_for_constraints

### PR DESCRIPTION
**Pull request by hlopko**
This change adds an incompatible flag to disable constrains bundled with Bazel
in @bazel_tools.

Incompatible change issue:
https://github.com/bazelbuild/bazel/issues/8622

Tracking issue:
https://github.com/bazelbuild/bazel/issues/6516

RELNOTES: Incompatible change `--incompatible_use_platforms_repo_for_constraints` has been added. See https://github.com/bazelbuild/bazel/issues/8622 for details.

### CODE REVIEW

**Comment by hlopko** [comment]
Yeah I will eventually (was running presubmits to see what will break, then got derailed by the rollback of @bazel_tools and @platforms cl :) I'll ping you when this is ready to be reviewed (assuming you have no objections to the approach in general).

**Comment by katre** [comment]
The approach is good, although I'm worried about dependency cycles (alias needs a configuration, but not platforms need the alias, but configurations need a platform...). Passing tests will reassure me greatly.

**Comment by hlopko** [comment]
Ptal! Looks green on the CI :)

**Comment by hlopko** [comment]
Actually let me import it and see what happens internally.

**Pull request closed without merging**
