### PR TITLE
Remove --experimental_enable_objc_cc_deps

### PR DESCRIPTION
**Pull request by keith**
This was flipped in 2017

### CODE REVIEW

**Comment by keith** [comment]
@susinmotion have time to check out this small cleanup?

**Comment by keith** [comment]
@googlewalt have time for this small cleanup?

**Comment by brentleyjones** [comment]
@bazelbuild/triage Can we get someone to review this please? 🙏

**Comment by googlewalt** [comment]
Sorry for the delay.  I'll review it.

**Review by googlewalt — APPROVED** [review]

**Comment by iancha1992** [comment]
@googlewalt is this awaiting PR merge?

**Comment by googlewalt** [comment]
Thanks for checking.  I will merge it.

**Pull request closed without merging**
