### PR TITLE
Recognize CUDA header file type (.cuh)

### PR DESCRIPTION
**Pull request by liuliu**
This PR mirrors the fix in
https://github.com/bazelbuild/bazel/commit/8804128f52a674b9f8faf3b9534ae156cbad00a1

.cuh is widely used as suffix for CUDA. It is made more prominent since
"cub" (https://nvlabs.github.io/cub/) recently distributed with CUDA
ToolKit 11, hence, now .cuh headers are in every CUDA ToolKit
distribution.

I would like to continue with this PR and fix any breakages that may encounter.

### CODE REVIEW

**Comment by liuliu** [comment]
Just noticed @chsigg has to rollback this change for some internal breakages. Would love to know more to close this one out.

**Review by oquenchil — APPROVED** [review]
LGTM

**Comment by liuliu** [comment]
@oquenchil do you want to merge it? Fixed the merge conflict earlier today.

**Comment by c-mita** [comment]
This had to be rolledback because it caused internal build failures. We don't yet know why.

**Comment by chsigg** [comment]
> We don't yet know why.

It's because Google internal builds try to build CUDA headers into header modules (a Google internal variant of C++ modules) and fail spectacularly. We can land this in bazel, but not in blaze.

See the comment here: https://github.com/bazelbuild/bazel/issues/6578#issuecomment-586636686

**Comment by oquenchil** [comment]
Ideally, we keep the codebase between Bazel and the internal version as close as possible. Can we control whether we build a type of header into modules through the toolchain? IMO that's the only thing that should be different instead of introducing yet another flag.

**Pull request closed without merging**
