### PR TITLE
Rewrite lcov path munging to make the paths all relative

### PR DESCRIPTION
**Pull request by ulfjack**
This makes coverage work with sandboxing, and gets rid of a previous workaround.

The only downside is that it requires running genhtml in the exec root in order
to be able to resolve relative pahts to source files, like so:

(GENHTML_CMD="genhtml -o $(pwd)/report/ -p "$(readlink -f bazel-project)" $(readlink -f bazel-testlogs)/path/to/coverage.dat" && cd bazel-project && $GENHTML_CMD)

### CODE REVIEW

**Comment by ulfjack** [comment]
I rebased this just now. PTAL.

**Comment by iirina** [comment]
Looks reasonable. How did you test this? Did you also test with `--instrumentation_filter`?

**Comment by ulfjack** [comment]
It passes all of Bazel's automated tests. I also tested manually on a test target in the Bazel repo, using an instrumentation_filter.

**Comment by iirina** [comment]
Unfortunately that is not very reliable since Bazel doesn't have a good setup for testing coverage (other than [bazel_coverage_test](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/bazel_coverage_test.sh)). ATM we can ask C++ coverage users (if there are any?) to try out a RC that will contain this change.

**Pull request closed without merging**
