### PR TITLE
Add patch failure fallback to -p1

### PR DESCRIPTION
**Pull request by kastiglione**
The [default `patch_args`](https://github.com/bazelbuild/bazel/blob/852c11f6f1f433cc4381d08701a882f1e21493fa/tools/build_defs/repo/git.bzl#L184) uses `-p0`. I'm not sure which cases called for choosing `-p0` as the default, but using patches produced by `git` calls for `patch -p1`. The output of `git diff` commands add `a/` and `b/` prefixes to file paths, and these prefixes need to be stripped. For a `git_repository` rule, it seems `-p1` would probably always be used over `-p0`.

Since it may not be feasible to change the default to `-p1`, this adds `-p0` to `-p1` fallback. If a patch fails to apply and `-p0` is in the `patch_args`, then the `patch` is tried again with `-p1`.

### CODE REVIEW

**Comment by jin** [comment]
assigning to @aehlig because dslomov is ooo

**Comment by kastiglione** [comment]
While the counter example given can certainly happen in theory. However, the point of the issue is that it should never be possible in the first place, because `git {diff,show}` does not produce unprefixed file paths like `tests/BUILD`. Instead it would be `a/tests/BUILD`.

Git can be forced to not add the path prefix (`--no-prefix`), but the only motivating reason I can think of for even using that flag, is as a work around to `git_repostiory()` defaulting to `-p0`. The way I see it, the problem scenario you describe can only happen _because_ `git_repository()` has a broken default. A user might add a patch produced by git, see it not working, and then proceed to generate a patch without the `a/` prefix. In our case, we did it by hand, because we didn't know about the default, didn't know it could be overridden.

> I don't see the need, as no one is forced to use the defaults

In fact this api forces people to never use the default: the default for `git_repository()` is _wrong by default_.

The reason for this PR was I wanted to help prevent other people from unavoidably experiencing the same confusion we faced.

> I don't think we want to merge this pull request.

Do you want to fix the problem it attempts to address?

**Comment by aehlig** [comment]
Over to @dslomov, as this is now about a product decision.

**Comment by aehlig** [comment]
> The above counter example can certainly happen in theory. However, the point of the issue is that it should never be possible in the first place, because `git {diff,show}` does not produce problematic unprefixed file paths like `tests/BUILD` path in your example. Instead it would be `a/tests/BUILD`.

Besides the possibility that repositories might contain a directories called `a` or `b` (which is not forbidden by `git`), I think the fundamentally wrong assumption behind this pull request is that patches will always be generated by `git` and no standard patches from other sources are used.

In any case, even if such a scenario might rarely happen, the fact that it might happen is a source of hard to understand errors which I would not like to have in a build tool.

> [....] In our case, we did it by hand, because we didn't know about the default, didn't know it could be overridden.

In this case, I think, reading [the documentation](https://docs.bazel.build/versions/master/repo/git.html) might have helped.

> Do you want to fix the problem it attempts to address?

As mentioned, I don't see the problem, but this is ultimately a product decision.

**Comment by kastiglione** [comment]
> the fundamentally wrong assumption behind this pull request is that patches will always be generated by git

And this is the obviously better default than what you have currently:

the fundamentally wrong assumption behind `git_repository` is that patches were not generated by git

**Comment by aehlig** [comment]
> the fundamentally wrong assumption behind `git_repository` is that patches were not simply generated by git

Except that it is also not a good experience if patching works differently for `http_archive` and `git_repostory`, and why should for a plain archive the default be to use `-p1` patches?

**Comment by dslomov** [comment]
I see two questions here:
1. Should we fallback?
2. What should be the default?

Re (1), @aehlig has shown that since patch does not fail side-effect-free, we cannot do fallbacks.
Re (2), whether default should be changed: I do agree that consistent defaults across different repo rules are important, but I also see how  git_repository should have a default suitable to git. At this point, it just feels that going through incompatible change to change the default is too much work and churn for the ecosystem, but I am happy to revisit this if there is more requests for changing those defaults.

**Comment by kastiglione** [comment]
Agreed on avoiding the churn. This was an attempt to not break existing use that fell in line with the current default, while also supporting the natural default of git.

If revisiting in the future, it might be possible to pre-check the patch for hunks that use a/ b/ prefixes, and then -p1 for those cases.

**Comment by kastiglione** [comment]
I created https://github.com/bazelbuild/bazel/pull/8368 to document these details for `git_repository`'s `patch_args` parameter.

**Pull request closed without merging**
