### PR TITLE
Update Truth to 0.45.

### PR DESCRIPTION
**Pull request by cpovirk**

### CODE REVIEW

**Comment by cpovirk** [comment]
I'll need to update the version of Compile-Testing, too. Will do that now.

**Comment by cpovirk** [comment]
Done. We'll see how the new tests go.

**Comment by cpovirk** [comment]
Tests are passing now. Sorry for the trouble earlier.

**Comment by iirina** [comment]
Merged in f2a3ba2a50784b1c2c546dcf485e5dc6353ef35d.

**Pull request closed without merging**
