### PR TITLE
Include zsh completion with installer

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by keith** [comment]
There shouldn't be much extra overhead for folks who don't use zsh though, which is why I felt it was reasonable.

I believe I've fixed the only failing test

**Comment by kastiglione** [comment]
Big +1 for inclusion

**Comment by keith** [comment]
This test failure passed on my machine and appears unrelated, I've rebased to kick it again

**Comment by keith** [comment]
Seems to be good now

**Comment by keith** [comment]
Can you check this again @aehlig

**Comment by keith** [comment]
Thanks!

**Pull request closed without merging**
