### PR TITLE
Fix link to Buildifier

### PR DESCRIPTION
**Pull request by mpassell**
Just fixing a broken link in the docs.

### CODE REVIEW

**Comment by gregestren** [comment]
Hi Matt,

Consider this a GitHub 101 question, but what makes the first link wrong?

**Comment by mpassell** [comment]
I'm no great sage of GitHub readme linking, but when I clicked on the link [as seen in the generated site](https://docs.bazel.build/versions/master/skylark/skylint.html), it 404'd. It's interesting that when viewed on GitHub, the link works... Either way, I believe that the version I provided will work when clicked on a site external to GitHub.

**Comment by gregestren** [comment]
Ah, I see. The generated docs do some extra link munging - in particular changing `README.md` to `README.html`, which doesn't exist. The direct GitHub source has no opportunity to do that. :)

Paging @jin who I think has expertise on this link munging. I'd like to check if this is the sanctioned way to make these links work vs. fixing up the renderer somehow.

**Comment by jin** [comment]
There's a blanket replacement of `.html` to `.md` somewhere in the site pipeline. This fix looks fine though.

**Comment by mpassell** [comment]
@jin Looks like the PR was closed a bit before you made your comment. Should I just drop this and let this be fixed via other means? 🤔

**Comment by jin** [comment]
Your change has been merged :)

**Pull request closed without merging**
