### PR TITLE
docs.bazel.build design refresh

### PR DESCRIPTION
**Pull request by jin**
Staging site: https://bazel-docs-staging.netlify.com

Discussion: https://groups.google.com/d/msg/bazel-dev/hjRP7JTtZ_U/9SZYZUSBDAAJ

Fixes https://github.com/bazelbuild/bazel/issues/10791

### CODE REVIEW

**Comment by gregestren** [comment]
Overall this looks amazing! I'm seriously impressed at how successfully you've re-stylized this.

Walkthrough comments:

**Linux desktop:**
 - The top links look squeezed together. Can we unsqueeze them some?
navbar
 - I'm torn on the phrasing "Create issue for this page". It's clear. But it's long, so breaks onto two lines easily, which is a bit jarring. Is "Create issue" or "Create doc issue" clear enough or is that too compromising?
* Is there any way to stop scrolling the right navbar when we get to the bottom of the page? 
* On the left navbar, what would a slightly thicker green bar look like?

  leftbar

  I'm curious because of https://reactjs.org/docs/release-channels.html. Does that make the focus any clearer?

* Higher min width for the left navbar? As-is we get overflow on narrow windows:
version

&nbsp;
**13" Macbook**: Looks great!

**iPhone 6:**: Looks great! Maybe consider making the right navbar inline (as a block element at the top of the page, like what we have now in production), since mobile viewers lose the horizontal space. But I wouldn't block this PR on that. And we might want to do some analytics review to verify how much time that's worth.

**Comment by jin** [comment]
> On the left navbar, what would a slightly thicker green bar look like?


Screen Shot 2020-02-19 at 2 56 33 PM

**Comment by gregestren** [comment]
> > On the left navbar, what would a slightly thicker green bar look like?
> 
> Screen Shot 2020-02-19 at 2 56 33 PM

Thanks for trying this.

I'm really not sure which looks better. I trust your judgment whichever choice you prefer - this is a minor nit in the grand scheme of things and I don't want to further block progress on it.

**Comment by jin** [comment]
I actually prefer the thicker one :) 

Pushed a new update with your comments, PTAL. https://bazel-docs-staging.netlify.com/versions/master/bazel-overview.html

I'll hold off the mobile optimizations as a follow up.

**Pull request closed without merging**
