### PR TITLE
Update rules_java 7.11.1 / java_tools 13.8

### PR DESCRIPTION
**Pull request by hvadehra**

### CODE REVIEW

**Comment by iancha1992** [comment]
@hvadehra do you want this in 7.4.0?

**Comment by hvadehra** [comment]
> do you want this in 7.4.0?

@comius @fmeum WDYT?

**Comment by fmeum** [comment]
> > do you want this in 7.4.0?
> 
> @comius @fmeum WDYT?

I don't see any downside and as far as I remember this also contains a Turbine fix, so yes.

**Comment by iancha1992** [comment]
@hvadehra @fmeum 
Also, just want to let you know that the few downstream is failing here, but they seem to be going through in the master. Might want to take a look at these:

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4118#0191e379-143f-4466-b517-670955e71972
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4118#0191e37d-98da-4077-8196-c541a596a3dc
All of rules_kotlin are failing here

Are these ok?

**Pull request closed without merging**
