### PR TITLE
Fix rpath for binaries in external repositories

### LINKED ISSUE #16003: Bazel 5.3 fails to run external tests
### Description of the bug:

Bazel fails to run C++ tests in external repositories on remote execution.

Running locally passes, even with linux-sandbox.  Bazel 5.0 worked.  This has broken bazel > 5.0 for us, and is blocking all upgrades.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`bazel test -c opt --config=engflow --config=build_without_the_bytes @aos//aos:condition_test`

Run a c++ test for an external repository on remote execution.  (I can't give you a remote execution cluster)

### Which operating system are you running Bazel on?

Debian Bullseye

### What is the output of `bazel info release`?

release 5.3.0-202207291633+f440f8ec3f

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

```
#!/bin/bash

# This script builds a Debian package from a Bazel source tree with the
# correct version.
# The only argument is the path to a Bazel source tree.

set -e
set -u

BAZEL_SOURCE="$1"

VERSION="5.3.0-$(date +%Y%m%d%H%M)+$(GIT_DIR="${BAZEL_SOURCE}/.git" git rev-parse --short HEAD)"
OUTPUT="bazel_${VERSION}"

(
cd "${BAZEL_SOURCE}"
bazel build -c opt //src:bazel --embed_label="${VERSION}" --stamp=yes
)

cp "${BAZEL_SOURCE}/bazel-bin/src/bazel" "${OUTPUT}"

echo "Output is at ${OUTPUT}"
```

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

```text
austin[504] cmbr (release-5.3.0) ~/local/bazel
$ git remote get-url origin; git rev-parse master; git rev-parse HEAD
https://github.com/bazelbuild/bazel
master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
f440f8ec3f63e5d663e1f9d9614f05a39422102a
```

### Have you found anything relevant by searching the web?

Reverting https://github.com/bazelbuild/bazel/commit/00805727b867d33fd922e63ca82b0d9825ad79fe fixes it.  https://github.com/bazelbuild/bazel/issues/12821 suggested that I add linkstatic to every C++ test we want to run, which seems like 1k's of lines of diffs off upstream, since no reasonable upstream would accept that patch.

### Any other information, logs, or outputs that you want to share?

```
bazel test -c opt --config=remote_execution --config=build_without_the_bytes @aos//aos:condition_test
INFO: Invocation ID: d91e1b30-a290-4282-99c6-029e4102ed35
INFO: Analyzed target @aos//aos:condition_test (86 packages loaded, 20904 targets configured).
INFO: Found 1 test target...
FAIL: @aos//aos:condition_test (see /home/austin/.cache/bazel/_bazel_austin/f5b123ff4a0d503fd09f4c4da36644a6/execroot/repo/bazel-out/k8-opt/testlogs/external/aos/aos/condition_test/test.log)
INFO: From Testing @aos//aos:condition_test:
==================== Test output for @aos//aos:condition_test:
/var/lib/worker/work/1/exec/bazel-out/k8-opt/bin/external/aos/aos/condition_test.runfiles/repo/../aos/aos/condition_test: error while loading shared libraries: libexternal_Saos_Saos_Slibcondition.so: cannot open shared object file: No such file or directory
================================================================================
Target @aos//aos:condition_test up-to-date:
  bazel-bin/external/aos/aos/condition_test
INFO: Elapsed time: 166.038s, Critical Path: 153.48s
INFO: 52 processes: 50 remote cache hit, 2 remote.
@aos//aos:condition_test                                                 FAILED in 127.2s
  /home/austin/.cache/bazel/_bazel_austin/f5b123ff4a0d503fd09f4c4da36644a6/execroot/repo/bazel-out/k8-opt/testlogs/external/aos/aos/condition_test/test.log

Executed 1 out of 1 test: 1 fails remotely.
INFO: Build completed, 1 test FAILED, 52 total actions
```

And to prove I'm not crazy:

```
bazel test -c opt -k @aos//aos:condition_test
INFO: Build options --experimental_inmemory_dotd_files, --experimental_inmemory_jdeps_files, --extra_execution_platforms, and 2 more have changed, discarding analysis cache.
INFO: Analyzed target @aos//aos:condition_test (0 packages loaded, 20897 targets configured).
INFO: Found 1 test target...
Target @aos//aos:condition_test up-to-date:
  bazel-bin/external/aos/aos/condition_test
INFO: Elapsed time: 12.246s, Critical Path: 10.91s
INFO: 120 processes: 42 internal, 78 linux-sandbox.
INFO: Build completed successfully, 120 total actions
@aos//aos:condition_test                                                 PASSED in 2.3s

Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 120 total actions
```

### PR DESCRIPTION
**Pull request by fmeum**
The solib directory is located within the subdirectory of the runfiles
directory corresponding to the workspace. Thus, if a binary is contained
in an external repository, its $ORIGIN relative rpath has to first
ascend to the runfiles directory and then descend into the workspace
directory.

Fixes #16003

### CODE REVIEW

**Comment by fmeum** [comment]
@oquenchil This PR is similar to #14600, but resolves a different issue. I can rebase this PR onto #14600 if you should prefer to merge that one first.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by AustinSchuh** [comment]
Success, this fixes test in external repositories!  Thanks @fmeum !

**Comment by kshyanashree** [comment]
@bazel-io fork 5.3.0rc1

**Comment by kshyanashree** [comment]
@bazel-io fork 5.3.0

**Comment by fmeum** [comment]
@kshyanashree The command lacks the rc1.

**Comment by kshyanashree** [comment]
@bazel-io fork 5.3.0rc1

**Comment by fmeum** [comment]
@kshyanashree I don't know why, but the last command failed as well.

**Comment by coeuvre** [comment]
Assigning to @oquenchil since this is about cc rules.

**Comment by kshyanashree** [comment]
Hi @fmeum, Is it possible for you to get the PR review done by today? Since we will be merging it under the release 5.3.0.

**Comment by fmeum** [comment]
@kshyanashree I don't know when @oquenchil will be able to review the change. It does fix a known Bazel 5 regression - is that sufficient to hold the release for it/up the priority?

**Review by oquenchil — APPROVED** [review]
LGTM

**Comment by fmeum** [comment]
CC @kshyanashree as a potential 5.3.0 regression.

@pcjanzen Would adding both rpaths fix this problem?

**Comment by pcjanzen** [comment]
> Would adding both rpaths fix this problem?

I _think_ so, but between this problem and #14600 there are starting to be kind of a lot of rpath entries and I can't honestly say I've thought through all the combinations.

**Pull request closed without merging**
