### PR TITLE
support action env in runfiles generation, cpp compile and cpp link

### PR DESCRIPTION
**Pull request by lightyang**
So that we can pass in LIBRARY_PATH, etc.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by aehlig** [comment]
Unfortunately, the change as is breaks a couple of google-internal targets: the patch changes the constructor of the `SymlinkTreeAction` while there are other calls to this constructor in the google-specific extensions of bazel. Is there a way to do the change in a more graceful way?

Adding our C++ experts for a second opinion on whether it is desirable to have that semantic change.

**Comment by philwo** [comment]
@lightyang Do you think you can rebase and maybe change this to not alter the constructor?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by lightyang** [comment]
@philwo I can keep the original constructors and add some new ones for this change, so code that depends on the original interface won't break. sounds okay?

**Comment by philwo** [comment]
@mhlopko Would you be happy with this change in general? (I can handle the merging and making sure it doesn't break tests, if you're busy :))

@lightyang I think that sounds good! Would be happy to run your proposed version through our test suite and report back.

**Comment by lightyang** [comment]
@philwo I've updated the commit to keep the old SymlinkTreeAction constructor

**Comment by laszlocsomor** [comment]
ping -- are there any updates? @lightyang , looks like there are merge conflict, could you please rebase your commits on top of https://github.com/bazelbuild/bazel/tree/master ?

**Comment by lfpino** [comment]
Hi @philwo, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if you'll take a look.

**Comment by ulfjack** [comment]
I'm afraid I didn't see this PR when I implemented a similar fix, which is now merged.

**Pull request closed without merging**
