### PR TITLE
[6.4.0] Mark isolated extension usages as experimental

### PR DESCRIPTION
**Pull request by keertk**
The `isolate` parameter of `use_extension` and the `is_isolated` field on `module_ctx` are only available with the `--experimental_isolated_extension_usages` flag.

Closes #19021.

PiperOrigin-RevId: 550582124
Change-Id: I7486a3b344ca9d29614c26044f1943bfedfcc654

Commits https://github.com/bazelbuild/bazel/commit/3a4b04f3e5e74f16a981a265e95b196899c79d54, https://github.com/bazelbuild/bazel/commit/f0ad0fe0e1fc663412a400c4e6d7960f220dd647

### CODE REVIEW

**Comment by Wyverald** [comment]
please also cherry-pick the change I have in flight to add the missing documentation for the flag!

**Comment by keertk** [comment]
Sure. For 6.3.1 as well, correct?

**Comment by Wyverald** [comment]
yes, thanks!

**Comment by keertk** [comment]
Ok, it might need to wait for rc2 though.
rc1 is almost out with just the original cherry-pick :/

**Review by Wyverald — APPROVED** [review]

**Pull request merged**
