### PR TITLE
Add references to jdk 17 and 18 for linux-aarch64

### LINKED ISSUE #14937: targeting  java language level 17 or using a java_runtime_level 17 causes build failures on arm64 linux
### Description of the problem / feature request:

seems that there's no jdk for linux arm64 for java 17...I didn't find any open or closed issues about this so opening this one
```
_JDKS = [
    "remotejdk11_macos",
    "remotejdk11_macos_aarch64",
    "remotejdk11_win",
    "remotejdk11_win_arm64",
    "remotejdk11_linux_aarch64",
    "remotejdk11_linux",
    "remotejdk11_linux_ppc64le",
    "remotejdk11_linux_s390x",
    "remotejdk17_macos",
    "remotejdk17_macos_aarch64",
    "remotejdk17_win",
    "remotejdk17_win_arm64",
    "remotejdk17_linux",
]
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

see below for examples...

### What operating system are you running Bazel on?

can fail on any system if targeting linux arm64, but will always fail on an arm64 linux host not cross-compiling for jdk 17 or using the java 17 runtime.

### What's the output of `bazel info release`?

5.0

###  Have you found anything relevant by searching the web?

nothing in the issue tracker

### Any other information, logs, or outputs that you want to share?

forcing linux x86_64 works fine:

```
bzl build --host_platform=//:linux_x86_64 --java_language_version=17 @bazel_tools//tools/jdk:remotejdk_17
INFO: Invocation ID: c77977bd-cdfd-41fe-880c-ae2bdd1eb9e0
INFO: Analyzed target @bazel_tools//tools/jdk:remotejdk_17 (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @bazel_tools//tools/jdk:remotejdk_17 up-to-date (nothing to build)
INFO: Elapsed time: 0.191s (0.00m), Critical Path: 0.00s (0.00m)
INFO: 1 process: 1 internal.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 1 total action
```

forcing linux arm64 does not:

```
bzl build --host_platform=//:linux_arm64 --java_language_version=17 @bazel_tools//tools/jdk:remotejdk_17
INFO: Invocation ID: b7b1bedc-6e5e-4776-930f-f40c0f75118e
INFO: Build options --host_platform and --platforms have changed, discarding analysis cache.
ERROR: /Users/chancila/Snapchat/Dev/.cache/_bazel_root/57e2a0029c5db09ba854cfc0b854c40c/external/bazel_tools/tools/jdk/BUILD:492:27: While resolving toolchains for target @bazel_tools//tools/jdk:remotejdk_17: no matching toolchains found for types @bazel_tools//tools/jdk:runtime_toolchain_type
ERROR: Analysis of target '@bazel_tools//tools/jdk:remotejdk_17' failed; build aborted:
INFO: Elapsed time: 0.203s (0.00m)
INFO: 0 processes.
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully (0 packages loaded, 153 targets configured)
```

### PR DESCRIPTION
**Pull request by nresare**
Closes #14937

### CODE REVIEW

**Comment by nresare** [comment]
Please note that it would be nice to have these artefacts be mirrored on mirror.bazel.build to lessen the load on the upstream  server.

**Comment by nresare** [comment]
I have verified that with these changes, a minimal java project now builds with both `--java_language_version=17` and `--java_language_version=18` on a linux aarch64 host.

**Comment by Franetse7** [comment]
Merci au développeur du logiciel Bazel

**Comment by nresare** [comment]
The build errors listed seems to be related to the test environment being unable to reach cdn.azul.com. See for example [this build log](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/0182a1d9-c206-44b0-9c50-50439c726d16/src/test/shell/bazel/workspace_resolved_test/shard_16_of_22/test_attempts/attempt_1.log):
```
Error in download_and_extract: java.io.IOException: Error downloading [...]/zulu17.32.13-ca-jdk17.0.2-linux_aarch64.tar.gz: Unknown host: cdn.azul.com
```

Getting the artefacts added to mirror.bazel.build would be most welcome :)

**Comment by perezd** [comment]
I filed the issue for mirroring.

**Comment by perezd** [comment]
Can someone poke the buildkite tests now? I think the mirror is setup.

**Comment by perezd** [comment]
OK what should we do then? Not sure how to proceed here.

**Review by comius — APPROVED** [review]

**Comment by perezd** [comment]
What release will this be available in?

**Comment by sgowroji** [comment]
@perezd, This is available in our next major release. Thanks!

**Pull request closed without merging**
