### PR TITLE
Show skipped tests as a warning

### PR DESCRIPTION
**Pull request by brentleyjones**
This matches the color used for the test outputs themselves.

### CODE REVIEW

**Comment by brentleyjones** [comment]
Changes the red in this output to match the magenta:

**Comment by gregestren** [comment]
@philsc 

Okay, this looks cool.

**Comment by gregestren** [comment]
@fweikert this looks like older code than the more recent incompatible target skipping @philsc and I have been involved with.  

Do you have better context? Do these overlap or are these completely separate?

**Review by philsc — APPROVED** [review]
Very cool. Thank you!

**Review by gregestren — APPROVED** [review]

**Pull request closed without merging**
