### PR TITLE
Update cpp-use-cases.md

### PR DESCRIPTION
**Pull request by Jackiexiao**
fix path error and add a empty BUILD

### CODE REVIEW

**Comment by aiuto** [comment]
FWIW, the fact that the tutorials are in the Bazel tree, but they refer to non-versioned examples is a problem. #13298 

This seems fine, just waiting for the CLAbot

**Comment by Jackiexiao** [comment]
@googlebot I signed it!

**Review by aiuto — APPROVED** [review]

**Comment by fweikert** [comment]
Please note that the file has moved to https://github.com/bazelbuild/bazel/blob/master/site/en/tutorials/cpp-use-cases.md.

**Comment by sgowroji** [comment]
We are closing this Above PR w.r.t this https://github.com/bazelbuild/bazel/pull/13297#issuecomment-1079257357. Feel free to reach us to reopen and work on the above PR.

**Pull request closed without merging**
