### PR TITLE
Preserve analysis cache through `--run_under` command changes

### PR DESCRIPTION
**Pull request by fmeum**
Work towards https://github.com/bazelbuild/bazel/issues/3325
Fixes https://github.com/bazelbuild/bazel/issues/10782

RELNOTES: Changing any part of --run_under that isn't the label (such as the shell command) no longer invalidates the analysis cache.

### CODE REVIEW

**Comment by fmeum** [comment]
@katre This is my attempt at a rollforward of https://github.com/bazelbuild/bazel/pull/24303. I am no longer trimming the `CoverageOptions`, but also keeping the analysis cache when they change. I'm not sure that's correct, but it should preserve the current behavior.

**Review by katre — APPROVED** [review]
Sorry for the delay. Looks good, I'll import and test ASAP.

**Comment by katre** [comment]
I'll handle merging and testing.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
(for 8.1.0)

**Pull request closed without merging**
