### PR TITLE
Allow `rules_shell` to use private APIs

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Review by meteorcloudy — APPROVED** [review]

**Comment by Wyverald** [comment]
Hmm, IIUC this PR would only work if `@bazel_tools` has a dep on `rules_shell`. Did you try this PR out?

**Comment by fmeum** [comment]
I did, it works with rules_shell as is. Adding a dep to `bazel_tools` is necessary for backwards compatibility eventually, but can come with autoloading.

**Comment by Wyverald** [comment]
Huh, I don't understand why then -- usually private API checks work by using the repo mapping of `@_builtins` which is based on `@bazel_tools`. `rules_shell` should be a foreign name to Bazel. Which private API is rules_shell using?

**Pull request closed without merging**
