### PR TITLE
Updated some files using switch-string

### PR DESCRIPTION
**Pull request by trosemberg**
Since Java 7, we can use switch case with strings, so i changed some files that had the if-else if structure to adapt to this possibility.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by trosemberg** [comment]
I signed it!

**Comment by mhlopko** [comment]
Friendly ping Tomás...

**Comment by buchgr** [comment]
Closing this for now. Please re-open if there's interest in this change.

**Pull request closed without merging**
