### PR TITLE
Update performance.md

### PR DESCRIPTION
**Pull request by alexeagle**
point to starlark_cpu_profile flag

### CODE REVIEW

**Review by jbedard — APPROVED** [review]
This would have been useful info for me recently 👍

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/commit/5cbb153c839f13c07d777a0175e88dc8a1ab2780 (`--experimental_command_profile`) would also be worth adding to that list.

**Review by fmeum — APPROVED** [review]

**Comment by fmeum** [comment]
Cc @tjgq

**Review by tjgq — APPROVED** [review]
I'll send a separate one for `--experimental_command_profile` later.

**Pull request closed without merging**
