### PR TITLE
Skip optional maven dependencies in generate_workspace.

### PR DESCRIPTION
**Pull request by wjywbs**

### CODE REVIEW

**Comment by damienmg** [comment]
@kchodorow can you take care of this one?

**Comment by kchodorow** [comment]
Thanks for the pull request, looks good! Could you please sign the CLA at https://cla.developers.google.com so we can merge in your change?  (Generally you'd be automatically prompted, but for some reason our CLA-signing webhook is erroring out on this pull request.)

**Comment by wjywbs** [comment]
I added my username in the "GitHub Account Name" of my signed CLA (previously for Chromium).

**Comment by kchodorow** [comment]
Got it, thanks!  Importing...

**Comment by damienmg** [comment]
We should update the list of contributors...

**Comment by damienmg** [comment]
Merged, thank you!

**Pull request closed without merging**
