### PR TITLE
Fix make substitution in starlark cc_test env

### PR DESCRIPTION
**Pull request by dflems**
https://github.com/bazelbuild/bazel/pull/18882 introduced an issue where nested make variable substitution would fail under `cc_test`. The change to the starlark tests fails before the change in `cc_helper.bzl` and passes after.

```
cc_test(
    name = "test",
    srcs = ["test.cc"],
    data = ["data.txt"],
    env = {
        "DATA_LOCATION": "$(location :data.txt)",
    }
)
```

```
ERROR: /playground/BUILD.bazel:1:8: in cc_test rule //:test:
Traceback (most recent call last):
	File "/virtual_builtins_bzl/common/cc/cc_test.bzl", line 70, column 29, in _impl
	File "/virtual_builtins_bzl/common/cc/cc_test.bzl", line 30, column 47, in _cc_test_impl
	File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 900, column 34, in _get_expanded_env
	File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 783, column 46, in _expand
	File "/virtual_builtins_bzl/common/cc/cc_helper.bzl", line 717, column 27, in _expand_nested_variable
Error in extend: trying to mutate a frozen list value
ERROR: /playground/BUILD.bazel:1:8: Analysis of target '//:test' failed
ERROR: Analysis of target '//:test' failed; build aborted:
```

@brentleyjones @oquenchil

### CODE REVIEW

**Comment by brentleyjones** [comment]
@iancha1992 I think this deserves going into a 6.3.1 release.

**Comment by brentleyjones** [comment]
@dflems thank you 🙏. Do we need a similar change on master? There it is also set to a default. Regardless it would be nice to have this test there as well.

**Comment by dflems** [comment]
@brentleyjones I think master differs in a way where this doesn't happen there

https://github.com/bazelbuild/bazel/blob/bef4f7ff0d6556c7a1ced3a0dd1a429113198d9d/src/main/starlark/builtins_bzl/common/cc/cc_helper.bzl#L742-L759

Alternatively, we could cherry-pick the changes from master if they apply ok

**Comment by iancha1992** [comment]
cc: @bazelbuild/triage

**Comment by keertk** [comment]
Hi @dflems could you submit a PR against master?
We can cherry-pick it into the release branch once approved and merged.

(Since 6.3.0 has been released, the release-6.3.0 branch is no longer active. We'll have to create a new one if we do a patch release.)

**Comment by dflems** [comment]
@keertk Master differs to the point where this patch cannot be applied, unfortunately

**Comment by dflems** [comment]
@brentleyjones @keertk @iancha1992 

Looks like a fix for this exists on master at a63d8ebb84caba9d1741a9d9fec725a7db52e25e

Landed ~6mo ago but never landed on 6.x?

**Comment by brentleyjones** [comment]
Ahh. I just missed it when performing my other cherry-pick. We should take that instead.

**Comment by brentleyjones** [comment]
I can cherry-pick that against the new branch (if you haven't by the time I get to my computer). Thanks for the find!

**Comment by brentleyjones** [comment]
@iancha1992 I'm pretty sure we will need a 6.3.1 release. Would you be able to create that branch?

**Comment by buildbreaker2021** [comment]
Hey, AFAIU we will cherry-pick https://github.com/bazelbuild/bazel/commit/a63d8ebb84caba9d1741a9d9fec725a7db52e25e instead of this PR right?
Because I remember I solved the same issue with that commit.

**Comment by keertk** [comment]
@brentleyjones the [6.3.1 branch](https://github.com/bazelbuild/bazel/tree/release-6.3.1) has been created. Could you submit a cherry-pick PR? (We'll also need the same against [6.4.0](https://github.com/bazelbuild/bazel/tree/release-6.4.0))

**Comment by brentleyjones** [comment]
- [ ] https://github.com/bazelbuild/bazel/pull/19052
- [ ] https://github.com/bazelbuild/bazel/pull/19053

**Comment by keertk** [comment]
@dflems @brentleyjones Thank you for reporting / looking into this issue.
We're looking to improve our release process so that we can catch more issues early on in the cycle (before the final release) and would love your input. What can we do to make it easier for you to test _release candidates_ in the future?

**Comment by meteorcloudy** [comment]
@dflems Can you please confirm if this issue has been fixed in 6.3.1rc1?

**Comment by BalestraPatrick** [comment]
@meteorcloudy Sorry for the delay, but yes this issue is fixed in 6.3.1.

@keertk Yes, we're very interested in this topic. We currently have an internal fork of Bazel with about 15 patches (used to be over 20 before 6.3.0 was released) on top of it (either open PRs that haven't been merged or other changes required to get our Android builds in a good/stable place). Every time we want to bump our version of Bazel we need to rebase our fork and fix any kind of conflict arising from new upstream changes. This would be much easier if we were able to reduce the number of patches we have and have them merged upstream so that we could directly test releases produced with every release candidate.

**Comment by meteorcloudy** [comment]
> This would be much easier if we were able to reduce the number of patches we have and have them merged upstream 

Have you tried to upstream those patches? Any blocker from the Bazel side?

**Comment by BalestraPatrick** [comment]
@meteorcloudy Here is our list with related PR/issue tracking it:

| Patch | Upstream issue / PR / commit |
| - | - |
| Add-link_library_resources-to-skip-linking-in-Androi.patch | [PR](https://github.com/bazelbuild/bazel/pull/11294)
| Add-output_library_linked_resources-to-remove-ap_-fi.patch | [PR](https://github.com/bazelbuild/bazel/pull/14786)
| Implement-non-transitive-R-class-via-android_non_tra.patch | [PR](https://github.com/bazelbuild/bazel/pull/15806)
| Patch-manifest-merger-25.0.0-with-queries-support.patch | [Issue](https://github.com/bazelbuild/bazel/issues/14285), [PR](https://github.com/bazelbuild/bazel/pull/14429)
| Add-debug_key_password-attribute-for-android_binary.patch | [Issue](https://github.com/bazelbuild/bazel/issues/10862)
| Expose-compatibility-arguments-on-java-toolchains.patch | [Commit](https://github.com/bazelbuild/bazel/commit/27fe30bb7cc1fdea7c60d7f73774149c0dd21457)
| Allow-passing-target-and-exec-constrains-to-java-rem.patch | [PR](https://github.com/bazelbuild/bazel/pull/17769)
| Add-patch-to-enable-R8-support-on-6.3.1.patch | [PR](https://github.com/bazelbuild/bazel/pull/14741)
| Fix-race-in-WorkerMetricsCollector.patch | [Issue](https://github.com/bazelbuild/bazel/issues/18545)
| Pass-host_jvmopt-to-host-options-attribute.patch | [PR](https://github.com/bazelbuild/bazel/pull/15978)

On top of these that are available publicly, we have a few more that I need to check if possible to upstream.

**Comment by fmeum** [comment]
@BalestraPatrick The two PRs for making Java runtime constraints accessible may become unnecessary with https://github.com/bazelbuild/bazel/pull/18262. I asked for clarification on the configurability PR.

**Pull request closed without merging**
