### PR TITLE
Accept tildes in --override_repository

### PR DESCRIPTION
**Pull request by keith**
This is useful for adding this in your global ~/.bazelrc file for easy
rules debugging.

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]
thanks!

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by ckolli5** [comment]
Hey @keith, we are trying to [cherry pick](https://github.com/bazelbuild/bazel/pull/15873) this change to the release-5.3.0. But presubmit checks are failing due to missing dependencies. So, could you please help us in cherry picking this change with appropriate commits? Thanks!

**Comment by ckolli5** [comment]
Hey @brentleyjones, based on the [above comment](https://github.com/bazelbuild/bazel/pull/15417#issuecomment-1184639985). Should we still consider this as a release blocker?

**Comment by brentleyjones** [comment]
@ckolli5, no. If it was easy to land it would have been nice, but let's drop it from 5.3. Thanks!

**Pull request closed without merging**
