### PR TITLE
Refactor building DLL example on Windows with windows_dll_library

### PR DESCRIPTION
**Pull request by meteorcloudy**
@excitoon Instead of https://github.com/bazelbuild/bazel/pull/7629, what do you think of this one?
I would recommend to use `cc_shared_library` to build dll on Windows. One `cc_shared_library` can even depend on another.

@hlopko Do you have any plan to implement a `cc_shared_library` in https://github.com/bazelbuild/rules_cc?

### CODE REVIEW

**Comment by excitoon** [comment]
@meteorcloudy This is a good solution, but I wanted a mechanism which would work with multiple extensions (`.dll`, `.so`, `.dylib`) and ideally correspond to current target OS (without 2 extra targets). Personally, I think this is kinda perfectionism, but this is how we do things.

So basically, as a part of plan I switch to one "wrong" (for 2 of 3 cases) extension, like we already have, but in parallel I would like to experiment with `cc_common.link` in order to write a rule which would link a binary with proper naming depending on target platform - #7538. Can you already tell if that is impossible that way? Or maybe can you provide any example to start hacking from?

BTW, we will keep waiting for C++ Sandwich and Transitive Linking anyway.

**Comment by meteorcloudy** [comment]
I am not so familiar with the C++ Starlark API, so I'm not sure you can rename the output file name based on target platform. But if https://github.com/bazelbuild/bazel/blob/6793b9358e51f0be8ea02376d530a847e2f3e2d4/tools/cpp/cc_toolchain_config.bzl.tpl#L1092-L1096 is exposed in the API, we can definitely do that. @oquenchil can you confirm if it is available or not?

**Comment by meteorcloudy** [comment]
Oh, looks like it is!
https://github.com/bazelbuild/bazel/blob/cf8ed7349c969b19b9b968923ff0c1a2b4530bf7/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/cpp/CcModuleApi.java#L720-L728

**Comment by hlopko** [comment]
Re `cc_shared_library`, the tracking issue is https://github.com/bazelbuild/bazel/issues/5200, and we plan to work on it in this quarter, definitely by Bazel 1.0.

Re naming, the api you found is what we use to replace CROSSTOOL, because that is where we specify extension names and prefixes (of output artifacts). With C++ sandwich API (https://github.com/bazelbuild/bazel/issues/4570) which is being finished these days (and should be available in 0.26), you'll be able to create artifacts without specifying prefix and extension, and C++ toolchain will set those.

**Comment by meteorcloudy** [comment]
@hlopko Do you think I can merge this change?

**Comment by hlopko** [comment]
So why do you want to change this at all? cc_shared_library from examples is just an example, it's not supported, and we don't document or recommend people to use it anywhere. Up until this PR I completely forgot it existed :)

**Comment by meteorcloudy** [comment]
Just to make the example more simple and clear. 
People from EA actually asked about how to build DLL on Windows, I recommended this way since `cc_shared_library` is not yet available. Of course, I don't want to advertise it too much, but for people who want to use this way, this PR can help them having a better interface, which will make it easier to migrate to the proper `cc_shared_library` in Starlark in the future.

**Comment by meteorcloudy** [comment]
OK, renamed the macro to `windows_dll_library` to not cause any confusion with the future `cc_shared_library`

**Comment by meteorcloudy** [comment]
@hlopko Does this PR look good now? :)

**Pull request closed without merging**
