### PR TITLE
Add util for finding credential helper to use

### PR DESCRIPTION
**Pull request by Yannic**
Progress on https://github.com/bazelbuild/proposals/blob/main/designs/2022-06-07-bazel-credential-helpers.md

### CODE REVIEW

**Review by tjgq — CHANGES_REQUESTED** [review]

**Comment by Yannic** [comment]
@tjgq ping?

**Review by tjgq — APPROVED** [review]

**Comment by tjgq** [comment]
FYI, I fixed a few of the test assertions to use `Truth8.assertThat` to appease our internal linter.

**Comment by Yannic** [comment]
@bazel-io flag

**Comment by ckolli5** [comment]
@bazel-io fork 5.3.0

**Pull request closed without merging**
