### PR TITLE
Tags propagation for java rules

### PR DESCRIPTION
**Pull request by ishikhman**
Part of #8830

RELNOTES[NEW]: tags: use --experimental_allow_tags_propagation flag to propagate tags to the action's execution requirements from java targets. Such tags should start with: no-, requires-, supports-, block-, disable-, cpu:. See #8830 for details.

### CODE REVIEW

**Comment by ishikhman** [comment]
@buchgr @hlopko This one is heavily based on #9267 , so look at the latest commit for specific changes: https://github.com/bazelbuild/bazel/pull/9274/commits/1cb34caf106fedcb4f37fd290aa957505ae183b2

**Comment by dslomov** [comment]
Is this still a 1.0 blocker?

**Comment by ishikhman** [comment]
@dslomov well, it merged, so not anymore

**Comment by buchgr** [comment]
yay! congrats!

**Pull request closed without merging**
