### PR TITLE
Add missing word in getting-started.md

### PR DESCRIPTION
**Pull request by adrian5**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by adrian5** [comment]
If this tiny correction cannot be committed without me signing the CLA, then simply discard my pull request and add the fix yourself.

**Comment by steren** [comment]
Thanks for reporting the issue. Sorry about the PR process :(
The CLA is a process that applies to any changes, it really is a one-click process to sign it, are you sure you do not want to do so?
I will let you close this PR if not

I sent a Pull Request fixing the problem in internal repo.

**Comment by adrian5** [comment]
I have to give my real name, address and phone number, which I don't do unless absolutely necessary.

**Pull request closed without merging**
