### PR TITLE
Build bazel as @io_bazel//src:bazel-bin

### PR DESCRIPTION
**Pull request by Yannic**
This patch makes it possible to build bazel as `@io_bazel//src:bazel-bin` (for example when imported into another repository, see #4435 #4285).

cc @dslomov @jmillikin-stripe 

This is WIP, will add some documentation why these changes are necessary later. It may also not work on Windows yet.

### CODE REVIEW

**Comment by ulfjack** [comment]
What's the purpose of this change? The referenced bugs are both closed.

**Comment by Yannic** [comment]
The purpose of this change is to build bazel itself as `@io_bazel//src:bazel-bin` which currently fails with a compilation error in C++ grpc code.

An example of why this is useful is for adding bazel as a data dependency to a CI runner binary so that it's not necessary to install anything on the CI machine. Just copy the binary and you're done. (I know that bazel currently has some external dependencies and that this change alone won't be sufficient to achieve this goal).

The referenced bugs are examples of previous changes going in a similar direction.

**Comment by ulfjack** [comment]
On Tue, Oct 30, 2018 at 9:19 PM Yannic <notifications@github.com> wrote:

> The purpose of this change is to build bazel itself as
> @io_bazel//src:bazel-bin which currently fails with a compilation error
> in C++ grpc code.
>

Isn't the official target //src:bazel? Why bazel-bin?

**Comment by Yannic** [comment]
`//src:bazel-bin` is the genrule producing `//src:bazel` or `//src:bazel.exe` on Windows (https://github.com/bazelbuild/bazel/blob/master/src/BUILD#L273).
However, It does not matter what target to build. All of those fail to compile with the same import error in grpc code, and once that's fixed, the produced bazel binary kinda works, but `@bazel_tools//x`, with `x` beeing an arbitrary path, must be referenced as `@io_bazel//external/io_bazel/x`. Hence the change to `src/create_embedded_tools.py` to remove this path prefix.

**Comment by ulfjack** [comment]
@lberki, can you take a look at this? Also @aehlig who has been looking at similar issues with workspaces in general.

**Comment by lberki** [comment]
Depends on within what time frame... for the week, I'm absolutely overwhelmed.

**Comment by jin** [comment]
Closing as activity seemed to have stalled and is no longer mergeable as-is. Please ping this PR if you intend to restart work on this.

**Comment by jin** [comment]
(Incorrectly closed prematurely, reopening as this is waiting on @lberki's input)

**Comment by lberki** [comment]
LGTM. Importing it anyway.

**Comment by Yannic** [comment]
@jin Hm, I can't reopen this either, and Github is thinking this comes from an unknown repository. Maybe I did delete my fork at some point and recreated it later?

@lberki Thanks! I'll create a new PR.

**Pull request closed without merging**
