### PR TITLE
Fix grammar mistake in build-ref

### PR DESCRIPTION
**Pull request by gboer**

### CODE REVIEW

**Review by gregestren — COMMENTED** [review]
Interesting change. I think I can see the point being made with both wordings? Do you see just ambiguous wording or a clear doc error being fixed?

**Comment by gboer** [comment]
Well, at least 'form' should be 'from' right? And I'm no native English speaker, but for me, the 'are' should be there as well.

**Comment by gregestren** [comment]
I think the original wording is saying that a subdirectory tree with its own `WORKSPACE` file actually *is* another workspace, which means that subtree forms its own workspace.

The new wording is subtly different in that it implies they're part of, but not necessarily the entire, workspace.

But I don't know the exact history. I'll link some folks I think can offer more authoritative input

@Wyverald 

Also see https://github.com/bazelbuild/bazel/issues/13771.

**Comment by Wyverald** [comment]
The wording here is indeed a bit unclear. The terminology we're going for right now is that the "workspace" is the whole thing you're running Bazel in (i.e. the "root" workspace), whereas the subdirectories with WORKSPACE files are just external repos that happen to reside in the same directory structure. I should fix the glossary page some time.

In any case, I don't believe the specific change in this PR clarifies anything. "A forms B" is a perfectly clear English sentence.

**Pull request closed without merging**
