### PR TITLE
Fix the broken genrule example.

### PR DESCRIPTION
**Pull request by dfabulich**
Fixes issue #866

### CODE REVIEW

**Comment by dfabulich** [comment]
Apropos @ahumesky's [comment](https://github.com/bazelbuild/bazel/issues/866#issuecomment-181673485).

I'm confused as to why this is necessary. What's the point of using `$(location create_foo.pl)` if it doesn't compute a path that `genrule` can use? At that point, shouldn't we just use `./create_foo.pl`?

**Comment by ahumesky** [comment]
$(location create_foo.pl) will correctly expand to the path for
create_foo.pl, it's just that this is executed in the shell, so it needs to
know where to find the file. "." is not on the path, so the shell will
complain that it can't find it. It's the same as if you'd typed it on the
command line.

**Comment by dfabulich** [comment]
Let me try to phrase a more specific question.

If I use `$(location)` and I give it a relative file path, e.g. `create_foo.pl` or `scripts/create_foo.pl` or whatever, then `$(location)` doesn't do anything, right? I give it `scripts/create_foo.pl` and it returns what I typed, `scripts/create_foo.pl`.

`$(location)` only does anything useful when I give it a _target_, like `:foo` or `//somepkg:foo` or whatever, right?

The `genrule` documentation goes out of its way to warn me _not_ to use a hard-coded path like `scripts/create_foo.pl`, and instead to use `$(location scripts/create_foo.pl)`. But why should I be afraid of a hard-coded relative path when `$(location)` is a passthrough?

**Comment by ahumesky** [comment]
$(location) is for translating a label to a path, and often these will
match up because your labels are referring to source files in the genrule's
package. Other times the label might refer to a generated file, in which
case the path is going to be somewhere in bazel-out and depend on the
configuration (like
"bazel-out/android-stub_armeabi-v7a-fastbuild/bin/java/bazel/libapplib.jar").
Other times the label might actually refer to multiple files, in which case
you want to use $(locations). The label might refer to a filegroup for
indirection or convenience, or be redirected by bind() rules, or it might
refer to something in an external repository.

**Comment by damienmg** [comment]
Just a test to see if @googlebot checks this one

**Comment by damienmg** [comment]
LGTM

**Comment by damienmg** [comment]
This was merged

**Pull request closed without merging**
