### PR TITLE
Update zlib to v1.2.11 (2017-01-16)

### PR DESCRIPTION
**Pull request by rongjiecomputer**
The original version (v1.2.8) was for 2013-04-29, time to update it to latest stable version.

/cc @buchgr

### CODE REVIEW

**Comment by irengrig** [comment]
cc @lberki

**Comment by lberki** [comment]
Hey there,

Updating zlib is great and useful! However, we need to know two things:
1. That these sources are legitimate
2. How to reproduce this source tree in case it's needed

Both of these can be accomplished by updating `README.md` (for simplicity, with the new commit hash). Could you do that?

**Comment by lberki** [comment]
Verified! There are files with different checksums, but they match after running the zlib tree through `dos2unix` and since we have all Unix line endings in the Bazel repository, it should be fine.

Assigning to our sheriff for merging this as per standard operating procedure.

**Comment by rongjiecomputer** [comment]
> but they match after running the zlib tree through dos2unix

Windows user here 😅. Git for Windows sometime do weird stuff with CRLF/LF.

**Comment by philwo** [comment]
Merging.

**Pull request closed without merging**
