### PR TITLE
Add a Java 17 toolchain

### PR DESCRIPTION
**Pull request by cushon**
https://github.com/bazelbuild/bazel/issues/13965
https://github.com/bazelbuild/bazel/issues/13416

### CODE REVIEW

**Comment by meteorcloudy** [comment]
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.28.13-ca-jdk17.0.0-linux_x64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.28.13-ca-jdk17.0.0-macosx_x64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.28.13-ca-jdk17.0.0-macosx_aarch64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.28.13-ca-jdk17.0.0-win_x64.zip

are now available

**Comment by davido** [comment]
Mention issue https://github.com/bazelbuild/bazel/issues/13416?

**Review by comius — APPROVED** [review]
Looks good to me. Sorry, for having so many locations that need updating.

The tests need java_tools update right?

**Comment by cushon** [comment]
> The tests need java_tools update right?

Yep--I updated to the new release, and the tests are passing now. I think this is ready to go.

**Pull request closed without merging**
