### PR TITLE
Give the Bazel server process a more appropriate name

### PR DESCRIPTION
**Pull request by akira-baruah**
See #4227.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by buchgr** [comment]
friendly ping @philwo :-)

**Comment by philwo** [comment]
I have an idea how we can import this without breaking the internal behavior: I'll move the workspace name computation into a new method in workspace_layout.cc. Then we just call it here. This allows me to override the method in an internal child class that implements the legacy behavior.

**Comment by akira-baruah** [comment]
Sounds like a great idea @philwo ! Thanks for moving it forward - I see some of the changes in [this Gerrit code review](https://bazel-review.googlesource.com/c/bazel/+/30232), but it seems like I should wait to see the full changes before reviewing. Is that correct?

**Comment by philwo** [comment]
@akira-baruah Sorry for the delay in getting this merged! We figured out the issue with our code review exporter that was blocking the Gerrit review and I’ll get this merged ASAP.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
No worries @philwo! Glad the exporter-Gerrit issue was resolved. Let me know you need anything else from my end - thanks!

**Comment by akira-baruah** [comment]
Hi @philwo ! Was wondering if we were able to merge this change yet. If so, perhaps we should close this PR? Let me know if there's anything I can do to help.

**Pull request closed without merging**
