### PR TITLE
[6.4.0] Add `--incompatible_merge_fixed_and_default_shell_env`

### LINKED ISSUE #12049: `PATH` not propagated to many darwin actions
This is a wider reaching version of https://github.com/bazelbuild/bazel/issues/8425

In the linked issue I did some investigation around default PATH variables for actions that at the time I thought only affected `py_*` targets but it turns out that many other actions on darwin do not inherit any `PATH` and therefore fallback to macOS's default shell env of `/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.` which can allow leakage of `/usr/local/*` binaries (which is specifically an issue because of homebrew).

While the default PATH may be ok for some use cases, if you actually try to restrict it using `--action_env=PATH=something` or by executing bazel with `env -i PATH=something bazel ...`, neither of these are applied to these actions.

For example any action that is executed in the context of Xcode is executed with these environment variables:

```
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    XCODE_VERSION_OVERRIDE=11.5.0.11E608c \
  external/local_config_cc/wrapped_clang ...
```

Some actions that don't require Xcode are executed with no environment variables:

```
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool ...
```

This is not the behavior of some other rules like `genrule` where if you build this target with `--action_env=/usr/bin:/bin` it hits the "Valid path":

```bzl
genrule(
    name = "foo",
    outs = ["foo.txt"],
    cmd = """
if [[ "$$PATH" != "/usr/bin:/bin" ]]; then
  echo "error: path not propagated: $$PATH"
  exit 1
else
  echo "Valid path! $$PATH"
  exit 1
fi
""",
)
```

I think that either all actions should get a very conservative default PATH like `/usr/bin:/bin`, or the flags like `--action_env` should be able to add env vars to these actions (I believe the latter is likely the more flexible path, but I'm not sure about the implementation implications).

For native actions it seems that this can be resolved by adding:

```java
.setInheritedEnvironment(ImmutableSet.of("PATH"));
```

to this logic https://github.com/bazelbuild/bazel/blob/8f678923ebea788fc1e03ba8c6359b51edafe0df/src/main/java/com/google/devtools/build/lib/rules/objc/ObjcRuleClasses.java#L140-L144

But for starlark actions they inherit this environment:

https://github.com/bazelbuild/bazel/blob/8f678923ebea788fc1e03ba8c6359b51edafe0df/tools/osx/crosstool/cc_toolchain_config.bzl#L4546-L4557

When accessing the environment variables for an action with the [`cc_common` api](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#get_environment_variables). There doesn't seem to be a way to craft an `env_entry` that doesn't impose a value. So I could add `/usr/bin:/bin` there, but it wouldn't allow overrides via `--action_env=PATH=foo`

I'm happy to make a change here but I'm hoping for some guidance on the right path!

### What operating system are you running Bazel on?

macOS

### Bazel version?

8f678923ebea788fc1e03ba8c6359b51edafe0df

### LINKED ISSUE #19312: [6.4.0] Add `--incompatible_merge_fixed_and_default_shell_env`
Forked from #18235

### PR DESCRIPTION
**Pull request by fmeum**
With the new flag, Starlark actions that specify both `env` and `use_default_shell_env` will no longer have `env` ignored. Instead, the values of `env` will override the default shell environment.

This allows Starlark actions to both pick up user-configured variables such as `PATH` from the shell environment as well as set variables to fixed values required for the action, e.g., variables provided by the C++ toolchain.

Rationale for having `env` override the default shell env: The rules know best which values they have to set specific environment variables to in order to successfully execute an action, so a situation where users break an action by a globally applied `--action_env` is prevented. If users really do have to be able to modify an environment variables fixed by the rule, the rule can always make this configurable via an attribute.

Work towards #5980
Fixes #12049

Closes #18235.

Commit https://github.com/bazelbuild/bazel/commit/d1fdc5303fd3cc22c5091aa4ce7df02eef09d922

PiperOrigin-RevId: 559506535
Change-Id: I7ec6ae17b076bbca72fab8394f3a8b3e4f9ea9d8

Fixes #19312

### CODE REVIEW

**Comment by fmeum** [comment]
@comius The cherry pick didn't apply cleanly and I had to make minor modifications (a new `if` branch). Let me know if you think that this is too complex for a cherry pick.

**Review by comius — CHANGES_REQUESTED** [review]
Can you also cherry-pick https://github.com/bazelbuild/bazel/commit/d5a963e28d8ee5dff526f296f6bcbb26ab740090?
That's where the actionEnvironment was removed from SpawnAction. I think cherry-picking is safer than adding an if branch. I suspect everything is fine, but tests after cherry-pick will show if there are any users.

**Comment by fmeum** [comment]
@iancha1992 If cherry-picking https://github.com/bazelbuild/bazel/commit/d5a963e28d8ee5dff526f296f6bcbb26ab740090 isn't straightforward let me know and I can try.

**Comment by fmeum** [comment]
Thanks for trying!

@comius Looks like the original cherry-pick will be cleaner even though it has an additional branch. What do you think?

**Comment by comius** [comment]
> Thanks for trying!
> 
> @comius Looks like the original cherry-pick will be cleaner even though it has an additional branch. What do you think?

Yes, probably.

Is there a guarantee that `actionEnvironment` is always `null` in 6.4.0 branch? I think that's the case, right?

**Comment by fmeum** [comment]
@comius Looks like it. I pushed a new commit that removes it, if all tests pass with that the cherry-pick will be even cleaner.

**Review by comius — APPROVED** [review]

**Comment by iancha1992** [comment]
@fmeum can you please resolve the conflicts? Thanks!

**Comment by fmeum** [comment]
@iancha1992 Done

**Pull request merged**
