### PR TITLE
Remove the embedded java tools from the bazel binary.

### PR DESCRIPTION
**Pull request by iirina**
The flags that enable using remote Java tools by default were pushed in 4d935d5ecad583dd9f87d3b08085145c900e21fb.

This PR shrinks the bazel binary by ~25%.

To measure the binary sizes I used `bazel build -c opt //src:bazel` at a57c879dbca95316ecf50f5e96143eb9f7d1acb8 with and without the changes in this PR:

```
$ ls -lh ~/bazel-with-java-tools | awk '{print $5}'
141M
$ ls -lh ~/bazel-no-java-tools | awk '{print $5}'
105M
```

Progress on #6316.

### CODE REVIEW

**Comment by meisterT** [comment]
Nice! How much does this save? Perhaps include numbers in the commit message.

**Comment by iirina** [comment]
Thanks! It reduces the binary size by 25%, I added some numbers in the initial comment.

I'll first import the third-party changes and then the bazel `src/BUILD` file.

**Comment by meisterT** [comment]
happy dance

**Comment by iirina** [comment]
cc @lberki

**Comment by iirina** [comment]
third_party changes merged in 714e3f2eebae97cd994ddf89627767fe2a86a16e

**Pull request closed without merging**
