### PR TITLE
Use valid name for local_repository example in external project docs

### PR DESCRIPTION
**Pull request by akira-baruah**
Addresses #4018

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
Friendly ping @damienmg @spomorski Is there anything blocking this merge?

**Comment by damienmg** [comment]
Importing since USA are in holidays. I guess serge forgot to import it.

**Comment by akira-baruah** [comment]
Ah okay. Thank you!

**Pull request closed without merging**
