### PR TITLE
Clean up build after update to 7.2.0

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@keertk @iancha1992 FYI, I prepared this PR to verify compatibility with the new lockfile format. Happy to finalize it when 7.2.0 lands.

**Comment by iancha1992** [comment]
> @keertk @iancha1992 FYI, I prepared this PR to verify compatibility with the new lockfile format. Happy to finalize it when 7.2.0 lands.

Just FYI, if you change the `.bazelversion`, I think you might need to update the lockfile on all four platforms.

**Comment by fmeum** [comment]
Thanks, I'm in the process of setting up a Windows VM for that. But I likely need to do it again after the actual release, so I'll wait for that.

**Comment by Wyverald** [comment]
> Thanks, I'm in the process of setting up a Windows VM for that. But I likely need to do it again after the actual release, so I'll wait for that.

I'd suggest you not to worry about it, and let us (me?) do the work when 7.2.0 is actually released :) I've done this multiple times now and have all four machine types on hand.

**Comment by Wyverald** [comment]
or, actually, if we could get rules_python to declare certain module extensions of theirs to be reproducible, we might be able to just remove all traces of them from the lockfile.

**Comment by fmeum** [comment]
> or, actually, if we could get rules_python to declare certain module extensions of theirs to be reproducible, we might be able to just remove all traces of them from the lockfile.

I looked into that today: Two of their extensions are trivially reproducible (https://github.com/bazelbuild/rules_python/pull/1892), but the `pip` extension is both os/arch dependendent and not reproducible: it talks to https://pypi.org/simple/ (don't click on that link, it might freeze your browser) during extension evaluation.

**Review by meteorcloudy — APPROVED** [review]
Awesome!

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Pull request closed without merging**
