### PR TITLE
Allow extra env vars on OSX toolchain config

### PR DESCRIPTION
**Pull request by illicitonion**
Just like we allow `tool_paths_overrides`.

### CODE REVIEW

**Comment by oquenchil** [comment]
Hey Tony, do you think this is a good idea?

**Comment by keith** [comment]
What's the use case for this?

**Comment by illicitonion** [comment]
I'm using this to set `DEVELOPER_DIR` and `SDKROOT` for a remote environment with Xcode installed.

**Comment by thii** [comment]
This doesn't seem right for that use-case. There's no guarantee that the same Xcode version is installed at the same location on the remote machine (though technically you can control that with your own infrastructure).

I would suggest to use an execution wrapper, and figure out the right DEVELOPER_DIR and SDKROOT for each action via the wrapper (there's already enough info to do that).

**Comment by ulfjack** [comment]
Sorry for the plug: our remote execution service has built-in support to set `DEVELOPER_DIR` and `SDKROOT` from the `XCODE_VERSION_OVERRIDE`, `APPLE_SDK_VERSION_OVERRIDE`, and `APPLE_SDK_PLATFORM` env variables. I'm not sure that's the right way to go either, but it is probably faster than a wrapper and more resilient to different fs layouts than setting the env variables on the client?

**Comment by ulfjack** [comment]
(To be clear, I'm not against this change, but it should be clear that setting env variables with absolute paths can go wrong depending on the service setup.)

**Pull request closed without merging**
