### PR TITLE
Fix markdown formatting in site/docs/skylark/aspects.md

### LINKED ISSUE #4132: Improper formatting on aspects.html
https://docs.bazel.build/versions/master/skylark/aspects.html#advanced-example

aspects

### PR DESCRIPTION
**Pull request by akira-baruah**
Fixes #4132

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
Note: This PR fixes the immediate bug, but it may be worth using `kramdown` instead of `redcarpet` for parsing markdown in site docs. I did a quick test by replacing `markdown: redcarpet` with `markdown: kramdown` in `site/_config.yml` and the bug was resolved without any changes to the docs.

It seems like `kramdown` supports a more robust set of markdown syntax than `redcarpet` does. [GitHub officially supports `kramdown`](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0), so it may be more intuitive (and consequently, less error prone) for GitHub contributors.

**Comment by meteorcloudy** [comment]
@dslomov @vladmos Can you take a look?

**Comment by vladmos** [comment]
Thanks, I've confirmed it fixes the formatting bug, the pull request will be merged soon.

**Pull request closed without merging**
