### PR TITLE
Allow DexArchiveAspect to see 'JavaInfo' provider from Starlark aspects.

### PR DESCRIPTION
**Pull request by ceason**
Currently the Android rules' dexing aspect can propagate over `proto_library` rules which are "aspected" by the native java_proto rules. This is pretty great when using the built-in `java_{lite_,}proto_library` rules, but there is still a gap in functionality--DexArchiveAspect cannot see the `JavaInfo` provider returned by Starlark aspects.

To allow the DexArchiveAspect to see the 'JavaInfo' provider returned by Starlark aspects two changes are necessary:
1. First change allows DexArchiveAspect to see JavaInfo provided by Starlark aspects for all rules except proto libraries
2. Second change needs to fall back to checking for JavaInfo if the special-cased proto library logic doesn't find any jars.

### CODE REVIEW

**Comment by lberki** [comment]
This looks reasonable but I don't know what went into the decision of special-casing `proto_library`. The code appears to have been written by @kevin1e100 , maybe he knows?

**Comment by kevin1e100** [comment]
To my recollection proto_library was special-cased because the aspect for java_lite_proto_library (the only flavor that should be used with Android) didn't provide JavaInfos.  (java_lite_proto_library itself does provide JavaInfos, but doesn't produce Jar files itself.)  Additionally we currently skip desugaring of proto libraries, since it's unnecessary as long as protos are compiled to version 51 bytecode, but this part could go away (see todo).

**Comment by ceason** [comment]
**_background:_** I'm trying to implement `java_grpc_library` as a drop-in replacement for `java_{lite_,}_proto_library` ([grpc-java#5237](https://github.com/grpc/grpc-java/pull/5237)). I'm using an aspect to do so, but the dexer cannot see the `ProtoInfo`s my aspect produces.

It's interesting that java_lite_proto_library returns what sounds like an empty JavaInfo? And is getting the actual jars from a native provider when visiting a proto library because of prior knowledge of the java lite proto aspect implementation? I wonder if the way to do this is by checking for JavaInfo in an `else` block after the `outputJarsProvider != null` check?

**Comment by ceason** [comment]
> Could you clarify what this addresses? DexArchiveAspect is in general able to process Starlark rules to my knowledge. I believe this applies to Starlark _aspects_ that provide JavaInfos? Maybe change the title and description accordingly.

Will do. After a more careful reading of the dexer, the two code changes necessary address:
1. First change allows DexArchiveAspect to see JavaInfo provided by Starlark aspects for all rules except proto libraries
2. Second change needs to fall back to checking for JavaInfo if the special-cased proto library logic doesn't find any jars.

**Comment by lberki** [comment]
/cc @haberman @dbabkin 

Actually, `proto_library` is becoming a simpler and simpler beast every day :)

The idiom of wrapping the language-specific providers into a LANG_proto_library specific provider in their aspect and them unwrapping them in the LANG_proto_library comes from the time when we were migrating the languages out of `proto_library` at Google.

Then, we necessarily had `proto_library` rules that did the language compilation themselves and rules where that was handled by an aspect and this wrapping was the way to make these two approaches work together. Now that `proto_library` doesn't do compilation (except for C++, which is on its way out), there is no reason to do this.

In fact, it's better not to: the idea is that a `proto_library` with the `java_proto_library` aspect should look exactly like a `java_library`. 

So this should be good to go.

I don't understand, though, why you would need to special-case `proto_library` -- since you declare that you want this provider, it should Just Be There as long as you reach a `proto_library` through `java_proto_library` (which should always be the case), shouldn't it?

**Comment by kevin1e100** [comment]
This may be a naive question but what happens when multiple aspects contribute the same provider for the same target?  Aspects for java_proto_library and java_lite_proto_library (and java_grpc_library) seemingly all could "reach" the same proto_library in the same build?

**Comment by lberki** [comment]
It's absolutely not a naive question, it's a very good one :)

It's fine for two aspects to contribute the same provider to the same target as long as they are not applied at the same time. E.g. target A can use regular protos for a given `proto_library` and target B can use lite protos for the same `proto_library` and it should be fine. It's technically even fine if the same target uses both, because the two aspects will be propagated by different LANG_proto_library rules.

The trouble would be if an aspect added a provider that the target already has or if an aspect was applied to a dependency that already has another aspect (for example, if `DexArchiveAspect` was applied to a `proto_library` reached through a `java_proto_library` and if both contributed `JavaInfo`)

Some providers are hard-coded to be exempt from this (e.g. `FileProvider` and `OutputGroupInfo`), but they are hard-coded exceptions. Mind you, it's conceivable to make merging possible for any provider, but it's extra rope, is somewhat involved because it's another thing to teach to Starlark and we have never needed that functionality until now.

**Comment by ceason** [comment]
@kevin1e100 AFAIK aspect supplied providers are unique on `(provider,target,aspect_and_paramvalues,build_configuration)`. The "aspect-requesting" rules in your example (java_proto_library and java_lite_proto_library) have distinct tuples of those things (bc of distinct aspects), so no wires get crossed and consuming targets see what they're supposed to, even within a single bazel invocation.

Instead of thinking about a target as having providers (misleading since that implies only one instance per provider-type per target), I try to visualize it as looking at transitive targets _through the "lens" of a consuming target_. If the consuming target has a different build configuration (eg android_binary's overridden crosstool_top), aspect, or parameterized aspect values a consuming target still only "sees" one provider-type per dependent target, but the actual provider instance it sees has been "colored" by the consuming target. I hope I didn't go too overboard with the analogy.

Disclaimer: this is only based on observed behavior and reading docs, so I'm happy to be disabused of any misunderstanding I have about how all of this actually works

**Comment by ceason** [comment]
I've updated the PR to check for JavaInfo only after the java_proto_library-specific provider to avoid unintended changes.

**Comment by lberki** [comment]
/cc @djwhang

I'm importing this patch now. We'll see if it breaks any internal test cases...

**Pull request closed without merging**
