### PR TITLE
Provide the default lcov_merger to all Starlark tests

### LINKED ISSUE #13978: Custom test rule without `_lcov_merger` attribute always fails under `bazel coverage`
### Description of the problem / feature request:

When a custom Starlark test rule without explicit coverage support in the form of the `_lcov_merger` attribute is invoked via `bazel coverage` with Bazel after 5b216b27435aeb9eb9c3bd3c552d6498e1050cc7, it fails with
```
FAIL: //:custom_test (see /home/fmeum/.cache/bazel/_bazel_fhenneke/767fd922858d516eb34a4dddb64ca1a0/execroot/__main__/bazel-out/k8-fastbuild/testlogs/custom_test/test.log)
ERROR: /home/fmeum/git/bazel-custom-test-coverage/BUILD:3:12: output 'custom_test/coverage.dat' was not created
ERROR: /home/fmeum/git/bazel-custom-test-coverage/BUILD:3:12: Testing //:custom_test failed: not all outputs were created or valid
Target //:custom_test up-to-date:
  bazel-bin/custom_test
INFO: Elapsed time: 5.635s, Critical Path: 0.17s
INFO: 7 processes: 1 disk cache hit, 5 internal, 1 linux-sandbox.
FAILED: Build did NOT complete successfully
//:custom_test                                                           FAILED in 0.0s
  /home/fmeum/.cache/bazel/_bazel_fhenneke/767fd922858d516eb34a4dddb64ca1a0/execroot/__main__/bazel-out/k8-fastbuild/testlogs/custom_test/test.log
```

The log says:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:custom_test
-----------------------------------------------------------------------------
--
Coverage runner: cannot locate file
```

With Bazel 4.2.1, the build succeeds:
```
INFO: Build completed successfully, 5 total actions
//:custom_test                                                           PASSED in 0.0s

Executed 1 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command
INFO: Build completed successfully, 5 total actions
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```sh
#!/usr/bin/env sh
touch WORKSPACE

cat << EOF > BUILD
load("//:rules.bzl", "custom_test")

custom_test(
    name = "custom_test",
)
EOF

cat << EOF > rules.bzl
def _custom_test_impl(ctx):
    executable = ctx.actions.declare_file(ctx.attr.name)
    ctx.actions.write(executable, "", is_executable = True)
    return [
        DefaultInfo(
            executable = executable,
        )
    ]

custom_test = rule(
    implementation = _custom_test_impl,
    test = True,
)
EOF

bazel coverage //:custom_test
```
### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 5.0.0-pre.20210831.2 

I bisected the origin of this issue back to 5b216b27435aeb9eb9c3bd3c552d6498e1050cc7.

###  Have you found anything relevant by searching the web?

With `5b216b27435aeb9eb9c3bd3c552d6498e1050cc7`, the `custom_test` rule in the reproducer now provides an `InstrumentedFilesInfo`, which [causes TestActionBuilder to collect coverage](https://github.com/bazelbuild/bazel/blob/ded65d28832ea419e0b8056aa88f9b135a25dabb/src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java#L201). However, since the rule does not have the [`:lcov_merger`](https://github.com/bazelbuild/bazel/blob/ded65d28832ea419e0b8056aa88f9b135a25dabb/src/main/java/com/google/devtools/build/lib/analysis/test/TestActionBuilder.java#L268) attribute set, the `LCOV_MERGER` env variable isn't set when [`collect_coverage.sh`](https://github.com/bazelbuild/bazel/blob/ded65d28832ea419e0b8056aa88f9b135a25dabb/tools/test/collect_coverage.sh#L93) is invoked, which causes the error message reproduced above.

### PR DESCRIPTION
**Pull request by fmeum**
Since 5b216b27, all Starlark-defined test rules either need to set the `_lcov_merger` attribute or fail if run with `bazel coverage`. This is fixed by attaching the default lcov merger as a late-bound default to all Starlark rules via a new attribute and falling back to that attribute in the TestActionBuilder.

This commit ensures backwards compatibility is maintained with existing Starlark test rules that set the `_lcov_merger` attribute. This is also verified in the included integration test.

Fixes #13978.

### CODE REVIEW

**Comment by fmeum** [comment]
@oquenchil Would you be able to take a look? The issue this resolves is labeled with team-Rules-CPP.

**Comment by meteorcloudy** [comment]
@c-mita Can you help review this change?

**Comment by c-mita** [comment]
Unfortunately, I can't accept this PR as is.
Internally, things are setup a little differently for coverage collection. We use a different `collect_coverage.sh` script and generally do not set the `:lcov_attribute`; this change does not play well with the internal setup.

I think the best (only?) way to handle this at the moment is by changing Bazel's `collect_coverage.sh` to simply do nothing if  the `LCOV_MERGER` variable has not been set.

**Comment by fmeum** [comment]
@c-mita I see the problem. While your proposed solution does resolve the linked issue, it would mean that there would still be no way for Starlark tests to access the merge as a late-bound attribute.

How about the following path forward:
1. You make the required change to `collect_coverage.sh` to resolve the release blocking #13978 and I close the current PR.
2. Someone who is familiar with Google's internal coverage setup provides some guidance on either #8736 or #10642 on how a solution to these issues could look like that would have a chance to be accepted.
3. I will look into providing such a solution as a separate PR.

**Comment by c-mita** [comment]
I'm ok with this approach; I've got a change ready to unblock the build.
It isn't ideal, but it's a way forward.

**Pull request closed without merging**
