### PR TITLE
[4.2.4] Disable some failing tests

### PR DESCRIPTION
**Pull request by keertk**
Disabled some failing tests, similar to what was done in https://github.com/bazelbuild/bazel/pull/17986

### CODE REVIEW

**Comment by keertk** [comment]
Hi @meteorcloudy could you help with the RBE failure [here](https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/15264) please? And could you confirm if other failing macos tests should be disabled?

I'll follow up on https://github.com/bazelbuild/bazel/pull/18047 and https://github.com/bazelbuild/bazel/pull/18041 once this PR is merged.

**Comment by meteorcloudy** [comment]
> could you help with the RBE failure here please?

@coeuvre Can you take a look at the RBE error, maybe something is no longer compatible with 4.x and we can disable the RBE platform entirely?

> And could you confirm if other failing macos tests should be disabled?

Yes, those are failing due to the removal of python 2, let's disable them. Thanks!

**Comment by meteorcloudy** [comment]
@keertk Let's disable the rest of the failing tests on macOS and the RBE platform as well.

**Comment by keertk** [comment]
I think that should be it, @meteorcloudy. I'm not seeing new failures. Could you approve?

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Pull request merged**
