### PR TITLE
HOME missing from the action env (despite mentioned in the docs)

### PR DESCRIPTION
**Pull request by grswk**
Issue #4401

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by grswk** [comment]
I signed CLA!

**Comment by jin** [comment]
@ulfjack, do you mind taking a look at this?

**Comment by jin** [comment]
I will import this.

**Comment by jin** [comment]
Thanks @grswk for your contribution!

**Pull request closed without merging**
