### PR TITLE
tests,windows: enable some of android.desugar.*

### PR DESCRIPTION
**Pull request by laszlocsomor**
On Windows, enable some tests under
c.g.d.build.android.desugar by adding them to
the transitive closure of //src:all_windows_tests,
thus running them on CI.

Depends on PR https://github.com/bazelbuild/bazel/pull/4796
See issue https://github.com/bazelbuild/bazel/issues/4292

### CODE REVIEW

**Comment by laszlocsomor** [comment]
This PR requires either that we update the Windows config scripts on Buildkite to add the `android_{s,n}dk_repository` rules to the WORKSPACE, or that we uncomment those rules in the checked-in WORKSPACE file.

@philwo tells me that @ahumesky said that it should be safe to uncomment those rules. I haven't tried yet.

**Comment by aj-michael** [comment]
I do not think we should add android_sdk_repository to the main bazel WORKSPACE file. We have some selects that are effectively conditional on whether or not android_sdk_repository is run (see //external:has_androidsdk) that allow loading and analysis to succeed (but execution fail) on some tests that require an Android SDK.

https://source.bazel.build/search?q=%2F%2Fexternal:has_androidsdk&ss=bazel

Adding android_sdk_repository to WORKSPACE would break some users who are doing blaze query over //... if they don't have ANDROID_HOME set.

**Comment by lfpino** [comment]
Hi all, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by laszlocsomor** [comment]
I still want to merge this, but I need to fix the CI machine setup first.

**Comment by philwo** [comment]
> I still want to merge this, but I need to fix the CI machine setup first.

What are the required changes on the CI machines?

**Comment by laszlocsomor** [comment]
Patch the Windows WORKSPACE file to have the android_{s,n}dk_repository rules.

**Comment by laszlocsomor** [comment]
> To patch the Windows WORKSPACE file to have the android_{s,n}dk_repository rules.

@philwo : Can you do that?

**Comment by philwo** [comment]
@laszlocsomor Will do, yes.

**Pull request closed without merging**
