### PR TITLE
Set C++ archive action mnemonic to CppArchive

### PR DESCRIPTION
**Pull request by keith**
Previously the archiver action shared the CppLink mnemonic which made it
impossible to differentiate with this like --modify_execution_info

### CODE REVIEW

**Comment by keith** [comment]
Considering this is public API I'm not sure what considerations there are about merging something like this?

**Comment by ckolli5** [comment]
Hello @keith, can you please check presubmit failures. Thanks!

**Comment by keith** [comment]
@ckolli5 updated

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by brentleyjones** [comment]
Actually, this is probably a breaking change, and can't get included in 5.x. You can just remove the label @ckolli5.

**Comment by meisterT** [comment]
Agreed, this should be in 6.0 but not 5.x.

**Pull request closed without merging**
