### PR TITLE
Add support for naming objc module maps

### LINKED ISSUE #2988: Feature Request: Objc Library Module Name
I'd like the ability to control the module name created by the objc_library rule. For more details refer to https://github.com/bazelbuild/rules_apple/issues/51.

### PR DESCRIPTION
**Pull request by ob**
This is symmetric with `swift_library`'s ability to name module maps. See [here](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-swift.md).

Fixes #2988 and https://github.com/bazelbuild/rules_apple/issues/51

### CODE REVIEW

**Comment by aiuto** [comment]
ob: Do you specifically want lberki to review this or will another team member do. He is out on vacation this week.

**Comment by ob** [comment]
I think the reviewer was auto-assigned by @googlebot

**Comment by ob** [comment]
No worries. Thanks for trying to find someone.

**Comment by iirina** [comment]
@lberki Can you take a look?

**Comment by lberki** [comment]
Looks good to me, but I'd rather @aragos make the final call because I'm not very knowledgeable in Objective-C. 

/cc @mhlopko

**Comment by allevato** [comment]
This looks reasonable, and is something I'm happy to see someone motivated enough to implement, because right now the only way to give an Objective-C library a different module name is to provide the full module map file, forcing you to make sure to keep your list of headers in sync there and in your build target.

On that last note, though, I feel like we should emit an error if the user provides both `module_name` and `module_map` attributes. They're mutually exclusive because the former changes the module name for the generated module map, and the latter causes the generated module map to be suppressed entirely. If we silently allow both to be present, I'm assuming that `module_map` takes priority, but it could be surprising to users that they don't get the module name they expected.

Some tests to verify those various cases would be great.

**Comment by ob** [comment]
@allevato I added the error checking and a test for the case where both `module_map` and `module_name` are specified. As I mentioned, I've been testing by hand using the `swift_library` rules which I imagine are not kosher in the bazel source base. Any pointers on how to test would be greatly appreciated.

**Comment by allevato** [comment]
Unfortunately it doesn't look like we have much testing around the auto-generated module maps in general from what I can see, at least in the unit tests.

Bazel unit tests are somewhat outside my area of expertise, but one solution would be to add a `@VisibleForTesting` public getter for `cppModuleMap` in [CppModuleMapAction.java](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CppModuleMapAction.java), then write a unit test that gets the `CppModuleMapAction` that generates the module map artifact (there's an [example here](https://github.com/bazelbuild/bazel/blob/de5462a61318dc14f8f21b129e6278219b307ee2/src/test/java/com/google/devtools/build/lib/rules/objc/ObjcLibraryTest.java#L691)) and then queries the `CppModuleMap` object to see if it has the name you expect to be pulled from the `module_name` attribute. (And if you want to add another test to cover the case of an auto-generated module name, that would be great since apparently we don't have it 🙂).

Unless @aragos has any other ideas?

**Comment by ob** [comment]
Thanks @allevato, I followed your recommendations and added tests both for changing the module name with the `module_name` attribute and for the auto-generated module name.

**Comment by allevato** [comment]
@aragos The name of the module only appears in the `module.modulemap` file once it's written to disk; the only place it's available at analysis time AFAIK is in the `CppModuleMap` object. How would the provider help here?

**Comment by ob** [comment]
Thanks @allevato and @aragos for your reviews. Does someone need to trigger the CI tests now?

**Comment by keith** [comment]
@aragos @allevato would it be reasonable to add this attribute for `objc_import` as well? It appears to have the same issue with generating a module name, which doesn't work for pre-compiled binaries without pre-processing the headers

**Comment by lberki** [comment]
over to @mhlopko for the C++ part

**Comment by lberki** [comment]
@mhlopko, never mind -- I misread the code, there isn't a lot of C++ here to review

**Comment by allevato** [comment]
@keith Can you elaborate on what you need here (I'm not sure what "pre-processing the headers" means). I would expect that many pre-compiled libraries would be providing their own modulemap so the `module_map` attribute would be more useful here (which, to be fair, we currently also don't support) instead of `module_name`, but I may be missing something about your use case.

**Comment by keith** [comment]
@allevato supporting `module_map` for that would solve the case we care about as well. By pre-processing the headers I meant that in the case where you have a pre-compiled library A, that includes another pre-compiled library B, the imports in the existing headers in A will likely use the expected module name, which could differ if you check in the library somewhere on disk and bazel comes up with a name based on the path.

**Comment by acecilia** [comment]
Hi:

@ob, related to your comment in https://github.com/bazelbuild/bazel/pull/5905#issuecomment-415111122, I tried also to consume an `objc_library` from a `objc_library` as follows:

```
load("@rules_cc//cc:defs.bzl", "objc_library")
load("@build_bazel_rules_apple//apple:ios.bzl", "ios_unit_test")

objc_library(
    name = "ObjcModule",
    srcs = ["Sources/ObjcModule.m"],
    hdrs = ["Sources/ObjcModule.h"],
    module_name = "ObjcModule",
)

objc_library(
    name = "ObjcModuleTestsLib",
    srcs = ["ObjcTests/SomeCodeTests.m"],
    deps = [":ObjcModule"],
)

ios_unit_test(
    name = "ObjcModuleTests",
    minimum_os_version = "8.0",
    deps = [":ObjcModuleTestsLib"],
)
```

The content of `ObjcTests/SomeCodeTests.m` is:

```
#import <XCTest/XCTest.h>
#import "ObjcModule/ObjcModule.h"

@interface ObjcModuleTests: XCTestCase
@end

@implementation ObjcModuleTests
- (void)test {
  XCTAssertEqual(text, @"Hello, World!");
}
@end
```

When running `bazel build //Libraries/ObjcModule:ObjcModuleTestsLib`, in line `#import "ObjcModule/ObjcModule.h"` I am getting the error `Libraries/ObjcModule/ObjcTests/SomeCodeTests.m:2:9: fatal error: 'ObjcModule/ObjcModule.h' file not found`. The only way I can make it work is by using `#import "Libraries/ObjcModule/Sources/ObjcModule.h"` instead.

I expected `#import "ObjcModule/ObjcModule.h"` to work when doing `module_name = "ObjcModule"`. Any idea why it doesn't? Any workaround?

Thanks!

**Comment by ob** [comment]
@acecilia unfortunately, you need more to make that work. I had to implement my own headermaps and pass them around using `-I` and `-iquote`. I ended up writing the code in C and wrapping it in starlark rules. Once objc_library() is pulled out of bazel I can try to contribute back the code.

**Comment by acecilia** [comment]
Thanks for your answer @ob! I also found a workaround, find it here: https://github.com/bazelbuild/bazel/issues/9461#issuecomment-537270226. And there is even a bazel repository providing a similar workaround ready to consume here: https://github.com/bazelbuild/bazel/issues/9461#issuecomment-537255782

**Pull request closed without merging**
