### PR TITLE
Use effective `StarlarkSemantics` with `cquery --output=starlark`

### PR DESCRIPTION
**Pull request by fmeum**
Previously, `BuildLanguageOption`s had no effect as the default semantics were used.

Work towards #17864

### CODE REVIEW

**Comment by fmeum** [comment]
@gregestren This is meant to prepare for https://github.com/bazelbuild/bazel/issues/17864#issuecomment-1688212436, which will provide a way to align `{a,c}query` output with that of `str(Label(...))` in Starlark.

CC @Wyverald

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
I added a test.

**Review by Wyverald — APPROVED** [review]
nice fix!

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Pull request closed without merging**
