### PR TITLE
Extract MountMap to a top-level class.

### PR DESCRIPTION
**Pull request by ulfjack**
Extract MountMap to a top-level class for sharing with the upcoming OSX sandbox.

Change-Id: I26cf10accaa6f62014c65f41637a36fbeab42b0a

### CODE REVIEW

**Comment by damienmg** [comment]
gerrit? ;)

**Comment by ulfjack** [comment]
We can accept pull requests here, and the change is simple enough.

**Comment by damienmg** [comment]
Right, I just saw more than 10 java lines :)

LGTM :)

**Comment by damienmg** [comment]
Merged

**Pull request closed without merging**
