### PR TITLE
Remove use of -undefined dynamic_lookup on darwin

### PR DESCRIPTION
**Pull request by keith**
This flag ignores undefined symbols at link time and forces them to be looked up dynamically. This is incompatible with the newer fixup chains macho format and theoretically shouldn't be necessary assuming your dependencies are well defined.

Fixes https://github.com/bazelbuild/bazel/issues/16413

### CODE REVIEW

**Comment by keith** [comment]
The second commit here shows a potential issue making this change could introduce, that library had incorrect dependencies but just happened to work at runtime because the library it needed must have been transitively loaded anyways. I also found this https://github.com/bazelbuild/bazel/issues/7607

**Comment by keith** [comment]
@oquenchil can you take a look?

**Review by oquenchil — APPROVED** [review]

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by keith** [comment]
for future reference there were some previous additions / removals of this too:

https://github.com/bazelbuild/bazel/issues/67
https://github.com/bazelbuild/bazel/commit/efd5d316c67173d6efe4267408b4f32db56c3bce
https://github.com/bazelbuild/bazel//commit/314cf1f9e4b332955c4800b2451db4e926c3e092
https://github.com/bazelbuild/bazel//commit/dc176903da9e84680a1cb2d19b469562e76e570f

**Comment by meteorcloudy** [comment]
This looks like a breaking change:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2819#0185a94e-46ce-4a78-aa61-e658115dac01
```
Undefined symbols for architecture x86_64:
  "_google_protobuf_MessageOptions_msg_init", referenced from:
      _upb_test_my_option_ext in proto3_test.upb.o
ld: symbol(s) not found for architecture x86_64
```
Detected by culprit finder: https://buildkite.com/bazel/culprit-finder/builds/4178#0185a952-34c1-46ae-99c8-9b40d67508ec

**Comment by meteorcloudy** [comment]
Since this is likely a breaking change, I'll remove the "potential release blocker" label.

**Comment by garymm** [comment]
@keith Is googletest doing something wrong?
It seems this change breaks using `gtest_main`.
Before this change:

```sh
USE_BAZEL_VERSION=7.0.0-pre.20221212.2 bazelisk test --java_runtime_version=remotejdk_11 --copt='-std=c++14' //googletest/test:gtest_all_test
```

Succeeds

After this change:

```sh
USE_BAZEL_VERSION=7.0.0-pre.20230118.2 bazelisk test --java_runtime_version=remotejdk_11 --copt='-std=c++14' //googletest/test:gtest_all_test

ERROR: /Users/garymm/src/google/googletest/BUILD.bazel:152:11: Linking libgtest_main.dylib failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //:gtest_main) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin_arm64-fastbuild/bin/libgtest_main.dylib-2.params

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Undefined symbols for architecture arm64:
  "testing::InitGoogleMock(int*, char**)", referenced from:
      _main in gmock_main.pic.o
  "testing::UnitTest::GetInstance()", referenced from:
      RUN_ALL_TESTS() in gmock_main.pic.o
  "testing::UnitTest::Run()", referenced from:
      RUN_ALL_TESTS() in gmock_main.pic.o
ld: symbol(s) not found for architecture arm64
```

**Comment by keith** [comment]
@garymm thanks I have a fix for this in https://github.com/bazelbuild/bazel/pull/16619 but also submitted https://github.com/bazelbuild/bazel/pull/17624 with just that so it might be merged sooner. In the meantime you can workaround by using the full Xcode toolchain, or you can pass `--features=-supports_dynamic_linker` on macOS

**Pull request closed without merging**
