### PR TITLE
Add //third_party/py/six to embedded_tools.

### PR DESCRIPTION
**Pull request by spxtr**
https://github.com/bazelbuild/bazel/pull/3363#issuecomment-314774384

### CODE REVIEW

**Comment by spxtr** [comment]
@damienmg @aj-michael it looks like the tests are just broken. In [this run](http://ci.bazel.io/job/PR/job/bazel-tests/52/) I reverted my commit so it was just testing master, but the job still failed.

**Comment by aj-michael** [comment]
@spxtr the run you linked shows four different tests failing. The tests in your other pull request were broken for legitimate reasons.

**Comment by spxtr** [comment]
Right, sorry. In [run 50](http://ci.bazel.io/job/PR/job/bazel-tests/50/) which was this PR, several tests failed. I reverted the commit and did it again, but 52 also failed.

**Comment by aj-michael** [comment]
Ah, I misunderstood. I agree, those failures look entirely unrelated. My first guess is that the CI server is out of disk space so it is failing to extract a zip file? @damienmg will likely know more.

This PR looks good to me, I'll let @damienmg merge it after we figure out whats up with CI.

**Comment by spxtr** [comment]
Sounds good. Thanks!

**Comment by damienmg** [comment]
This cannot be easily imported as such, third_party and non third_party code must be in separate change, sorry for that :/

**Comment by spxtr** [comment]
Do you mean that #3378 needs to go in separately from this one?

**Comment by damienmg** [comment]
Thanks PR #3378 has been merged, can you rebase this one?

**Comment by spxtr** [comment]
Done.

**Comment by damienmg** [comment]
retest this please

**Comment by spxtr** [comment]
retest this please

**Pull request closed without merging**
