### PR TITLE
Only download JDK repositories that are needed

### PR DESCRIPTION
**Pull request by comius**
The problem were `select`s that pointed to remote repos, which causes all the remote repos to be downloaded. Inserting an alias in between prevents this download.

Fixes https://github.com/bazelbuild/bazel/issues/12778

### CODE REVIEW

**Comment by Wyverald** [comment]
Sorry for randomly jumping in, but this seems rather surprising to me. I would've expected that with `select("true":"@A//:thing", "false":"@B//:thing")`, the repo B should not be fetched at all. Is there a valid reason why B is fetched in this case? If not, can we fix this spurious loading instead?

**Comment by comius** [comment]
> Sorry for randomly jumping in, but this seems rather surprising to me. I would've expected that with `select("true":"@A//:thing", "false":"@B//:thing")`, the repo B should not be fetched at all. Is there a valid reason why B is fetched in this case? If not, can we fix this spurious loading instead?

I can confirm this is the behaviour, but I don't know the reason.
@katre ?

**Comment by katre** [comment]
I believe this behavior is due to how a target is loaded: all of the labels referenced in a target need to be loaded (unless the attribute is declared as LABEL_NODEP).

An example of why this is needed is that in the example you gave, if `@B//:thing` didn't exist, the error would never be reported.

I may be mistaken, however, so I'll tag in @gregestren to see if that matches his understanding.

**Comment by Wyverald** [comment]
> An example of why this is needed is that in the example you gave, if `@B//:thing` didn't exist, the error would never be reported.

I'd argue that's WAI. In fact, for part of the external deps overhaul, I was banking on the fact that B is allowed to not exist in this case -- imagine that B is a repo produced by a Windows executable only, and is completely missing when the user is running on other platforms.

**Pull request closed without merging**
