### PR TITLE
Docs: add Cosmodev to commercial offerings in remote-execution.md

### PR DESCRIPTION
**Pull request by dymart**

### CODE REVIEW

**Comment by hicksjoseph** [comment]
I usually request a quick demo of the functionality before I recommend that we add a vendor to the list of commercial Remote Execution offerings. I will reach out to them to schedule a demo for January.

**Comment by aiuto** [comment]
+Danielle Roberts <daroberts@google.com>

On Thu, Dec 17, 2020 at 10:00 PM Joe Hicks <notifications@github.com> wrote:

> I usually request a quick demo of the functionality before I recommend
> that we add a vendor to the list of commercial Remote Execution offerings.
> I will reach out to them to schedule a demo for January.
>
That makes sense. We also have an action item to move the list of vendors
to https://bazel.build/ rather than being embedded in the docs. (
https://github.com/bazelbuild/bazel-website/issues/262)
We should to the restructuring and then recreate this PR to the
bazlebuild/bazel-website repository.

**Comment by hicksjoseph** [comment]
I have proposed a time to receive a demo from Cosmodev in mid January. I
can invite whoever is interested closer to the date.

Thanks,

Joe

**Comment by aiuto** [comment]
Also, let's resolve https://github.com/bazelbuild/bazel-website/issues/262  and then add the name there, so we can drop the list here.

**Comment by hicksjoseph** [comment]
I met with cosmodev.tech and think that they would initially be a better fit as a Bazel Expert. I will close this PR and work with them directly on becoming a Bazel Expert.

**Pull request closed without merging**
