### PR TITLE
Don't suggest using bazel clean --async when it's unsupported

### LINKED ISSUE #4176: bazel clean: don't suggest to use --async, if it is not supported on current platform
On Bazel@HEAD, on Windows:

```
  $ bazel clean
  INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
```

Now trying to pass `--async`, as suggested:

```
  $ bazel clean --async
  INFO: --async cannot be used on non-Linux platforms, falling back to synchronous clean
  INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
```

### PR DESCRIPTION
**Pull request by akira-baruah**
Fixes #4176 (https://github.com/bazelbuild/bazel/issues/4176).

Hasn't been tested on unsupported platforms (i.e. Windows) yet.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
There were some recent changes to CleanCommand, so just to sanity check, @cvcal do these changes look okay to you?

**Comment by cvcal** [comment]
Ah, yes, I didn't notice that the --sync suggestion was unconditional, sorry about that. This fix looks good to me :)

**Comment by cvcal** [comment]
I went to import this change, but then noticed the "hasn't been tested" bit again. Can you confirm that you have tested this? And if you want to prevent us from accidentally breaking this in the future, a test would be helpful :)

**Comment by cvcal** [comment]
@akira-baruah Quick ping on tests. I don't have a windows machine on which to test this patch, I'd rather not push this through with the "hasn't been tested" tag

**Comment by akira-baruah** [comment]
@cvcal sorry for the delay! I've rebased this branch onto master and added some tests for the `clean --async` suggestion text.

I don't have a working Windows build for this repo yet. I think I can get that set up in the next day or two. Is it possible to run these tests on a Windows build through Jenkins?

**Comment by cvcal** [comment]
If there are tests, our automated testing will run them on windows, thanks! Going to attempt to push this through now.

**Comment by akira-baruah** [comment]
Awesome - thanks @cvcal! I was also able to build and run the test manually on Windows:

`bazel test src/test/java/com/google/devtools/build/lib:runtime-tests` fails at 2e182ed971bc0ccc2269d127e1cc023a0efc0e5b (test without fix) and succeeds at 5520ac0a8d85a0936dc93bb43c09569d758a93a3 (test with fix).

**Comment by akira-baruah** [comment]
I'd also like to confirm the functionality of the command manually, but I'm running into a run time error on Windows (unrelated to this change).

My repro steps were:
- [Install bazel using Chocolatey](https://docs.bazel.build/versions/master/install-windows.html#install-using-chocolatey) on Powershell
- Clone this repo
- Checkout `master`
- Run `bazel build //src:bazel.exe`
- Run `.\bazel-bin\src\bazel.exe version`

The error I see:
```
...
Server crashed during startup. Now printing 'c:\users\akira\appdata\local\temp\_bazel_akira\gdtpmzpe/server/jvm.out':
java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.google.devtools.build.lib.windows.runfiles.WindowsRunfiles.ensureRunfilesParsed(WindowsRunfiles.java:47)
        at com.google.devtools.build.lib.windows.runfiles.WindowsRunfiles.getRunfile(WindowsRunfiles.java:37)
        at com.google.devtools.build.lib.windows.jni.WindowsJniLoader.loadFromRunfileOrThrow(WindowsJniLoader.java:48)
        at com.google.devtools.build.lib.windows.jni.WindowsJniLoader.loadJni(WindowsJniLoader.java:33)
        at com.google.devtools.build.lib.windows.jni.WindowsProcesses.getpid(WindowsProcesses.java:213)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:45)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1048)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1037)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1030)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:572)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:60)
ERROR: <unknown> crash in async thread:
java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at com.google.devtools.build.lib.windows.runfiles.WindowsRunfiles.ensureRunfilesParsed(WindowsRunfiles.java:47)
        at com.google.devtools.build.lib.windows.runfiles.WindowsRunfiles.getRunfile(WindowsRunfiles.java:37)
        at com.google.devtools.build.lib.windows.jni.WindowsJniLoader.loadFromRunfileOrThrow(WindowsJniLoader.java:48)
        at com.google.devtools.build.lib.windows.jni.WindowsJniLoader.loadJni(WindowsJniLoader.java:33)
        at com.google.devtools.build.lib.windows.jni.WindowsProcesses.getpid(WindowsProcesses.java:213)
        at com.google.devtools.build.lib.util.ProcessUtils.getpid(ProcessUtils.java:45)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.getPidUsingJNI(BlazeRuntime.java:1048)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeForceJNIByGettingPid(BlazeRuntime.java:1037)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.maybeGetPidString(BlazeRuntime.java:1030)
        at com.google.devtools.build.lib.runtime.BlazeRuntime.main(BlazeRuntime.java:572)
        at com.google.devtools.build.lib.bazel.BazelMain.main(BazelMain.java:60)
```

The problem seems to stem from a failure to [retrieve the env var `RUNFILES_MANIFEST_FILE`](https://github.com/bazelbuild/bazel/blob/259c9e8014ad960985c0ed99db2a879cdd2ac301/src/main/java/com/google/devtools/build/lib/windows/runfiles/WindowsRunfiles.java#L47).

Any guidance here would be gladly appreciated!

**Comment by cvcal** [comment]
Thanks @akira-baruah, this looks like it's unrelated to the change, is it in Bazel-at-head in general? If so, let's file an issue for visiblity :)

**Comment by akira-baruah** [comment]
Yeah, good call :) I'll poke around the existing issues some more and file a new one if I can't find a fix.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
