### PR TITLE
Fix a bug that `--remote_download_toplevel` doesn't download unused_inputs_list

### LINKED ISSUE #11732: `--remote_download_toplevel` doesn't download unused_inputs_list
### Description of the problem / feature request:

A build action created in Starlark with `ctx.actions.run` with `unused_inputs_list` set fails to build with remote cache enabled and `--remote_download_toplevel` set.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

defs.bzl

```bazel
def _test_rule_impl(ctx):
    inputs = ctx.files.inputs
    output = ctx.outputs.out
    unused_inputs_list = ctx.actions.declare_file(ctx.label.name + ".unused")
    arguments = []
    arguments += [output.path]
    arguments += [unused_inputs_list.path]
    for input in inputs:
        arguments += [input.path]
    ctx.actions.run(
        inputs = inputs,
        outputs = [output, unused_inputs_list],
        arguments = arguments,
        executable = ctx.executable._executable,
        unused_inputs_list = unused_inputs_list,
    )

test_rule = rule(
    implementation = _test_rule_impl,
    attrs = {
        "inputs": attr.label_list(allow_files = True),
        "out": attr.output(),
        "_executable": attr.label(executable = True, cfg = "host", default = "//:exe"),
    },
)
```

BUILD

```bazel
load(":defs.bzl", "test_rule")

test_rule(
    name = "test_non_toplevel",
    inputs = ["1.txt", "2.txt"],
    out = "3.txt",
)

sh_binary(
    name = "exe",
    srcs = ["a.sh"],
)

genrule(
    name = "test",
    srcs = [":test_non_toplevel"],
    outs = ["4.txt"],
    cmd = "cat $< > $@",
)
```

a.sh

```shell
#!/bin/sh

output="$1"
shift
unused="$1"
shift
inp0="$1"
shift

cat "$inp0" > "$output"
echo "$1" > "$unused"
```

Run:

```shell
$ touch 1.txt 2.txt # input files
$ CACHEDIR=$(mktemp -d)
$ bazel build --disk_cache=$CACHEDIR --remote_download_toplevel :test
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 31d03dfc-29ed-4660-a942-7a0e1e0e5b18
INFO: Analyzed target //:test (17 packages loaded, 54 targets configured).
INFO: Found 1 target...
Target //:test up-to-date:
  bazel-bin/4.txt
INFO: Elapsed time: 3.124s, Critical Path: 0.08s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed successfully, 6 total actions
$ bazel clean
$ bazel build --disk_cache=$CACHEDIR --remote_download_toplevel :test
INFO: Invocation ID: 578f6a17-0902-4073-95ca-772c40ec58a2
INFO: Analyzed target //:test (17 packages loaded, 54 targets configured).
INFO: Found 1 target...
ERROR: /home/riatre/unused_inputs_list_remote_download_toplevel/BUILD:3:10: Action 3.txt failed: Action did not create expected output file listing unused inputs: bazel-out/k8-fastbuild/bin/test_non_toplevel.unused: /home/riatre/.cache/bazel/_bazel_riatre/<...redacted...>/execroot/__main__/bazel-out/k8-fastbuild/bin/test_non_toplevel.unused (No such file or directory)
Target //:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.487s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

### What operating system are you running Bazel on?

Linux

### What's the output of `bazel info release`?

release 3.3.1

###  Have you found anything relevant by searching the web?

I found an issue tracking a lot of similar issues: https://github.com/bazelbuild/bazel/issues/6862, but I don't think this particular case has been covered before.

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

### PR DESCRIPTION
**Pull request by coeuvre**
When enabling remote caching with flag `--remote_download_toplevel`, Bazel only [downloads output directory metadata, stdout and stderr as well as the contents of `inMemoryOutputPath` if specified](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/remote/RemoteCache.java#L522). However, file specified by`unused_inputs_list` of [`ctx.actions.run`](https://docs.bazel.build/versions/master/skylark/lib/actions.html#run) isn't downloaded in this case but is [required](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/analysis/actions/StarlarkAction.java#L195) after starlark action execution.

This PR specify `inMemoryOutputPath` to the `unused_inputs_list` file by inserting `ExecutionRequirements.REMOTE_EXECUTION_INLINE_OUTPUTS` to `SpawnAction`'s `executionInfo`.

Fixes #11732.

### CODE REVIEW

**Comment by ulfjack** [comment]
This looks reasonable to me.

**Comment by philwo** [comment]
@coeuvre Lots of tests are failing for this PR - any idea what's up with that?

**Comment by coeuvre** [comment]
Get tests passed!

Reverted last commit in favor of a new solution where we [always](https://github.com/bazelbuild/bazel/pull/11763/commits/9395a5c27f0ca66e5b83405730d3bb2521a4907d#diff-b604907e2f234f2839600aabf9dc4498R268) download `unused_inputs_list` file if it is presented.

This also remove the only usage of option [`--experimental_inmemory_unused_inputs_list`](https://github.com/bazelbuild/bazel/blob/d03c12706a1dd7c022d9d66c343ec5d9ce6dbe16/src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java#L790) which suggests to remove it after this PR merged.

**Comment by philwo** [comment]
> This also remove the only usage of option [`--experimental_inmemory_unused_inputs_list`](https://github.com/bazelbuild/bazel/blob/d03c12706a1dd7c022d9d66c343ec5d9ce6dbe16/src/main/java/com/google/devtools/build/lib/analysis/config/CoreOptions.java#L790) which suggests to remove it after this PR merged.

I think this flag might be manually set by some users inside Google. 😬

I guess this change might still be fine though - let's just see if the tests internally pass, too. I'll also add a colleague as a reviewer on the merge commit who might help us out whether this is safe.

**Pull request closed without merging**
