### PR TITLE
Remove ancient PY2 warning messages from python_stub_template.txt

### PR DESCRIPTION
**Pull request by jvolkman**
These messages are rarely helpful and often misleading. The associated TODO (#6443) was closed years ago.

### CODE REVIEW

**Comment by jvolkman** [comment]
Turns out there was a test case. I've removed that as well and the tests are passing now.

**Comment by groodt** [comment]
Should this be removed as well? https://github.com/bazelbuild/bazel/blob/c3d43ec123cf9a0d214a950eca3e15637b3fd325/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L181

**Comment by jvolkman** [comment]
> Should this be removed as well? https://github.com/bazelbuild/bazel/blob/c3d43ec123cf9a0d214a950eca3e15637b3fd325/src/main/java/com/google/devtools/build/lib/bazel/rules/python/BazelPythonSemantics.java#L181

Good catch.

**Review by groodt — APPROVED** [review]
LGTM

**Comment by comius** [comment]
cc @rickeylev can you take a look at this?

**Review by comius — APPROVED** [review]

**Pull request closed without merging**
