### PR TITLE
Starlark mix max key callback param

### PR DESCRIPTION
**Pull request by Tomsons**
Handles request [#15022](https://github.com/bazelbuild/bazel/issues/15022)

Used `sorted` builtin mechanism to provide to key callback parameter

### CODE REVIEW

**Comment by tetromino** [comment]
You are proposing an O(n log n) time and O(n) memory solution for an O(n) time and O(1) memory problem.

**Comment by Tomsons** [comment]
Ok, great thank you for the feedback. But why do you close instead of requesting changes and iterate over it until the actual implementation fulfills your request?

**Comment by tetromino** [comment]
I apologize for misjudging the situation; I will reopen the PR.

**Review by tetromino — CHANGES_REQUESTED** [review]
Please don't call `sorted` in min/max: finding a maximum or minimum requires O(n) time, O(1) temp memory; `sorted` is O(n log n) time, O(n) temp memory.

Note that `key` may be heavy and could have side effects, so it should be called at most once for each element - please add a test verifying that fact.

**Comment by Tomsons** [comment]
No worries, I'll push something new in the coming days

**Comment by Tomsons** [comment]
@tetromino, I've just pushed something new with a `SortKeyHelper.java` class, can you check if this kind of implementation could suit. I'll do some extensive testing later on

**Pull request closed without merging**
