### PR TITLE
Stale workflow - process updates

### PR DESCRIPTION
**Pull request by keertk**

### CODE REVIEW

**Comment by keertk** [comment]
@sventiffe @radvani13 @oquenchil @Wyverald @alexeagle @keith @brentleyjones 

Hi all, we've made some updates to the stale workflow. Specifically, 
- We're going to start looking at all issues/PRs that are older than 3 years and close them out 14 days after a notification. Once this is complete, we'll move to more recent issues (2 years, 1 year, etc.) -- we're doing this in phases to avoid spamming and important notifications getting lost.
- If authors feel that a particular issue/PR is still relevant, they can ping the triage team (`@bazelbuild/triage`) who will then reopen and/or tag the appropriate team lead to decide how to proceed - will this be worked on, is it in fact "not stale", etc.
- All P0 and P1 labeled issues will be excluded from the stale workflow. 

Please let us know if you have any comments or suggestions for improvement. We'll let the wider community know once we've finalized this process.

Thank you for your patience and support with this effort.

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by alexeagle** [comment]
I think this PR mistakes what was the problem: @sgowroji was marking issues stale (manually I guess) and then closing them *at the same time*, for example

https://github.com/bazelbuild/bazel/issues/9429#issuecomment-1427694554

The stale.yml file gives reporters a chance to comment, both before and after this PR. I do agree with the changes here, but you should also make sure the team knows that the robot does this process, not humans.

**Comment by alexeagle** [comment]
Also there's another problem not addressed in this PR.

After all those issues were closed, a few were re-opened because someone complained and got your attention. However there are probably many of them which are still valid issues representing bugs in Bazel, either because no one noticed when it was closed, they did notice but figured it's just "Bazel team doesn't care" so they didn't try to complain, or they *did* complain and no one noticed the comment so it stayed closed.

I think it would be nice to go back through the issues which were manually closed (not using the stale bot process) and evaluate what to do (maybe re-open them and let the stale bot do its thing)

For example @keith spent half a day filing issues which were all closed without anyone even looking at them.

**Comment by meteorcloudy** [comment]
@alexeagle Yes, the team is now in sync that we'll use the stale bot to ping and close inactive issues and PRs, we won't close the issue without any notification first. There is a blog post on that going out very soon.

For the manually closed inacitve issues, I believe we did reopen all issues that got a reply. @keertk and @sgowroji can confirm that and perhaps provide the numbers of how many issues got closed and reopened.

**Review by meteorcloudy — APPROVED** [review]

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
