### PR TITLE
Improve unavailable Xcode message for Bzlmod

### PR DESCRIPTION
**Pull request by brentleyjones**
Context: https://bazelbuild.slack.com/archives/C014RARENH0/p1709547684815279?thread_ts=1709324251.252319&cid=C014RARENH0

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by brentleyjones** [comment]
(This will have merge conflicts. I'll be able to submit a manual PR.)

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.2.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!

**Pull request closed without merging**
