### PR TITLE
Fix missing singlejar on arm and windows

### LINKED ISSUE #3988: [Windows] build failed with: "must produce a single file"
### Description of the problem / feature request / question:
     I am building a project in windows, it failed with:
    /c/msys64/tmp/_bazel_usera/9l56y845/external/bazel_tools/tools/jdk/BUILD:187:17: in singlejar attribute of java_toolchain rule @bazel_tools//tools/jdk:toolchain: '@bazel_tools//tools/jdk:singlejar' must produce a single file.

while I can successfully build it in a linux VM, 

### Environment info
* Operating System: Windows 7 Professional Service Pack 1

* Bazel version (output of `bazel info release`): 

Build label: 0.7.0- (@non-git)
Build target: bazel-out/msvc_x64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Oct 30 02:52:43 2017 (1509331963)
Build timestamp: 1509331963
Build timestamp as int: 1509331963

* Source code are downloaded from bazel release 0.7 dist.zip file: [here](https://github.com/bazelbuild/bazel/releases/download/0.7.0/bazel-0.7.0-dist.zip)

### PR DESCRIPTION
**Pull request by pterjan**
This was broken by the jar being renamed from SingleJar_deploy.jar to bazel-singlejar_deploy.jar in commit 6705b508fe069147c853ca9669363342f3527689 (Fixes #3988)

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
@philwo @ulfjack Does this look correct?

**Comment by ulfjack** [comment]
Yeah, looks good.

**Comment by laszlocsomor** [comment]
Thanks for confirming! I'll import this.

**Pull request closed without merging**
