### PR TITLE
Flip --incompatible_load_proto_rules_from_bzl

### LINKED ISSUE #8922: incompatible_load_proto_rules_from_bzl: load the Protobuf rules from @rules_proto
Flag: `--incompatible_load_proto_rules_from_bzl`
Available since: 0.29
Will be flipped in: TBD
Tracking issue: #8891

`proto_library` and `proto_lang_toolchain` have to be loaded from [@rules_proto](https://github.com/bazelbuild/rules_proto).

For example, if you are using`proto_library`, add the following load statement to your BUILD/bzl file.
```python
load("@rules_proto//proto:defs.bzl", "proto_library")
```

You can use the following buildifier command to automate the changes to your BUILD/bzl files:
```
buildifier --lint=fix --warnings=native-proto <path/to/BUILD>
```

You will have to add `proto_library` to your WORKSPACE file as well:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_proto",
    sha256 = "602e7161d9195e50246177e7c55b2f39950a9cf7366f74ed5f22fd45750cd208",
    strip_prefix = "rules_proto-97d8af4dc474595af3900dd85cb3a29ad28cc313",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
        "https://github.com/bazelbuild/rules_proto/archive/97d8af4dc474595af3900dd85cb3a29ad28cc313.tar.gz",
    ],
)
load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()
```

### PR DESCRIPTION
**Pull request by Yannic**
DO NOT SUBMIT until Bazel 0.29 was cut.

RELNOTES: The flag --incompatible_load_proto_rules_from_bzl from_bzl has been flipped.

Fixes #8922

### CODE REVIEW

**Comment by lberki** [comment]
Huh, this is scary (just like all the other "force load rule from .bzl file" changes). I'd love to know what downstream projects this breaks, but for some reason, BuildKite is not telling :(

**Comment by Yannic** [comment]
I think downstream testing only works for brances directly in the Bazel repo https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md.
I expect that this change currently breaks most, if not all, downstream projects :(.

**Comment by lberki** [comment]
...but the flag is already available at Bazel HEAD. Actually, I think I know now: our incompatible change testing pipeline only considers flags that are released (which this flag is not)

Alas, yes, it will break most of the downstream projects. I expect the same for the Java and C++ versions, too. I don't have a good plan about tackling that...

**Comment by meisterT** [comment]
What's the state of this PR?

**Comment by Yannic** [comment]
The state of this is "Won't flip this flag for Bazel 4.0" https://docs.google.com/spreadsheets/d/1hahSlNA9E-SXZckoVWnNkE2jwbX6MZpjTjgsfKSmAyk/edit?disco=AAAAJtxFoNo

I'll close this for now and send a new one once the flag is ready to flip.

**Pull request closed without merging**
