### PR TITLE
Fix Java tests to use Java toolchain resolution.

### PR DESCRIPTION
**Pull request by comius**
The flag is flipped for tests, old configuration options `javabase` and `java_toolchain` are marked deprecated. All the tests are fixed to execute using new toolchain resolution.

Changed `local_java_repository` to generate `java_runtime` with `java_home` parameter set (instead of srcs). This behaves better, because `java_stub_template.txt` then does not need runfiles to execute produced `deploy.jar`. Kept the same version with `srcs` in the `jdk.WORKSPACE`.

Fixes https://github.com/bazelbuild/bazel/issues/4592.
Flips https://github.com/bazelbuild/bazel/issues/7849.

### CODE REVIEW

**Review by katre — COMMENTED** [review]
With all of this code deleted, can users actually unset the flag? If someone needs to do "bazel build --noincompatible_use_toolchain_resolution_for_java_rules", will that work, or will it fail?

**Comment by comius** [comment]
> With all of this code deleted, can users actually unset the flag? If someone needs to do "bazel build --noincompatible_use_toolchain_resolution_for_java_rules", will that work, or will it fail?

I will fail, I should remove the flag as well.

**Comment by katre** [comment]
That's the opposite of what I would prefer: we should only flip the flag in this release, wait a bazel release, and **then** remove the code.

**Comment by comius** [comment]
> That's the opposite of what I would prefer: we should only flip the flag in this release, wait a bazel release, and **then** remove the code.

Ok. I reverted the removal and kept everything else.

**Review by katre — APPROVED** [review]
I am very excited to see this!

**Comment by comius** [comment]
I will delay flipping the flag a bit, because RBE would potentially break on downstream projects. I need to prepare couple of fixes in both bazel and bazel_toolchains.

**Pull request closed without merging**
