### PR TITLE
[2/3] Bump grpc from 1.47.0 to 1.48.1

### PR DESCRIPTION
**Pull request by davido**
Previous PR: https://github.com/bazelbuild/bazel/pull/18240

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@davido Please rebase so that we can merge this one!

**Comment by davido** [comment]
@meteorcloudy 

> Please rebase so that we can merge this one!

Done.

**Review by meteorcloudy — APPROVED** [review]

**Comment by Pavank1992** [comment]
HI @davido, As the PR is approved for merge, could you please squash the commits to one so we can proceed? Thanks!

**Comment by davido** [comment]
@Pavank1992 Squashed, Done.

**Comment by Pavank1992** [comment]
Merged at https://github.com/bazelbuild/bazel/commit/1a4da7f331c753c92e2c91efcad434dc29d10d43

**Pull request closed without merging**
