### PR TITLE
[6.3.0] Teach ijar about dynamic constants.

### PR DESCRIPTION
**Pull request by iancha1992**
Teach ijar about dynamic constants.

Fixes https://github.com/bazelbuild/bazel/issues/18360

Closes https://github.com/bazelbuild/bazel/pull/18406

Commit https://github.com/bazelbuild/bazel/commit/69d299165743613d303f19f47d8b3db4481d58b5

PiperOrigin-RevId: 540750474
Change-Id: If61bcaaf018b92a1bf87335c1075c28294932b1f

### CODE REVIEW

**Comment by cushon** [comment]
@iancha1992 this PR was already imported: https://github.com/bazelbuild/bazel/commit/69d299165743613d303f19f47d8b3db4481d58b5

**Comment by iancha1992** [comment]
@benjaminp our team is trying to cherry-pick this for release-6.3.0. However, looks like in order to merge your work, we have to have you sign the Contributor License Agreement (CLA), which is a one-time process, which only takes seconds. Please refer to this: https://github.com/bazelbuild/bazel/pull/18711/checks. Thank you

**Comment by benjaminp** [comment]
Somehow https://github.com/bazelbuild/bazel/commit/69d299165743613d303f19f47d8b3db4481d58b5 was imported/exported under my personal email rather than my work email, which is listed under a corporate CLA. Perhaps you can change the address of the commit in this PR? (See any of my other commits in this repository for it.)

**Comment by iancha1992** [comment]
Closing this PR because I just amended the commit's author email for CLA compliance

**Pull request closed without merging**
