### PR TITLE
Fix `SerializationTests` on M1 Macs

### LINKED ISSUE #17016: //src/test/java/com/google/devtools/build/lib/skyframe/serialization:SerializationTests failing with Bazel 6.0.0rc5 and Bazel@HEAD
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2783#01850f44-ca27-4f15-868b-e0e09da937e3

https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01850f44-ca27-4f15-868b-e0e09da937e3/src/test/java/com/google/devtools/build/lib/skyframe/serialization/SerializationTests/test.log
```
There was 1 failure:
1) stackOverflowTransformedIntoSerializationException(com.google.devtools.build.lib.skyframe.serialization.ArrayCodecTest)
java.lang.AssertionError: expected com.google.devtools.build.lib.skyframe.serialization.SerializationException to be thrown, but nothing was thrown
	at org.junit.Assert.assertThrows(Assert.java:1028)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at com.google.devtools.build.lib.skyframe.serialization.ArrayCodecTest.stackOverflowTransformedIntoSerializationException(ArrayCodecTest.java:52)

FAILURES!!!
Tests run: 115,  Failures: 1
```

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #17016

### CODE REVIEW

**Comment by fmeum** [comment]
@meteorcloudy The same fix as for #17017 works here as well. Can you review or does this need team-Core input?

**Comment by meteorcloudy** [comment]
Looks simple enough that I can review, thanks!! 😁

**Review by meteorcloudy — APPROVED** [review]

**Comment by haxorz** [comment]
Hi, this PR caused the test to sometimes fail on Linux machines, at least internally at Google.

The symptom was the JVM running out of stack space and segfaulting.

I have a fix in mind, but it may be best to just rewrite the test so the code-under-test can pretend it's observing a `StackOverflowError` rather than try to get it to observe one for real.

**Comment by meteorcloudy** [comment]
Thanks for the fix and sorry for the breakage, I'll make sure to cc the core team next time.

**Pull request closed without merging**
