### PR TITLE
remove harmful BlazeDirectories.getExecRoot()

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by hlopko** [comment]
Can you pls provide more context (github issue, or cl description) explaining why is it harmful? I honestly don't know why :)

**Comment by buchgr** [comment]
Yes I will. I just wanted to test CI. I forgot that github automatically requests reviews.

**Comment by hlopko** [comment]
Yeah this is happening to me way too often these days. I'm thinking whether we should just tell github to stop doing that.

**Comment by buchgr** [comment]
@hlopko you can create a draft PR. I always forgot to do that though :)

**Comment by hlopko** [comment]
Yeah draft PRs work, but I'm often times on the receiving end of pings :)

**Pull request closed without merging**
