### PR TITLE
Support build bazel on s390x platform

### PR DESCRIPTION
**Pull request by clyang82**
Signed-off-by: clyang82 <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by hlopko** [comment]
LGTM! Thanks!

**Comment by clyang82** [comment]
Why this PR was closed? Do we have the similar PR to support s390x? Thanks.

**Comment by hlopko** [comment]
It was closed because it was imported into master in https://github.com/bazelbuild/bazel/commit/21941fec589439d5476d2e3899b49917fdc06ea6 (that's how we accept PRs, we manually import them, we cannot just merge them because of technicalities).

**Comment by clyang82** [comment]
Thanks for your explanation.

**Comment by berrylaw** [comment]
Location

**Comment by clyang82** [comment]
@hlopko Can this PR be included into next release? I saw the latest `0.25.2` release does not have this PR. Thanks.

**Comment by hlopko** [comment]
Yup, this is in 0.26 (+ we announce release candidates on bazel-discuss@googlegroups.com so you can get it an test it - the latest RC https://releases.bazel.build/0.26.0/rc11/index.html).

**Comment by clyang82** [comment]
@hlopko Thanks for your information. I can build the `bazel` successfully in s390x platform.

**Pull request closed without merging**
