### PR TITLE
Remove the "discarding analysis cache" message

### PR DESCRIPTION
**Pull request by Utsav2**
It doesn't seem to be providing any value for a user, who generally doesn't even know what an analysis cache is.

### CODE REVIEW

**Comment by gregestren** [comment]
Hi Utsav,

I'm just coming back from two weeks offline, so just catching up on Github now. Thanks for writing this request.

There's indeed a cost to discarding that cache. In a worst case you can see builds take way longer than they should because of it. So I think it's still a good signal. And it can help users understand when optimizations are possible to speed up their builds.

Plus @serynth is doing work to make this discarding more efficient. The short story is today if you change practically any command-line flag, the whole build graph gets rebuilt. @serynth is trying to make that more efficient. So, e.g., when you change a C++ flag it doesn't discard Go targets. 

See, for example https://github.com/bazelbuild/bazel/issues/5579.

Also CC'ing @tomlu, who wrote the current message.

**Comment by tomlu** [comment]
Yeah I'm inclined to say we should close this as working-as-intended. It is my opinion that the more we can tell users about why a build took the time it did, the better.

**Comment by serynth** [comment]
Agreed. I'm open to suggestions of changing the text of the message if "discarding analysis cache" is unclear, but I concur with the others; it's a useful signal for anyone who wants to know why a build that should have been a simple incremental step took a long time, whether that's the user running the build or the people they bring their build output to for help.

**Comment by Globegitter** [comment]
@tomlu @serynth The only thing that I think would really help with this message if it was possible to display which flags caused the discarding of the analysis cache, as it is not always immediately obvious, especially know with this (great!) improvements coming.

**Comment by gregestren** [comment]
That sounds like an easy win to me. If we just started with something simple like:

1. If < n flags have changed, mention them explicitly
1. else say "lots of flags"

it's still not 100% precise but seems like a nice practical step up from the status quo.

@serynth - worth a new prioritized issue?

**Comment by serynth** [comment]
Sounds legit to me! :) #6548 opened!

**Pull request closed without merging**
