### PR TITLE
Update java_tools v13.9 / rules_java 7.12.0

### PR DESCRIPTION
**Pull request by iancha1992**
https://github.com/bazelbuild/java_tools/issues/92

### CODE REVIEW

**Comment by iancha1992** [comment]
@hvadehra could you please take a look at the presubmit errors? Thanks!

**Comment by hvadehra** [comment]
I'm afraid the failures look legit, checking.

**Comment by iancha1992** [comment]
@hvadehra 
Could you please take a look at the downstream failures below? Are these safe to ignore?: 

https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b839-4ad5-82a8-188bfbdf7f05
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b840-42c0-a69b-e4485b956434
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b848-49ee-8935-3a9736ff92a9
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b84b-4418-8134-eb3fa5519f06
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad1f-4d8a-a945-aae73f5d7f97
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad25-49d9-bbe6-dcc5ccb473b1
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad2a-4ccd-b5a5-0f8d1a0a25b1
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad2d-4def-9f93-b9db770d2a56
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad2f-4b3a-a280-aca707b010f8
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-ad31-40a1-8f89-5364818825d0
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b218-461c-9724-8a5392d92cc3
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b21a-4a15-ad3c-44a77abe475c
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b221-4516-9afb-f8e931b80973
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b224-48c4-ab8f-157e3f0565a8
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b651-4730-84b2-10057a2eb55d
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b655-4a52-9db7-9810e26e925f
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b65d-4683-b850-9835f4008603
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b661-4bb5-9391-8441418ceec1
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-bbc6-4066-a89a-ee95abbdcb57
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-bbca-4a8b-8006-16b3cdf5630a
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-bbd0-4f46-8761-20c88b393128
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-bbd3-438f-84b8-d8fa33d17781
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a496-47ad-a12a-1c84528137ed
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a49c-4e16-9420-001263504c4b
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a498-4e2f-b4e6-015c138e1a9f
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a49e-437a-854f-fbde101464be
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-bee8-472d-84b7-16634877ff6a
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-beea-4c83-99b9-579231e9f28e
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-beed-4e3a-b145-50f84cde547f
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-beef-42bb-9ee0-dfdcc9298856
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-c13e-4cd4-9f20-6e181ab6c63a
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-c141-4528-8a22-8b56f8a7a162
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-c146-469d-a019-56a1206a4dc9
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-c148-4e17-b5b1-7bcbd1da50db
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a8e8-43c0-ab35-a9ac69fe27d1
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a8ed-4c32-96b4-17ba1b5653c2
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a8f3-49c1-a25f-49d558dfd3e2
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-a8f7-4c79-a123-696b6df7c991
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b402-4c71-976c-69b52edf0307
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b406-467c-b2e1-41801da779c8
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b40c-4b66-965a-37d64cae3e0a
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-b410-4f4f-a255-c0487874ad27
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-771f-4c6e-8e3c-f492fab9d06d
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a95-1242-4c3b-ae20-07827768a2b6
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4148#01922a8a-772a-442f-92a8-f3991d6e0f78

**Comment by hvadehra** [comment]
I see the same failures in the scheduled build on master, so I think it's okay to proceed.

**Comment by iancha1992** [comment]
@hvadehra could you please take a look at the presubmits? Thanks!

**Comment by hvadehra** [comment]
I'm seeing this locally which seems relevant to the failures:

```
WARNING: The module extension @@rules_jvm_external+//:extensions.bzl%maven produced an invalid lockfile entry because it referenced @@[unknown repo '' requested from @@rules_jvm_external+]. Please report this issue to its maintainers.
```

cc @meteorcloudy @shs96c

**Comment by meteorcloudy** [comment]
What changed in rules_java?

**Comment by hvadehra** [comment]
Only relevant bit might be adding a dependency on stardoc which is pulling in rules_jvm_external

**Comment by meteorcloudy** [comment]
Can we turn that into a dev_dependency so that it doesn't propagate to dependent?

**Comment by hvadehra** [comment]
Thanks Yun! That seems to have done it. 

@iancha1992 A test also needed fixing, so made a fresh PR for this in https://github.com/bazelbuild/bazel/pull/23811

**Comment by iancha1992** [comment]
@hvadehra opened https://github.com/bazelbuild/bazel/pull/23811. Closing.

**Pull request closed without merging**
