### PR TITLE
Hardcode path to dirname on macOS

### PR DESCRIPTION
**Pull request by keith**
It seems that some repos have customized PATH so this isn't available.
This should fix that.

### CODE REVIEW

**Comment by keith** [comment]
https://github.com/bazelbuild/bazel/pull/10185#issuecomment-552968409

**Comment by keith** [comment]
cc @philwo can we run that failed test with this change? I don't really see how this is possible still since if users removed `/usr/bin` on macOS it seems like nothing would work.

**Comment by jmillikin-stripe** [comment]
@keith It looks like the failures are specific to rules_rust, which is running commands under `env -`.

**Comment by keith** [comment]
So they run with no `PATH` defined? I'm surprised that really works at all, but I guess this is a safe change then

**Comment by philwo** [comment]
I'm also surprised that this works at all. 🤷‍♂ Let's merge this.

**Comment by keith** [comment]
@philwo should we cherry pick this to fix the downstream tests in the rc?

**Comment by philwo** [comment]
@keith Yes, I will cherry-pick this into 1.2.0rc2.

**Comment by kastiglione** [comment]
Thanks @philwo

**Comment by thii** [comment]
FWIW, `rules_swift` also runs commands under `env -`.

**Comment by keith** [comment]
Let me know if you see issues with that and this change, it should be ok now

**Pull request closed without merging**
