### PR TITLE
Release 4.2.0 pr fe1e25b

### PR DESCRIPTION
**Pull request by larsrc-google**
Fixes multiple problems in dynamic execution: race condition (Issue #13149), handling of no usable strategies in one branch, running extra spawns locally.

Other commits were needed for cherrypicking.

Commits included:
039461c
b2231c5
1b9e2fb
5b95d91
c7d2616
060d596
fe1e25b

### CODE REVIEW

**Comment by katre** [comment]
The PR should be for the release-4.2.0-patches branch, not master. I think that's the cause of all the conflicts. Can you update that and make sure the tests are re-triggered?

**Comment by larsrc-google** [comment]
Bother. Let me retry. I thought I started off the 4.1.0 branch, not sure
why it got put on master. But even that would have been wrong.

-Lars

**Comment by katre** [comment]
It's a setting when you create the PR, not when you create the branch in your local repo.

**Comment by larsrc-google** [comment]
Of course now I managed to commit those patches straight to the
release-4.2.0-patches branch, that was not my intention. I would fix that,
but given my limited knowledge of Git, I would probably create a bigger
mess.

-Lars

**Comment by katre** [comment]
This is why I always work with a fork, and push to that except for rare cases.

The commits are in now, though, so we'll call it done. Thanks.

**Pull request closed without merging**
