### PR TITLE
Treat existence of managed directories as a part of repository dirtiness.

### LINKED ISSUE #8487: Managed directories should rerun repository rule if directory is deleted or timestamp changes
### Description of the problem / feature request:

rules_nodejs yarn_install & npm_install with managed directories can't handle deleted or manually regenerated node_modules folder. See https://github.com/bazelbuild/rules_nodejs/issues/802 for full description.

### Feature requests: what underlying problem are you trying to solve with this feature?

When using managed directories with yarn_install & npm_install in rules_nodejs 0.30.0+, when a user deletes the node_modules folder and runs bazel the repository rule should re-run (managed directory missing) which would recreate the node_modules folder from scratch.

If a user deletes the node_modules folder and recreates it manually using `yarn` or `npm install` then the repository rule should also re-run in that case as well (managed directory timestamp changed).

Currently after deleting node_modules, the only way to get back to a working build (besides modifying package.json or the lock file) is to run `bazel clean --expunge` to clear out the external repository and force the yarn_install or npm_install rule to rerun.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

case 1:
```
git clone https://github.com/gregmagolan/bazel_with_users_node_modules
cd bazel_with_users_node_modules
bazel version
bazel test ...
rm -rf ./node_modules
bazel test ...
```

case 2:
```
git clone https://github.com/gregmagolan/bazel_with_users_node_modules
cd bazel_with_users_node_modules
bazel version
bazel test ...
rm -rf ./node_modules
yarn install
bazel test ...
```

error in both cases:

```
greg@macbook bazel_with_users_node_modules (master) $ bazel test ...
ERROR: /private/var/tmp/_bazel_greg/8cb9ee79286b251e74f070e4ed053074/external/npm/typescript/BUILD.bazel:123:1: no such package '@npm//node_modules/typescript': BUILD file not found on package path and referenced by '@npm//typescript:typescript'
ERROR: Analysis of target '//:main' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.205s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

### What operating system are you running Bazel on?

OSX but issue is OS agnostic.

### What's the output of `bazel info release`?

release 0.26.0-homebrew

### PR DESCRIPTION
**Pull request by irengrig**
- If managed directory is declared for the external repository and does not exist (probably was deleted by user), make external repository dirty and re-fetch it.
- Add tests to demonstrate the added behavior to ManagedDirectoriesBlackBoxTest.
- Closes #8487.

### CODE REVIEW

**Comment by Globegitter** [comment]
@irengrig will this be cherry picked into the 0.26 and/or 0.27 release?

**Comment by irengrig** [comment]
Asked for cherry-pick into 0.27, as 0.26.1 is already out.

**Comment by dslomov** [comment]
@alexeagle do we absolutely need this cherry-picked for 0.27? Or is it ok for this fix to be in 0.28?

**Comment by laurentlb** [comment]
When you think a bug should be a release blocker, please add the [release blocker](https://github.com/bazelbuild/bazel/labels/release%20blocker) label (if you can) and cc the release manager (the person assigned to the release tracking issue).

The bug was filed 9 days ago. If it was critical, it would have been useful to mention it earlier.

**Comment by alexeagle** [comment]
We haven't been able to adopt the managed_directories feature, so this bug is a show-stopper for us. So it is quite important for us to have it fixed in next release, yes. Is it risky/difficult to cherry-pick?

reasoning:
Node developers are accustomed to problems with their third-party deps, and their instinctive reaction is to delete them and re-install. If you do this after Bazel has installed the deps, that deletion destroys the BUILD files we wrote, and then the re-install does not re-create them. The error doesn't give any hint that you need to `bazel clean --expunge` to fix the wrong state of the managed directory, so users get stuck. For now we don't recommend they use the feature because it's so hard to recover from this common situation. This means they still have to install all of their dependencies twice which makes Bazel seem much slower than existing tooling.

**Comment by dslomov** [comment]
@alexeagle what if we fix it in 0.28 (July) release?

**Comment by alexeagle** [comment]
Then it is another month before we can finish rolling out the feature, which makes me worry we'll miss other problems that require some dogfooder adoption.
In the meantime we have already switched our documentation and quickstart to managed directories so we have users getting really confused - have seen a few already and we anticipate more.

**Comment by laurentlb** [comment]
Related discussion around release frequency: https://groups.google.com/d/msg/bazel-dev/Ez4B3N_YEQY/PVzVJZL3BAAJ

**Comment by dslomov** [comment]
@laurentlb what do you think about cherry-picking this given @alexeagle comments?

**Pull request closed without merging**
