### PR TITLE
Change from some-user to user to reflect the hash value computed

### PR DESCRIPTION
**Pull request by rogerhu**
Changing to be consistent with the hash value computed.

```
echo "/home/user/src/my-project" | md5sum
7ffd56a6e4cb724ea575aba15733d113  -
```

### CODE REVIEW

**Comment by sgowroji** [comment]
@rogerhu Can you please sign the CLA with below email used. Thanks!
Screenshot 2022-11-28 at 9 29 18 AM

**Comment by rogerhu** [comment]
Same deal here:

image

**Review by gregestren — APPROVED** [review]

**Comment by rogerhu** [comment]
Is there someone on the Google end who can help me sort out the CLA issues? This doesn't feel like a user error to me!

**Comment by sgowroji** [comment]
Thanks for being patience. let me check and get back to you on this CLA error.

**Comment by sgowroji** [comment]
@gregestren Could you please confirm on importing this PR as it is approved. It is awaiting to merge.

**Pull request closed without merging**
