### PR TITLE
Update java_tools v13.2 / rules_java 7.3

### PR DESCRIPTION
**Pull request by keertk**

### CODE REVIEW

**Comment by keertk** [comment]
@fmeum do we need to update rules_java to 7.3 here?

**Comment by fmeum** [comment]
> @fmeum do we need to update rules_java to 7.3 here? 

Yes, that would be great!

**Review by hvadehra — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
(for 7.1.0)

**Comment by keertk** [comment]
@bazel-io fork 7.1.0

**Pull request closed without merging**
