### PR TITLE
Avoid a race condition in the remote upload

### PR DESCRIPTION
**Pull request by mmorearty**
Avoid triggering #3360. Immediately before a file's digest is computed for the first time, cache its last-modified time (mtime). Later, before uploading output artifacts, check if any of the inputs' mtimes have changed since their digest was computed, and if so, don't upload the outputs to the remote cache.

We need to use mtime, not ctime (last-change time), because some files (e.g. genrule-setup.sh) have their metadata changed after their digest is computed.

Also, the cache needs to resolve symbolic links, because some files are accessed from multiple paths that all resolve to the same file.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by mmorearty** [comment]
@ola-rozenfeld I think this greatly improves the race condition detection. A few things to note:

I have not written tests yet. If you feel that this is headed in the right direction, I could write tests, but I would also love to have some help in that area, because writing them myself would require spending more time learning your testing setup.

I manually tested this in several scenarios:

* Two genrules (as shown in https://github.com/bazelbuild/bazel/issues/3360#issuecomment-342712952) — modified `main.in` while the first genrule (`:lib`) was running. This correctly prevented caching of `main.out`, but allowed caching of `lib.out`.

* Two genrules — modified `lib.in` while the first genrule (`:lib`) was running. This correctly prevented caching of `lib.out` and `main.out`.

* Two genrules — did not modify any files. This correct allowed caching of both `lib.out` and `main.out`.

As noted in the above description, ctime (`path.getLastChangeTime()`) did not work, because some code somewhere modified some metadata of `genrule-setup.sh` after that file's digest was computed. Perhaps made it executable or something.

Also as noted, I deliberately resolve symlinks; if we don't do that, nothing ever gets cached in the above examples.

Also, one thing that is undesirable about this code is that there is an implicit assumption that the earlier code that originally computed and saved the digests went through `DigestUtils`. That assumption is correct, but still definitely undesirable. It would be cleaner to carry the `mtime` through all the code with the digests; but that turned out to be a huge change.

**Comment by ola-rozenfeld** [comment]
Looks good me me, thank you! But please send it to @ulfjack for review.

**Comment by mmorearty** [comment]
Great. @ulfjack can you please review? I don't have GitHub permissions to assign reviewers to this pull request.

**Comment by mmorearty** [comment]
There are two bugs that I've found with my pull request:

The first is that I didn't account for the fact that Bazel continues running in the background as a server. In my cache of timestamps in DigestUtils.java, the cache never gets cleared; I was operating under the traditional assumption that when the program "starts," all variables are in a clean state.

I have a fix for that locally, and will add it as a second commit to this pull request sometime soon (not today). I've added an initialization function which gets called from `CacheFileDigestsModule.executorInit()`.

The second bug is that by the time `RemoteSpawnRunner.executeLocallyAndUpload()` is reached, it seems that some inputs may have never had their digests computed, and thus will never have had their timestamps stored in my timestamp cache in DigestUtils.java. So far I've seen this in two cases: When compiling a `cc_library`, the file `libtool.sh` (or is it `libtool`?) may not have had its digest computed; and when building a `genrule`, the file `genrule-setup.sh` may not have had its digest computed.

I'm not sure of the best way to fix this. I'm also not sure why these inputs have not yet had their digests computed. `libtool.sh` and `genrule-setup.sh` seem like "special" files, perhaps the equivalent of files created with `ctx.actions.write()` (although it's hard for me to figure out from the source). They're not "real" inputs from the user; they're files that are generated during the build.

Are those the only kinds of files which will not have had their digest computed before reaching `RemoteSpawnRunner.executeLocallyAndUpload()`? If so, is it safe to assume that if a file had not had its digest computed before, then it's "safe"? Feels risky.

Another possible fix is, in `RemoteSpawnRunner.executeLocallyAndUpload()`, right before calling `fallbackRunner.exec()`, loop through all the files and call `DigestUtils.getDigestOrFail()` on all of them. I think that's safe.

**Comment by ola-rozenfeld** [comment]
When I build a Merkle tree of all the input nodes in RemoteSpawnRunner, I compute all their digests (repository.computeMerkleDigests(inputRoot)). So the only digests not computed are ones that are not part of the action input files -- they wouldn't get uploaded to remote execution, if remote execution is enabled, and they do not comprise a part of the Action digest.
I find it very surprising that genrule-setup.sh is one of them.

**Comment by mmorearty** [comment]
Interesting. Here is a test case that attempts to show that genrule-setup.sh is one of the files used in the Merkle tree (I hope I did this right):

In TreeNodeRepository.java, apply this change, to make it print out the paths of the files that it adds to the tree:

```diff
diff --git a/src/main/java/com/google/devtools/build/lib/remote/TreeNodeRepository.java b/src/main/java/com/google/devtools/build/lib/remote/TreeNodeRepository.java
index 055468272..5b56c69f1 100644
--- a/src/main/java/com/google/devtools/build/lib/remote/TreeNodeRepository.java
+++ b/src/main/java/com/google/devtools/build/lib/remote/TreeNodeRepository.java
@@ -249,6 +249,7 @@ public final class TreeNodeRepository extends TreeTraverser<TreeNodeRepository.T
       if (e.getValue() == SpawnInputExpander.EMPTY_FILE) {
         inputs.add(new EmptyActionInput(e.getKey()));
       } else {
+        System.err.println(">>>buildFromActionInputs: " + e.getKey());
         inputs.add(e.getValue());
       }
     }
```

Then in a small test project:

`BUILD`:

```python
genrule(
    name = "main",
    srcs = ["main.in"],
    outs = ["main.out"],
    cmd = "cp $< $@"
)
```

... plus make a file called `main.in` (doesn't matter what it contains).

Build with

```sh
bazel build \
  --remote_rest_cache=<your remote-cache url> \
  --spawn_strategy=remote \
  :main
```

When I do this, the output includes:

```
>>>buildFromActionInputs: external/bazel_tools/tools/genrule/genrule-setup.sh
>>>buildFromActionInputs: main.in
```

**Comment by ola-rozenfeld** [comment]
So, if I understand correctly, you see that this file is indeed part of the
input tree, so its digest should be computed during computeMerkleDigests.
Right?

**Comment by philwo** [comment]
@buchgr FYI

**Comment by ulfjack** [comment]
I'm sorry, I haven't managed to take a look yet. I think the problem with genrule-setup.sh is that it's not declared as an action input, but it is declared as a spawn input. That'd explain why it's not hashed before the remote spawn runner sees the spawn.

As a general comment, I'd prefer to not add another cache to DigestUtils. In fact, I'd also like to remove the existing cache. I realize that that will require more work, maybe significantly more work. I have a couple experimental changes to improve our metadata handling, but they're not ready for merging yet.

**Comment by mmorearty** [comment]
Okay. Since you would prefer not to add another cache to DigestUtils, I don't think I should put any more work into this pull request. You can close it if you like. (At Asana we're going to continue to use this until Bazel has a fix of some kind, because we've been bitten by this race condition in the past.) Thanks!

**Comment by ulfjack** [comment]
We're working on the larger refactoring now.

**Pull request closed without merging**
