### PR TITLE
Docs: add Flare.build to remote-execution.md

### PR DESCRIPTION
**Pull request by rescuerunaways**

### CODE REVIEW

**Comment by aiuto** [comment]
@hicksjoseph / @floriographygoth  The list of commercial vendors seem inappropriate for the versioned docs. We should split this page apart and put the vendors list on bazel.build.

**Review by aiuto — CHANGES_REQUESTED** [review]
@rescuerunaways Do you represent Flare?

Before adding a link to a business or project we always verify that they want to be added.

**Comment by hicksjoseph** [comment]
LGTM

**Comment by rescuerunaways** [comment]
@aiuto yes, I do represent Flare. That would be great to be added!

**Comment by zachgrayio** [comment]
Just wanted to confirm this is coming from us @ flare.build, as I see changes are still requested. Thanks @aiuto for double checking!

**Pull request closed without merging**
