### PR TITLE
Fix Bash runfiles calling repository lookup for directly run scripts

### PR DESCRIPTION
**Pull request by fmeum**
When an `sh_binary` is run directly from `bazel-bin`, its path won't be contained in the manifest and will not match a `bazel-out` regex. Instead, make the path absolute and then match after the `bazel-bin` to extract the binaries repository name.

Also improve the error message when `runfiles_current_repository` can find neither the runfiles manifest nor the runfiles directory.

Work towards fixing https://github.com/bazelbuild/bazel/pull/19796#discussion_r1358234830

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]

**Comment by fmeum** [comment]
@meteorcloudy This doesn't fix the full problem. When invoking the script directly, it also fails to find `RUNFILES_DIR` and `RUNFILES_MANIFEST_FILE` and I still don't know why.

**Comment by fmeum** [comment]
@meteorcloudy Looks like an existing test reproduces the problem. I will look into fixing it.

**Comment by fmeum** [comment]
@meteorcloudy Failure is fixed, I simply forgot the `.exe` suffix on Windows

**Review by meteorcloudy — APPROVED** [review]
I see, thanks!

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
(for 7.0.0)

**Comment by iancha1992** [comment]
@bazel-io fork 7.0.0

**Pull request closed without merging**
