### PR TITLE
Add sanitizer support to Apple platforms

### LINKED ISSUE #4984: Support for asan/tsan/ubsan on Apple builds on OS X crosstool
> ATTENTION! Please read and follow:
> - if this is a _question_ about how to build / test / query / deploy using Bazel, ask it on StackOverflow instead: https://stackoverflow.com/questions/tagged/bazel
> - if this is a _discussion starter_, send it to bazel-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Add “features” in OS X crosstool to enable usage of TSAN, UBSAN and ASAN. There have begun api changes in rules_apple but they are not functional until the crosstool supports these features 

### Feature requests: what underlying problem are you trying to solve with this feature?

I would like to run tests using clang sanitizers.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This is a feature request. You cannot specify a “feature” from the CLI for this currently.
### What operating system are you running Bazel on?

> Replace this line with your answer.

### What's the output of `bazel info release`?

0.12.0rc2

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

> Replace this line with your answer.

###  Have you found anything relevant by searching the web?

> Replace these lines with your answer.
>
> Places to look:
> - StackOverflow: http://stackoverflow.com/questions/tagged/bazel
> - GitHub issues: https://github.com/bazelbuild/bazel/issues
> - email threads on https://groups.google.com/forum/#!forum/bazel-discuss

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.

### PR DESCRIPTION
**Pull request by keith**
This adds support for asan, tsan, and ubsan on Apple platforms.

Fixes https://github.com/bazelbuild/bazel/issues/4984 and https://github.com/bazelbuild/bazel/issues/6932

### CODE REVIEW

**Comment by trybka** [comment]
Yeah, this is generally fine.

I'd note that we also set the following flags when any of the sanitizers are in use:
```
                    flags = [
                        "-O1",
                        "-gmlt",
                        # All failed checks are fatal.
                        "-fno-sanitize-recover=all",
                        "-fno-omit-frame-pointer",
```

**Comment by keith** [comment]
Would you recommend I add those here? I saw some flags in a previous PR that were similar, but I didn't want to add them w/o knowing if it was something that made sense generally or just for google

**Comment by trybka** [comment]
I think they're generally useful.

These two are recommended by the [Clang ASan Usage](https://clang.llvm.org/docs/AddressSanitizer.html#usage) docs:
- `-O1` is to get reasonable performance, especially if your `dbg` or `fastbuild` configs default to `-O0`.
- `-fno-omit-frame-pointer` gets better stack traces.

For the other two:
- `-fno-sanitize-recover=all` is a good default if you want tests and whatnot to fail immediately, this will be workflow dependent. For a heavy CI usage, you often just want to catch the first failure.
- `-gmlt` is just ["line number tables only"](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-gline-tables-only)

YMMV

**Comment by keith** [comment]
Fair enough! Added them here

**Comment by jin** [comment]
@trybka could you approve this PR? I'll import it as well.

**Review by trybka — APPROVED** [review]

**Comment by keith** [comment]
Thanks!

**Comment by DoDoENT** [comment]
Note: `-gline-tables-only` caused problems with the debugger. See [this issue](https://github.com/bazelbuild/apple_support/issues/613)

**Pull request closed without merging**
