### PR TITLE
Add `bazel mod lock`

### PR DESCRIPTION
**Pull request by fmeum**
RELNOTES: Use `bazel mod lock` in combination with `--lockfile_mode=update` or `--lockfile_mode=refresh` to evaluate all module extensions and update their entries in the lockfile. In the future, other subcommands of `bazel mod` may no longer evaluate all extensions.

### CODE REVIEW

**Comment by Wyverald** [comment]
Could you remind me what the plan was regarding other commands potentially no longer evaluating all extensions?

**Comment by fmeum** [comment]
> Could you remind me what the plan was regarding other commands potentially no longer evaluating all extensions?

My idea would be to make it so that this command is the only one that guarantees evaluation of all extensions, every other one would be free to evaluate whatever is needed.

**Comment by Wyverald** [comment]
I guess my question more specifically was _which_ commands you envision to no longer evaluate all extensions. How would `bazel mod graph` behave, for example?

This is not a huge deal, but I'm just a bit worried about the messaging. Technically, the "locking" part is only really meaningful for non-reproducible extensions; I kind of don't want people to assume they have to run `bazel mod lock` regularly, if they don't have to. Or maybe people should? I'm not fully sure. I guess the other thing is that whatever we name the new subcommand for this purpose should more immediately suggest to people that it's "locking" _all_ extensions, as opposed to a normal build that only locks the transitive dep closure of the top-level target.

**Comment by fmeum** [comment]
> I guess my question more specifically was _which_ commands you envision to no longer evaluate all extensions. How would `bazel mod graph` behave, for example?

`bazel mod graph` would need to evaluate all extensions with usages in modules reachable from the root given the limited `depth`. While it's not clear to me that's worth the implementation complexity, I could see `show_extension` and `show_repo` being clear candidates for optimization.

> I kind of don't want people to assume they have to run `bazel mod lock` regularly, if they don't have to. Or maybe people should? I'm not fully sure.

As far as I can tell, we are in a situation where many extension are still unnecessarily included in the lockfile (since rulesets haven't all been updated to make use of `reproducible`) and few extensions legitimately use the lockfile (the only popular example I know of is https://github.com/bazelbuild/rules_python/blob/218f8e161830ccd4f731a6a8d2a6dd36efe4488a/python/private/pypi/extension.bzl#L623-L629). It will take time for ruleset authors to come up with truly "Bzlmod native" designs. (This is actually also why I still consider it too early to decide on the fate of isolated usages).

In any case, there seem to be two common classes of lockfile users:
* "Casual" users who just run with the `--lockfile_mode=update` default and don't check it in. They don't need this command.
* "Committed" users who check that the lockfile is up-to-date in CI. They can't rely on incremental builds updating their lockfiles as a local change can easily cause an extension entry to become outdated without refreshing it, thus resulting in a failure in CI. This is where they need the "force lock all extensions" functionality.

>  I guess the other thing is that whatever we name the new subcommand for this purpose should more immediately suggest to people that it's "locking" all extensions, as opposed to a normal build that only locks the transitive dep closure of the top-level target.

I'm open to other names. `ensure_locked`, `force_lock` or `lock_all_extension` come to mind.

**Comment by Wyverald** [comment]
> `bazel mod graph` would need to evaluate all extensions with usages in modules reachable from the root given the limited `depth`.

This is the kicker -- I don't think we'll ever implement the pruning based on `--depth`, so `bazel mod lock` ends up just being a synonym of `bazel mod graph` (or technically `bazel mod graph > /dev/null`, I guess). That makes it harder to justify this new subcommand. I understand that it still has other advantages, eg. the implicit `> /dev/null`, the more focused name, etc.

In the interest of moving things forward -- how about this: I plan to spend some time fixing up the `mod` command after the 8.0 craze is over. (what does `bazel mod explain` even do, really?) After that, maybe things will be cleared up a bit, and we can revisit the decision then.

**Comment by fmeum** [comment]
Sounds good, an overhauled `bazel mod` could help quite a bit. Maybe we can even get Bazel's command "framework" to properly support sub-commands?

**Pull request closed without merging**
