### PR TITLE
fix bug of zip file larger than 2G with zipper tool

### PR DESCRIPTION
**Pull request by dhmemi**
Replace file size data type (`int` to `u8`) to support file larger than 2G.

See #19407

### CODE REVIEW

**Comment by cushon** [comment]
> /cc @cushon does this look good to you?

Is it possible to include a test for this?

FWIW I think we should also consider a long-term plan to turn down the ijar zipper (https://github.com/bazelbuild/bazel/issues/19446). I am curious if singlejar would be a viable alternative for the `py_` rules that are using zipper.

**Comment by meteorcloudy** [comment]
> I am curious if singlejar would be a viable alternative for the py_ rules that are using zipper.

I guess so? Essentially, what we need is a way to create a zip file for all Python runfiles. /cc @rickeylev

**Comment by rickeylev** [comment]
Ah, I see, //tools/zip:zipper is an alias to //tools/ijar:zipper

> Singlejar is a fast, general-purpose tool for creating deterministic zip archives, which a more robust zip implementation.

That sounds pretty nice. I know internally we use something similar to get deterministic zip files and larger zip file size support.

As long as it creates zip files, then its fine. The two main use cases are (1) copying the zip file elsewhere to be extracted (e.g. by unzip), and (2) can be read by Python's zipfile implementation (which is a pretty standard implementation).

If you grep py_executable_bazel.bzl for "zipper", you'll see the invocation the Python rules use.

**Comment by hvadehra** [comment]
@dhmemi please add a test as requested in https://github.com/bazelbuild/bazel/pull/19408#issuecomment-1710528848

**Comment by dhmemi** [comment]
> @dhmemi please add a test as requested in [#19408 (comment)](https://github.com/bazelbuild/bazel/pull/19408#issuecomment-1710528848)

done.

**Review by hvadehra — APPROVED** [review]

**Pull request closed without merging**
