### PR TITLE
Set //third_party/py/six:srcs to public visibility.

### PR DESCRIPTION
**Pull request by spxtr**

### CODE REVIEW

**Comment by laszlocsomor** [comment]
What's the rationale for this change?

**Comment by laszlocsomor** [comment]
Ah, never mind, I see it is https://github.com/bazelbuild/bazel/pull/3369#issuecomment-315031322. Assigning to @damienmg

**Comment by laszlocsomor** [comment]
Damien, apparently I have no write access to the repo, and can't merge this PR. Can you do it?

**Comment by damienmg** [comment]
We need to merge it on googlesource.com, yes I was about to do it but got
distracted.

**Pull request closed without merging**
