### PR TITLE
Add support for `@repo` target patterns

### PR DESCRIPTION
**Pull request by fmeum**
The `@repo` shorthand for `@repo//:repo` is supported by essentially all parts of Bazel and emitted by buildifier, but before this change could not be used on the commandline.

Fixes https://github.com/bazelbuild/bazel/issues/4385

### CODE REVIEW

**Comment by fmeum** [comment]
CC @aherrmann

**Review by aherrmann — APPROVED** [review]
Nice, thank you!

Fixes https://github.com/bazelbuild/bazel/issues/4385 (thanks @benradf for the link!)

**Comment by Wyverald** [comment]
Thanks for the PR! I have changes in flight to clean up the `TargetPattern` class, add a lot more tests, and eventually switch to using `LabelParser` to unify the logic, so this PR might end up obsolete. I'll keep it open for now until my changes are in.

**Comment by Wyverald** [comment]
This has been fixed on HEAD (see linked issue).

**Pull request closed without merging**
