### PR TITLE
Remove stale files in cc_inc_library include dirs

### PR DESCRIPTION
**Pull request by werkt**
Augment the CreateIncSymlinkAction to delete files found under the
includePath which are not in the symlinks map.  This corrects staleness
incurred when the contents of cc_inc_library targets change through
successive builds, and prevents errors in non-sandboxed strategies.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by werkt** [comment]
CLA corporation signer is Uber.  Member of Uber open source mailing list and https://github.com/UberATC

**Comment by laszlocsomor** [comment]
@werkt : The UberATC organization is private and its member list is private too. Do you have a GH account that's linked to Uber?

@dslomov : Do you know how I can check that Uber or UberATC as an organization signed the CLA?

**Comment by laszlocsomor** [comment]
Adding folks who are knowledgeable about incremental builds.

**Comment by werkt** [comment]
Closing this, an alternative solution with some facets of this has been provided elsewhere.

**Pull request closed without merging**
