### PR TITLE
Make the llvm coverage tests a little more robust.

### PR DESCRIPTION
**Pull request by c-mita**
Check that the actual coverage data simply contains the expected coverage data, rather
than checking for an exact match. This matters for when we start to process baseline
coverage, which may result in header files getting included in the report. This is
in-keeping with the other coverage tests.

Also adds the branch data into the reports, which we will check when we're using an LLVM
version that supports branch coverage, and a test that checks header files that include
coverage data are actually included in the final report.

Required for https://github.com/bazelbuild/bazel/pull/24593

### CODE REVIEW

**Comment by fmeum** [comment]
Can header files not provide coverage data for regular coverage, e.g. via macros?

**Comment by c-mita** [comment]
> Can header files not provide coverage data for regular coverage, e.g. via macros?

There are cases where header files should produce coverage (e.g. templates), just not in these test cases.

However, I seem to remember having issues with LLVM and coverage for header files that results in them either not being generated or not ending up in the final report.

**Comment by c-mita** [comment]
I've added a test to check that we do get coverage for header files that actually contribute something.

It seems that LLVM omits files that contribute nothing (headers that only contain declarations), which conflicts somewhat with our current baseline coverage implementation.
Down the road, when we can actually generate a baseline coverage file more intelligently, this probably won't be a problem.

**Review by fmeum — APPROVED** [review]

**Comment by c-mita** [comment]
I'll be doing the import myself.

**Comment by fmeum** [comment]
@bazel-io flag 8.1.0

**Comment by iancha1992** [comment]
@bazel-io fork 8.1.0

**Pull request closed without merging**
