### PR TITLE
Bump grpc to 1.48.1 and abseil-cpp to 20220623.1

### PR DESCRIPTION
**Pull request by davido**
Fixes https://github.com/bazelbuild/bazel/issues/18167.

abseil-cpp is missing stdint.h header include, that broke recent compiler versions. This problem was fixed in this commit upstream: [1].

Due to another commit: [2] in abseil-cpp, we also have to bump grpc as well to make them compatible.

[1] https://github.com/abseil/abseil-cpp/commit/36a4b073f1e7e02ed7d1ac140767e36f82f09b7c
[2] https://github.com/abseil/abseil-cpp/commit/b8bbe92f84ffe1e249016cfe8b79efdffb7a35c1

### CODE REVIEW

**Comment by davido** [comment]
@meteorcloudy 

Is the test breakage on Darwin is actually unrelated here?

**Comment by davido** [comment]
@meteorcloudy 

> Yes, we are doing some tuning for Bazel CI which caused some test timeouts, sorry about that!

Can you restart the verification once the problem fixed?

> Yes, unfortunately the grpc team doesn't maintain the BCR module currently, do you mind giving it a try to update it?

You mean to upload a new BCR module version for grpc: 1.48.1? Yes, will do.

**Comment by davido** [comment]
@meteorcloudy 

Once this [PR](https://github.com/bazelbuild/bazel-central-registry/pull/595) is merged, should I bump grpc blzmod version to 1.48.1 in this PR as well?

**Comment by meteorcloudy** [comment]
> Once this https://github.com/bazelbuild/bazel-central-registry/pull/595 is merged, should I bump grpc blzmod version to 1.48.1 in this PR as well?

Yes, please do!

**Comment by davido** [comment]
> Yes, please do!

Done.

**Comment by meteorcloudy** [comment]
We'll have to merge the changes in the third_party change separately, can you split this change into three ones:
- Add grpc patch files for new version
- Upgrade grpc
- Delete old grpc patch files.

**Comment by davido** [comment]
Superseded by https://github.com/bazelbuild/bazel/pull/18240, https://github.com/bazelbuild/bazel/pull/18241 and https://github.com/bazelbuild/bazel/pull/18242.

**Comment by meteorcloudy** [comment]
@davido Thanks!

**Comment by davido** [comment]
@meteorcloudy thank you for your assistance and fast review, very much appreciated!

**Pull request closed without merging**
