### PR TITLE
Allow locally build actions with scrubber

### PR DESCRIPTION
**Pull request by bozaro**
Since cannot run remote cache key scrubbing action with remote execution, run this actions only locally. Actions without scrubber can still be executed remotely.

The part from https://github.com/bazelbuild/bazel/pull/20070 that didn't cause much rejection.

### CODE REVIEW

**Review by tjgq — CHANGES_REQUESTED** [review]
Can you please add an integration test verifying that the fallback to local execution works? (Search for `test_cache_key_scrubbing` in `//src/test/shell/bazel/remote/remote_execution_test.sh`.)

**Review by tjgq — APPROVED** [review]
Looks good, thanks. We should also amend the description for the `--experimental_remote_scrubbing_config` flag, but I will do that myself when I import it.

**Comment by tjgq** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
