### PR TITLE
process runner for junit integration test framework

### PR DESCRIPTION
**Pull request by irengrig**

### CODE REVIEW

**Comment by ittaiz** [comment]
Hi,
Did you see bazel-integration-testing?
Sounds like there’s some overlap.
We’d love to collaborate...

**Comment by irengrig** [comment]
Hi Ittai, I am the new member of the Bazel team.
It is a part of the new Java integration tests, to gradually replace the existing shell integration tests. (If I understood your question correctly).

**Comment by ittaiz** [comment]
@ulfjack @helenalt @davidstanke I have to say this is really discouraging as a community member.

I approached the Bazel team requesting to use the previous bash FW and you said it’s going away.

We (@damienmg and myself) started working on bazel-integration-testing library in bazelbuild organization to solve this problem and what I now see happening is that you decide to just resolve the problem instead of leveraging the community effort that has already started.

If we had a discussion and couldn’t agree on the design and approach I would understand but no discussion was made.

**Comment by ittaiz** [comment]
I understand and my criticism was in no way about you. It was to those who
have much more context and history about this.
Are you planning on having this FW only for Bazel’s own usage?
If not what’s the release strategy?
Given this is trying to replace existing code and given existing pains (at
least one GH issue in this repo is about this) then I think there’s value
in answering these questions before committing to a solution.

**Comment by irengrig** [comment]
Yes, absolutely, we should discuss the possibilites.

>Are you planning on having this FW only for Bazel’s own usage?
The primary goal currently is to replace internal tests.
In the process, we are planning to open-source more internal tests.
Further the framework can be used outside; probably, we should create a separate artifact (library) that can be used with arbitrary Bazel installation. Currently there is no no exact plan for that.

We believe bazel-integration-testing is a great framework which allows external users right now to test Bazel binaries with external rules, and in several languages. Am I right in understanding the goals of bazel-integration-testing?

----------------------
A bit more context:

I am continuing the activity started by Julio Merino http://julio.meroh.net/2018/03/bazel-tests-in-java-part-2.html
It is about replacing existing tests, which test the Bazel/Blaze itself.

The test framework should allow to run the same tests with Bazel or Blaze,
so that the code of the test does not depend on the environment.
The framework should prepare the test environment, and there is much more work for the Blaze variant with that.

We also want to let tests select what parts of Bazel/Blaze it needs (for instance, whether it is using android or coverage tools) to speed up the test environment initialization.

Other big part of this is actually porting existing tests to Java.
I must be very accurate and first port the shell code to Java and then look for possibilities to improve it. This means that I should also port current Bazel test environment initialization very exactly as well, it might be that our tests mock more things for internal testing and not actually using "black box model".

**Comment by dslomov** [comment]
I agree @ittaiz in retrospect we should have conducted the conversation about this more in the open.
But to say we are ignoring community contributions with this work is too harsh, I think. 

The goal of @irengrig's and @jmmv's work here is solely to replace _our existing shell tests within Bazel (and also the internal version of Bazel)_ (basically https://github.com/bazelbuild/bazel/tree/master/src/test/shell). This is not intended to be a framework for rule writers to test their rules  (we should expand on https://github.com/bazelbuild/bazel-integration-testing for that instead). Our internal integration tests have *a lot* of idiosyncrasies irrelevant to rule and tool writer communities (OSS vs. Google environment, tools locations etc), and shell testing framework accumulated a lot of cruft of the years, that is probably not useful or downright harmful in clean OSS solution that bazel-integration-testing aims to provide. At the same time, some dimensions that bazel-integration-testing needs to address simply do not exist for Bazel internal tests (e.g. support for testing with multiple versions of Bazel). Also, depending inside Bazel on external code that also depends on Bazel would be quite complicated indeed.

Taking all this into account, I believe that the decision we have made - not to burden bazel-integration-testing with all this additional, and mostly irrelevant outside of Bazel itself, functionality - is the right one. I agree that we should have communicated this decision more explicitly, e.g. on [this thread](https://www.google.com/url?q=https://groups.google.com/forum/%23!msg/bazel-dev/E74l7J9qE7w/wSMAQSAtBwAJ&ust=1530363229032000&usg=AFQjCNFsqVgXD6CAXIwBefjffe-uO4-s5A), but in no way this decision ignores the work that is put into bazel-integration-testing. The opposite is true - we do not want to jeopardize that effort with extra, irrelevant, requirements. 

In the future, I see opportunities for some consolidation (e.g. this PR and https://github.com/bazelbuild/bazel-integration-testing/tree/master/java/build/bazel/tests/integration have some overlapping functionality), but before we introduce any complicated framework we need to experiment and try things out.

**Pull request closed without merging**
