### PR TITLE
New operators for Skylark:

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
- list \* int
- int \* list

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by abergmeier-dsfishlabs** [comment]
Connected issue is https://github.com/bazelbuild/bazel/issues/1523.

**Comment by damienmg** [comment]
@abergmeier-dsfishlabs: your company needs to sign the CLA. Please ping back here when it is done.

**Comment by abergmeier-dsfishlabs** [comment]
@damienmg I know, I know. Still have some hope.

**Comment by damienmg** [comment]
:)

**Comment by abergmeier-dsfishlabs** [comment]
I saw the signature!
I signed it!

**Comment by damienmg** [comment]
I found the signature for "Deep Silver FISHLABS / Koch Media GmbH" :)

**Comment by meteorcloudy** [comment]
@damienmg Can you review this again?

**Comment by meteorcloudy** [comment]
Sorry, this is already assigned to @dslomov

**Comment by abergmeier-dsfishlabs** [comment]
Any progress?

**Comment by philwo** [comment]
Adding / pinging @laurentlb and @fweikert - could you have a look at this?

**Comment by laszlocsomor** [comment]
@laurentlb ping

**Comment by laurentlb** [comment]
Change looks good. I'll come back to you on Wednesday.

**Comment by laszlocsomor** [comment]
Gentle ping @abergmeier-dsfishlabs , would you still like to get this change in?

**Comment by abergmeier-dsfishlabs** [comment]
@laszlocsomor yes I would. Am currently working on `label_dict`, though. Do you mind waiting a bit on this?

**Comment by laszlocsomor** [comment]
@abergmeier-dsfishlabs : Absolutely, no problem. Take your time. I was just curious to know if this PR should remain open.

**Comment by abergmeier-dsfishlabs** [comment]
@fweikert @laszlocsomor  There you go.

**Comment by abergmeier-dsfishlabs** [comment]
Has been merged with a397340f6cd45f101ff0c13a1eeeaf3957e1d59c

**Pull request closed without merging**
