### PR TITLE
Update turbine

### PR DESCRIPTION
**Pull request by cushon**
https://github.com/google/turbine/commit/cb6006005b4b3196a29d87775245076c2205ef10

https://github.com/bazelbuild/bazel/issues/13965

### CODE REVIEW

**Comment by philwo** [comment]
Sorry, I had to revert this (and should have waited for the presubmit tests to complete...), because it breaks some tests: https://buildkite.com/bazel/bazel-bazel/builds/17471

**Comment by cushon** [comment]
Sorry about that, and thanks for taking care of the rollback.

I think this has exposed an issue with those tests, I mailed cl/399718766 to prepare them for this change.

**Comment by cushon** [comment]
The CI is passing with the pending change to `src/test/shell/bazel/bazel_java_test.sh` patched in, I'll submit that and then update the PR to be just the turbine change

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
@philwo This PR is ready for a manual merge.

**Pull request closed without merging**
