### PR TITLE
[6.2.0] Add version to JavaRuntimeInfo

### PR DESCRIPTION
**Pull request by hvadehra**
(cherry picked from commit 7556e1107b666d10b660470a571631463c7eb4ec)

1. As suggested in https://github.com/bazelbuild/bazel/issues/6354#issuecomment-1310489402, add a JDK version attribute to the java_runtime rule. This will allow changing behavior based on the Java runtime's version.

2. As an application of the above, pass -Djava.security.manager=allow to Java tests on JDK 17+. This makes the Bazel Java test runner to work on JDK 19. Fixes https://github.com/bazelbuild/bazel/issues/14502.

3. To make the above generally useful, the remote_java_repository and local_java_repository must set the new version attribute in the java_runtime rules that they create. This means the old static jdk.BUILD file no longer suffices. Move the contents of jdk.BUILD into a Starlark file, so the version can be interpolated in by JDK repository rules and macros. (This isn't the nicest, but local_java_repository is not a repository rule, so the template cannot be in a non-Starlark file.)

Closes #17775.

PiperOrigin-RevId: 518860040
Change-Id: I8223b6407dd09528a4e5a6bf12354e5fc68278c6

### CODE REVIEW

**Comment by hvadehra** [comment]
@meteorcloudy looks like we will also need https://github.com/bazelbuild/bazel/commit/844b5d2dbc3ff1dda43d78b81a00c6323e4e8115 for this to work "as is". IIUC that would be a breaking change. Is that fine?

**Comment by meteorcloudy** [comment]
@hvadehra I think we should respect our policy to not cherry pick any incompatible change, is it possible to cherry pick part of https://github.com/bazelbuild/bazel/commit/844b5d2dbc3ff1dda43d78b81a00c6323e4e8115 that's backwards compatible to make this one work?

**Review by kshyanashree — APPROVED** [review]

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@hvadehra  Thanks!

**Comment by meteorcloudy** [comment]
@hvadehra Is it possible to split the change into two commits (one is the original commit, one is your custom changes), it would be easier to review and would probably help us if we have merge conflict in future.

**Comment by hvadehra** [comment]
@meteorcloudy Done

**Pull request merged**
