### PR TITLE
Add profiler task for calling a credential helper.

### PR DESCRIPTION
**Pull request by tjgq**
This might help debug future performance issues related caused by slow
credential helpers.

### CODE REVIEW

**Comment by tjgq** [comment]
cc @Yannic

**Review by coeuvre — APPROVED** [review]

**Comment by tjgq** [comment]
@bazel-io fork 5.3.1

**Comment by Wyverald** [comment]
@bazel-io fork 5.3.1

**Review by Yannic — COMMENTED** [review]
LGTM

**Pull request closed without merging**
