### PR TITLE
Allow replace zlib with Debian system libs

### PR DESCRIPTION
**Pull request by meteorcloudy**
Related https://github.com/bazelbuild/bazel/issues/9408

### CODE REVIEW

**Comment by meteorcloudy** [comment]
FYI @olekw

**Comment by meteorcloudy** [comment]
It turned out the zlib sources are packaged in the embedded tools. I cannot ship a BUILD file that uses the `distribution_rules.bzl", so I created a BUILD.tools file for zlib. PTAL.

**Comment by meteorcloudy** [comment]
I have to rename the BUILD.tools to BUILD.bazel for the embedded source, PTAL

**Comment by olekw** [comment]
Quick question on this: does Bazel need to link zlib statically? If so, is it possible to link dynamically at least in the Debian variant? Debian is rather averse to static linking if it can possibly be avoided. (Security considerations) Thanks!

**Comment by meisterT** [comment]
cc @oquenchil for the question on static vs dynamic linking

**Comment by oquenchil** [comment]
I have verified that meteorcloudy's proposed solution of removing the dependency from zlib_client and adding linkopts = ["-lz"] to the zipper cc_binary works. So, yes this is possible.

**Comment by meteorcloudy** [comment]
Cool, I'll send a change to update the debian_cc.BUILD file

**Comment by meteorcloudy** [comment]
Merged at https://github.com/bazelbuild/bazel/commit/2a07773baa0f64bb5b467df77088130486ffb3e9

**Pull request closed without merging**
