### PR TITLE
WIP: disable WORKSPACE in shell integration tests

### PR DESCRIPTION
**Pull request by meteorcloudy**
Working towards https://github.com/bazelbuild/bazel/issues/23023

This PR is huge, I'm going to try to break it down:
- [ ] Add MODULE.bazel setup in testenv.sh
- [ ] Migrate tests in batches
- [ ] Remove WORKSPACE setup in testenv.sh and add --noenable_workspace by default (some test cases can still enable WORKSPACE)

### CODE REVIEW

**Comment by ted-xie** [comment]
All of the native Android rule tests require WORKSPACE to exist, so I think CI won't pass until we delete those tests and eventually the rules.

**Comment by meteorcloudy** [comment]
> All of the native Android rule tests require WORKSPACE to exist, so I think CI won't pass until we delete those tests and eventually the rules.

Do you still want to keep the android tests in Bazel repo? (We disabled them on macOS already) If so, we can still set `--enable_workspace` for those tests).

**Comment by ted-xie** [comment]
I don't think we've migrated all of these tests to rules_android yet, so we can't outright delete them for now. I'd be OK with disabling them for Linux and Windows to unblock this work.

**Comment by meteorcloudy** [comment]
Got it, then I'll just enable WORKSPACE for those tests to keep them running.

**Comment by meteorcloudy** [comment]
This PR has been broken down and merged.

**Pull request closed without merging**
