### PR TITLE
Prefex references to //tools and //third_party with @bazel_tools

### LINKED ISSUE #421: Touching WORKSPACE and building //... fails
@pgr0ss noticed that if someone creates a new workspace, touches the WORKSPACE file, and runs //..., it will fail because the base_workspace tools now have a bunch of external dependencies from skylark rules (https://github.com/bazelbuild/bazel/blob/master/tools/BUILD#L28-L30) that aren't declared in the user's WORKSPACE file. Maybe all BUILD rules with external dependencies should be declared in the appengine.BUILD (or rust.BUILD) files so they don't get dragged into the user's base workspace.

### PR DESCRIPTION
**Pull request by kchodorow**
This allows --package_path not to be set for builds, since all of the
tools are loaded from the local repository, instead.

Note that //tools/defaults is still in the main repo, since it's
generated, and there are a couple of //tools references in the objc
rules, with comments about why they cannot be in @bazel_tools.

Fixes #421.

RELNOTES: Specifying --package_path=%workspace%:/path/to/base_workspace
is no longer required.

### CODE REVIEW

**Comment by kchodorow** [comment]
I haven't actually removed it from the bootstrap or the installer yet, I'll deal with those in followup cls.

**Comment by damienmg** [comment]
overall LGTM, just let's keep the prelude_bazel file in the main repository for now.

**Comment by kchodorow** [comment]
SGTM.

**Comment by damienmg** [comment]
LGTM

**Comment by hanwen** [comment]
kristina, what's the deal here. Should this PR be pulled in?

**Comment by kchodorow** [comment]
Working on it, unfortunately this breaks several things internally.

**Comment by damienmg** [comment]
Closing this PR and it is being merged by small chunk

**Pull request closed without merging**
