### PR TITLE
Let Starlark tests inherit env variables

### PR DESCRIPTION
**Pull request by fmeum**
Adds an inherited_environment field to testing.TestEnvironment to allow
Starlark rules to implement the equivalent of the native rules'
`env_inherit` attribute.

Work towards https://github.com/bazelbuild/bazel/issues/7364. To fully resolve that issue, it remains to handle
executable non-test rules.

RELNOTES: Starlark test rules can use the new inherited_environment
parameter of testing.TestEnvironment to specify environment variables
whose values should be inherited from the shell environment.

Closes https://github.com/bazelbuild/bazel/pull/14849.

PiperOrigin-RevId: 439277689

Cherry-pick contains parts of:

Delete non-interning, non-singleton @AutoCodec.

PiperOrigin-RevId: 411683398

Cherry-pick makes the following additional changes:

- Replace use of ImmutableMap.buildKeepingLast with .copyOf

Closes https://github.com/bazelbuild/bazel/pull/15240.

### CODE REVIEW

**Comment by fmeum** [comment]
It looks like this patch doesn't apply cleanly to the 5.x branch without also cherry-picking some of the AutoCodec refactorings. I do not know what the policy regarding this is.

**Comment by ckolli5** [comment]
Hello @fmeum, Can you please check the buildkite presubmit failures. Thanks!

**Comment by fmeum** [comment]
@comius Would it be safe to cherry-pick only some of the @AutoCodec changes for Bazel 5.2.0?

**Comment by fmeum** [comment]
@ckolli5 Tests are passing with minor changes applied to the cherry-picked commit.

**Comment by ckolli5** [comment]
@fmeum The release branch has been updated. Could you please update your branch with latest changes to release-5.2.0 branch? Thanks!

**Comment by fmeum** [comment]
@ckolli5 Done, tests pass.

**Pull request merged**
