### PR TITLE
[7.4.0] Verify in tests that coverage supports `--nobuild_runfile_links`

### LINKED ISSUE #20577: remote_coverage_tools/Main cannot locate runfiles directory when building with `--nobuild_runfile_links`
### Description of the bug:

Whenever `--nobuild_runfiles_links` is enabled I encounter a failure where the `remote_coverage_tools/Main` tool errors and fails to find runfiles. The logging is confusing as searching appears as though it should be inhibited.

https://buildkite.com/bazel/rules-rust-rustlang/builds/10120#018c7929-4564-4947-9fa6-ea73aa7e0e26
```
+ JAVA_RUNFILES=
+ exec bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/remote_coverage_tools/Main --coverage_dir=/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/3234/execroot/rules_rust/bazel-out/k8-fastbuild/testlogs/test/rust_test_suite/tests_suite_tests/integrated_test_b/_coverage --output_file=/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/3234/execroot/rules_rust/bazel-out/k8-fastbuild/testlogs/test/rust_test_suite/tests_suite_tests/integrated_test_b/coverage.dat --filter_sources=/usr/bin/.+ --filter_sources=/usr/lib/.+ --filter_sources=/usr/include.+ --filter_sources=/Applications/.+ --source_file_manifest=/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/3234/execroot/rules_rust/bazel-out/k8-fastbuild/bin/test/rust_test_suite/tests_suite_tests/integrated_test_b.instrumented_files
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/3234/execroot/rules_rust/bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/remote_coverage_tools/Main: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
```

This issue is reproduced on https://github.com/bazelbuild/rules_rust/pull/2340

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This issue is reproduced on https://github.com/bazelbuild/rules_rust/pull/2340

### Which operating system are you running Bazel on?

Linux, MacOS

### What is the output of `bazel info release`?

7.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by bazel-io**
Fixes #20577

Closes #22676.

PiperOrigin-RevId: 649065192
Change-Id: I0a57f580c1cb3a03184950e3e5ea24e9ef4962b4

Commit https://github.com/bazelbuild/bazel/commit/c8006084e70f7faa942572808b6329b044f0f7ab

### CODE REVIEW

**Comment by iancha1992** [comment]
@c-mita do you have fix for the presubmit errors?

**Comment by Ryang20718** [comment]
@iancha1992 @c-mita I don't think this cherry-pick is correct.

https://github.com/bazelbuild/bazel/commit/404d8d97fafedb7c43a3c164a7446d2e1bf2e436 is the actual fix whereas the cherry-pick above is only for adding tests

**Comment by c-mita** [comment]
Attempting to cherry-pick https://github.com/bazelbuild/bazel/commit/404d8d97fafedb7c43a3c164a7446d2e1bf2e436 into 7.4.0 results in quite a few merge conflicts that I don't feel comfortable resolving myself.

Assigning to @lberki to take a look if it's reasonable or not.

**Comment by Ryang20718** [comment]
@lberki small ping! would love to get this in 7.4 if possible

**Comment by meteorcloudy** [comment]
@Ryang20718 If a commit causes too much merge conflicts, we may eventually decide not to cherry pick it. But feel free to give it a try if you desperately need it.

**Pull request closed without merging**
