### PR TITLE
Simplify confusing test code and options parsing

### PR DESCRIPTION
**Pull request by gregestren**
We can lightly refactor test code to no longer need a logical exception in Bazel's option parsing.

Supports https://github.com/bazelbuild/bazel/pull/20107 and https://github.com/bazelbuild/bazel/issues/20081.

### CODE REVIEW

**Comment by gregestren** [comment]
> `c0` has to be replaced in even more places, but apart from that this looks fine.

Where else?

**Comment by fmeum** [comment]
https://github.com/bazelbuild/bazel/blob/ff0c35c7bfe134fda4cfc0683d648ad62270eb86/src/test/java/com/google/devtools/build/lib/runtime/BlazeOptionHandlerTest.java#L503 and other occurrences in that file.

**Review by katre — APPROVED** [review]

**Comment by gregestren** [comment]
> https://github.com/bazelbuild/bazel/blob/ff0c35c7bfe134fda4cfc0683d648ad62270eb86/src/test/java/com/google/devtools/build/lib/runtime/BlazeOptionHandlerTest.java#L503
> 
> and other occurrences in that file.

Ah, I didn't notice that dependency at first. Thanks.

**Comment by gregestren** [comment]
Updated as requested, CI passes.

**Review by fmeum — APPROVED** [review]

**Comment by sgowroji** [comment]
Hi @gregestren, While merging the above PR our CI is gettin failed because of above code conflicts.  https://buildkite.com/bazel/google-bazel-presubmit/builds/73609#018bb7f5-0d9d-4e61-899d-c7843bccc766
```
//src/test/shell/integration:starlark_configurations_test                FAILED ```

**Comment by gregestren** [comment]
> Hi @gregestren, While merging the above PR our CI is gettin failed because of above code conflicts. https://buildkite.com/bazel/google-bazel-presubmit/builds/73609#018bb7f5-0d9d-4e61-899d-c7843bccc766
> 
> ```
> //src/test/shell/integration:starlark_configurations_test                FAILED ```
> ```

Updated. Let's see how CI responds.

**Pull request closed without merging**
