### PR TITLE
Remove tools/build_defs/hash

### PR DESCRIPTION
**Pull request by philwo**
This seems completely unused, but maybe I'm missing something?

### CODE REVIEW

**Comment by clintharrison** [comment]
These are used by `rules_docker`.

See [`container/import.bzl`](https://github.com/bazelbuild/rules_docker/blob/0d6d69a2a4bbc33fc61a8350897b0e8136491ad5/container/import.bzl#L92) for one example.

**Comment by aehlig** [comment]
Over to @laurentlb as it is mainly about a policy question, which skylark code should go
- to bazel proper,
- to [skylib](https://github.com/bazelbuild/bazel-skylib), or
- to the repository actually using the function.

**Comment by laurentlb** [comment]
hash.bzl seems like a good fit for skylib

**Comment by laurentlb** [comment]
It seems a good fit for Skylib if you think the function can be useful for other projects.

Maybe the code is too specific and should be in the user repository.

**Comment by philwo** [comment]
Skylib or user-specific - both works for me. Which one should we pick?

My goal is just to not ship these kind of things inside Bazel itself. :)

**Comment by jin** [comment]
can we merge this?

**Pull request closed without merging**
