### PR TITLE
Change error on adding a directory to the remote cache to be non-fatal

### PR DESCRIPTION
**Pull request by rahul-malik**
@ulfjack @buchgr  - I'm resubmitting https://github.com/bazelbuild/bazel/pull/3984 on behalf of @mterring to get past CLA issues that are holding it up from merging.

This is a temporary fix for the issue https://github.com/bazelbuild/bazel/issues/3891 while we wait for https://github.com/bazelbuild/bazel/pull/4011 to be reviewed and tested

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ulfjack** [comment]
On it.

**Comment by jacobstr** [comment]
Will this appear in a 0.8.2 release?

**Comment by ulfjack** [comment]
We only cherrypick regressions for point releases, and this isn't one, so if it's not in 0.8.0, it should be in 0.9.0. And we actually just released 0.9.0:
https://github.com/bazelbuild/bazel/releases/tag/0.9.0
https://releases.bazel.build/0.9.0/release/index.html

**Pull request closed without merging**
