### PR TITLE
[6.4.0] Bump c++ standard to c++14 per default

### PR DESCRIPTION
**Pull request by thii**
Fixes: https://github.com/bazelbuild/bazel/issues/18181.

Closes: #18280.

Closes #18280.

PiperOrigin-RevId: 530246609
Change-Id: I6b49d1bd827e98ca65db87c34c1bb13106ffc232 (cherry picked from commit 978cd23e80f202a03e99a87f2089a9a0622b5d5d)

### CODE REVIEW

**Comment by thii** [comment]
@bazel-io flag

**Comment by keertk** [comment]
Hi @thii thanks for the PR! Is this critical for 6.4, or can we push to the next release?
We've created the last release candidate and plan to do the final release tomorrow.

**Comment by thii** [comment]
@keertk I can wait for the next release.

**Comment by keertk** [comment]
So turns out we're creating a new RC after all, so we'll include this one as well.

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
