### PR TITLE
pkg_deb: support depends_file attribute

### LINKED ISSUE #7886: pkg_deb should support a way of embedding version into control fields
### Description of the problem / feature request:

Cannot add `pkg_deb`'s version from `version_file` into Debian control field (i.e. `Depends:`)

### Feature requests: what underlying problem are you trying to solve with this feature?

I have several dependent packages (say, `A` and `B` depending on `A`) which I'm building at once. I want to specify dependency from `B` (of version `$version`) to `A` (of same `$version`). However, as I'm using `version_file` to specify version, I'm not able to specify `depends` = [`A (=<$version — how would I get it?>)`]

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```
load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_deb")

pkg_deb(package = "A", version_file = "//:VERSION")
pkg_deb(package = "B", version_file = "//:VERSION", depends=["A (=version)"]) # <-- how can I make `A` the same version as in `//:VERSION` here?
```

### What operating system are you running Bazel on?

macOS Mojave 10.14.4

### What's the output of `bazel info release`?

`release 0.23.0`

###  Have you found anything relevant by searching the web?

#7474 is probably relevant

### PR DESCRIPTION
**Pull request by vmax**
Fixes #7886 by adding support for `depends_file` attribute in `pkg_deb`
Summoning @aiuto for review as he expressed the wish to do it.

### CODE REVIEW

**Comment by tuananhckpt90** [comment]
Chi

**Comment by tuananhckpt90** [comment]
Có

**Comment by aiuto** [comment]
Thanks. Reviewing now.

**Comment by aiuto** [comment]
This doesn't pass tests. 

$ bazel test tools/build_defs/pkg/...
INFO: Analysed 27 targets (26 packages loaded, 611 targets configured).
INFO: Found 23 targets and 4 test targets...
ERROR: .../tools/build_defs/pkg/BUILD:206:1: MakeDeb tools/build_defs/pkg/titi_test_all.deb failed (Exit 1) make_deb failed: error executing command bazel-out/host/bin/tools/build_defs/pkg/make_deb '--output=bazel-out/k8-fastbuild/bin/tools/build_defs/pkg/titi_test_all.deb' ... (remaining 14 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File ".../sandbox/linux-sandbox/22/execroot/io_bazel/bazel-out/host/bin/tools/build_defs/pkg/make_deb.runfiles/io_bazel/tools/build_defs/pkg/make_deb.py", line 355, in <module>
    main(FLAGS(sys.argv))
  File ".../sandbox/linux-sandbox/22/execroot/io_bazel/bazel-out/host/bin/tools/build_defs/pkg/make_deb.runfiles/io_bazel/tools/build_defs/pkg/make_deb.py", line 332, in main
    depends=GetFlagValue(FLAGS.depends),
  File ".../.cache/bazel/_bazel_aiuto/c42451a13f00e0b53b5ffe5391e00b77/sandbox/linux-sandbox/22/execroot/io_bazel/bazel-out/host/bin/tools/build_defs/pkg/make_deb.runfiles/io_bazel/tools/build_defs/pkg/make_deb.py", line 301, in GetFlagValue
    flagvalue = flagvalue.decode('utf-8')
AttributeError: 'list' object has no attribute 'decode'
INFO: Elapsed time: 1.946s, Critical Path: 0.57s
INFO: 22 processes: 22 linux-sandbox.
FAILED: Build did NOT complete successfully
//tools/build_defs/pkg:archive_test                                      PASSED in 0.2s
//tools/build_defs/pkg:make_rpm_test                                     PASSED in 0.2s
//tools/build_defs/pkg:path_test                                         PASSED in 0.2s

**Comment by vmax** [comment]
@aiuto should be fixed in https://github.com/bazelbuild/bazel/pull/8100/commits/00ed7fc25ea4b8a96d31679be46700a41ae5c9bb
why didn't CI catch it though?

**Comment by aiuto** [comment]
It is possible that the pre-mail CI does not run all the tests.
Either way. PRs should pass local testing before sending for review. This simply didn't.

**Comment by aiuto** [comment]
Merged. It should be in the next release. Some CI troubles caused it to take a while.

**Pull request closed without merging**
