### PR TITLE
Remote: Don't check declared outputs for failed action

### PR DESCRIPTION
**Pull request by coeuvre**
Fix a bug that Bazel print message

```
Invalid action cache entry ...: expected output ... does not exist.
```

instead of the underlying error message when remote action failed.

### CODE REVIEW

**Comment by brentleyjones** [comment]
@bazel-io fork 5.2

**Comment by Wyverald** [comment]
@bazel-io fork 5.1.1

**Comment by kjlubick** [comment]
I'm still seeing this behavior in 5.2.0

**Comment by coeuvre** [comment]
I see. This check was implemented to intentionally avoid that issue, see https://github.com/bazelbuild/bazel/issues/14543.

**Pull request closed without merging**
