### PR TITLE
Update to latest available JDK 11 update releases

### PR DESCRIPTION
**Pull request by cushon**
The new binaries are:

```
e064b61d93304012351242bf0823c6a2e41d9e28add7ea7f05378b7243d34247 https://cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz
fc7c41a0005180d4ca471c90d01e049469e0614cf774566d4cf383caa29d1a97 https://cdn.azul.com/zulu-embedded/bin/zulu11.56.19-ca-jdk11.0.15-linux_aarch64.tar.gz
9750e11721282a9afd18a07743f19c699b2b71ce20d02f3f0a906088b9ae6d9a https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1+1/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.14.1_1.tar.gz
79a27a4dc23dff38a5c21e5ba9b7efcf0aa5e14ace1a3b19bec53e255c487521 https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1+1/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.14.1_1.tar.gz
2614e5c5de8e989d4d81759de4c333aa5b867b17ab9ee78754309ba65c7f6f55 https://cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-macosx_x64.tar.gz
6bb0d2c6e8a29dcd9c577bbb2986352ba12481a9549ac2c0bcfd00ed60e538d2 https://cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-macosx_aarch64.tar.gz
a106c77389a63b6bd963a087d5f01171bd32aa3ee7377ecef87531390dcb9050 https://cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-win_x64.zip
```

This is a step towards https://github.com/bazelbuild/bazel/issues/14533

### CODE REVIEW

**Comment by ckolli5** [comment]
Hello @cushon, Can you please check the buildkite presubmit failures. Thanks!

**Comment by cushon** [comment]
@ckolli5 the `//src/test/shell/bazel:verify_workspace` failures are because the new artifacts need to be added to the Bazel mirror, similar to e.g. https://github.com/bazelbuild/bazel/pull/15119#issuecomment-1078540263. I don't have permissions to upload them, is that something you can help with?

**Comment by cushon** [comment]
I also did some testing in https://github.com/bazelbuild/bazel/pull/15303 (which is based on top of this PR) with the Bazel mirror URLs removed and the CI is clean, which confirms everything should work once the new artifacts are available in the mirror.

**Comment by james-deee** [comment]
Do these 2 need to be for 11.0.15 first?

```
9750e11721282a9afd18a07743f19c699b2b71ce20d02f3f0a906088b9ae6d9a https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1+1/OpenJDK11U-jdk_ppc64le_linux_hotspot_11.0.14.1_1.tar.gz
79a27a4dc23dff38a5c21e5ba9b7efcf0aa5e14ace1a3b19bec53e255c487521 https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.14.1+1/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.14.1_1.tar.gz
```

**Comment by cushon** [comment]
@james-deee the temurin release of 11.0.15 isn't available yet, but I was planning to update the PR (or do another update) once they are

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
I mirrored the files

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
