### PR TITLE
Split toolchains from cc_toolchains in cc_configure

### PR DESCRIPTION
**Pull request by hlopko**
This change modifies which part of cc_configure is executed unconditionally and which only on demand.

The root of the problem was the call `register_toolchains(@local_config_cc//:all)`. Because this was appended to the WORKSPACE file, each Bazel project executed the repository (and therefore tried to detect C++ toolchain and its capabilities) even when the C++ toolchain was not needed for the build.

This change split `@local_config_cc` into 2 repositories:

1. `@local_config_cc_toolchains` which contains only `toolchain` targets, and doesn't require C++ toolchain to be detected.
2. `@local_config_cc` which contains `cc_toolchain` targets, which do require C++ toolchain to be detected.

The point is that toolchain resolution has all the information needed to select the appropriate toolchain without autoconfiguration, therefore C++ toolchain will only be autoconfigured only after we already know it will be selected.

This cl is backwards incompatible for projects that relied on `@local_config_cc` containing `toolchain` targets. But because https://github.com/bazelbuild/bazel/issues/7260 is not yet flipped, there are not that many users of toolchains with C++ who manually instantiate `cc_autoconf` rule.

Fixes https://github.com/bazelbuild/bazel/issues/7751.
Progress towards https://github.com/bazelbuild/bazel/issues/7260.

RELNOTES: Repository containing autoconfigured C++ toolchain `@local_config_cc` has been split in 2 - see `local_config_cc_toolchains`.

### CODE REVIEW

**Comment by hlopko** [comment]
@jmillikin-stripe - to allow smooth incremental migration regarding https://github.com/bazelbuild/bazel/issues/7260, envoy will have to copypaste `@local_config_cc_toolchains` into the build. Then once it migrates to Bazel 0.27 it can remove the copy and instead load the repository from `@bazel_tools`. Does that sound reasonable to you?

**Comment by nlopezgi** [comment]
Hi Marcel,
RBE heavily depends on local_config_cc contaning the c toolchain artifacts. Specifically, rbe_autoconfig (https://github.com/nlopezgi/bazel-toolchains/blob/master/rules/rbe_repo.bzl) relies on this being the repo which describes a c toolchain and uses that to configure a c toolchain for remote execution. 
How will this change affect us?
Can we guard it with an incompatible flag?

**Comment by hlopko** [comment]
Good points :)

1) `@local_config_cc` still contains `cc_toolchain` and `cc_toolchain_suite` targets. It still contains all the artifacts.  That stays backwards compatible. `@local_config_cc_toolchains` now contains `toolchain` targets that used to be in `@local_config_cc`.
1.1) Do you use toolchain targets? They look like this:

```
load("@local_config_platform//:constraints.bzl", "HOST_CONSTRAINTS")
toolchain(
    name = "cc-toolchain-%{name}",
    exec_compatible_with = HOST_CONSTRAINTS,
    target_compatible_with = HOST_CONSTRAINTS,
    toolchain = "@local_config_cc//:cc-compiler-%{name}",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
```

I assume you need to pass different constraints to `exec_compatible_with` and `target_compatible_with`. From that I extrapolate you don't use them, but you write your own. But I didn't check.

1.2) If you use these targets, you have following options:

* copypaste the repo function to bazel-toolchains
* watch out for `@local_config_cc_toolchains` and if present, take it out together with `@local_config_cc`.
* watch out for `@local_config_cc_toolchains` and if present, append its BUILD file into `@local_config_cc//:BUILD` to get the previous behavior.

2) There is currently no support for incompatible flags in repository rules. Of course Bazel is just code and we can tell it to do anything, but the effort required would be substantial, and IMHO the benefit minimal. You'd still have to change bazel-toolchain to be forward compatible, so the only things you'd get is a bazel release you can play with. I'll gladly prepare such Bazel version by hand today :)

Wdyt?

**Comment by nlopezgi** [comment]
Thanks for the quick response and for the clarifications.
RBE does not currently rely on the toolchain targets themselves (we generate them), we only use the `cc_toolchain` and `cc_toolchain_suite` targets, so as long as these remain in `@local_config_cc` this change should not impact us.
Thanks for offering to provide a bazel version for us to test, I think it should not be necessary, however, whenever there is an rc or release that includes this, please let me know so I can set up automated tests to verify its not impacting us.
Thanks again!

**Pull request closed without merging**
