### PR TITLE
Starlark: use Math.floorDiv in Starlark.floordiv

### PR DESCRIPTION
**Pull request by stepancheg**
`Math.floorDiv` does multiplication to compute a remainder.

JVM is supposed to
[detect a pair of division and remainder](http://hg.openjdk.java.net/jdk9/jdk9/hotspot/file/jdk-9+181/src/share/vm/opto/compile.cpp#l3176)
when C2 is kicked in, but somehow it seems to not do it on my laptop.

Benchmark can be made a little even more faster by
[adding `yl - 1` instead of multiplication](https://git.io/JIYY6)
but better keep implementation simple.

Anyway, using `Math.floorDiv` is a safe bet.

```
def test():
    for i in range(10):
        print(i)
        for j in range(1000000):
            1 // 100
            1000 // 20
            -1 // 30
            -33 // 9
            500000 / 22
            1 // 100
            1000 // 20
            1 // 30
            3306 // 11
            500000 // 22

test()
```

```
A: n=80 mean=5.149 std=0.317 se=0.035 min=4.709 med=5.102
B: n=80 mean=4.634 std=0.280 se=0.031 min=4.234 med=4.552
B/A: 0.900 0.883..0.918 (95% conf)
```

### CODE REVIEW

**Review by alandonovan — APPROVED** [review]

**Comment by alandonovan** [comment]
> JVM is supposed to detect a pair of division and remainder when C2 is kicked in, but somehow it seems to not do it on my laptop.

Mine neither. This 90s loop doesn't even engage the C1 compiler even after 15s of CPU.
```
for _ in range(1000000000):
    y += (1 << 18) // (1 << 17)
```
(That said, I guess there's little gained from optimizing code whose bottleneck is the hardware: the div instruction takes 80 cycles regardless of whether it's called from the interpreter or compiled code.)

**Review by alandonovan — APPROVED** [review]

**Comment by alandonovan** [comment]
(cr/345661089)

**Comment by brandjon** [comment]
Question: Should we do the same thing for mod and use `Math.floorMod()`? Or is there no benefit there since there's no mod/div to merge?

**Comment by stepancheg** [comment]
@brandjon `StarlarkInt.mod` is implemented with single `%` operation, while `Math.floorMod` is implemented using `Math.floorDiv` (at least in my JDK version) so it does division and multiplication, so `Math.floorMod` might be a little slower.

**Pull request closed without merging**
