### PR TITLE
Update error prone version to 2.3.4

### LINKED ISSUE #9286: Upgrade error-prone to 2.3.3?
It looks like Bazel is still using 2.3.2 snapshot version.  Any chance to upgrade to the latest 2.3.3 release?

### LINKED ISSUE #11272: Update error prone version to 2.4.0
Last EP upgrade attempt to 2.3.3 was reverted to `RefersToDaggerCodegen` breakage in rules_kotlin: [1],[2].

This is a feature request to update EP version to 2.3.4.

It turns out, that with EP 2.3.4 there are at least two breakages:

- rule_closure: [3]
- rules_kotlin: [4]

[1] bazelbuild/bazel#10023
[2] bazelbuild/bazel@d990746
[3] https://github.com/bazelbuild/rules_closure/issues/483
[4] https://github.com/bazelbuild/rules_kotlin/issues/321

### PR DESCRIPTION
**Pull request by davido**
Fixes #11272 (first attempt that was reverted: #9286).

### CODE REVIEW

**Comment by davido** [comment]
//CC @cushon @meisterT.

**Comment by meisterT** [comment]
Yun, can you please have a look how this ties into your Debian efforts?

**Comment by davido** [comment]
@meteorcloudy @meisterT Thanks for the feedback. Note, though, that this PR also adds new dependency to Bazel: Ben-Manes caffeine library. By chance I know, that Gerrit is also relying on the same version: 2.7.0, so that it should be already imported in Google's Monorepo.

But are there any special procedures to include new third dependency in Bazel?

**Comment by meteorcloudy** [comment]
Oh.. I see. Thanks for the notice. I checked the caffeine library is not in Debian. So this will add more difficulties for the effort of getting Bazel into Debian. Check https://github.com/bazelbuild/bazel/issues/9408

Is it because the new error prone version requires this library? Besides, the checked in version is 2.8.0  in Google.

**Comment by meisterT** [comment]
David, how large is the new dependency?

**Comment by davido** [comment]
> Is it because the new error prone version requires this library?

Sure. The dependency was added in EP tree in this CL: [1] and was updated in this CL: [2].

> David, how large is the new dependency?

It's 846706 bytes:

```
$ wget https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.7.0/caffeine-2.7.0.jar
--2020-05-04 10:50:49--  https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.7.0/caffeine-2.7.0.jar
Connecting to 16.175.95.22:8080... connected.
Proxy request sent, awaiting response... 200 OK
Length: 846706 (827K) [application/java-archive]
Saving to: ‘caffeine-2.7.0.jar’

caffeine-2.7.0.jar                       100%[==================================================================================>] 826,86K  --.-KB/s    in 0,1s

2020-05-04 10:50:49 (5,45 MB/s) - ‘caffeine-2.7.0.jar’ saved [846706/846706]
```

**Comment by davido** [comment]
>Besides, the checked in version is 2.8.0 in Google.

@meteorcloudy Thanks for checking!

I have sent this PR: [1] to sync Caffeine version in EP tree to 2.8.0.

[1] https://github.com/google/error-prone/pull/1602

**Comment by davido** [comment]
@meteorcloudy 

> Besides, the checked in version is 2.8.0 in Google.

My PR: [1] was merged in EP, so that I will adapt this PR correspondingly.

[1] https://github.com/google/error-prone/pull/1602

**Comment by davido** [comment]
> My PR: [1] was merged in EP, so that I will adapt this PR correspondingly.

Done.

**Comment by davido** [comment]
Superseded by https://github.com/bazelbuild/bazel/pull/11426.

**Pull request closed without merging**
