### PR TITLE
Report evaluation start and end for module extensions as fetch events

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io flag

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@bazel-io fork 7.0.0

**Review by Wyverald — APPROVED** [review]
nice!

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
