### PR TITLE
Java template windows performance

### PR DESCRIPTION
**Pull request by rpaquay**
Address issue #2426

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
LGTM, thanks!

**Comment by meteorcloudy** [comment]
@rpaquay It seems we can't remove the invocation of cygpath.

What if to_win_path is dealing with an absolute path?

$ to_win_path /home/a/b
\home\a\b

$ cygpath -w /home/a/b
C:\tools\msys64\home\foo\bar

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by rpaquay** [comment]
> What if to_win_path is dealing with an absolute path?
> 
> $ to_win_path /home/a/b
> \home\a\b
> 
> $ cygpath -w /home/a/b
> C:\tools\msys64\home\foo\bar

I would hope that the paths used in java_stub_template.txt don't depend on that behavior, because the notion of top-level absolute path (e.g. /home) is a figment of the imagination of msys. There is no such native concept on Windows, hence I would think it is a problem to have scripts that depend on that behavior when trying to move off msys for these scripts.

In anyways, in case you absolutely need to support this behavior, feel free to update my patch to remove the cygpath invocations. Most of the performance gain was obtained by fixing the implementation of "rlocation" (because it is O(# jars)), whereas there is a constant # of cygpath invocations (2).

**Pull request closed without merging**
