### PR TITLE
[6.4.0] Respect main repository mapping in `platform_mappings`

### LINKED ISSUE #17127: Repo names in platform_mappings aren't handled with bzlmod
### Description of the bug:

With a `platform_mappings` file like:

```
platforms:
  @build_bazel_apple_support//platforms:macos_x86_64
    --cpu=darwin_x86_64
```

and this in your MODULE.bazel:

```
bazel_dep(
    name = "apple_support",
    repo_name = "build_bazel_apple_support",
    version = "1.3.2",
)
```

bazel errors with:

```
no such package '@build_bazel_apple_support//platforms': The repository '@build_bazel_apple_support' could not be resolved: Repository '@build_bazel_apple_support' is not defined
```

changing to:

```
platforms:
  @apple_support~1.3.2//platforms:macos_x86_64
    --cpu=darwin_x86_64
```

seems to work, but I believe that would require updating version each time you updated the rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

6.0.0rc4

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #17127

Closes #17133.

PiperOrigin-RevId: 563803704
Change-Id: I0f49fbfce624207b81a6ca4f7e564d9f3b525d54

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald @brentleyjones Called it, the weird errors that look completely unrelated at first are back on 6.4.0. I don't think it's feasible to backport this.

**Comment by brentleyjones** [comment]
😢

**Comment by meteorcloudy** [comment]
Do we know which changes are needed?

**Comment by fmeum** [comment]
> Do we know which changes are needed?

I don't. Based on the test failures I would suspect one of the fixes to built-ins injection, but that is just a wild guess.

@brentleyjones If you would like to see this in 6.4.0, you could run a bisect between 6.4.0 and HEAD with this commit applied to find out where the tests start to pass.

**Comment by brentleyjones** [comment]
My main motivation for this fix landing in 6.4.0 is rules_apple 3.0 requires the use of a platform_mappings file, so this change will allow easier migration for people that also use Bzlmod.

**Comment by brentleyjones** [comment]
f70e6b81079da2d90ec786dd0f940c88c889aaa4 is the first commit where the tests start to pass with this commit applied.

**Comment by meteorcloudy** [comment]
@brentleyjones Thanks!
@fmeum Let's try adding https://github.com/bazelbuild/bazel/commit/f70e6b81079da2d90ec786dd0f940c88c889aaa4?

**Comment by fmeum** [comment]
> @fmeum Let's try adding [f70e6b8](https://github.com/bazelbuild/bazel/commit/f70e6b81079da2d90ec786dd0f940c88c889aaa4)?

I tried, but this is a commit with quite non-trivial merge conflicts in `SkyframeExecutor.java`.

@aoeui We would need to cherry-pick f70e6b81079da2d90ec786dd0f940c88c889aaa4 into 6.4.0 to fix some test failures. Do you think that would be feasible or does this commit depend on more changes on master that we would need to cherry-pick as well?

**Comment by aoeui** [comment]
That change only affects test code.

My hunch is that test failures would not be resolved by that change alone
because that only starts the process of migrating test code to the new
implementation, but I'm not 100% sure.

**Comment by iancha1992** [comment]
@fmeum @aoeui @brentleyjones @meteorcloudy @Wyverald are we still interested in cherry-picking this to release-6.4.0? The release date for the first candidate for 6.4.0 is next Monday (9/18/2023)

**Comment by fmeum** [comment]
> @fmeum @aoeui @brentleyjones @meteorcloudy @Wyverald are we still interested in cherry-picking this to release-6.4.0? The release date for the first candidate for 6.4.0 is next Monday (9/18/2023)

Interested yes, but I won't realistically be able to work on this.

**Comment by iancha1992** [comment]
Hi. RC1 is going out this morning (9/18). Looks like the test failures aren't easy to resolve for this one. So we are dropping and closing this PR for now. Thank you!

cc: @bazelbuild/triage

**Pull request closed without merging**
