### PR TITLE
Support LoongArch64

### PR DESCRIPTION
**Pull request by zunley**
To Supports [build tensorflow from source](https://www.tensorflow.org/install/source) on [alpine](https://wiki.alpinelinux.org/wiki/Loongarch64).

### CODE REVIEW

**Comment by zunley** [comment]
Depends on https://github.com/bazelbuild/platforms/pull/106

**Comment by katre** [comment]
Why does this need to be in Bazel? Defining the constraint and platform in tensorflow should be sufficient without any Bazel or platforms changes.

**Comment by zunley** [comment]
> Why does this need to be in Bazel? 

@katre I hope that bazel can support it natively and widely, which is more friendly for building projects such as kubernetes and envoy on loongarch64, which is why I added support for rules_go https://github.com/bazelbuild/rules_go/pull/4142.

**Comment by katre** [comment]
Bazel does not need to support this natively, defining a custom `constraint_value` with your own platform and toolchain definitions (in your project) will be sufficient.

**Pull request closed without merging**
