### PR TITLE
[6.1.0]Fix bugs with unicode filenames in runfiles.

### PR DESCRIPTION
**Pull request by kshyanashree**
We had a cc_test using a bunch of files (`data = glob(["data/**"]),`), some which were in subdirectories where the directory name had unicode characters (e.g. `data/test_öΩ/`). This resulted in an error:
```
ERROR: C:/users/.../BUILD.bazel:233:8: Creating runfiles tree bazel-out/x64_windows-opt/test-shared.exe.runfiles failed: build-runfiles.exe failed: error executing command
  cd /d C:\users\...
  SET BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
    SET PATH=...
  C:\users\...\install\eadbc20bd36081cbe58dcb5129383507\build-runfiles.exe bazel-out/x64_windows-opt/test-shared.exe.runfiles_manifest bazel-out/x64_windows-opt/test-shared.exe.runfiles: Process exited with status 1: Process exited with status 1
build-runfiles error: MakeDirectoriesW failed (\\?\c:\users\...\test-shared.exe.runfiles\test\data\layer_middle_??): (error: 123): The filename, directory name, or volume label syntax is incorrect.
```

`build-runfiles-windows.cc` expects the `.runfiles_manifest` to be encoded in UTF-8; but Java was writing it as latin-1. This resulted in unicode characters (not representable in latin-1) being stored as `?` in the `.runfiles_manifest` file. Question marks are not valid in filenames, causing the error in `build-runfiles`.

This commit changes the encoding of `.runfiles_manifest` from latin-1 to UTF-8. Additionally, it fixes a bug in `build-runfiles-windows.cc` where the `space_pos` was calculated from the UTF-8 representation but then used for the UTF-16 wstring, which caused string containing unicode characters to be split incorrectly.

Closes #15846.

PiperOrigin-RevId: 509492501
Change-Id: I82d5119160c16d4513e9e744d9f398727bac1dc4

### CODE REVIEW

**Comment by Wyverald** [comment]
@dgrunwald , could you please sign the CLA again? It looks like it's barfing because you signed the previous CLA with two emails and this one has only one or something (I don't fully understand what's wrong).

**Review by Wyverald — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Still seeing

> ❌ https://github.com/bazelbuild/bazel/commit/2b7b4c34cf928df50044353157da1db7255ee6c6 Author: @dgrunwald <da***l​@danielgrunwald.de>

@dgrunwald Can you make sure you have signed the CLA with the above email address, otherwise we cannot cherry pick this one and it could have problems with your future PRs.

**Comment by meteorcloudy** [comment]
OK, this change is being rolled back at HEAD, we no longer need to cherry pick it.

**Comment by dgrunwald** [comment]
Any explanation why the change was rolled back?

Should I made another PR with the correct email address; or is there another issue?

**Comment by meteorcloudy** [comment]
Sorry, when I was commenting yesterday, the rollback was still in progress. Here is the rollback commit: https://github.com/bazelbuild/bazel/commit/474fc1895cd5ed34841e32ab8e2ece1fbffe2ab4, you can find the reason in the commit message.

**Comment by dgrunwald** [comment]
Uhh, you do realize that `[build-runfiles-windows.cc` was *already* using UTF-8 to read that file?
Umlauts like `ö` are broken without my PR!

**Comment by Wyverald** [comment]
Daniel, please take a look at this thread https://groups.google.com/g/bazel-dev/c/JIrbn8QZs0o . If we can work out the proper fix, we can roll it forward again. Thanks!

**Comment by fmeum** [comment]
The `CstringToWstring` method expects UTF-8 (https://github.com/bazelbuild/bazel/blob/532a52e79237c7f6229f442916570a3b9633c3f4/src/main/cpp/util/strings.cc#L379), which does seem to cause the latin-1 invariant to be broken in a number of places. Unless there are places that actually want UTF-8, changing the encoding used in that function may end up fixing a number of encoding issues at once.

**Pull request closed without merging**
