### PR TITLE
[6.0.0] [remote/downloader] Don't include headers in `FetchBlobRequest`

### PR DESCRIPTION
**Pull request by Yannic**
Including the headers in the request is very inefficient as credentials should never change the content of the downloaded archive. In fact, given that Bazel verifies the checksum of the downloaded file, the credentials cannot possibly used in a way where they influence the outcome of the download (other than deciding whether or not the user is allowed to download the blob at all). Hence, the credentials should not be included in the request.

Users that need to send credentials to the remote downloader should do so by passing the credentials as metadata to the gRPC call.

Note that the remote downloader is behind an experimental flag, so this change does not need to go thorugh the incompatible change process.

Closes #16595.

PiperOrigin-RevId: 485576157
Change-Id: I8afc7c818e4eed63ac1f70c3e4c2115a1d365830

### CODE REVIEW

**Comment by Yannic** [comment]
cc @tjgq

**Comment by Yannic** [comment]
@meteorcloudy can you help getting this merged please?

**Comment by meteorcloudy** [comment]
@Yannic Please also rebase this one so that it'll get merged ;)

**Comment by Yannic** [comment]
done

**Pull request merged**
