### PR TITLE
Delete macOS link_cocoa feature

### PR DESCRIPTION
**Pull request by keith**
This feature doesn't appear to be necessary at this point, importing
this framework will link it successfully.

### CODE REVIEW

**Comment by keith** [comment]
I don't know the history here so maybe there was a larger purpose before

**Comment by trybka** [comment]
This is added in rules_apple https://github.com/bazelbuild/rules_apple/blob/bd873c4ed8de4c0cd75a5fc5fa0ad14c73cdce19/apple/macos.bzl#L63 to implicitly add it for UI applications (vs. command-line).

That being said, this is a no-op in our crosstool. Just not sure if someone out there could be depending on it?

**Comment by keith** [comment]
ah thanks, I didn't think to look there, testing to see if any tests are covering it https://github.com/bazelbuild/rules_apple/pull/1149 based on the git blame it dates all the way back to the initial commit to those rules

**Comment by keith** [comment]
Seems like this is still required for the common case, so I guess we can leave it for now

**Pull request closed without merging**
