### PR TITLE
Update upb to fix compilation error with gcc 10

### PR DESCRIPTION
**Pull request by meteorcloudy**
Fixes https://github.com/bazelbuild/bazel/issues/12056

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@vbatts Can you verify if this PR fix the compilation error for you?

**Comment by aiuto** [comment]
The change looks fine, but the distfile tests are still failing in various ways.

**Comment by aiuto** [comment]
https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/6893#23242da4-4c34-4fd8-bf2e-f391ee10d809

It seems to be downloading 9effcbcb27f0a665f9f345030188c0b291e32482 instead of the newer version.
Did this miss the instance at WORKSPACE@641?

**Comment by meteorcloudy** [comment]
@aiuto Nice catch, fixed!

**Comment by meteorcloudy** [comment]
Hmm, looks like we have to explicitly override the upb on WORKSPACE file.

**Comment by aiuto** [comment]
Now it fails in the non_determinism test. Could it be related to //third_party/grpc:grpc_1.26.0.patch?

**Comment by aiuto** [comment]
Or maybe it is the grpc patch doing it.

**Comment by meteorcloudy** [comment]
> Now it fails in the non_determinism test. Could it be related to //third_party/grpc:grpc_1.26.0.patch?

No, the patch is for something else. The upb is actually introduced in grpc_deps(), I tried to override it by declaring it directly in Bazel's WORKSPACE file. But it doesn't seem to work because the new upb version doesn't work with the old grpc version.. This is not looking good ...

**Comment by aiuto** [comment]
Yeah. I still see the same error with the update patch.  But, if you decide you want it. 
```
diff --git a/third_party/grpc/grpc_1.26.0.patch b/third_party/grpc/grpc_1.26.0.patch
index 03b4aed96a..25d0631773 100644
--- a/third_party/grpc/grpc_1.26.0.patch
+++ b/third_party/grpc/grpc_1.26.0.patch
@@ -70,12 +70,14 @@ index 09fcad95a2..9b737e5deb 100644
      if "com_google_absl" not in native.existing_rules():
 @@ -209,7 +212,10 @@ def grpc_deps():
              name = "upb",
-             sha256 = "61d0417abd60e65ed589c9deee7c124fe76a4106831f6ad39464e1525cef1454",
-             strip_prefix = "upb-9effcbcb27f0a665f9f345030188c0b291e32482",
+-            sha256 = "61d0417abd60e65ed589c9deee7c124fe76a4106831f6ad39464e1525cef1454",
+-            strip_prefix = "upb-9effcbcb27f0a665f9f345030188c0b291e32482",
 -            url = "https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz",
++            sha256 = "7992217989f3156f8109931c1fc6db3434b7414957cb82371552377beaeb9d6c",
++            strip_prefix = "upb-382d5afc60e05470c23e8de19b19fc5ad231e732",
 +            urls = [
-+                "https://mirror.bazel.build/github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz",
-+                "https://github.com/protocolbuffers/upb/archive/9effcbcb27f0a665f9f345030188c0b291e32482.tar.gz",
++                "https://mirror.bazel.build/github.com/protocolbuffers/upb/archive/382d5afc60e05470c23e8de19b19fc5ad231e732.tar.gz",
++                "https://github.com/protocolbuffers/upb/archive/382d5afc60e05470c23e8de19b19fc5ad231e732.tar.gz",
 +            ],
          )
      if "envoy_api" not in native.existing_rules():
```

**Comment by meteorcloudy** [comment]
Thanks for coming up with the patch, unfortunately the newer version isn't compatible with grpc. The best I can come up with is to patch the original upb version, see https://github.com/bazelbuild/bazel/pull/12083

**Comment by aiuto** [comment]
So, is this PR moot, and we should do 3.5.1 with a cherrpick of #12083?

**Comment by meteorcloudy** [comment]
Yes, looks like a regression we should fix.

**Pull request closed without merging**
