### PR TITLE
[6.1.0]Rollback #14510 because it causes remote test execution to fail

### PR DESCRIPTION
**Pull request by kshyanashree**
When the parent process is run as a different user to the test itself (as can happen in some remote build environments, such as buildbarn) using `kill -0 $PPID` fails, causing the test to be prematurely killed.

This PR rolls back the (nicer, cleaner, not always working) fix and replaces it with the (less nice, less clean, more often working) check that was there before.

Tested with a local build against buildbarn.

Closes #17147.

PiperOrigin-RevId: 500691976
Change-Id: Ife55db5c1ed88d40ba502257ce9b679b04eeb179

### CODE REVIEW

**Comment by larsrc-google** [comment]
What's the difference between this and #17210?

**Comment by kshyanashree** [comment]
> What's the difference between this and #17210?

Hi @larsrc-google! This is the forked issue. Once I get approval from you then I will go ahead & merge this PR,Following I can close the forked issue. Thanks!

**Comment by kshyanashree** [comment]
> > What's the difference between this and #17210?
> 
> Hi @larsrc-google! This is the forked issue. Once I get approval from you then I will go ahead & merge this PR,Following I can close the forked issue. Thanks!

**Comment by larsrc-google** [comment]
I'm confused, but it's certainly OK to merge.

**Comment by kshyanashree** [comment]
> > > What's the difference between this and #17210?
> > 
> > 
> > Hi @larsrc-google! #17210 This is the forked issue. Once I get approval from you then I will go ahead & merge this PR, following I can close the forked issue. Thanks!

**Review by larsrc-google — APPROVED** [review]

**Pull request merged**
