### PR TITLE
 Packaging rules: Remove documentation for pkg_tar

### PR DESCRIPTION
**Pull request by steple**
Remove inaccurate documentation for deprecated rules.
These rules are deprecated and they should be removed soon. Delete the documentation now to discourage use of these rules. (Also the documentation is outdated.)

Issue: #14797

### CODE REVIEW

**Comment by aiuto** [comment]
I'm heading out on vacation shortly. I can't merge until sometime in March.

**Comment by steple** [comment]
No rush, be safe, enjoy.

**Review by aiuto — APPROVED** [review]

**Review by aiuto — COMMENTED** [review]
I changed my mind. The right thing to do is
- remove the docs so people do not keep trying to use this.
- step up the removal of pkg_tar

**Comment by steple** [comment]
I'm happy to try to take care of the removal.
Would you like me to a) amend to this branch?  b) start a new branch and new pull request? c) something else?

**Comment by steple** [comment]
I updated this pull request to remove the documentation.

**Comment by aiuto** [comment]
The file was removed in another PR.

**Pull request closed without merging**
