### PR TITLE
DO NOT SUBMIT -- clone https://github.com/bazelbuild/bazel/pull/4449 for testing

### PR DESCRIPTION
**Pull request by laszlocsomor**

### CODE REVIEW

**Comment by laszlocsomor** [comment]
i signed it

**Comment by laszlocsomor** [comment]
link to https://github.com/bazelbuild/bazel/pull/4449

**Comment by lfpino** [comment]
Hi all, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by laszlocsomor** [comment]
The PR served its purpose (ran the BuildKite tests successfully), so I'm closing it.

**Pull request closed without merging**
