### PR TITLE
Use execution info instead of hard-coded mnemonics for Java path mapping

### LINKED ISSUE #21092: --experimental_output_paths=strip cannot be disabled for built-in mnemonics
### Description of the feature request:

When this flag is enabled, it doesn't respect the execution requirements for a hardcoded list of `SUPPORTED_MNEMONICS`, meaning they cannot be disabled by the end user if they are misbehaving.

### Which category does this issue belong to?

Java Rules

### What underlying problem are you trying to solve with this feature?

Our custom starlark actions work great with this flag, so we would like to use it for those, but the built-in rules are misbehaving (see #21091)

### PR DESCRIPTION
**Pull request by fmeum**
By removing Java rules from the hard-coded mnemonics allowlist for path mapping, users can rely on `--modify_execution_info` to selectively disable path mapping for them just like for Starlark actions.

This requires fixing two minor inconsistencies in how execution info is populated for Java actions:
* In `JavaCompilationHelper`, `buildKeepingLast` is used instead of `buildOrThrow` to prevent a crash when a target sets `supports-path-mapping` via `tags`.
* In `JavaHeaderCompileAction`, `--experimental_inmemory_jdeps_files` no longer causes all other execution info to be lost.

Fixes #21092

### CODE REVIEW

**Comment by fmeum** [comment]
@hvadehra Could you review this? While the aim is to remove tech debt related to the path mapping feature, the PR almost exclusively touches execution info logic for Java actions.

CC @aranguyen

**Review by hvadehra — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io flag 7.1.0

**Comment by iancha1992** [comment]
Just FYI, this is being imported in [cl/606319644](https://critique.corp.google.com/cl/606319644)

cc: @bazelbuild/triage @Wyverald @meteorcloudy

**Comment by fmeum** [comment]
Good find, I didn't think of that. 

I'm not aware of any other execution info entry with a unique value. As a quick win, we could just not inline infos containing this particular key in the `SpawnAction` constructor.

Maybe a custom `SortedMap` implementation that stores the unique part separately from the interned constant part could improve the savings further?

**Comment by justinhorvitz** [comment]
I have https://bazel-review.googlesource.com/c/bazel/+/242796 out for review, which reduces memory on the internal benchmark target by 1.0%. So it ends up even better than before your PR.

There might be more savings to be had by using something other than a map, but it also might be negligible so long as  interning is effective.

**Comment by fmeum** [comment]
@bazel-io fork 7.1.1

**Comment by fmeum** [comment]
@iancha1992 Forking again for the fix in https://github.com/bazelbuild/bazel/pull/21093#issuecomment-1992617787.

**Comment by justinhorvitz** [comment]
Memory improvement submitted as https://github.com/bazelbuild/bazel/commit/e8d844e8dc39288493fdc2c3e9e9c33198fc858d.

**Pull request closed without merging**
