### PR TITLE
[7.1.0] Do not store the repository name in `RepoSpec`

### PR DESCRIPTION
**Pull request by iancha1992**
The name can instead be set centrally in `BzlmodRepoRuleFunction`. This removes some unnecessary glue code and paves the way for rewriting canonical repo names based on knowledge of the full dep graph.

Work towards #20997

Closes #21026.

Commit https://github.com/bazelbuild/bazel/commit/a87a8db23885535232ace3f64ac45e595c95d2f5

PiperOrigin-RevId: 604256186
Change-Id: Ia49123f016d1512074b04ec458f017f4bbb88233

### CODE REVIEW

**Comment by Wyverald** [comment]
Looks like you might need to run `bazel run //src/test/tools/bzlmod:update_default_lock_file`

**Comment by iancha1992** [comment]
> Looks like you might need to run `bazel run //src/test/tools/bzlmod:update_default_lock_file`

@Wyverald hmm.. I just did run it. But looks like it's giving a different error.

cc: @bazelbuild/triage

**Comment by Wyverald** [comment]
ok hang on, the lockfile situation is getting out of hand... let me see if I can update the release-7.1.0 branch to use Bazel 7.0.2 first.

**Comment by Wyverald** [comment]
Sent https://github.com/bazelbuild/bazel/pull/21209 instead

**Pull request closed without merging**
