### PR TITLE
Split ModuleThreadContext off from ModuleFileGlobals

### PR DESCRIPTION
**Pull request by Wyverald**
ModuleFileGlobals used to serve as both the definition of Starlark methods available in MODULE.bazel files, *and* the state tracker for a module being built. This commit brings it more in line with other Starlark evaluation contexts where there's a simple object that just holds methods, and the actual state is stored in the StarlarkThread. ModuleThreadContext is that state object.

This commit is a pure mechanical refactor with no behavioral changes. It paves the way for us to allow root module MODULE.bazel files to import other files.

Work towards https://github.com/bazelbuild/bazel/issues/17880.

### CODE REVIEW

**Comment by Wyverald** [comment]
@zhengwei143 this PR includes a very small usage of `record`, which seems to be causing some failure on Windows arm64 only (`could not locate class file for java.lang.Record`). Any ideas?

**Comment by fmeum** [comment]
@Wyverald Pretty sure this is the same issue as in https://github.com/bazelbuild/bazel/pull/21702#issuecomment-1998562967

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/rules_java/releases/tag/7.5.0 has been released, we can just upgrade rules_java for Bazel.

**Comment by hvadehra** [comment]
> https://github.com/bazelbuild/rules_java/releases/tag/7.5.0 has been released, we can just upgrade rules_java for Bazel. /cc @hvadehra

https://github.com/bazelbuild/bazel/pull/21729

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
