### PR TITLE
Use exec transitions in Java related rules.

### PR DESCRIPTION
**Pull request by comius**
Android rule's transitions are the first thing Java toolchain resolution hits. Android uses Java to build build tools and needs correct transition of Java for this.

### CODE REVIEW

**Comment by comius** [comment]
Failing on Ubunu 20 is related to missing python2 installation https://github.com/bazelbuild/continuous-integration/issues/1042, @philwo is working on that.

**Comment by comius** [comment]
cc @lberki @c-mita @oquenchil

**Review by katre — APPROVED** [review]
This looks good, but I'd like to see a full Bazel downstream test run, and a TGP internally.

**Comment by comius** [comment]
Downstream works https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1682, with rules_cc already failing and a flake in rules_kotlin.

**Pull request closed without merging**
