### PR TITLE
jvm_import_external

### PR DESCRIPTION
**Pull request by natansil**
This PR copies "upstream" a change made to java_import_external in`rules_scala` (see [PR](https://github.com/bazelbuild/rules_scala/pull/473))

This change was originally proposed by @dslomov [here](https://github.com/bazelbuild/bazel/issues/3528) (search for 'jvm_import_external')

java_import_external was changed to `jvm_import_external` 'template like' rule + `java_import_external` macro in order to allow for other jvm languages (e.g. scala and kotlin) to utilize the 'import_external' functionality without copying the boiler plate again and again.

This has already been used in `rules_scala` with the introduction of `scala_import_external` and `scala_maven_import_external`

In addition to the `import rule name`, `jvm_import_external` can also be called with custom attributes needed by the underlying import rules, as well as a custom load statement.

`java_import_external` is used as a macro in rules_scala to make sure it's still functioning properly after the change.

`jvm_maven_import_external` exposes maven artifact terminology.
This will also allow to create a `maven_import_external` macro that will delegate to `jvm_maven_import_external` with a `maven_import` rule which will have `MavenCoordinates` Provider as discussed [here](https://github.com/bazelbuild/bazel/issues/4654)

### CODE REVIEW

**Comment by zaaraameera2014** [comment]
Google bot

**Comment by zaaraameera2014** [comment]
Ok thank u

**Comment by ittaiz** [comment]
cc [bazel-discuss thread](https://groups.google.com/d/msg/bazel-discuss/PTRJX8cUjNY/6Y99OJhjBwAJ) also #4876

**Comment by ittaiz** [comment]
@jart I’m not sure I understand the problem.
The user API did not change, right?
What is it that you’d like to change?

The motivation for templating the actual rule is to have reuse of the core
logic. It was suggested by @dslomov.

**Comment by ittaiz** [comment]
@dslomov I think we need your help here.
This change was strongly encouraged by you.

**Comment by jin** [comment]
This looks like it's just a drop in replacement for existing `java_import_external` calls?

**Comment by ittaiz** [comment]
it is

**Comment by jart** [comment]
> @jart I’m not sure I understand the problem. The user API did not change, right? What is it that you’d like to change?

I can't easily verify that is the case because this change rewrites the whole file. java.bzl is a high risk file to modify, because projects using it can pin the version of `@bazel_tools`, so breaking changes would break historical revisions, even if the user migrates to the new API. I'd recommend developing this new functionality in a different file. In that case, you can do anything you want, and I would have zero concerns.

**Comment by natansil** [comment]
@jart taken out the `jvm_import_external` definition to `jvm.bzl`.
If you compare `jvm.bzl` to the original `java.bzl` you will find there are only minor changes.

IIUC, you're suggesting to write a macro for java with a different name and keep the original `java.bzl` as well, but I think this would lead to 85% code duplication. 

Also the API hasn't changed at all (in terms of attributes of `java_import_external`)

**Comment by dslomov** [comment]
I generally like this idea. @jart, what is the nature of your objection? Looks like `java_import_external` user-facing API does not change, there is full backward compatibility for `java_import_external`.
Do we have tests for `java_import_external`? This should validate that it stays backward compatible now and in the future.

**Comment by dslomov** [comment]
ping @jart

**Comment by jart** [comment]
I took a closer look at the code. Is there a design doc for this? The main change that seems to be happening here is it'll accept Maven coordinate triplet strings.

I recommend using `java_import_external` with verbatim URLs. We need to be able to grep URLs (see [GitHub BigQuery](https://cloud.google.com/bigquery/public-data/github) dataset) in order to offer high availability mirroring via mirror.bazel.build. Folks who do things like `https://%s` or `maven:abbreviation:v1` will miss out on those reliability and performance benefits. Yes it makes your WORKSPACE file ugly, but it's worth it.

**Comment by jin** [comment]
> The main change that seems to be happening here is it'll accept Maven coordinate triplet strings.

@jart I think the main change here is abstracting the *_import rule generation away from the user interface (macro). With `jvm_import_external`, anyone can write a custom *_import rule and create an externalized version of it with `jvm_import_external.rule_name`. For one, I can create `android_import_external` easily by creating a macro that wraps `jvm_import_external` with `aar_import`.

**Comment by ittaiz** [comment]
@jingwen Exactly.
@jart It *allows* one to use it with maven coordinates while still allows
using URLs like you currently do.
Just for reference we have in rules_scala scala_import_external (uses URLs)
and scala_maven_import_external (uses coordinates).

“Yes it makes your WORKSPACE file ugly, but it's worth it.”-
1. Why are you the one making the tradeoff? Why not allow users to choose?
2. I think you’re also a bit wrong since you can pass in server_urls to the
maven macro which will append the maven coordinates URL to each server. If
the servers respect the maven coordinates url layout you’ll have many URLs.
3. Having maven as the abstraction layer enables propagating the maven
coordinates which many people want for easier bazel to maven export

**Comment by jart** [comment]
> I think the main change here is abstracting the *_import rule generation away from the user interface (macro).

@jin I understan;, I agree; I would ask if we've considered generalizing to *all* build rules, rather than just JVM? I would support Skylark automatically defining a `foo_external` for all `foo`. I consider repository rules like `java_import_external` and [`filegroup_external`](https://github.com/bazelbuild/rules_closure/blob/master/closure/filegroup_external.bzl) (see also [NodeJS](https://github.com/tensorflow/tensorboard/blob/master/third_party/js.bzl#L25), [DefinitelyTyped](https://github.com/tensorflow/tensorboard/blob/master/third_party/typings.bzl#L20)) to be simple one-off solutions. I want one to become infinity. I'm less excited about the integers between.

> 1. Why are you the one making the tradeoff? Why not allow users to choose?

@ittaiz I'm very interested in hearing more of what you have to say.

**Comment by ittaiz** [comment]
@jart I think I said what I have to say so I’ll repeat but if you can guide
me to what’s unclear I’d appreciate it.
I think the tradeoff is between resiliency and maintenance/readability.
Some organizations will be happy with their internal binary repository
(artifactory / nexus) and would rather have less duplication of the URLs
and have it be more readable.

**Comment by jart** [comment]
It's only worthwhile to go to the trouble of defining redundant URLs explicitly when you're a public project that wants its build definitions to be as universally reliable / performant as possible. For example, any Skylark rule that uses `repository_ctx.download` (e.g. `java_import_external`) will respect the `http_proxy` environment variable. That grants private entities the flexibility to use their own private storage / retrieval infrastructure when inheriting public definitions. This is also the case if you write a macro wrapper that fills in URLs for convenience.

**Comment by ittaiz** [comment]
@jart I’m sorry but I don’t understand the point you’re trying to make. Can
you please reiterate?
Btw, we want this change (and the usage of repository_ctx.download) mainly
for the external dependencies cache

**Comment by jart** [comment]
By we you're referring to rules_scala, correct? Is rules_scala blocked by this change? If so, why?

**Comment by dslomov** [comment]
@jart I think @ittaiz has argumented the point behind this change rather well. I do support the trade-off argument; it is important for the rules to be able to refer to maven coordinates as opposed to just urls, so that Bazel and Maven can interoperate.

**Comment by dslomov** [comment]
> @jin I understand; I agree; I would ask if we've considered generalizing to all build rules, rather than just JVM? I would support Skylark automatically defining a foo_external for all foo. I consider repository rules like java_import_external and filegroup_external (see also NodeJS, DefinitelyTyped) to be simple one-off solutions. I want one to become infinity. I'm less excited about the integers between.

I am not sure "I want one to become infinity. I'm less excited about the integers between." is a good reason to block this PR. We should first explore the "integers between" before we generalize.

**Comment by ittaiz** [comment]
In we I meant my company’s builds which need to cache the external
dependencies

**Comment by jart** [comment]
@ittaiz I sometimes use [stash.sh](https://gist.github.com/jart/8c5288db4398b8bd7a1e20f8deec4a16) to cache HTTP downloads, since it's easier than Squid, and cheaper than Artifactory. I was under the impression Bazel supported this, but just noticed 86a28b0fa2940377d5073071f79a81383fd7cfe3 which unsets `http_proxy` in `blaze.cc` to workaround a gRPC issue. Is this something that'd be helpful to you and your employer? Because that support could easily be added back via a flag.

**Comment by ittaiz** [comment]
I need a systematic and easy solution for many hundreds of external
dependencies.
I didn’t deep dive into the above script but I’m not sure that is it.

Additionally,
What is the problem you’re trying to solve?

It almost sounds like you’re trying to mandate people to work with URLs.
Why?
The suggestion is equally resilient if you have the same layout of the URL
as maven artifacts have.
The suggestion just asks you for base URLs of the servers and computes the
rest.

**Comment by jart** [comment]
The Bazel software is free as in freedom. I believe deeply in those values. Please treat me with the same respect I've given you.

Having a caching HTTP proxy like [stash.sh](https://gist.github.com/jart/8c5288db4398b8bd7a1e20f8deec4a16) is useful because you'll hit a point where GitHub starts sending `HTTP/1.1 429 TOO MANY REQUESTS` responses, or goes slow, or has an outage, or your policymakers are concerned about confidentiality. URL caching is zero config, language agnostic, and doesn't cost $30k/year like certain enterprise artifact management solutions. If that script saves your company money, send me a postcard.

**Comment by ronshapiro** [comment]
The current form of this PR doesn't handle android rules/aars. I imagine that we could, and probably should handle that, otherwise we raise the risk for another fork.

To go back to @jart's desire for infinity rules, one thing that may make this more concrete is a rule like so:

```python
download_file(
  name = "foo.jar",
  urls = [
    # list of url strings
  ],
  sha256 = "abcdefgh",
  licenses = [], 
)
```

That seems to be the minimum necessary to use `repository_ctx.download`. That file doesn't do a whole lot, but it does mean that I can now write the `java_import`, `scala_import`, `aar_import` directly on top of that. And people can define macros on top of it.

**Comment by ronshapiro** [comment]
The current form of this PR doesn't handle android rules/aars. I imagine that we could, and probably should handle that, otherwise we raise the risk for another fork.

To go back to @jart's desire for infinity rules, one thing that may make this more concrete is a rule like so:

```python
download_file(
  name = "foo.jar",
  urls = [
    # list of url strings
  ],
  sha256 = "abcdefgh",
  licenses = [], 
)
```

That seems to be the minimum necessary to use `repository_ctx.download`. That file doesn't do a whole lot, but it does mean that I can now write the `java_import`, `scala_import`, `aar_import` directly on top of that. And people can define macros on top of it.

(maybe that's the same as `native.http_file`, but with `licenses`?)

**Comment by jin** [comment]
> The current form of this PR doesn't handle android rules/aars. I imagine that we could, and probably should handle that, otherwise we raise the risk for another fork.

Yes, I plan to upstream parts of https://github.com/bazelbuild/gmaven_rules/blob/master/import_external.bzl into Bazel once this PR is resolved and merged.

**Comment by jart** [comment]
@ronshapiro That's how we did things before 2017, when we'd define a folder in `//third_party/java/...` to `java_library(name = "foo", exports = ["@foo//jar"], deps = ["//third_party/java/bar"])` because `maven_jar` doesn't have `deps`. The main concern is not having a canonical label across repositories. For example, is it `@args4j//jar` or `@io_bazel_rules_closure//third_party/java/args4j` or `@domain_registry//third_party/java/args4j`? Arching towards canonical labels isn't a strict requirement, but it does make things a lot simpler / elegant plus avoids `bind()` soup if folks can agree on names.

**Comment by ronshapiro** [comment]
That seems like two separate issues. `java_import_external` and `maven_jar` download the _file_ to different locations, but the actual rule for them both defines `@foo//jar`.

**Comment by ittaiz** [comment]
What does android support mean other than supporting the aar packaging?

Why do you think neverlink is a feature creep? To me it feels closely
related since this concept in bazel is very related to the declaration site

**Comment by jin** [comment]
@ronshapiro Here's the prototype PR: https://github.com/bazelbuild/bazel/pull/5319

**Pull request closed without merging**
