### PR TITLE
Update aosp_gradle_core in preparation for updating manifest merger to version 30.1.3

### PR DESCRIPTION
**Pull request by rjobredeaux3**
I'm in the process of updating the version of android_common, which hasn't been done in 6 years. The code under aosp_gradle_core depends on android_common and needs updating in preparation for this. This PR updates the code under aosp_gradle_core to be compatible with version 30.1.3. Since the transition to the new version cannot be atomically done with this change, I've made a copy of the file, on which I've made the required changes.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@rjobredeaux3 Can you also update the PR description, thanks!

**Comment by rjobredeaux3** [comment]
Following Yun's suggestion I have removed the jars from the PR and left it with just the update to aosp_gradle_core. We'll use the work in https://github.com/bazelbuild/bazel/pull/17112 to provide the jars via a maven import rule instead

**Comment by rjobredeaux3** [comment]
Erm, this can only work once https://github.com/bazelbuild/bazel/pull/17112 is submitted and the top-level WORKSPACE file is updated to contain the required android_common dependency

**Review by ahumesky — APPROVED** [review]

**Comment by rjobredeaux3** [comment]
@meteorcloudy Neither Alex nor I have permission to merge this, can you help with next steps?

**Comment by meteorcloudy** [comment]
The gTech team will help us merge third_party change as well. /cc @sgowroji 

@rjobredeaux3 Can you squash all the commits into one so that it's easier to merge?

**Comment by rjobredeaux3** [comment]
> The gTech team will help us merge third_party change as well, just add the `awaiting-PR-merge` label. /cc @sgowroji
> 
> @rjobredeaux3 Can you squash all the commits into one so that it's easier to merge?

Done.

**Comment by sgowroji** [comment]
Merged at 275198533372ee7958dfcb4167fb98fdfaceabef

**Pull request closed without merging**
