### PR TITLE
Windows: remove custom WindowsRunfiles impl.

### PR DESCRIPTION
**Pull request by laszlocsomor**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Please fix the test error? ;)

**Comment by laszlocsomor** [comment]
Oh, that's embarrassing. Thanks for the notice :)

**Comment by meteorcloudy** [comment]
Hmmm,, `//src/test/shell/bazel:bazel_bootstrap_distfile_test` is broken by this change

**Comment by laszlocsomor** [comment]
PTAL, should be fixed now.
I'll be more careful next time before sending out for review.

**Pull request closed without merging**
