### PR TITLE
Enable Bzlmod in shell integration tests

### PR DESCRIPTION
**Pull request by meteorcloudy**

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Failing shell tests after enabling Bzlmod:
- [ ] //src/main/starlark/tests/builtins_bzl:cc_builtin_tests                  
- [ ] //src/test/shell/bazel:bazel_coverage_hermetic_py_test                   
- [ ] //src/test/shell/bazel:bazel_coverage_java_jdk11_toolchain_head_test     
- [ ] //src/test/shell/bazel:bazel_coverage_java_jdk11_toolchain_released_test 
- [ ] //src/test/shell/bazel:bazel_coverage_java_jdk17_toolchain_head_test     
- [ ] //src/test/shell/bazel:bazel_coverage_java_jdk17_toolchain_released_test 
- [ ] //src/test/shell/bazel:bazel_coverage_java_test                          
- [ ] //src/test/shell/bazel:bazel_hermetic_sandboxing_test                    
- [ ] //src/test/shell/bazel:bazel_java17_test                                 
- [ ] //src/test/shell/bazel:bazel_with_jdk_test                               
- [ ] //src/test/shell/bazel:bazel_workspaces_test                             
- [ ] //src/test/shell/bazel:cc_flags_supplier_test                            
- [ ] //src/test/shell/bazel:check_external_files_test                         
- [ ] //src/test/shell/bazel:cross_repository_test                             
- [ ] //src/test/shell/bazel:execroot_test                                     
- [ ] //src/test/shell/bazel:external_correctness_test                         
- [ ] //src/test/shell/bazel:platform_mapping_test                             
- [ ] //src/test/shell/bazel:platforms_test                                    
- [ ] //src/test/shell/bazel:python_version_test                               
- [ ] //src/test/shell/bazel:runfiles_test                                     
- [ ] //src/test/shell/bazel:starlark_git_repository_test                      
- [ ] //src/test/shell/bazel/remote:remote_execution_http_test                 
- [ ] //src/test/shell/integration:aquery_test                                 
- [ ] //src/test/shell/integration:aspect_test                                 
- [ ] //src/test/shell/integration:bazel_aquery_test                           
- [ ] //src/test/shell/integration:bazel_java_test                             
- [ ] //src/test/shell/integration:cpp_test                                    
- [ ] //src/test/shell/integration:runfiles_test                               
- [ ] //src/test/shell/integration:target_compatible_with_test                 
- [ ] //src/test/shell/integration:build_event_stream_test                     
- [ ] //src/test/shell/bazel:bazel_example_test                                
- [ ] //src/test/shell/bazel:local_repository_test                             
- [ ] //src/test/shell/integration:sandboxing_test                             
- [ ] //src/test/shell/bazel:bazel_test_test                                   
- [ ] //src/test/shell/bazel/remote:remote_execution_test                      
- [ ] //src/test/shell/bazel:workspace_test                                    
- [ ] //src/test/shell/bazel:starlark_repository_test                          
- [ ] //src/test/shell/integration:configured_query_test                       
- [ ] //src/test/shell/integration:toolchain_test                              
- [ ] //src/test/shell/bazel:cc_integration_test                               
- [ ] //src/test/shell/integration:discard_graph_edges_test

**Comment by meteorcloudy** [comment]
@fmeum Can you help check why `test_incompatible_tool_system_classpath` from `//src/test/shell/bazel:bazel_java17_test` doesn't work when Bzlmod is enabled? The expected error message wasn't printed somehow.

**Comment by fmeum** [comment]
> @fmeum Can you help check why `test_incompatible_tool_system_classpath` from `//src/test/shell/bazel:bazel_java17_test` doesn't work when Bzlmod is enabled? The expected error message wasn't printed somehow.

This test overrides `java_tools` by adding repos to `WORKSPACE`, but with Bzlmod these repos aren't the source of truth for the tools.

**Comment by meteorcloudy** [comment]
@fmeum Can you take a look why `test_config_function` from `//src/test/shell/integration:configured_query_test` is failing?

**Comment by fmeum** [comment]
> @fmeum Can you take a look why `test_config_function` from `//src/test/shell/integration:configured_query_test` is failing? I feel it might be a bug in Bazel when Bzlmod is enabled.

@meteorcloudy Yes, this appears to be a bug in Bazel with Bzlmod enabled. When I recreate the setup of the integration test in a reproducer and run `bazel cquery "deps(//$pkg:demo)"` followed by `bazel config`, I get four reported configurations when running with `--noenable_bzlmod`, but no configurations when running with `--enable_bzlmod`.

CC @gregestren

**Comment by gregestren** [comment]
> 
> CC @gregestren Do you happen to have an idea why configs may be dropped with Bzlmod?

No but I'll look.

What ETA are you looking at for bzlmod flipping?

**Comment by meteorcloudy** [comment]
@gregestren Thanks! We can fix this even after the release cut by backporting. So this isn't blocking the release cut, just the final release, which is expected to be baked for at least a month based on past experience.

**Comment by meteorcloudy** [comment]
FYI, @katre is also looking into this.

**Pull request closed without merging**
