### PR TITLE
http: handle SocketTimeoutException directly

### PR DESCRIPTION
**Pull request by beasleyr-vmw**
SocketTimeoutException derives from InterruptedIOException, but its occurrence
in HttpConnectorMultiplexer (HCM) is truly distinct from a HCM-prompted job
control interruption, and it should be resported as such.  Otherwise users
may only see "java.net.IOException: thread interrupted" when a download fails.

NB: I'm not a Java developer.  (Should `catch InterruptedIOException`
include an `if (Thread.interrupted())` check instead?)

Relates to #10294.

### CODE REVIEW

**Comment by laurentlb** [comment]
@aehlig Can you review this PR?

**Comment by aiuto** [comment]
ping

**Comment by aiuto** [comment]
another ping, but with new reviewers

**Comment by ahumesky** [comment]
thanks!

**Pull request closed without merging**
