### PR TITLE
Fixed error message

### PR DESCRIPTION
**Pull request by alex**
The product is now named bazel and that's the binary people have installed.

### CODE REVIEW

**Comment by janakdr** [comment]
The product is still called blaze internally at Google. You can use the
GetProductName function just as it's used on the lines above and below your
change to fix the issue you're addressing in a portable way.

**Comment by alex** [comment]
@janakdr done. thanks!

**Comment by janakdr** [comment]
Thanks for the proposed change, it looks good! Have you read the steps at
http://bazel.io/contributing.html? Unfortunately I think we're not yet set
up to accept git pull requests directly.

**Comment by kchodorow** [comment]
We can import changes from a GitHub pull request for simpler changes (which this qualifies as).  I'll import it now.

**Comment by damienmg** [comment]
This was merged, closing

**Pull request closed without merging**
