### PR TITLE
Support other default C++ standards instead of 11

### PR DESCRIPTION
**Pull request by abergmeier**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by abergmeier** [comment]
@damienmg Please validate whether change will be upstreamed. Will add tests then.

**Comment by mhlopko** [comment]
Looking good, pls update list of env variables in cc_configure.bzl.

**Comment by abergmeier** [comment]
What about replacing that with a general handling for `cxx_flag`? Then we do no need a special case for std.

**Comment by mhlopko** [comment]
I'd actually prefer that. Call it BAZEL_CXX_FLAGS or smth?

**Comment by abergmeier** [comment]
I'll try that as part of https://github.com/bazelbuild/bazel/pull/4123 then.

**Comment by philwo** [comment]
@abergmeier Shall we close this PR now that you put the changes into #4123?

**Comment by mhlopko** [comment]
I understand so. Andreas please complain if that is not the case :)

**Pull request closed without merging**
