### PR TITLE
Reland Unicode bug fixes

### PR DESCRIPTION
**Pull request by fmeum**
Compared to the original commit a58fe3fa6b9ab1f7bfcd1ad8c94ab1f09a4cca39, which was rolled back in https://github.com/bazelbuild/bazel/commit/fc6b384772c41feff9fe572735d64b2ef021932b, this change restores the UTF-16 code fallback in `latin1_jni_path.cc` and logs paths that result in it being taken.

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io fork 8.0.0

**Comment by lberki** [comment]
Hold on for a bit; we are discussing with @tjgq @justinhorvitz @haxorz  how to avoid causing trouble at Google again. 

@fmeum do you think it would be possible to surface the "there was an encoding issue" information to Java? (it'd be nice to have a Java call stack available for failures)

**Comment by fmeum** [comment]
> @fmeum do you think it would be possible to surface the "there was an encoding issue" information to Java? (it'd be nice to have a Java call stack available for failures) 

I discussed this with @tjgq, the second commit in this PR (https://github.com/bazelbuild/bazel/commit/43ddb08db7c51e90be43dd6bf12dbf7b833994a3) logs up to one problematic path, including a stack trace.

**Comment by lberki** [comment]
Well that's a delightful case of acausal development then, my wishes being fulfilled before I voice them :)

@justinhorvitz @haxorz I'd be inclined to call `BugReport.logException()` instead because I do know that we have tools to collate those, but maybe way have ways to do so for `logger.atInfo().withStackTrace()`, too?

**Comment by tjgq** [comment]
> Well that's a delightful case of acausal development then, my wishes being fulfilled before I voice them :)
> 
> @justinhorvitz @haxorz I'd be inclined to call `BugReport.logException()` instead because I do know that we have tools to collate those, but maybe way have ways to do so for `logger.atInfo().withStackTrace()`, too?

To summarize internal discussions: we're indeed going with `BugReport` (which makes it easier to find and fix cases where the precondition fails to hold at Google). I'll make these changes myself since it's easier than going back-and-forth here on GitHub.

**Comment by meisterT** [comment]
> @bazel-io fork 8.0.0

While these changes are great and they improve Bazel (and the Bazel codebase!), I don't think we should cherry-pick non-bug-fixes at this stage of the release cycle (cc @Wyverald).

**Comment by fmeum** [comment]
> While these changes are great and they improve Bazel (and the Bazel codebase!), I don't think we should cherry-pick non-bug-fixes at this stage of the release cycle (cc @Wyverald).

I don't mind if we arrive at the conclusion that this shouldn't be cherry-picked because it's too big, but it really is nothing more than a large collection of bug fixes. It was only rolled back due to Google-internal tools using parts of the Bazel codebase for other purposes.

**Comment by fmeum** [comment]
Merged in https://github.com/bazelbuild/bazel/commit/1744d45c0c57af23f631c2145e8af4b185dca77f

**Comment by iancha1992** [comment]
> Merged in [1744d45](https://github.com/bazelbuild/bazel/commit/1744d45c0c57af23f631c2145e8af4b185dca77f)

@fmeum let me know if you want to cherry-pick this for 8.0.0. Thanks

**Comment by fmeum** [comment]
@iancha1992 I would support that cherry-pick, but I'll leave it to @Wyverald to make the call.

**Pull request closed without merging**
