### PR TITLE
remote: add aws auth for remote caching

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by buchgr** [comment]
@GregBowyer when merging your PR I had to split it into two (third_party and none-third_party). This is is the none-third_party part. Do you remember what the issue for Windows failures was?

**Comment by GregBowyer** [comment]
Its down to newline parsing in the unit test. I was fixed by @jjudd by adding to `.gitattributes` here https://github.com/bazelbuild/bazel/pull/4889/commits/c3c336c13c79a66bdbdcf39c62eae9995fc66b0d#diff-fc723d30b02a4cca7a534518111c1a66

The unit test reads the file up from the OS and typically adds the OS native line endings. This causes windows to have an errant `\r` that the tests will ignore as that is not per spec.

**Comment by jjudd** [comment]
Yep. As far as I'm aware, the functionality was fine, but the `\n` on Linux vs `\r\n` on Windows was causing test failures. Hence the `.gitattributes` change.

**Comment by buchgr** [comment]
It seems to fail even with the `.gitattributes` file?

**Comment by buchgr** [comment]
I think I am missing something here. My understanding of the `.gitattributes` file is that these rules are applied on checkout. The rules in there state that git should not convert the line endings of files in third_party/aws* to `\n\r` but just check them out as they are. Correct?

**Comment by jjudd** [comment]
AFAIK, that is correct.

When I had Windows test failures on this branch, I would get different test results based on the `core.autocrlf` setting in git. This is why I set `.gitattributes` to not change the line endings of the test files.

Taking a look at the test failure now to see if this is the same thing.

**Comment by jjudd** [comment]
Aight. I have my VM up and running again. I'll try to repro the failures and if I can, I'll create a PR that fixes them.

**Comment by jjudd** [comment]
Been looking at this off and on throughout the day. Something funky is going on when a file is read out of a jar on windows. There are no carriage returns on disk, but the file when read from the resource loader has some. Hope to have a PR for this today.

**Comment by jjudd** [comment]
Aight. It's a git thing. It was caused by splitting the commit, but not including the `.gitattributes` change. 

I'm not sure how Bazel CI works, but I imagine it has some kind of existing git state and then moves to a different commit? Otherwise this failure doesn't make sense to me.

On my Windows machine, if the files that need to have `lf` endings already are checked out with `crlf`, then this PR's commit does not change them to `lf`.

If I 
* delete the aws test directory and then `git checkout` that directory
* or move from a commit that does not have these files to a commit that does have these files at this commit
then the correct line endings are present.

For example.

On master with a fresh checkout of the `aws-sig-v4-test-suite` directory, after the third_party commit. Everything is crlf:
```
PS C:\Users\james\opensource\bazel\third_party> git ls-files --eol .\aws-sig-v4-test-suite\
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/BUILD
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/LICENSE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/NOTICE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/README.md
i/none  w/none  attr/                   aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.authz
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.creq
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.req
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.sreq
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.sts
```

Moving to this branch from master, without deleting and re-checking out the directory. Everything is still crlf:
```
PS C:\Users\james\opensource\bazel\third_party> git ls-files --eol .\aws-sig-v4-test-suite\
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/BUILD
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/LICENSE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/NOTICE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/README.md
i/none  w/none  attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.authz
i/lf    w/crlf  attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.creq
i/lf    w/crlf  attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.req
i/lf    w/crlf  attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.sreq
```

After deleting the `aws-sig-v4-test-suite` directory and checking out the directory again, `lf` endings are correctly used for the test files.
```
PS C:\Users\james\opensource\bazel\third_party> git ls-files --eol .\aws-sig-v4-test-suite\
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/BUILD
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/LICENSE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/NOTICE
i/lf    w/crlf  attr/                   aws-sig-v4-test-suite/README.md
i/none  w/none  attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.authz
i/lf    w/lf    attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.creq
i/lf    w/lf    attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.req
i/lf    w/lf    attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.sreq
i/lf    w/lf    attr/-text              aws-sig-v4-test-suite/get-header-key-duplicate/get-header-key-duplicate.sts
```

I don't know how to fix this. Anyone ran into this before who knows? Perhaps something other than `-text` needs to be used in the `.gitattributes` file?

**Comment by jjudd** [comment]
Wanted to ping this and see what next steps are.

**Comment by buchgr** [comment]
@jjudd thanks for taking a look. Do I understand correctly that we'd need to check in the `.gitattributes` changes before checking in the third party `aws-sig-v4-test-suite`?

**Comment by jjudd** [comment]
I think if they were checked in at the same commit as the changes, that would work as far as I understand. 

I think the issue is that anyone who has the files checked out currently will have them with CRLF line endings and changing `.gitattributes` doesn't affect those files until they are modified or checked out.

I'm not git expert, though. Perhaps there is a way to cause `.gitattributes` line ending changes to impact clones without needing to recheck something out.

**Comment by buchgr** [comment]
Even if the files are in the same commit, it doesn't seem to work: https://github.com/bazelbuild/bazel/pull/6911

**Comment by buchgr** [comment]
I tried a few more things - including the .gitattributes file and the SDK in the same commit, but didn't work. The thing that strikes me is that the error message is `a header value must not end with '\r' or '\n':value2` ... so why would this work even if we kept line endings at LF?

**Comment by jjudd** [comment]
This is definitely a line ending issue. I can reproduce that error when the line endings in the test files are `\r\n` but not when they are `\n`. The test splits lines on `\n`, so with `\r\n`, header lines end with `\r`, which causes the error: `a header value must not end with '\r'`.

@buchgr does the Bazel CI start from a clean checkout every time or does it already have a repo on disk somewhere? I imagine it is the latter. The issue I ran into during my testing is that once a file is checked out on disk with a certain line ending, the line ending will not change if just `.gitattributes` is changed. Perhaps if a change was made to the file, then Git would change the line ending.

I imagine this can be fixed by either
1. Making a change to the files such that Git changes the line endings, even if the file is already checked out. This should be relatively easy to test.
2. Reverting the commit which added these files, waiting until CI and other users remove those files, and then readding them with the `.gitattributes` file in a single commit. I imagine this will be error prone - if anyone checks out an old commit and then moves to a new commit with the files re-added, I don't think Git will modify their line endings.

**Comment by buchgr** [comment]
We always do a clean checkout on CI but reference a local git bundle so that we don't need to clone everything from remote.

```
git clone -v --reference c:\buildkite\bazelbuild -- https://github.com/bazelbuild/bazel.git .
```

> The test splits lines on \n, so with \r\n, header lines end with \r, which causes the error: a header value must not end with '\r'.

@jjudd how hard would it be to fix the test to use platform specific split?

**Comment by jjudd** [comment]
Not sure. I know that @GregBowyer tried that. I'm not sure if it worked. I went the `.gitattributes` route. I should be able to play around with this some more tomorrow. I'm not sure I'll have time this afternoon.

**Comment by jjudd** [comment]
Aight. A bit later than expected, but I'll have time to take a look at this today. Hope to have a solution by either changing the test or figuring out why `.gitattributes` behaves the way it does.

**Comment by buchgr** [comment]
@philwo would it be an option to disable the gitbundle for this CL if it turns out for that to be the issue?

**Comment by jjudd** [comment]
I did more digging into EOL stuff in Git yesterday. In the Bazel repo, the tests files are part of the index as `lf`, but get checked out as `crlf` if you have `core.autocrlf` set to true. Even if you set those files to be `-text` or `text eol=lf` in `.gitattributes`. 

When I do `git ls-files --eol .\third_party\aws-sig-v4-test-suite\` on master, files look like this

```
i/lf    w/crlf  attr/                   third_party/aws-sig-v4-test-suite/post-x-www-form-urlencoded/post-x-www-form-urlencoded.sts
```

After I switch to a branch which has `text eol=lf` or `-text` set in `.gitattributes` I get something like this

```
i/lf    w/crlf  attr/text eol=lf        third_party/aws-sig-v4-test-suite/post-x-www-form-urlencoded/post-x-www-form-urlencoded.sts
```

If I delete those files and check them back out, then both the index and working tree show `lf`.

I can't figure out a way to make Git convert the line endings of files in the working tree without checking them out again. 

I'm going to attempt to make the test work with multiple line endings.

**Comment by jjudd** [comment]
@buchgr your branch has a PR to make line endings normalized in these tests. They pass regardless of line endings on Windows and Linux. I don't have a Mac to test on.

**Comment by GregBowyer** [comment]
@jjudd thanks for that

**Comment by jjudd** [comment]
I am ok with my commits being contributed to this project.

**Comment by jjudd** [comment]
Ahoy. Want to check what the latest on this is @buchgr. We good for review, what else needs to be done?

**Comment by buchgr** [comment]
@jjudd I ll import it tonight! thanks for all the fixes.

**Comment by jjudd** [comment]
Awesome! :smile:  Please let me know if there's anything else we need to do.

**Comment by buchgr** [comment]
@jjudd I listed you as co-author and greg as author in the commit. is that ok?

**Comment by jjudd** [comment]
Up to @GregBowyer. He did all the hard work, I just fixed bugs :D

**Comment by buchgr** [comment]
I have sent it for review internally. Assuming all goes well it should be on github in a few hours.

**Comment by buchgr** [comment]
@jjudd there's been another delay. I ll need to refactor the code a bit in order to not introduce a aws dependency to the google internal codebase.

**Comment by philwo** [comment]
I can confirm that it's imported and reviewed 😏 As soon as we can convince the internal test system to not turn red, it goes in. :D

**Pull request closed without merging**
