### PR TITLE
Add Updating Bazel back into navigation

### PR DESCRIPTION
**Pull request by floriographygoth**

### CODE REVIEW

**Review by gregestren — APPROVED** [review]
I'm fine either way, but did you say you wanted a distinct section here or to put it under "Backward Compatibility"?

**Review by Rada8732 — APPROVED** [review]

**Comment by aiuto** [comment]
@Rada8732 Please stop approving PRs for projects you do not work on. It is unhelpful.

**Comment by aiuto** [comment]
Friendly ping. Are we each waiting for someone else to merge?

**Comment by gregestren** [comment]
I was waiting for feedback on my question. But it's try I approved the PR. I'd still like a confirmation since this is a bit old now and doc navigation moves quickly.

**Pull request closed without merging**
