### PR TITLE
Flip incompatible_enable_cc_toolchain_resolution

### PR DESCRIPTION
**Pull request by comius**
RELNOTES[INC]: Flip incompatible_enable_cc_toolchain_resolution (https://github.com/bazelbuild/bazel/issues/7260)

### CODE REVIEW

**Review by lberki — APPROVED** [review]
This is great. I mean, it will be great when it sticks, but merging this pull request is a necessary part of the path for getting there :)

**Comment by comius** [comment]
Downstream tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2641#01835443-ca23-4d89-b700-dd2ef89c8f7a

Failures:
- rules_android_ndk: doesn't have platform configuration, should disable cc_toolchain_resolution flag in bazelci
- rules_foreign_cc: ?
- Gerrit: ?
- Google Logging: ?
- rules_perl: Missing `use_cpp_toolchain`
- Other failures are preexisting: upb, Tensorflow, Android Studio Plugin

**Comment by comius** [comment]
Failing test needs rules_cc 0.0.2 on bzlmod repository.

**Comment by meteorcloudy** [comment]
You can also view the broken downstream project here:
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1264

image

**Pull request closed without merging**
