### PR TITLE
Quick and dirty fix for #456.

### PR DESCRIPTION
**Pull request by JackSullivan**
#456

### CODE REVIEW

**Comment by JackSullivan** [comment]
I've signed the CLA.

**Comment by laurentlb** [comment]
I won't change the time on the individual files. I suggest this instead (untested):
find {out}_tmp -exec touch -t 198001010000 {} \;

**Comment by JackSullivan** [comment]
@laurentlb I'm afraid I don't follow, are you saying we don't want to change the time or that what I proposed doesn't work. On my machine (Mac OSX) when I extract jars produced in #458 all of the files have Jan 1, 1980 as their create date. Let me know if this doesn't generalize.

**Comment by hanwen** [comment]
Laurent said he was wrong. I'm importing this patch.

**Pull request closed without merging**
