### PR TITLE
Delete android_common v25 and references.

### PR DESCRIPTION
**Pull request by rjobredeaux3**
Related https://github.com/bazelbuild/bazel/issues/17036

### CODE REVIEW

**Review by ahumesky — APPROVED** [review]

**Review by meteorcloudy — APPROVED** [review]
Awesome! Is this still draft?

**Comment by meteorcloudy** [comment]
Do you have plan to migrate the rest of the android jars to `maven_install_android`?

**Comment by rjobredeaux3** [comment]
The switch to the new version just happened so I want to wait a few days (probably until next week) to see if issues arise before I delete the old jars. As for the rest of the android jars there are no immediate plans to migrate them, I suspect this will happen as starlarkification of the rules progresses but we don't have a set timeline for this.

**Comment by ahumesky** [comment]
I believe this is covered by https://github.com/bazelbuild/bazel/commit/94d5d53ff4ac75abf24f0e1eaf249ce7d3830ae5

**Pull request closed without merging**
