### PR TITLE
Document and test toolchain registration order

### PR DESCRIPTION
**Pull request by fmeum**
Related Slack discussion: https://bazelbuild.slack.com/archives/C014RARENH0/p1696893626545609

### CODE REVIEW

**Comment by fmeum** [comment]
CC @Wyverald

**Review by aherrmann — APPROVED** [review]
Thank you!

**Comment by fmeum** [comment]
CI failures seem unrelated, I think that one of the Darwin runners is out of disk space.

**Review by katre — APPROVED** [review]
Thanks!

**Review by Wyverald — APPROVED** [review]

**Pull request closed without merging**
