### PR TITLE
the build file and bash example out of synch

### PR DESCRIPTION
**Pull request by shlomi-shemesh**
comparing to the latest code in the java tutorial repo

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by shlomi-shemesh** [comment]
I signed it!

**Comment by spomorski** [comment]
The tutorial was correct. It's the sample project file that needs fixing. I am going to submit a fixed project file and revert this doc change. In the future, please run doc reviews by either me or michelleirvine.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
