### PR TITLE
Integrate abseil-py to replace deprecated gflags with absl.flags

### LINKED ISSUE #3816: pkg_tar fails to import gflags when using py3
From https://github.com/bazelbuild/rules_docker/issues/169

On Linux Ubuntu 14.10 and bazel 0.5.4:
```
$ bazel build --force_python=py3 --python_path=/usr/bin/python3 :bazel-srcs
INFO: Analysed target //:bazel-srcs (0 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/dmarting/git/bazel/BUILD:63:1: error executing shell command: 'bazel-out/host/bin/tools/build_defs/pkg/build_tar --flagfile=bazel-out/local-py3-fastbuild/bin/bazel-srcs.args' failed (Exit 1)
Traceback (most recent call last):
  File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/4c68128ea7d752c9535d956d14249eea/bazel-sandbox/5414131446493874244/execroot/io_bazel/bazel-out/host/bin/tools/build_defs/pkg/build_tar.runfiles/io_bazel/tools/build_defs/pkg/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/usr/local/google/home/dmarting/.cache/bazel/_bazel_dmarting/4c68128ea7d752c9535d956d14249eea/bazel-sandbox/5414131446493874244/execroot/io_bazel/bazel-out/host/bin/tools/build_defs/pkg/build_tar.runfiles/io_bazel/third_party/py/gflags/__init__.py", line 1, in <module>
    from gflags import *
ImportError: No module named 'gflags'
Target //:bazel-srcs failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.721s, Critical Path: 0.83s
FAILED: Build did NOT complete successfully
$ bazel build :bazel-srcs
INFO: Analysed target //:bazel-srcs (0 packages loaded).
INFO: Found 1 target...
Target //:bazel-srcs up-to-date:
  bazel-bin/bazel-srcs.tar
INFO: Elapsed time: 0.867s, Critical Path: 0.03s
INFO: Build completed successfully, 2 total actions
```

### PR DESCRIPTION
**Pull request by akirabaruah**
Fixes #3816 (Python 3 incompatibility issue). May also help address:
* #1580 
* #3871 
* #3872 
* #4097 
* bazelbuild/rules_docker#57

As of version 3.1.1, [python-gflags](https://pypi.python.org/pypi/python-gflags) has been marked obsolete, preferring the `flags` subpackage of [absl-py](https://pypi.python.org/pypi/absl-py/0.1.1) (a.k.a. [abseil-py](https://github.com/abseil/abseil-py)) as a replacement.

I've followed existing convention and placed all source files from the `absl-py` PyPI tarball inside `third_party/py/abseil/` and subsequently removed the existing `third_party/py/gflags/` package.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
As I mentioned in the description, the current convention seems to involve committing all files of a third-party Python dependency rather than using the [http_archive](https://docs.bazel.build/versions/master/be/workspace.html#http_archive) or [new_http_archive](https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive) rule. Is there a reason to include all third-party source files directly in this repo? It would probably be simpler to update dependencies using the `http_archive` rules instead of committing entire packages.

**Comment by damienmg** [comment]
(for Jenkins: test this please)

Can you rebase your change? Also since it touches third_party and non-third_party it will take me some time to merge.

**Comment by damienmg** [comment]
And thanks for doing that. This is definitely a good idea :)

**Comment by damienmg** [comment]
retest this please

**Comment by damienmg** [comment]
weird errors, let's try again: retest this please.

**Comment by akira-baruah** [comment]
@damienmg I've rebased this branch to master.

**Comment by akira-baruah** [comment]
Is there any decision on including upstream abseil source vs. using the `http_archive` rule? This branch currently includes the entire source, since that was the existing convention.

**Comment by damienmg** [comment]
Jenkins: test this please

@akira-baruah: the decision so far is to vendor the sources. I want people to use `{new_,}local_repository` now to point to the third_party directory so we can replug them when we need, but this is not a requirement.

**Comment by akira-baruah** [comment]
`tools/android/incremental_install_test.py` failed.

- `Adb._Exec()` tries to access a flag directly. The test calls this function, but doesn't parse any flags, so abseil.flags throws an `UnparsedFlagAccessError`.
- The old `gflags` module [allowed unparsed flags access](https://github.com/google/python-gflags/blob/9f00edd8bb0c8c0019f98541655263d5923cec0a/gflags/flagvalues.py#L490) under test conditions.
- The replacement `absl.flags` deprecates this behavior and [doesn't allow unparsed flag access](https://github.com/abseil/abseil-py/blob/ed0faa035139d118806802c06eba7f02abd3e2a9/absl/flags/_flagvalues.py#L468).

One solution is to provide the flag value as an arg to `Adb`'s constructor, so that the flag value can be parsed in `main()` first and passed to the contructor safely. This arg can default to an empty list in the case that extra ADB args are not passed (i.e. the failing test).

**Comment by akira-baruah** [comment]
@damienmg I think this is ready to be retested

**Comment by damienmg** [comment]
retest this please

**Comment by damienmg** [comment]
(that was for jenkins)

**Comment by hwright** [comment]
I can confirm that this PR fixes the issue as originally reported.

**Comment by akira-baruah** [comment]
@damienmg I rebased with master to remove a merge conflict, so it might be a good time to retest?

**Comment by hwright** [comment]
It would be nice to see this merged; it fixes a few issues with python 3 compatibility, particularly in the docker rules.

(I'll also note that it does break a few things as well, since the abseil modules export different symbols than their gflags counterparts, but those problems are trivial to fix.)

**Comment by akira-baruah** [comment]
@ulfjack I've rebased this branch to master. There are failing tests, but they seem to be the same as those on the master branch. Please let me know if you need me update anything here.

**Comment by ulfjack** [comment]
Looks good to me; thank you very much.

I'm traveling this week and next, and won't be able to help with merging until I'm back home. Note that most of the team is out this week, and we're also all at the Bazel summit in California next week, which may delay this until the week after. Sorry about that.

@damienmg did you just want me to take a look or do you need help?

**Comment by akira-baruah** [comment]
Cool! Thanks for the update @ulfjack 

Is the Bazel Summit open to the public? I couldn't find much info on the web or in the [Google Group](https://groups.google.com/forum/#!searchin/bazel-discuss/bazel$20summit%7Csort:date/bazel-discuss/O73yUt9jJ4o/eu1hZ45qAgAJ), but I'd be interested in seeing what kinds of talks are being held.

**Comment by ulfjack** [comment]
This should be publicly accessible:
https://conf.bazel.build/schedule

**Comment by damienmg** [comment]
@ulfjack: sorry I should have been clearer, I am trying to offload too many third-party change as per your advice. Merging this one require some dancing so I do not want to "delegate" to someone. Someone on the sheriff rotation need to be involved in this merge.

**Comment by akira-baruah** [comment]
@ulfjack I've rebased to master. No rush - just trying to keep this branch fresh.

Sounds like the first BazelCon was a success. I'm bummed I couldn't attend this year, but I'm looking forward to watching the talks when they come out!

**Comment by hwright** [comment]
It would be nice to see this go in before the next release (although I realize 0.8.0 has already been cut).  This looks to fix #3816, which itself is required to fix the use of the docker rules with py3.

**Comment by hwright** [comment]
I don't mean to be a pest (and I'm not even the author of this PR!), but could the assigned reviewer (@ulfjack, I believe) take a look at this?  It's been open for almost five weeks, with very little traffic from the core Bazel team in the last three.  The contributing guidelines (https://bazel.build/contributing.html) seem to indicate that 2 business days is the SLO for review, and this PR has been lingering well beyond that.

I have work in other repositories which depends on this PR, and it'd be nice to have it in the next Bazel release.  Given the upcoming US holiday, in practice, it means that it should be reviewed/merged this week.  Please take a look.

**Comment by akira-baruah** [comment]
@ulfjack I've rebased to master. It sounds like quite a few downstream projects depend on this change, so please let me know if there's anything I can do to help expedite merging this PR. Thanks!

**Comment by akira-baruah** [comment]
Friendly ping @ulfjack @damienmg any updates regarding this merge?

I've been updating the PR description to include affected issues - as you can see the number of those issues is increasing. I'd love to help, but I'm not sure if I've missed something or if it's internal dependencies holding up the merge.

Thank you!

**Comment by akira-baruah** [comment]
@hwright it seems like bazelbuild/rules_docker#229 which was previously blocked by this PR has been resolved. Are you still blocked by this merge?

If there's anything I can do to help unblock you, please let me know. Thanks!

**Comment by hwright** [comment]
@akira-baruah Yes, I believe I'm unblocked.

(Though I'd still like to see this PR merged at some point.)

**Comment by gunan** [comment]
Ping!
I think for TF mobile builds we need this change.
@damienmg @ulfjack any updates?

**Comment by hwright** [comment]
@akira-baruah Sadly, I was mistaken: I'm still blocked by this.  #3816 was opened in place of bazelbuild/rules_docker#169, which is the core problem I'm (still) having.

**Comment by ulfjack** [comment]
I've merged the first two commits - I have to merge changes to third_party separately. I'm working on the third commit right now.

**Comment by ulfjack** [comment]
Please split up the fourth commit to separate the third_party and non-third_party changes. This requires doing it in three steps: 1. add absl, 2. change code to use it, 3. remove gflags.

We don't currently have a compatible version of gflags 3.1.1 internally, so I can't easily import the third commit. However, I'm not sure it's necessary if we go with the changes above?

**Comment by hwright** [comment]
@ulfjack Should step (3) wait for a subsequent Bazel release?

I'm envisioning the scenario where downstream users are depending upon the old package in `third_party`, and it disappears out from under them without any warning a new Bazel release.  Having both present in an interim given release, while not required by the compatibility guidelines, would probably be good form.

**Comment by aj-michael** [comment]
Ulf, I think merging fb15f0f broke Android: #4208. I'm having a hard time reading the github UI, so apologies if this is not the pull request that created fb15f0f.

**Comment by akira-baruah** [comment]
@ulfjack thanks for moving forward with the merge!

I rebased the remaining commits to master and split out the "replace gflags with absl.flags' commit into 3 separate commits, as you asked.

The commit removing gflags entirely has been moved to the end of the sequence, so that step can be deferred to a subsequent release as @hwright suggested.

**Comment by akira-baruah** [comment]
@ulfjack The `Replace gflags with absl.flags` commit is now ready for review / merge. The subsequent commit involving a small refactor is required to properly use absl.flags. Would you like me to combine them into one single commit?

**Comment by ulfjack** [comment]
I'm looking into merging the second commit of the current stack right now. It looks like it's passing all tests. I haven't looked at the third commit yet, but if I can merge that, I'll skip the first commit entirely. Also, I don't think we need to keep the copy of gflags in Bazel - I am not concerned about someone depending on that from external.

**Comment by yilei** [comment]
Is this still being worked on?

**Comment by akirabaruah** [comment]
Thanks for the bump @yilei - I'd love to complete this merge. @ulfjack is there anything that's preventing this merge?

**Comment by lfpino** [comment]
Hi @ulfjack, Bazel sheriff here, what's the status of this pull request? It hasn't been updated in a very long time so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by ulfjack** [comment]
Sorry for the delay, I haven't been able to keep up with email. I am not aware of anything blocking a merge, although we'll have to merge the changes individually (we can't import changes to third_party and non-third_party code in an atomic change).

**Comment by ulfjack** [comment]
Okay, I can't import the first patch as-is, because it doesn't work with our internal version of gflags. Maybe I can merge the first two patches, and import that?

**Comment by akirabaruah** [comment]
Merging the first two patches as one sounds good to me!

**Comment by aiuto** [comment]
Jon: Since you own Python rules now, can you take a look and see if this makes sense to merge or is obsolete?

**Comment by yilei** [comment]
Ping?

**Comment by aiuto** [comment]
Closing this.

- It is a year old with no activity.
- AFAICT, all the code has move to absl.flags already, so this would be redundant.

**Pull request closed without merging**
