### PR TITLE
Add cc_toolchain targets for the new entries in the default

### LINKED ISSUE #6662: 0.19.1: `@bazel_tools//tools/cpp:cc-compiler-local-k8' is not a cc_toolchain rule`
### Description of the problem / feature request:

C++ builds fail with:

```
ERROR: The label '@bazel_tools//tools/cpp:cc-compiler-local-k8' is not a cc_toolchain rule
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

On Linux/amd64, in an otherwise empty workspace with an empty WORKSPACE file, run:

```
bazel build --crosstool_top=@bazel_tools//tools/cpp:default-toolchain //...
```

### What operating system are you running Bazel on?

Linux (Debian variant)

### What's the output of `bazel info release`?

```
release 0.19.1
```

###  Have you found anything relevant by searching the web?

In the file https://github.com/bazelbuild/bazel/blob/0.19.1/tools/cpp/BUILD:

On the 0.19.0 tag, [this line](https://github.com/bazelbuild/bazel/blob/f0c844c77a2406518c4e75c49188390d5e281d3d/tools/cpp/BUILD#L100) refers to `cc-compiler-local`, a `cc_toolchain` rule that exists.

On the 0.19.1 tag, [this line](https://github.com/bazelbuild/bazel/blob/eb2af0f699350ad187048bf814a95af23f562c77/tools/cpp/BUILD#L100) refers to `cc-compiler-local-k8`, a `cc_toolchain` rule that does not exist.

This appears to be the cause of the issue, although I am not sure why this was changed.

### PR DESCRIPTION
**Pull request by katre**
cc_toolchain_suite.

Fixes #6662.

### CODE REVIEW

**Comment by katre** [comment]
This fixes the immediate issue, but since I don't understand why the code is in the current state I don't know if it's the right fix.

**Comment by lberki** [comment]
I'll let @scentini judge -- I *think* this is simply because there is a discrepancy between the labels in the `toolchains` attribute of `default-toolchain` and the actual names of the `cc_toolchain` rules by mistake and thus the right answer is to rename them and not to add a new one.

**Comment by scentini** [comment]
Yes, this is a discrepancy between the default-toolchain values and the actual cc_toolchain names, introduced in c3fb1db. Reverting the [changes made to default-toolchain](https://github.com/bazelbuild/bazel/commit/c3fb1db9e4e817e8a911f5b347b30f2674a82f7c#diff-3235599013b541d4c41fbf2f5f169238L91) should do.

**Comment by katre** [comment]
I will update this PR and send it shortly.

**Pull request closed without merging**
