### PR TITLE
Fix link to Skylark Linter docs from main docs navigation

### LINKED ISSUE #4202: Extensions > Linter documentation doesn't exist (HTTP 404)
### Description of the problem / feature request / question:

If you go to the Bazel documentation and select "Linter", you get a Page not found error.

### If possible, provide a minimal example to reproduce the problem:

Go to https://docs.bazel.build/versions/master/skylark/lib/skylint.html

### PR DESCRIPTION
**Pull request by akira-baruah**
Fixes #4202

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
Note that documentation won't successfully build at current HEAD due to a bug addressed by #4212, so this PR may depend on that fix.

**Comment by iirina** [comment]
Does this build @ HEAD now?

**Comment by akira-baruah** [comment]
Yes, this builds @ HEAD now. I can also confirm that the fixed link works.

**Pull request closed without merging**
