### PR TITLE
add mips64 support

### PR DESCRIPTION
**Pull request by FengRillian**
Bazel can work on mips platform. Please help to support mips64.

### CODE REVIEW

**Comment by hlopko** [comment]
Hi @FengRillian, sorry for the slow review. This PR looks good to me. Do you use Bazel's autoconfigured toolchain on mips? Does it work? Or you have your own C++ toolchain that you maintain?

**Comment by FengRillian** [comment]
Thanks for your review. I have my own C++ toolchain on mips64 platform. 
To use bazel on mips64 platform, I have to compile the first bazel. So I modify the code to work for mips64. And my bazel can work and compile another project (set up with bazel).

**Comment by hlopko** [comment]
I see. I think it shouldn't be too much work to make bazel autoconfigured toolchain work on mips, if you want to give it a go :)

I'm importing thic PR. Thanks!

**Comment by hlopko** [comment]
Oh wait, you have to sign the CLA first. Otherwise we cannot accept your contribution.

**Comment by FengRillian** [comment]
I agree CLA, but it is difficult for me to visit  https://cla.developers.google.com/ from China. Would you please help submit this modify with your account?

**Comment by hlopko** [comment]
Uff I'm not sure I can do that. @dslomov wdyt?

**Comment by hlopko** [comment]
Ok as per the policy I have to reject this PR. I'm sorry you'll have to find a way to sign the CLA :( Please reopen if you found a way! Thank you!

**Pull request closed without merging**
