### PR TITLE
Use URLs as default canonical IDs in common repo rules

### LINKED ISSUE #19749: unflip --repository_cache_urls_as_default_canonical_id
### Description of the bug:

Looks like https://github.com/bazelbuild/bazel/pull/19549 flipped `--repository_cache_urls_as_default_canonical_id` flag on by default which hurts `rctx.download` performance and breaks rules_oci's layer deduping mechanism completely. 

Cross-ref: https://github.com/bazel-contrib/rules_oci/issues/387

### Which category does this issue belong to?

External Dependency

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

- clone https://github.com/bazel-contrib/rules_oci
- run `bazel build //oci/tests/...  --repository_cache_urls_as_default_canonical_id`

### Which operating system are you running Bazel on?

darwin/arm64

### What is the output of `bazel info release`?

release 6.3.2

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### LINKED ISSUE #19990: [7.0.0] unflip --repository_cache_urls_as_default_canonical_id
Forked from #19749

### PR DESCRIPTION
**Pull request by fmeum**
RELNOTES[INC]: The `--experimental_repository_cache_urls_as_default_canonical_id` flag is no longer available. Instead, the `http_archive`, `http_file`, `http_jar`, `jvm_maven_import_external`, and `jvm_import_external` repository rules now use the URLs as the canonical ID if none is provided explicitly. If this behavior is not desired, it can be disabled via `--repo_env=BAZEL_HTTP_RULES_URLS_AS_DEFAULT_CANONICAL_ID=0`.

Fixes #19749

Closes #20047.

PiperOrigin-RevId: 580826938
Change-Id: I32bfb04084ce75b74f664794e1924d3188f58805

Closes #19990

### CODE REVIEW

**Comment by fmeum** [comment]
@keertk This merge conflict was purely due to `MODULE.bazel.lock`. We will probably see this more often in the future. We could look into updating the lockfile automatically as part of the cherry-pick workflow.

**Comment by keertk** [comment]
Good to know, thanks @fmeum! Makes sense to add this to the workflow.

**Comment by meteorcloudy** [comment]
Good idea, when `MODULE.bazel.lock` is the only conflict
```
git checkout --ours MODULE.bazel.lock
bazel mod deps
```
should resolve it during cherry-pick.

**Comment by keertk** [comment]
Thank you both. Just created https://github.com/bazelbuild/bazel/pull/20147 since we needed to fix this again. Closing this one.

**Pull request closed without merging**
