### PR TITLE
Use `_repo_mapping` in C++ runfiles library

### PR DESCRIPTION
**Pull request by fmeum**
Work towards #16124

### CODE REVIEW

**Comment by fmeum** [comment]
Stacked on #16652, please ignore the first commit.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.0.0

**Review by oquenchil — APPROVED** [review]

**Comment by fmeum** [comment]
I resolved the merge conflicts.

**Review by Wyverald — APPROVED** [review]

**Comment by fmeum** [comment]
@Wyverald Keep in mind that this is still stacked on the `_repo_mapping` PR, which should probably be merged separately.

**Comment by fmeum** [comment]
Rebased and no longer stacked.

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
