### PR TITLE
Title

### PR DESCRIPTION
**Pull request by tawanjairew**
#3042

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by tawanjairew** [comment]
I signed it

**Comment by damienmg** [comment]
@tawanjairew: this PR conflict with https://bazel-review.googlesource.com/c/bazel/+/16810. Also the baseline of your PR seems off compared to head...

**Comment by damienmg** [comment]
Wow the PR is actually just trying to merge into the release branch, closing this seems like an error.

**Pull request closed without merging**
