### PR TITLE
Fixing docs of remote worker

### PR DESCRIPTION
**Pull request by or-shachar**
Seems like we cannot change the `DigestFunction` from command line and it must reside in your `.bazelrc` file.
I first opened #3294 but then realized my settings were wrong

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ittaiz** [comment]
Docs changing to reflect reality is great.
Is this maybe a bug as well?

**Comment by or-shachar** [comment]
Not sure. It used to be possible to configure it as command line argument and now it doesn't pick it up

**Comment by ittaiz** [comment]
@ulfjack WDYT? Is fixing the docs the correct thing to do or should we open a new bug to restore the ability to pass it via command line flags?

**Comment by ulfjack** [comment]
Uhm, what? The only thing startup does is to add the line to the startup args, just as if it was passed on the command line... if this isn't working, then something is seriously broken.

**Comment by or-shachar** [comment]
@ulfjack  - this is the output when I pass it as regular argument:
```bash
$ bazel test  --host_jvm_args=-Dbazel.DigestFunction=SHA1 --javabase=/usr/lib/jvm/jdk1.8.0_131 --remote_executor=localhost:3030 --remote_cache=localhost:3030 --strategy=TestRunner=remote --remote_local_fallback=false --remote_timeout=600  //...

..................
ERROR: Unrecognized option: --host_jvm_args=-Dbazel.DigestFunction=SHA1
```

**Comment by ulfjack** [comment]
It needs to go before the command 'test':

$ bazel --host_jvm_args=-Dbazel.DigestFunction=SHA1 test --javabase=/usr/lib/jvm/jdk1.8.0_131 --remote_executor=localhost:3030 --remote_cache=localhost:3030 --strategy=TestRunner=remote --remote_local_fallback=false --remote_timeout=600  //...

**Comment by or-shachar** [comment]
@ulfjack - thanks for the clarification!

**Pull request closed without merging**
