### PR TITLE
Add type git_repository to SourceJson class

### PR DESCRIPTION
**Pull request by lifengxiang1025**
Add type git_repository to SourceJson class

### CODE REVIEW

**Review by meteorcloudy — CHANGES_REQUESTED** [review]
Thanks for the contribution! Can you please also add an integration test in https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/bzlmod/bazel_module_test.py;l=580?

**Comment by lifengxiang1025** [comment]
> Thanks for the contribution! Can you please also add an integration test in https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/bzlmod/bazel_module_test.py;l=580?
Hi, I want to add test in bazel_module_test.py. But I only find test examples about "git repository" in "src/test/shell/bazel/". For example "src/test/shell/bazel/starlark_git_repository_test.sh".

**Comment by lifengxiang1025** [comment]
> 

Hi, I want to add test in bazel_module_test.py. But I only find test examples about "git repository" in "src/test/shell/bazel/". For example "src/test/shell/bazel/starlark_git_repository_test.sh".

**Comment by lifengxiang1025** [comment]
>Thanks for the contribution! Can you please also add an integration test in >https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/bzlmod/bazel_module_test.py;l=580?

Thanks for the contribution! Can you please also add an integration test in https://cs.opensource.google/bazel/bazel/+/master:src/test/py/bazel/bzlmod/bazel_module_test.py;l=580?

**Comment by meteorcloudy** [comment]
@lifengxiang1025 Yes, what you can do is to set up a registry with source.json file containing git_repository type and test Bazel can successfully fetch the module. bazel_module_test.py is the right place to add the test.

**Comment by lifengxiang1025** [comment]
OK, I will add test in bazel_module_test.py.

**Comment by Wyverald** [comment]
this landed in https://github.com/bazelbuild/bazel/pull/20912

**Pull request closed without merging**
