### PR TITLE
Take windows junctions into account with --watchfs

### PR DESCRIPTION
**Pull request by tomdegoede**
Related PR: #11334 I enabled --watchfs for windows under --experimental_windows_watchfs. 

Related issues: #11619:
1. (infinite) recursion occurs on the convenience symlinks when they are created while watch is active. This also causes a delay on the first bazel invocation after the symlinks are created.
2. quite often an overflow warning occurs `WARNING: Overflow when watching local filesystem for changes...`. I think this is because the watcher also watches the bazel-* symlinks with many file changes due to being output directories.

The reason that this behavior is different on windows seems to be that the convenience symlinks are actually created as junctions. I have tried changed this logic to creating actually directory symlinks which seemed to resolve the issues. This however could be a breaking change on some systems because creating symlinks requires more privileges than creating junctions.

~~Therefore I propose the following changes:~~
~~1. Watch the root directory non-recursively. As it's done on non windows systems.~~
~~2. Watch each direct sub-directory recursively. Excluding junctions.~~

~~The downside of this approach is that the convenience symlinks must be at the root of the workspace. When using --symlink_prefix with a sub-directory (which is the case for in the linked issue) both issues would still occur.~~

I have updated the PR to reflect my comment below because this also resolves the above mentioned downside and is a simpler solution. I have tested several scenarios with regards to the folder locking but was able to delete workspace folders from explorer, ide and cli every time.

### CODE REVIEW

**Comment by tomdegoede** [comment]
Some other thought: I'm uncertain if the initial issues that caused windows --watchfs to become a non-op as discussed in #1931 and angular/angular#29541 were only related to output directory file handles. With the knowledge that excluding junctions from the tree walk excludes watching bazel-out etc. we may be able to just watch each individual directory again allowing to check for junctions on all sub-directory levels.

What do you think @meteorcloudy ?

**Comment by meteorcloudy** [comment]
@tomdegoede Thanks for looking into this!

Do I understand correctly, on other platforms, bazel-* folders are also skipped because they are symlinks? If so, this solution looks good to me.

Just to make sure we are not relying on checking the bazel-* folder. Can you verify after enabling --watchfs on Windows, the following still work?
```
bazel build examples/cpp:hello-world
rm -f bazel-bin/examples/cpp/hello-world
touch bazel-bin/examples/cpp/hello-world
bazel build examples/cpp:hello-world -s  # The link action should be re-executed
```

**Comment by tomdegoede** [comment]
Jep thats correct @meteorcloudy. The Files.walkFileTree does skip symlinks by default but was lacking junctions.

I've validated that the test binary is build again. This is because output files are checked via the `SequencedSkyframeExecutor::handleDiffsWithMissingDiffInformation` when checkOutputFiles is true.

**Comment by meteorcloudy** [comment]
Great, thanks!

**Review by meteorcloudy — APPROVED** [review]

**Pull request closed without merging**
