### PR TITLE
Patch manifest merger 25.0.0 with queries support

### PR DESCRIPTION
**Pull request by Bencodes**
Built using the instructions seen [here](https://github.com/bazelbuild/bazel/issues/14285).

https://github.com/bazelbuild/bazel/issues/14285

### CODE REVIEW

**Comment by Bencodes** [comment]
I'm hesitant to actually have this one merged because updating the Android tools dependencies seems like a might better long term solution.

**Comment by Bencodes** [comment]
cc: @ahumesky

**Comment by ahumesky** [comment]
We're actually looking to update from 25 to the latest version. It might take a few weeks though given how much has changed since 25

**Comment by nkoroste** [comment]
Any updates on this? curious to know what's the best way to go about working around this issue

**Pull request closed without merging**
