### PR TITLE
Gracefully handle output symlinks with BwoB

### PR DESCRIPTION
**Pull request by fmeum**
If an action creates output symlinks, `--remote_download_minimal` now falls back to downloading all its outputs rather than failing with an exception, which most of the time led to a broken build.

### CODE REVIEW

**Comment by fmeum** [comment]
@meteorcloudy I assume that this would fix a breakage in rules_go caused by https://github.com/bazelbuild/continuous-integration/pull/1579: https://buildkite.com/bazel/rules-go-golang/builds/5049#018777f3-a4a6-4396-aecc-a7abe4de7ae8/256-294

@coeuvre Could you review this?

**Comment by coeuvre** [comment]
cc @tjgq

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
@coeuvre I fixed the test on Windows (by skipping it), but `test_symlink_outputs_not_allowed_with_minimial` now fails because the warning is no longer printed. Is the warning something that should be preserved? I couldn't figure out how to access `EventHandler` from `RemoteExecutionService` to show a warning without throwing an exception.

**Comment by tjgq** [comment]
> @coeuvre I fixed the test on Windows (by skipping it), but `test_symlink_outputs_not_allowed_with_minimial` now fails because the warning is no longer printed. Is the warning something that should be preserved? I couldn't figure out how to access `EventHandler` from `RemoteExecutionService` to show a warning without throwing an exception.

Can you do something similar to `RemoteExecutionService#reportUploadError`? I think the warning is warranted because we're degrading performance in a non-obvious way, but if it's too annoying to plumb it through, I think it's also fine to just delete the test.

**Comment by fmeum** [comment]
@tjgq I added a warning and updated the test.

**Review by coeuvre — APPROVED** [review]

**Comment by keertk** [comment]
@bazel-io fork 6.2.0

**Pull request closed without merging**
