### PR TITLE
Don't convert InterruptException to EvalException in struct field call expressions.

### PR DESCRIPTION
**Pull request by benjaminp**
This is probably only a theoretical problem, since a blocking struct field is probably a very bad idea.

### CODE REVIEW

**Comment by benjaminp** [comment]
`callFunction` handles not dropping `InterruptedException` internally. That's why I moved it out of the `try` block (`InvocationTargetException` being checked). Though that brings up the root cause of this issue: delicate `InvocationTargetDexception` handling is duplicated all over `syntax/`. (Some places also convert unchecked unexceptions; others don't.)

**Comment by buchgr** [comment]
ping @c-parsons

**Comment by laurentlb** [comment]
What's the status of this pull request?

**Comment by benjaminp** [comment]
Could someone import this PR, please?

**Comment by c-parsons** [comment]
I'm on it. Sorry about the delay.

**Pull request closed without merging**
