### PR TITLE
Add path mapping support for C++ compile action templates

### PR DESCRIPTION
**Pull request by fmeum**
C++ action templates are now properly path mapped.

Since the default Unix toolchain doesn't support object file groups on macOS, `apple_support` is needed in the test. This requires wiring up `LocalEnvProvider` in the remote worker to get `DEVELOPER_DIR` to be set, which in turn requires improving the runfiles handling for the the worker.

Work towards #6526

### CODE REVIEW

**Comment by fmeum** [comment]
@keith Any idea why this test may be failing on macOS?
```
ld: unknown options: --start-lib --end-lib 
```

Does Apple lld not support `--start-lib`?

**Comment by keith** [comment]
Apple's linker does not support start-lib/end-lib. ld64.lld from llvm does since looks like version 14+

**Comment by fmeum** [comment]
@keith I added `apple_support` for its `object_file_group` support, but I'm getting an error about `DEVELOPER_DIR` missing. Any idea about that one?

**Comment by keith** [comment]
looks like it's the remote only test (at least on the last failure), isn't this where the remote executor has to duplicate the logic around setting DEVELOPER_DIR?

**Review by comius — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Comment by iancha1992** [comment]
@fmeum @comius @keith Just a friendly reminder, the 7.3.0RC1 is scheduled for next Monday, July 29th. Thanks!

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.4.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.0rc1`. Thanks!

**Pull request closed without merging**
