### PR TITLE
Make //tools/android compatible with Python 3

### PR DESCRIPTION
**Pull request by duggelz**
Addresses https://github.com/bazelbuild/bazel/issues/4310

### CODE REVIEW

**Comment by duggelz** [comment]
Oops, looks like https://github.com/bazelbuild/bazel/pull/4265 also addresses this.

**Comment by aehlig** [comment]
As this is related to #4265, better have the same reviewer for both pull requests.

**Comment by duggelz** [comment]
Rebased to include submitted Python 3 changes, troubleshooting the CI failures now

**Comment by duggelz** [comment]
Reworking this in a different way.

**Comment by duggelz** [comment]
Submitted as https://github.com/bazelbuild/bazel/commit/246ee5601c28e99385a2a722b57c1977d5ef1aa8

**Pull request closed without merging**
