### PR TITLE
[7.0.0] Fix extraction of tar archives containing sparse files.

### LINKED ISSUE #20090: http_archive: hash of content file different from origin file
### Description of the bug:

hash of content file different from origin file

### Which category does this issue belong to?

Core

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`WORKSPACE`:
```
workspace(
    name = "demo",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "ruff_macos",
    build_file_content = """exports_files(["ruff"], visibility = ["//visibility:public"])""",
    sha256 = "27a2800606b417d8f3102354efd0c09b8e08c94f754aaea9809a74a76e7456da",
    urls = [
        "https://github.com/astral-sh/ruff/releases/download/v0.1.4/ruff-x86_64-apple-darwin.tar.gz",
    ],
)
```
-----
**Flow**:
1. `bazel build @ruff_macos//:ruff`
2. `sha256sum $(bazel info output_base)/external/ruff_macos/ruff`

    `cbb610d58da995d6cee14804e088be7e2ece50f85b7b3afef3fa7e617af522de`
-----

**but origin file hash(sha256sum) is** `c644ed5d190a4db8b153e84b25e45ae4ed00be7e690d802feeecee22876f4a22  ruff`

### Which operating system are you running Bazel on?

linux(x86-64), macos(m1)

### What is the output of `bazel info release`?

release 6.4.0

### PR DESCRIPTION
**Pull request by keertk**
By upgrading the Apache Commons Compress library to 1.20. I'm deliberately not upgrading to the most recent one (1.24.0) because it would require an additional JDK module (java.desktop) and significantly regress the binary size.

Fixes #20090.

Closes #20110.

Commit https://github.com/bazelbuild/bazel/commit/93729f49e3c6644afc294f732ddd66c939c7499f

PiperOrigin-RevId: 580935354
Change-Id: I6c9728ac3fd925432f44a55efaef8f5b52d428c0

### CODE REVIEW

**Comment by keertk** [comment]
@meteorcloudy @tjgq could you take a look at the failures please? I'm hesitant to run any of the suggested commands without context, but lmk if there's anything needed.

**Comment by tjgq** [comment]
I believe you need to run `REPIN=1 bazel run @unpinned_maven//:pin` (to regen `maven_install.json`) followed by `bazel mod deps` (to regen `MODULE.bazel.lock`). If that doesn't work, please let me know here and I'll give it a try tomorrow morning.

**Comment by keertk** [comment]
Looks good now, thanks.

**Review by tjgq — APPROVED** [review]

**Comment by honwen** [comment]
can u fix lts-6 as well?

**Comment by keertk** [comment]
@honwen we don't have plans for another 6.x release at the moment. We'll include this if we get more requests and go through with a release.

**Pull request merged**
