### PR TITLE
Implement namespaced R classes

### PR DESCRIPTION
**Pull request by jongerrish**
Enable rudimentary R class namespacing where each library only contains
references to the resources it declares instead of declarations plus all
transitive dependency references.

This basically implements the `android.namespacedRClass=true` Gradle feature in Bazel.

For our build this saves a total of 215MB outputs + 145 Actions for a clean build in addition to previous open PRs.

No resource merging for android_library targets
Smaller R.{class,txt}
Less desugaring + dexing

### CODE REVIEW

**Comment by jongerrish** [comment]
@jin

**Comment by jin** [comment]
cc @donaldchai @timpeut @donaldchai

**Comment by ulfjack** [comment]
Not much progress here. Anyone willing to make a decision here? If Google isn't using these rules internally, maybe someone from the community can take over responsibility for reviews (but would require a Googler to merge)?

**Comment by Bencodes** [comment]
It's been a while since there have been any updates here. Could someone make a call here?

**Comment by nkoroste** [comment]
Any updates on this?

**Comment by ahumesky** [comment]
Closing this one in favor of the Starlark version of this issue: https://github.com/bazelbuild/rules_android/pull/66

**Pull request closed without merging**
