### PR TITLE
Buffer the output instead of writing every byte individually.

### LINKED ISSUE #1860: Experimental UI writes every character individually
Experimental UI writes every character individually. That results in a really bad experience under load, as you can see the output slowly build up character by character.

There are two reasons for this:
1. PositionAwareAnsiTerminalWriter splits up strings by char.
2. GrpcServerImpl.RpcOutputStream does not implement buffering (even though the old AfUnixSocket does).

There's even a todo in GrpcServerImpl to implement buffering.

### PR DESCRIPTION
**Pull request by ulfjack**
Fixes #1860.

### CODE REVIEW

**Comment by michajlo** [comment]
Any chance we can do this without line buffering? Some outputs may send binary data which may not play nicely.

**Comment by ittaiz** [comment]
Wow, that was fast 😀

**Comment by ulfjack** [comment]
The old (pre-grpc) protocol was using line buffering, so that seemed appropriate. Instead of doing it at the grpc level, we could also do it in the experimental UI handler, or some other place. There's also still a bug in the CL, so it can't be merged as-is, and we might want to add tests.

**Comment by ulfjack** [comment]
@ittaiz - when I filed the bug, I already had part of the fix ready. :-)

**Comment by meteorcloudy** [comment]
//cc @aehlig Can you review this change?

**Comment by meteorcloudy** [comment]
Assign this PR to @lberki as #1860 is already assigned to him.

**Pull request closed without merging**
