### PR TITLE
Update install-ubuntu.md

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
Fixed small grammatical error (sending this doc change through GH to demonstrate how this change process looks for a completely external contributor, see also https://github.com/bazelbuild/bazel/pull/2784)

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by buchgr** [comment]
ping @MarkusTeufelberger . Please sign our CLA and reply with "I signed it".

**Comment by MarkusTeufelberger** [comment]
The page doesn't let me choose which Google account I'm using and always tries to select my work account, which is the wrong one...

I'll try again later with incognito mode or similar, maybe it'll work then. I still don't get why I need to enter my home address and a phone number to "sign" a legally binding agreement by the way instead of submitting a digital signature with my government ID...

**Comment by MarkusTeufelberger** [comment]
I typed a few letters and numbers in a webform in a foreign language, aka. "I signed it".

;-)

**Comment by MarkusTeufelberger** [comment]
🎶 ...and I have waited 500 hours and I have (nearly) waited 500 more... 🎶

Any updates?

**Comment by buchgr** [comment]
@MarkusTeufelberger I am very sorry - I forgot about this change. I have submitted it internally and it will be published to github by the next export (tomorrow).

Thanks for your contribution!

**Comment by MarkusTeufelberger** [comment]
Thanks, I hope it helped to illustrate the flow of a Github contribution and maybe also some pitfalls (e.g. not regularly checking PRs here). Hopefully I'll also manage to get some more meaningful contributions submitted in the future. :-)

**Pull request closed without merging**
