### PR TITLE
Introduce Apache Commons Lang3 3.8.1

### PR DESCRIPTION
**Pull request by lindner**

### CODE REVIEW

**Comment by jin** [comment]
(See internal thread to bazel-engprod, from PR author)

**Comment by philwo** [comment]
I verified that this dependency and version is available in Debian stable, too: https://packages.debian.org/buster/libcommons-lang3-java

Happy to import it.

Don't we need a `java_import` target in `third_party/BUILD`, too, though?

**Comment by lindner** [comment]
I think we can discard this now that the commons lang code is being modified to use Guava instead.

**Comment by lindner** [comment]
It might be needed for an upgrade of Apache Velocity, but that's a larger discussion.

**Comment by philwo** [comment]
Yup, thank you!

**Pull request closed without merging**
