### PR TITLE
Test that a credential helper can supply credentials for bzlmod.

### PR DESCRIPTION
**Pull request by tjgq**

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]
Nice!

**Comment by tjgq** [comment]
Made a couple changes:

- `SimpleHTTPRequestHandler` can only serve from the current working directory in Python <= 3.6 (which we're stuck with on CI). Fixed by monkey-patching.
- The helper used in the test is a Python script, which can't be executed on Windows. I've just disabled the test, since there's little value in writing a separate version.

**Comment by tjgq** [comment]
@bazel-io flag

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.3.0

**Pull request closed without merging**
