### PR TITLE
Add Java to the list of supported languages

### PR DESCRIPTION
**Pull request by stubbsd**
Java wasn't in the list of programming languages, I'm fairly sure it should be.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by stubbsd** [comment]
I signed it!

**Comment by Androbin** [comment]
@davidstanke Friendly ping

**Comment by ulfjack** [comment]
Thanks for the PR. I didn't see this and merged #4095 instead, though. Sorry! Closing this one.

**Pull request closed without merging**
