### PR TITLE
Delete unused osx_wrapper

### PR DESCRIPTION
**Pull request by keith**
I missed this in 17273615633abbbdcd0b0f7b0945a7d479b709e4

### CODE REVIEW

**Comment by keith** [comment]
@sgowroji bump

**Review by Wyverald — APPROVED** [review]

**Comment by brentleyjones** [comment]
Does this need its labels adjusted now?

**Comment by Wyverald** [comment]
Thanks. @sgowroji we discussed this before and I remember the conclusion being that we can just merge if the PR has approval, with or without the "awaiting-pr-merge" label. Is that still true?

**Comment by Wyverald** [comment]
We chatted offline and decided that we'll keep applying the "awaiting-pr-merge" label.

**Pull request closed without merging**
