### PR TITLE
Look for WORKSPACE.bazel as well in Bazel wrapper script

### PR DESCRIPTION
**Pull request by GMNGeoffrey**
WORKSPACE.bazel is a valid alternative name for this file
(https://docs.bazel.build/versions/master/build-ref.html#workspace)

### CODE REVIEW

**Comment by GMNGeoffrey** [comment]
@philwo PTAL

**Review by philwo — APPROVED** [review]

**Comment by philwo** [comment]
LGTM, but please fix the failing tests.

**Comment by GMNGeoffrey** [comment]
> LGTM, but please fix the failing tests.

Done (syntax error). And since this revealed where the tests were, I added a test for this case. How do you usually merge PRs? Would you like me to squash this into a single commit?

Also, since this is the thing that detects which version to use, I'm not sure just releasing it with the next release it would be a part of makes sense. Basically no one who relies on `.bazelversion` could safely rename their WORKSPACE file to WORKSPACE.bazel right now as long as there's any likelihood of someone using bazel <4. Maybe it would make sense to do a patch release for old versions?

**Comment by jin** [comment]
Imported PR to internal review, @philwo please feel free to LGTM that if there are no actionables here.

**Pull request closed without merging**
