### PR TITLE
Add profiling for Bzlmod operations

### PR DESCRIPTION
**Pull request by fmeum**
The resolution of Bazel modules and evaluation of module extensions is now represented in the profile.

Profile from a run of `bazel build //src:bazel-dev --enable_bzlmod --nobuild`:
Bzlmod profile

### CODE REVIEW

**Comment by fmeum** [comment]
The profile shows that module resolution is much slower than it could be due to serial downloads. I will see whether we can get a quick win here with a thread pool.

**Comment by meteorcloudy** [comment]
@meisterT Can anyone from the build productivity team also take a look?

**Review by meteorcloudy — APPROVED** [review]
Awesome, thanks!

**Review by Wyverald — APPROVED** [review]
thank you!

**Comment by Wyverald** [comment]
Could you share your profile result here? I'd love to take a look too (too many '...'s in that screenshot :))

**Comment by fmeum** [comment]
> Could you share your profile result here? I'd love to take a look too (too many '...'s in that screenshot :))

[command.profile.gz](https://github.com/bazelbuild/bazel/files/12402448/command.profile.gz)

**Comment by fmeum** [comment]
It's interesting to see how the cyclic dependency between rules_go and gazelle contributes to the critical path.

**Comment by Wyverald** [comment]
> It's interesting to see how the cyclic dependency between rules_go and gazelle contributes to the critical path.

Yeah that's essentially a really long dependency chain. We could be smarter there -- don't bother with deps at lower versions if we know there's no multiple-version override, for example. It would make the discovery code a bit more gnarly, but anyway.

**Comment by Wyverald** [comment]
> > It's interesting to see how the cyclic dependency between rules_go and gazelle contributes to the critical path.
> 
> Yeah that's essentially a really long dependency chain. We could be smarter there -- don't bother with deps at lower versions if we know there's no multiple-version override, for example. It would make the discovery code a bit more gnarly, but anyway.

But do note that this needs to be done very carefully, or version resolution might become nonreproducible -- if the lower version itself has higher-version deps, we need to make sure we have a reproducible way to decide which "lower version" to drop. The end result is still _some_ set of minimal versions, but is not the original MVS. This is related to the original idea by @meteorcloudy

**Review by meisterT — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
@fmeum @meisterT We may need another commit before we cherry-pick this one to 6.4.0 because in "src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java" line 623, we have ```earlyExitCode = optionHandler.parseStarlarkOptions(env, reporter);``` in the release-6.4.0, instead of ```earlyExitCode = optionHandler.parseStarlarkOptions(env);```

**Comment by iancha1992** [comment]
@fmeum @meisterT I think we may need another commit before we cherry-pick this one to 6.4.0 because in "src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java" line 622, we have ```earlyExitCode = optionHandler.parseStarlarkOptions(env, reporter);``` in the release-6.4.0 branch, instead of ```earlyExitCode = optionHandler.parseStarlarkOptions(env);```

cc: https://github.com/orgs/bazelbuild/teams/triage

**Comment by iancha1992** [comment]
@fmeum @meisterT @Wyverald @meteorcloudy I think we may need another commit before we cherry-pick this one to 6.4.0 because in ```src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java``` line 622, we have ```earlyExitCode = optionHandler.parseStarlarkOptions(env, reporter);``` in the release-6.4.0 branch. But it really should be ```earlyExitCode = optionHandler.parseStarlarkOptions(env);``` before the change.

cc: https://github.com/orgs/bazelbuild/teams/triage

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 6.4.0 RC1](https://releases.bazel.build/6.4.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
