### PR TITLE
Implement `describeKey` for more actions

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Review by tjgq — CHANGES_REQUESTED** [review]
This will only cover `ctx.actions.symlink` when the output is a `declare_symlink`. Do you also want to add an implementation for `SymlinkAction`, which would also cover `declare_file` and `declare_directory` outputs?

**Comment by tjgq** [comment]
> This will only cover `ctx.actions.symlink` when the output is a `declare_symlink`. Do you also want to add an implementation for `SymlinkAction`, which would also cover `declare_file` and `declare_directory` outputs?

(Feel free to push back if this isn't something you currently need, I'm happy to import as-is.)

**Comment by fmeum** [comment]
I added `describeKey` implementations for more actions.

**Review by tjgq — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
