### PR TITLE
Remove --incompatible_blacklisted_protos_requires_proto_info

### PR DESCRIPTION
**Pull request by Yannic**
Cleanup after flipping the flag in Bazel 4.0 (53705f6a014067a8f17cf0af4da0ad99fe1169be)

### CODE REVIEW

**Comment by Yannic** [comment]
@comius PTAL, thanks!

**Comment by meisterT** [comment]
Note that 4.0 has not been cut yet.

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
> Note that 4.0 has not been cut yet.

Merge/submit needs to wait the release.

**Review by lberki — APPROVED** [review]
I'll import this.

**Pull request closed without merging**
