### PR TITLE
[7.3.0] Locate BCR module overlay files under the `overlay` subdirectory

### PR DESCRIPTION
**Pull request by bazel-io**
This avoids collisions between overlay files and regular BCR files such as `source.json`.

Overlay support has been released in 7.2.0, but hasn't been used in the BCR yet.

Closes #22811.

PiperOrigin-RevId: 645071272
Change-Id: Ib05855a728ebb09795bf70afb14457e9e6d23bf0

Commit https://github.com/bazelbuild/bazel/commit/36da00463d4b645752d1be7c5b8d41139d3b8811

### CODE REVIEW

**Comment by Wyverald** [comment]
@iancha1992 could you rebase this?

**Comment by iancha1992** [comment]
> @iancha1992 could you rebase this?

@Wyverald  it says it's already up-to-date.

**Comment by iancha1992** [comment]
> @iancha1992 could you rebase this?

@Wyverald it says it's currently up-to-date with the `release-7.3.0` branch.

**Comment by Wyverald** [comment]
ah yeah, sorry -- the RBE failure is not fixed on release-7.3.0 yet. Let's wait a little bit.

**Pull request merged**
