### PR TITLE
Avoid emitting canonical labels into generated repos

### PR DESCRIPTION
**Pull request by fmeum**
As long as #20722 isn't resolved, the canonical name for the given apparent name can change without the repo rule being refetched.

### CODE REVIEW

**Comment by Wyverald** [comment]
Just so I understand, this won't break any users, right? We did this originally to anticipate for the move of `java_import` into `rules_java`, so before that happens, it doesn't matter whether we use the native `java_import` or the `rules_java` one?

Side note: I think we need to eventually deprecate `http_jar` and move it into `rules_java` anyway. Weird that jars get special treatment.

**Comment by fmeum** [comment]
I think that this is safe, these are pure forwarders except for a tag. With the caveat that someone out there may be patching rules_java with custom rule logic, but I don't think that's a supported use case.

**Review by Wyverald — APPROVED** [review]

**Comment by fmeum** [comment]
> OK. I think I'm more comfortable with cherry-picking this one for 7.0.1 (instead of waiting on a fix for #20722). WDYT?

I agree, 7.0.1 is probably already the largest point release ever.

**Comment by Wyverald** [comment]
@bazel-io fork 7.0.1

**Comment by iancha1992** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.0.1 RC2](https://releases.bazel.build/7.0.1/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
