### PR TITLE
bazel: add jline to third_party

### PR DESCRIPTION
**Pull request by alandonovan**
This is the third_party portion of
https://github.com/bazelbuild/bazel/pull/12544

jline jars are downloaded from the
[maven repo](https://repo1.maven.org/maven2/org/jline/).

### CODE REVIEW

**Comment by alandonovan** [comment]
@stepancheg Could you appease the CLA-bot? Thanks.

**Comment by stepancheg** [comment]
@googlebot I consent.

**Comment by philwo** [comment]
Merged! :)

**Comment by alandonovan** [comment]
Hi Phil, sorry to trouble you, but could you revert the change? We discovered that jline is quite buggy so I no longer want to add a dependency on it.

**Comment by philwo** [comment]
Sure, no problem! I’ll revert it.

**Comment by philwo** [comment]
Reverted in 7f6715c8e5c01887bfa65d6c799723f4d360436f.

**Comment by jin** [comment]
Can this be closed?

**Pull request closed without merging**
