### PR TITLE
Starlark benchmark utility

### PR DESCRIPTION
**Pull request by stepancheg**
```
% bazel run //src/main/java/com/google/devtools/starlark:Benchmark
...
iteration 0
bubble_sort   : 2554ms; min 2554ms
sorted_strings: 2056ms; min 2056ms
iteration 1
bubble_sort   : 1722ms; min 1722ms
sorted_strings: 1900ms; min 1900ms
...
```

Very simple benchmarking utility useful when doing perf optimizations.

### CODE REVIEW

**Comment by stepancheg** [comment]
cc @alandonovan

**Comment by meisterT** [comment]
cc @laurentlb @Quarz0

**Comment by meisterT** [comment]
See also https://github.com/bazelbuild/starlark/pull/75

**Comment by aiuto** [comment]
ping @alandonovan

**Pull request closed without merging**
