### PR TITLE
Replace HTML entities with the actual characters outside the <pre> tag

### PR DESCRIPTION
**Pull request by chrismgrayftsinc**
The current document at https://bazel.build/docs/user-manual shows some HTML entities literally.  Inside backticks, it seems that using the actual character works while inside `<pre>` using the entity works.

### CODE REVIEW

**Comment by sgowroji** [comment]
Hi @chrismgrayftsinc, Could you please take a look at the failing checks?

**Comment by chrismgrayftsinc** [comment]
Hi @sgowroji I have looked into the failures but have not been able to solve them yet.  The problem is there is a test to check for unclosed HTML tags and the changes I've made look like unclosed HTML tags.  Should there be a different way of denoting a changing string?  Or should we change the test to ignore unclosed HTML tags in backticks?

**Comment by chrismgrayftsinc** [comment]
I have proposed a change to the test.

**Comment by chrismgrayftsinc** [comment]
Ping

**Comment by fmeum** [comment]
@fweikert Friendly ping

**Comment by chrismgrayftsinc** [comment]
Monthly ping.  @fweikert

**Review by Wyverald — APPROVED** [review]

**Pull request closed without merging**
