### PR TITLE
Bump c++ standard to c++17 per default

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
Some tests are failing:

```bash
------------------------------------------------------------------------
test_compile_helloworld FAILED: Unexpected regexp Loading package: hello found.
/home/davido/.cache/bazel/_bazel_davido/4596c3304267e4c44bca87d41e038f29/sandbox/linux-sandbox/3620/execroot/_main/bazel-out/k8-fastbuild/bin/src/test/shell/integration/discard_analysis_cache_test.runfiles/_main/src/test/shell/integration/discard_analysis_cache_test:91: in call to test_compile_helloworld
```

**Comment by fmeum** [comment]
That's because change to bazel_tools require updating the default lockfile, see src/test/tools/bzlmod/verify_default_lock_file/test_attempts/attempt_1.log for how to fix that.

**Comment by davido** [comment]
> [...] see src/test/tools/bzlmod/verify_default_lock_file/test_attempts/attempt_1.log for how to fix that.

Thanks for the pointer I tried this command, but it said me, that nothing was changed.

**Comment by meteorcloudy** [comment]
Yes, bump the Bazel version will affect the final dependency graph because `bazel_tools` is a builtin module and it introduces some transitive dependencies.

**Comment by davido** [comment]
> Yes, bump the Bazel version will affect the final dependency graph because bazel_tools is a builtin module and it introduces some transitive dependencies.

Thanks for confirmin. The questione remains, why `bazelisk run //src/test/tools/bzlmod:update_default_lock_file` failing here?

**Comment by meteorcloudy** [comment]
Probably because you are running under /home/davido/projects/davido_bazel/src instead of /home/davido/projects/davido_bazel

**Comment by davido** [comment]
@meteorcloudy, @fmeum Thanks for your help!

**Comment by meteorcloudy** [comment]
@buildbreaker2021 should take a look and confirm if it's fine to bump the default c++ standard.

**Review by buildbreaker2021 — APPROVED** [review]

**Comment by buildbreaker2021** [comment]
lgtm, I think this should not break anything internally.

**Comment by iancha1992** [comment]
@buildbreaker2021 The tests are failing. Looks like we need to `run bazel mod deps --lockfile_mode=update`?

**Pull request closed without merging**
