### PR TITLE
Fix capitalization of Apple platforms, Xcode, “SDK”, and “OS”

### PR DESCRIPTION
**Pull request by brentleyjones**

### CODE REVIEW

**Review by mattrobmattrob — APPROVED** [review]

**Review by luispadron — APPROVED** [review]

**Comment by sgowroji** [comment]
Hi @brentleyjones, Could you please take a look at the failing checks?

**Comment by brentleyjones** [comment]
Yep. Seems to just be the bzlmod lockfile. I'll push that update soon.

**Comment by brentleyjones** [comment]
@sgowroji All green now.

**Comment by brentleyjones** [comment]
@susinmotion Could you give this a review (and if you aren't the right person for these types of PRs, can you please tell me who I should ping going forward 🙏)? Thanks!

**Comment by susinmotion** [comment]
Hi! I'll merge this one in, but I think allevato@ and nglevin@ might be good candidates going forward. I'll have a more definitive answer later this week I hope.

**Comment by brentleyjones** [comment]
Thanks @susinmotion! Just let me know here. I'll wait for an answer before I open up another PR that I want to propose, which is more than just some doc changes.

**Pull request closed without merging**
