### PR TITLE
Fix crash on `IOException` in SingleExtensionEvalFunction

### LINKED ISSUE #22688: [7.2.0] Unrecoverable error while evaluating node 'SINGLE_EXTENSION_EVAL:ModuleExtensionId
### Description of the bug:

Hi,

we've observed the following error on Windows after upgrading to 7.2.0 and moving `rules_rust` over to bzlmod (both happened at the same time).
The error is spurious.

```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'SINGLE_EXTENSION_EVAL:ModuleExtensionId{bzlFileLabel=@@rules_rust~//crate_universe:extension.bzl, extensionName=crate, isolationKey=Optional.empty}' (requested by nodes 'SINGLE_EXTENSION:ModuleExtensionId{bzlFileLabel=@@rules_rust~//crate_universe:extension.bzl, extensionName=crate, isolationKey=Optional.empty}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:550)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:414)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Can't get the number of an unknown enum value.
	at com.google.devtools.build.lib.server.FailureDetails$ExternalDeps$Code.getNumber(FailureDetails.java:57724)
	at com.google.devtools.build.lib.server.FailureDetails$ExternalDeps$Builder.setCode(FailureDetails.java:58182)
	at com.google.devtools.build.lib.bazel.bzlmod.ExternalDepsException.<init>(ExternalDepsException.java:37)
	at com.google.devtools.build.lib.bazel.bzlmod.ExternalDepsException.withCauseAndMessage(ExternalDepsException.java:51)
	at com.google.devtools.build.lib.bazel.bzlmod.SingleExtensionEvalFunction$RegularRunnableExtension.run(SingleExtensionEvalFunction.java:948)
	at com.google.devtools.build.lib.bazel.bzlmod.SingleExtensionEvalFunction.compute(SingleExtensionEvalFunction.java:194)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:461)
	... 7 more
BAZEL FAILED
```

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

N/A

Some part of our repository is open-source though, including the offending module extensions definition, see: https://github.com/github/codeql (current main)

### Which operating system are you running Bazel on?

Windows Server 2019

### What is the output of `bazel info release`?

7.2.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

_No response_

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

The error is spurious, so it's hard to bisect.

### Have you found anything relevant by searching the web?

no

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #22688

### CODE REVIEW

**Review by meteorcloudy — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Comment by criemen** [comment]
> Should this go into a 7.2.1 together with other fixes?

As the expected release date of 7.3.0 is middle of august (and, realistically, this'll be more end of August) from a customer perspective, 7.2.1 with this and potentially other fixes would be great.

**Comment by meteorcloudy** [comment]
@criemen Yes, we'll make a 7.2.1 to fix this. 
However, is there anything we could do better to catch this kind of errors before the final release? Did you receive any notifications for rcs? And how easy is it for rules_rust to test the rcs?

**Comment by meteorcloudy** [comment]
@fmeum Do we need a regression test for this?

**Comment by fmeum** [comment]
I don't think so, we just used a special protobuf enum value that always crashes in this case, there is nothing special about the call site.

@cushon This may be an interesting case for an ErrorProne check.

**Review by meteorcloudy — APPROVED** [review]

**Comment by criemen** [comment]
> If so, you could set USE_BAZEL_VERSION=last_rc to always test against the latest rc.

We are using bazelisk, but we're also pinning the bazel version for our repository.

Me testing a bazel RC is right now making a PR against `.bazelversion`, bumping it to the version number of that RC. I could switch that to `last_rc` instead, but it doesn't really help - it's still a manual process of bumping `.bazelversion` and opening a PR to trigger CI. That's also why I'm not diligently testing all RCs, but only the first (and maybe I should add testing the last one before a release just for good measure, too).
 Defaulting our entire setup to `last_rc` and only switching to a fixed version number once we observe breakage doesn't fit our risk appetite.

**Comment by meteorcloudy** [comment]
You could probably have the exact same pipeline with env var USE_BAZEL_VERSION=last_rc (which would overrides .bazelversion), then you can trigger a build when a new rc comes out.

**Comment by keertk** [comment]
@bazel-io fork 7.2.1

**Comment by criemen** [comment]
@meteorcloudy 
> However, is there anything we could do better to catch this kind of errors before the final release?

If it makes you feel any better, reverting to bazel 7.1.2 doesn't help either, so this is not a regression in 7.2.0, it's something that was exposed by us moving from workspace to bzlmod for `rules_rust` alone. The code has been in-tree for 8 months, and is already in 7.0.0.

Rather than a problem with the bazel release process, this rather highlights that Windows testing for Bazel is limited, and maybe that your file/directory deletion code is missing some retries to deal with the windows problem that files can't be deleted if another process (like an AV 🙄 ) is around and still keeps a handle to the file around.

**Comment by meteorcloudy** [comment]
>  and maybe that your file/directory deletion code is missing some retries to deal with the windows problem that files can't be deleted if another process

Maybe not trying hard enough? We definitely suffered a lot from this.  😂
https://github.com/bazelbuild/bazel/blob/3e552cb2ad3a01cce58c8287dc56c22393192348/src/main/native/windows/file.cc#L735-L738

Anyway, the ship for 7.2.1 has sailed, we'll just continue the process.

**Pull request closed without merging**
