### PR TITLE
Use the java_tools release split into platform independent and prebuilt part.

### PR DESCRIPTION
**Pull request by comius**
This builds on top of the commit "Separate java_tools into platform independent and prebuilt part.".

- java_tools release 11.0 is used
- java_tools platform independent repo is added
- java toolchain definitions appropriate for new release are added to tools/jdk/BUILD
- remote_java_tools are replaced with aliases
- tests are reenabled

### CODE REVIEW

**Comment by comius** [comment]
To see changes without baseline: https://github.com/bazelbuild/bazel/pull/12552/files/6226acf45d2d11566d6c89e8491f62ac6019adf9..ba1fff02d1223bd56d19941b4dd9b5c0372ff886

**Comment by comius** [comment]
Downstream tests: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1785

**Review by philwo — APPROVED** [review]

**Comment by philwo** [comment]
Wow. Great work!

**Comment by comius** [comment]
Fixes https://github.com/bazelbuild/bazel/issues/8406

**Pull request closed without merging**
