### PR TITLE
Update Error Prone

### PR DESCRIPTION
**Pull request by cushon**

### CODE REVIEW

**Review by comius — APPROVED** [review]

**Comment by comius** [comment]
@philwo I believe this PR requires a direct github merge.
Who are the other people that have the special powers? Transferring to anyone?

**Comment by philwo** [comment]
@comius I'll reply to you in chat.

**Comment by comius** [comment]
@meteorcloudy manual merge please :)

**Comment by meteorcloudy** [comment]
OK, it's done.

**Pull request closed without merging**
