### PR TITLE
Add whitelist file for starlark transitions

### PR DESCRIPTION
**Pull request by juliexxia**
Whitelist all the things!

### CODE REVIEW

**Comment by dslomov** [comment]
What is the intent of this? Does this whitelist transitions in external repositories?

**Comment by juliexxia** [comment]
Reopening to whitelist external dependencies

**Comment by deeglaze** [comment]
Is the requirement for the whitelist label equaling the //tools/etc path going to work when the reference is @bazel_tools//tools/etc ?

**Comment by jin** [comment]
What's the current status of this PR?

**Comment by juliexxia** [comment]
@jin I believe this is now obsolete because of commit 8536172a6743c3ca05c49dddc63325bf69dc5799. Closing. Thanks for the ping!

**Pull request closed without merging**
