### PR TITLE
docs: layout is singular

### PR DESCRIPTION
**Pull request by elharo**
@aiuto

### CODE REVIEW

**Review by aiuto — APPROVED** [review]
Thanks. 
But wow, the requirements section is irrelevant to most users.
It probably belongs in a design doc somewhere which we reference. For now, what about moving it to the bottom of the page?

**Comment by elharo** [comment]
You're better able to judge that than me. I just noticed some grammar nits while reading.

**Comment by aiuto** [comment]
Doing the merge now.

**Comment by aiuto** [comment]
The tests keep failing for reasons I do not understand yet.
https://buildkite.com/bazel/google-bazel-presubmit/builds/43913#c0872d2e-f2f4-43e7-babf-d8d6f780a4db
I'll keep trying.

**Pull request closed without merging**
