### PR TITLE
Propagate `linkopts` of header-only libraries to `cc_shared_library`

### LINKED ISSUE #21884: cc_shared_library ignores linkopts from header only cc_library deps
### Description of the bug:

With this example:

```bzl
cc_library(
    name = "foo",
    srcs = ["foo.cpp"],
    linkopts = ["-lcompression"],
)

cc_library(
    name = "baz",
    hdrs = ["baz.hpp"],
    linkopts = ["-blah"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":baz",
        ":foo",
    ],
)

cc_shared_library(
    name = "bar",
    deps = [
        ":baz",
        ":foo",
    ],
)
```

The cc_binary target fails to build, but the cc_shared_library doesn't, it ignores the invalid `-blah` linkopt. If you add an empty cpp file to `baz` it works correctly.

### Which category does this issue belong to?

_No response_

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which operating system are you running Bazel on?

macOS

### What is the output of `bazel info release`?

7.1.1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

_No response_

### Is this a regression? If yes, please try to identify the Bazel commit where the bug was introduced.

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### LINKED ISSUE #23053: Possible regression between 6.4.0 and 7.x: `cc_library` does not propagate `linkopts` option
### Description of the bug:

Hello. It seems that Bazel 7.x does not link library specified in `linkopts` of dependency, even though 6.4.0 do.

For example, the following code, which creates `libtest.so`, should link to `libuim.so` as specified in `uim` dependency. However, in 7.x, it does not link.
```bazel
# BUILD.bazel

cc_library(
    name = "uim",
    hdrs = glob([
        "usr/include/uim/**"
    ]),
    copts = [
        ""
    ],
    includes = [
        "usr/include/uim"
    ],
    linkopts = [
        "-luim",
        "-luim-scm"
    ],
)

cc_library(
    name = "test_lib",
    srcs = ["test.cc"],
    deps = [
        ":uim",
    ]
)

cc_shared_library(
    name = "test",
    roots = ["test_lib"],
)
```

I confirmed that by executing `ldd`, and also looking at `libtest.so-2.params` file. When built with 7.x, the `libtest.so-2.params` file does not include `-luim` or `-luim-scm` line.

Also, when I copy linkopts to `test_lib`, it works fine.
```diff
cc_library(
    name = "test_lib",
    srcs = ["test.cc"],
    deps = [
        ":uim",
-   ]
+   ],
+   linkopts = [
+       "-luim",
+       "-luim-scm"
+   ],
)
```

### Which category does this issue belong to?

C++ Rules

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. Create `WORKSPACE.bazel` and `MODULE.bazel`.
2. Create `BUILD.bazel` posted above.
3. Create empty `test.cc`.
4. Run `bazel build test --experimental_cc_shared_library` in either bazel 6.4.0 or 7.2.1.
5. Check if `src/bazel-bin/libtest.so-2.params` contains `-luim` or `-luim-scm`.

### Which operating system are you running Bazel on?

Linux

### What is the output of `bazel info release`?

release 7.2.1 (used bazelisk)

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse HEAD` ?

_No response_

### If this is a regression, please try to identify the Bazel commit where the bug was introduced with bazelisk --bisect.

I tried to run bisect but failed, because 6.4.0 (good Bazel commit) is not an ancestor of 7.2.1 (bad Bazel commit), and their merge base commit fails to run.

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #21884
Fixes #23053

### CODE REVIEW

**Comment by fmeum** [comment]
@oquenchil The Windows failure may just be a long path issue. Could we try to use less deeply nested test cases? I don't know how that would interfere with the internal directory layout though.

**Comment by fmeum** [comment]
@oquenchil Friendly ping

**Comment by fmeum** [comment]
@pzembrod Could you take a look if Pedro is unavailable as a reviewer?

**Comment by pzembrod** [comment]
I think shortening cc_shared_library/test_cc_shared_libraryX to cc_shared_library/testX is a good idea, not just okay. I think the context for the tests is absolutely clear enough from the parent directory cc_shared_library so it doesn't need to be repeated in the test directory.

**Review by pzembrod — APPROVED** [review]

**Comment by fmeum** [comment]
@pzembrod Could you roll back this change? I still haven't found a good solution to https://github.com/bazelbuild/bazel/issues/24518 and I don't think I will have the capacity to investigate this further. It may require adopting new features, e.g. propagating the graph aspect to toolchains.

**Comment by pzembrod** [comment]
> @pzembrod Could you roll back this change? I still haven't found a good solution to #24518 and I don't think I will have the capacity to investigate this further. It may require adopting new features, e.g. propagating the graph aspect to toolchains.

Sorry, I missed this message. Could I ask you to once eyeball my rollback https://bazel-review.googlesource.com/c/bazel/+/283514 ?

**Comment by pzembrod** [comment]
@fmeum Thanks for taking a look. The rollback is now submitted.

**Pull request closed without merging**
