### PR TITLE
Need to expose generated protobuf C++ headers…

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
…so they can actually be used from other libraries.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by davidzchen** [comment]
Since `third_party/protobuf` was imported from the protobuf repo, it would be better to make this change to the `protobuf.bzl` in the [`google/protobuf`](https://github.com/google/protobuf/blob/master/protobuf.bzl) repository, then import an updated version of `google/protobuf` with that change back into `third_party/protobuf` in Bazel. This way, the version used by Bazel doesn't diverge from the upstream repository.

**Comment by abergmeier-dsfishlabs** [comment]
Filed upstream: https://github.com/google/protobuf/pull/1959

**Comment by meteorcloudy** [comment]
//cc @davidzchen Can you review this change again?

**Comment by davidzchen** [comment]
This is a change specific to protobuf and was filed upstream at google/protobuf#1959. Let's go ahead and close this and pull in the changes from upstream protobuf once google/protobuf#1959 is merged?

**Comment by meteorcloudy** [comment]
Sounds good.

**Pull request closed without merging**
