### PR TITLE
[6.3.0] Update Android tools to 0.27.2 for fixes to DexMapper for https://gith...

### PR DESCRIPTION
**Pull request by ahumesky**
…hub.com/bazelbuild/bazel/issues/16368

This is equivalent to https://github.com/bazelbuild/bazel/commit/37ceec5bfba7bf118946d1b2377ef9c389080bf3 for Bazel 6.3.0. Android Tools 0.28.0 contained updates to the manifest merger which will not work with 6.x, so Android tools 0.27.2 is based on the 6.3.0 branch at 9d73206269430e18f827bb0974c7bceb9bc3842f.

### CODE REVIEW

**Comment by keertk** [comment]
Thanks for the cherry-pick, @ahumesky. Could you help with the failures please?

**Comment by ahumesky** [comment]
Thanks, if I understand the issue correctly, it may take a bit to resolve this, and require some more cherrypicks

**Comment by ahumesky** [comment]
The summary here is that we removed the "classic" desugar tool that's technically still possible to use in Bazel 6. Everyone should be using the newer D8 based desugaring, but changing Bazel 6.3.0 to use the newest Android tools bundle would technically be a breaking change.... so for consistency I restored the classic tool here: https://github.com/bazelbuild/bazel/pull/18909

When that's merged, I can build another version of the Android tools bundle and update this PR.

**Comment by keertk** [comment]
Thanks! https://github.com/bazelbuild/bazel/pull/18909 has been merged into 6.3.

**Comment by ahumesky** [comment]
I should have the updates to this PR within the next hour or so

**Comment by ahumesky** [comment]
Looks like the test failure is the same timeout problem as here:
https://github.com/bazelbuild/bazel/pull/18853#issuecomment-1626244199
I'll try retrying, but we may want to just cherrypick https://github.com/bazelbuild/bazel/commit/3f0b223116f103807fdaf3d47f09079b0c6c9c80

**Comment by iancha1992** [comment]
> 

I think that was just a flaky test failure. I think this time, it should go thru. But let's see @ahumesky

**Comment by ahumesky** [comment]
Finally passed on the 3rd try, so looks like this is good to go!

**Pull request merged**
