### PR TITLE
Refactor and cleanup the sandboxing code.

### PR DESCRIPTION
**Pull request by philwo**
- Remove Optional<> where it's not needed. It's nice for return values, but IMHO it was overused in this code (e.g. Optional<List<X>> is an anti-pattern, as the list itself can already signal that it is empty).
- Use Bazel's own Path class when dealing with paths, not String or java.io.File.
- Move LinuxSandboxUtil into the "sandbox" package.
- Remove dead code and unused fields.
- On Darwin, put the "stats.out" file for statistics collection into a <sandbox_base>/stats subdirectory, which should be a no-op change, but makes the code simpler.
- Migrate deprecated VFS method calls to their replacements.
- Fix a bug in ExecutionStatistics where a FileInputStream was not closed.

### CODE REVIEW

**Comment by philwo** [comment]
FYI @rupertks, please let me know if you have any objections.

**Comment by rupertks** [comment]
Thanks!
 
Re: removal of Optionals, @jmmv

**Comment by rupertks** [comment]
(Personally I think we should keep the Optionals, but the original request for using Optionals came from Julio and/or Peter, I believe)

**Comment by jmmv** [comment]
This change ought to be 7 different commits per the description. As is, it's very hard to review. We shouldn't allow suboptimal tools (GitHub's review system) make us to do the wrong thing. (And given the triviality of these changes, it seems just fine to just send a PR with different commits in it.)

**Comment by philwo** [comment]
Thanks @jmmv, but I was not asking for your code review here. I already got my review and LGTM. :)

Let me know if you feel strongly about using Optional<> for private fields, private method parameters, ... and I'm happy to consider this, otherwise I'll go ahead here.

**Comment by rupertks** [comment]
FYI @aragos

**Comment by philwo** [comment]
> We shouldn't allow suboptimal tools (GitHub's review system)

Also, this isn't GitHub's fault and I don't know why you think so. I put all of the changes into one commit - no code review system in the world will split this up into more logical pieces.

(In general I'm happy to split up changes, but for this one I just didn't happen to - sorry.)

**Comment by jmmv** [comment]
It's GitHub's fault because of the difficulty of reviewing a chain of commits. The way such a refactoring should be done is by creating a branch, committing each individual cleanup as a separate commit, and then sending a PR for the whole branch. Reviewers can choose to look at each individual step or at the combined diff. The problem is that GitHub makes it hard to iterate on such a PR (as we have previously discussed). Or the problem is that our internal import process is too painful and dealing with 7 tiny commits would be awful. Anyway, these are the reasons I assumed you chose to go with a single change.

**Comment by philwo** [comment]
@jmmv I *absolutely* agree that the way you describe it is the way it should be done. It's entirely my fault that I didn't split this CL up into more detailed commits. I went through the whole refactoring in one go, one change led to the other and in the end, I could have split it up, but then individual bits would not have built anymore. That's why I decided to commit it in one big chunk. Really sorry for that. I'll split up things like this next time in much smaller pieces.

I don't think GitHub's UI would have been a big problem here (unfortunately it's hard to try out now - but will do so next time!).

Regarding our import process: It would currently just merge the thing in one huge squashed commit. Not ideal for history keeping, but the review is already done at that point, so it's probably OK? Considering that GitHub PRs are not curated & amended patch series of commits that can stand on their own by design, but more like a timeline of changes, so they'll often contain commits like "Oops, fix broken build due to typo in earlier commit" or something like that. We probably wouldn't want to merge them as individual commits anyway. (But it would be nice if the script supported that as an optional mode, so that we *could* do it for PRs that are structured like patch series.)

**Comment by jmmv** [comment]
Glad we agree. Regarding the "Fix blah" in separate commits in a PR, yes, agree that merging those into the master branch would be awful. (That's why I have, in the past, squashed _only_ those commits into the commits they affect within the pending chain. It's more work and requires a force-push to the PR before merging, but keeps the history tidy.)

BTW, I didn't mean to block this CL on this issue. I was looped in (unsure why) so I thought about making that comment.

**Comment by ittaiz** [comment]
Btw,
AFAIR Copybara indeed supports syncing these commits separately

**Pull request closed without merging**
