### PR TITLE
Update protobuf to 3.7.1

### PR DESCRIPTION
**Pull request by davido**

### CODE REVIEW

**Comment by davido** [comment]
//CC @drigz @laurentlb @meteorcloudy.

Note, that 3.7.1 wasn't tagged yet on the `protobuf` side. I used the code from this commit on 3.7.x branch: https://github.com/protocolbuffers/protobuf/commit/4b9a5df4e8ba2066794da56598ad2905dc42051e. This was the backport of my fix from master: [1].

[1] https://github.com/protocolbuffers/protobuf/pull/5811

**Comment by davido** [comment]
It seems that Protobuf is using bazel_skylib. Tests are failing:

```
ERROR: /home/davido/.cache/bazel/_bazel_davido/4596c3304267e4c44bca87d41e038f29/sandbox/linux-sandbox/1669/execroot/io_bazel/_tmp/69b4d07d7f58456ce79df1b29fbdc766/workspace/test_modify_execution_info_various_types/BUILD:24:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: error loading package '@com_google_protobuf//': in /home/davido/.cache/bazel/_bazel_davido/4596c3304267e4c44bca87d41e038f29/sandbox/linux-sandbox/1669/execroot/io_bazel/_tmp/69b4d07d7f58456ce79df1b29fbdc766/root/cccd58d5baf92601474e7dca6142d199/external/com_google_protobuf/protobuf.bzl: Unable to load package for '@bazel_skylib//lib:versions.bzl': The repository '@bazel_skylib' could not be resolved
ERROR: Analysis of target '//test_modify_execution_info_various_types:proto' failed; build aborted: error loading package '@com_google_protobuf//': in /home/davido/.cache/bazel/_bazel_davido/4596c3304267e4c44bca87d41e038f29/sandbox/linux-sandbox/1669/execroot/io_bazel/_tmp/69b4d07d7f58456ce79df1b29fbdc766/root/cccd58d5baf92601474e7dca6142d199/external/com_google_protobuf/protobuf.bzl: Unable to load package for '@bazel_skylib//lib:versions.bzl': The repository '@bazel_skylib' could not be resolved
```

**Comment by aiuto** [comment]
Note to reviewers: I added people who had done this update before. Could one of you please volunteer to follow it by de-assigning the others, or fully assigning it to yourselves. We don't need 3 people on it.

**Comment by laszlocsomor** [comment]
David, what's to motivation for this PR, what is 3.6.1 (and 3.7.0) missing?

**Comment by davido** [comment]
> David, what's to motivation for this PR, what is 3.6.1 (and 3.7.0) missing?

Upgrade to the recent protobuf release (3.7.0) is needed to make Bazel build tool chain forward compatible (incompatible options).

Upgrade to 3.7.x branch is needed, because 3.7.0 is missing this fix: [1].

[1] https://github.com/protocolbuffers/protobuf/pull/5811

**Comment by laszlocsomor** [comment]
Thank you.

Please send out (PR 1)[https://github.com/bazelbuild/bazel/tree/master/third_party/protobuf#1st-pr-add-the-new-protobuf-version-to-the-bazel-tree] alone first, and PR 2..4 after PR 1 is merged.

Rationale: separately, they are easier to review and roll back.

**Comment by davido** [comment]
@laszlocsomor 

> Please send out PR 1 alone first, and PRs 2..4 after PR 1 is merged.

OK, will do once I figured out how to fix test breakages. There are two complications compared to previous protobuf version upgrades:

* Dependency on bazel_skylib
* Dependency on zlib

**Comment by laszlocsomor** [comment]
@davido : Thanks. Let me know if you need help.

**Comment by davido** [comment]
@laszlocsomor Most of the test jobs are passing now. But some (flaky) are still failing. Dou you have any clou, what is going on here? Thanks!

**Comment by laszlocsomor** [comment]
I'll take a look.

**Comment by laszlocsomor** [comment]
@davido: I'll create a separate PR of your PR 1 (https://github.com/bazelbuild/bazel/pull/7681/commits/026afdb8b14d69d442a32475d146d2b255f0eb08). It must be merged directly to https://bazel.googlesource.com/bazel/+/master, and I don't know if you have permission to merge there. Does that sound good?

**Comment by davido** [comment]
@laszlocsomor 

> Does that sound good?

Thank you. Your help is very much appreciated!

**Comment by iirina** [comment]
@laszlocsomor was this PR merged? Could you please close the PR when/if it's closed? Thanks!

**Comment by laszlocsomor** [comment]
@iirina : It wasn't, we're debating whether it's required. Will close afterwards.

**Comment by jin** [comment]
@laszlocsomor can this be closed if https://github.com/bazelbuild/bazel/pull/7775 is closed?

**Comment by laszlocsomor** [comment]
Yes.

**Pull request closed without merging**
