### PR TITLE
Test flipping `--incompatible_stop_exporting_build_file_path`

### PR DESCRIPTION
**Pull request by mai93**

### CODE REVIEW

**Comment by iancha1992** [comment]
Duplicate for https://github.com/bazelbuild/bazel/pull/21822? 
@mai93

**Comment by mai93** [comment]
no, this is a different flag

**Comment by brentleyjones** [comment]
Btw, the recommended way in the deprecation message to generate the path doesn't account for the fact that someone could use `BUILD.bazel` instead of `BUILD`.

**Comment by brentleyjones** [comment]
(And my ruleset depends on this attribute.)

**Pull request closed without merging**
