### PR TITLE
Revert "Work around bug in desugar"

### PR DESCRIPTION
**Pull request by cushon**
This change caused desugar to compute incorrect max stack sizes for v51
and newer bytecode, which is required to include dead code in the max
stack computation.

This may cause issues similar to #5855 for builds containing jar files
with invalid class files with missing stack map frames. The solution is to
fix the invalid jar files; it does not indicate a bug in ASM or desugar.

This reverts commit 209c82eb5f56dceb30b9fab22c7cb8383507e131.

### CODE REVIEW

**Comment by cushon** [comment]
@jin any concerns with rolling this forward now that https://github.com/googlesamples/android-testing/pull/197 is merged?

**Comment by kevin1e100** [comment]
LGTM :)

**Comment by jin** [comment]
LGTM, I'll merge this.

**Comment by jin** [comment]
Merged as https://github.com/bazelbuild/bazel/commit/9f7545e6de638e63b25d8454e95305289c3fea94

**Pull request closed without merging**
