### PR TITLE
Weakly cache runfiles mappings of tools

### PR DESCRIPTION
**Pull request by fmeum**
Benchmarks showed that this can reduce eden space garbage by 1-4%.

### CODE REVIEW

**Comment by fmeum** [comment]
@justinhorvitz I added some comments for future readers of the OSS code base without access to buganizer. Feel free to change them as you see fit.

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Review by justinhorvitz — APPROVED** [review]

**Comment by fmeum** [comment]
@justinhorvitz The failure of `ruleConfiguredTargetValue_roundTripsToRemoteConfiguredTargetValue` seems legitimate, but I don't know how to fix it.

**Comment by justinhorvitz** [comment]
Spoke with the author of this test. I'm going to import this PR and disable the test for now and we'll plan to add better handling for `WeakReference` in the serialization tests.

**Pull request closed without merging**
