### PR TITLE
docs: add breaking change note to 5.0.0

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
cc @laurentlb

**Comment by Wyverald** [comment]
The changelog file is unfortunately a bit messed up for the 5.0 release (it does not contain any relnotes); we're trying to fix that for the next release. Unfortunately this PR doesn't really fix the problem either (the commit in question is not a cherry-pick; moreover, it only calls out this specific breaking change, implying there aren't any others). In the meantime, please refer to the [blog post for 5.0](https://blog.bazel.build/2022/01/19/bazel-5.0.html).

**Comment by davidxia** [comment]
Thanks for the quick response. The blog post doesn’t mention this breaking change either. Any chance it can be updated?

**Comment by davidxia** [comment]
@Wyverald i'm happy to make a PR for the blog post to update it if that's possible. Lmk!

**Comment by Wyverald** [comment]
Sorry I missed your previous comment. Yes the blog post should be updatable ([sample PR](https://github.com/bazelbuild/bazel-blog/pull/264)). I just realized this change didn't show up in any changelogs because it didn't correctly have the RELNOTES section in its commit message.

**Pull request closed without merging**
