### PR TITLE
Update new target_compatible_with attribute to not exist on repository_rules

### LINKED ISSUE #12374: Downstream projects broken by toolchain change
Culprit: 22b4dbcaf05756d506de346728db3846da56b775

Looks like this defines `target_compatible_with` in native rule definitions, which breaks starlark rules which themselves define `target_compatible_with`.

Example failure: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1730#4d3a9a33-e977-4628-a935-215399f01bc2

```
ERROR: Traceback (most recent call last):
--
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/16110e835b9d4ea88c095e954d089457/external/bazel_toolchains/rules/rbe_repo.bzl", line 621, column 34, in <toplevel>
  | _rbe_autoconfig = repository_rule(
  | Error in repository_rule: There is already a built-in attribute 'target_compatible_with' which cannot be overridden
```

### PR DESCRIPTION
**Pull request by katre**
…y rules.

Fixes #12374.

### CODE REVIEW

**Comment by katre** [comment]
Once the standard tests pass I'll kick off the downstream tests.

**Comment by katre** [comment]
We could consider reverting 4381dbf4c40ce0c5ad769b3e67ce0ed6005a67f9 (patch RBE's use of `target_compatible_with`) and 8946cc1746f4092d86380a23b0ac8b2d8699d3fc (actually applies the patch) after this is in, if we wanted to clean up our WORKSPACE slightly.

**Review by gregestren — APPROVED** [review]

**Comment by katre** [comment]
Downstream tests are running: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1731

**Comment by katre** [comment]
Downstream tests have all passed, I'll start merging this internally.

**Pull request closed without merging**
