### PR TITLE
Catch Exception instead of Throwable

### PR DESCRIPTION
**Pull request by ehkloaj**
This fixes the problem in #11579 but it might be a good idea to also change all occurences of Throwable to Exception in the class as discussed in the issue.

### CODE REVIEW

**Comment by ehkloaj** [comment]
@googlebot I signed it!

**Comment by ehkloaj** [comment]
@googlebot I signed it!

**Comment by ehkloaj** [comment]
@googlebot I signed it!

**Comment by laurentlb** [comment]
The commit is associated with the address `ehkloaj@seroiuts01372.sero.gic.ericsson.se`.
Can you make sure you signed the CLA for this exact address? Or you can try to update the address in the commit.

**Comment by ehkloaj** [comment]
Thanks for looking at this @laurentlb. I also found that this was the problem, the address I signed the CLA with is `kalle.johansson@ericsson.com` and I've changed this in my later pull requests. The problem is that while troubleshooting I deleted the fork that this commit was made from and I don't think there is a way to recover from that.
Do you want me to close this PR and create a new commit with the right email?

**Pull request closed without merging**
