### PR TITLE
Remove deprecated -Xverify:none option

### LINKED ISSUE #11773: Consider to remove deprecated -Xverify:none option from javac invocation
Trying to build with [java toolchain 14](https://github.com/bazelbuild/bazel/pull/11514), I'm seeing this warning:

```
INFO: From Compiling Java headers javatests/com/google/gerrit/server/query/group/libabstract_query_tests-hjar.jar (1 source file):
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

This is because of: https://bugs.openjdk.java.net/browse/JDK-8214731.

We should consider to remove this option entirely.

### PR DESCRIPTION
**Pull request by davido**
Closes #11773.

### CODE REVIEW

**Comment by meisterT** [comment]
I assume we added the flag for a reason. Was used it for performance? Do you see any difference in launch time before and after?

**Comment by davido** [comment]
@meisterT I don't have any mean to tun load tests.
@joeleba Can you run Bazel load test suite on this PR?

**Comment by philwo** [comment]
@meisterT The flag was indeed (a loooong time ago) added for performance reasons, but I don't know if it was ever measured that it provides them. The reasoning was: Hey, we build these binaries ourselves, so there's no reason to validate the bytecode as we know it's fine.

I think it's fine to remove it if we cannot detect a performance regressiojn.

**Comment by meisterT** [comment]
I don't think we want to merge this. I built Bazel with and without line 371 in `src/main/cpp/blaze.cc` and benchmarked `bazel info server_pid`.

before
```
# NumSamples = 20; Min = 1.06; Max = 1.21
# Mean = 1.159300; Variance = 0.001866; SD = 0.043193; Median 1.175500
# each ∎ represents a count of 1
    1.0570 -     1.0722 [     2]: ∎∎
    1.0722 -     1.0874 [     1]: ∎
    1.0874 -     1.1026 [     0]: 
    1.1026 -     1.1178 [     0]: 
    1.1178 -     1.1330 [     0]: 
    1.1330 -     1.1482 [     1]: ∎
    1.1482 -     1.1634 [     2]: ∎∎
    1.1634 -     1.1786 [     8]: ∎∎∎∎∎∎∎∎
    1.1786 -     1.1938 [     4]: ∎∎∎∎
    1.1938 -     1.2090 [     2]: ∎∎
```

after
```
# NumSamples = 20; Min = 1.42; Max = 1.48
# Mean = 1.456000; Variance = 0.000242; SD = 0.015566; Median 1.457500
# each ∎ represents a count of 1
    1.4240 -     1.4295 [     2]: ∎∎
    1.4295 -     1.4350 [     1]: ∎
    1.4350 -     1.4405 [     0]: 
    1.4405 -     1.4460 [     1]: ∎
    1.4460 -     1.4515 [     4]: ∎∎∎∎
    1.4515 -     1.4570 [     2]: ∎∎
    1.4570 -     1.4625 [     2]: ∎∎
    1.4625 -     1.4680 [     3]: ∎∎∎
    1.4680 -     1.4735 [     3]: ∎∎∎
    1.4735 -     1.4790 [     2]: ∎∎
```

That's almost a ~25% regression. So let's not do that until we have to.

**Comment by meisterT** [comment]
Closing as we don't want to regress Bazel server startup performance.

**Comment by meisterT** [comment]
I reran some more benchmarks triggered by https://github.com/bazelbuild/bazel/pull/16541:

```
$ for b in "../bazel-head --host_jvm_args=-Xverify:none" "../bazel-head --host_jvm_args=-Xverify:remote" "../bazel-jdk17 --host_jvm_args=-Xverify:none" "../bazel-jdk17 --host_jvm_args=-Xverify:remote" ; do echo $b; for i in {1..10}; do $b shutdown; before=$(date +"%s%N"); $b info server_pid &> /dev/null; after=$(date +"%s%N"); diff=$((after-before)); echo $diff; sleep 1; done; done
../bazel-head --host_jvm_args=-Xverify:none
Starting local Bazel server and connecting to it...
1299535144
1301074883
1303934630
1313109651
1304823778
1303782215
1312437975
1309525109
1302843422
1308788761
../bazel-head --host_jvm_args=-Xverify:remote
WARNING: Running Bazel server needs to be killed, because the startup options are different.
1584886191
1603006828
1578305278
1607584148
1590731773
1690847604
1620805724
1601359714
1691928474
1592457227
../bazel-jdk17 --host_jvm_args=-Xverify:none
Starting local Bazel server and connecting to it...
1164813710
1165860675
1169026308
1162510410
1166776506
1171392865
1182343892
1187027022
1190862472
1183832828
../bazel-jdk17 --host_jvm_args=-Xverify:remote
WARNING: Running Bazel server needs to be killed, because the startup options are different.
1404368070
1406040812
1439698985
1390351269
1419591755
1394455560
1395118551
1414991003
1397152202
1401241186
```

**Pull request closed without merging**
