### PR TITLE
Update rules_java 7.1.0 / java_tools 13.1.0

### PR DESCRIPTION
**Pull request by hvadehra**
https://github.com/bazelbuild/java_tools/issues/83

### CODE REVIEW

**Review by keertk — APPROVED** [review]

**Comment by sgowroji** [comment]
Hi @hvadehra, We have a few conflicts on the moduleFileHash variable from third_party/bazel/src/test/tools/bzlmod/MODULE.bazel.lock while importing in CL. Can you guide which should be considered? or resolve the conflicts. Thanks!

**Comment by hvadehra** [comment]
Fixed merge conflicts.

cc @keertk after https://github.com/bazelbuild/bazel/commit/c1f2afff305f5dec67f2a5bc0d8bccf7916c5e82 `distdir_deps.bzl` is deleted and we'll have to make updates to `workspace_deps.bzl`

**Comment by hvadehra** [comment]
Unfortunately, this means when we fork this for bazel 7.0.0, we'll need to manually port back the changes to `distdir_deps.bzl`. Sigh. 

Unless of course, https://github.com/bazelbuild/bazel/commit/c1f2afff305f5dec67f2a5bc0d8bccf7916c5e82 is also being picked into 7.0.0 @meteorcloudy ?

**Comment by meteorcloudy** [comment]
Yes, https://github.com/bazelbuild/bazel/commit/c1f2afff305f5dec67f2a5bc0d8bccf7916c5e82 will also be cherry picked to 7.0.0. I'll do it now!

**Comment by meteorcloudy** [comment]
Please wait for https://github.com/bazelbuild/bazel/pull/20097 before cherry-picking this one.

**Pull request closed without merging**
