### PR TITLE
Add digest func to Remote Asset Downloader

### PR DESCRIPTION
**Pull request by sluongng**
A follow up from https://github.com/bazelbuild/remote-apis/pull/286

### CODE REVIEW

**Review by coeuvre — APPROVED** [review]

**Comment by sluongng** [comment]
@coeuvre What do you think about including this in 7.2.0?

**Comment by coeuvre** [comment]
> @coeuvre What do you think about including this in 7.2.0?

Let's do it!

**Comment by coeuvre** [comment]
@bazel-io fork 7.2.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.2.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.2.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=7.2.0rc1. Thanks!

**Pull request closed without merging**
