### PR TITLE
Add a `doc` parameter to `repository_rule()`

### PR DESCRIPTION
**Pull request by jmillikin**
Fixes https://github.com/bazelbuild/bazel/issues/6271

### CODE REVIEW

**Comment by jmillikin-stripe** [comment]
Gentle ping.

**Comment by dslomov** [comment]
Importing now, sorry

**Comment by dslomov** [comment]
I have had some issues importing this, will try again

**Comment by dslomov** [comment]
Rebased and fixed PR is https://github.com/bazelbuild/bazel/pull/7401 (this one had some syntax errors(

**Pull request closed without merging**
