### PR TITLE
Use case-insensitive comparison for Windows paths in `runfiles.bash` 

### PR DESCRIPTION
**Pull request by fmeum**
When matching paths or path segments in the Bash runfiles library, use a case-insensitive comparison when running in MSYS2 as Bazel emits paths that can be capitalized differently. In particular, this fixes failures when the output base path contains uppercase letters.

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]

**Comment by Wyverald** [comment]
Hmm, actually, the test failure may be relevant. Could you take a look?

**Comment by fmeum** [comment]
The test failure was indeed relevant, I switched to a different approach.

I failed to reproduce this in a test as I would need to modify the `--output_root` of the outer Bazel instance - changing the inner one only still results in lowercase paths in MSYS. I tested this manually with both manifest and directory.

**Comment by fmeum** [comment]
@bazel-io flag

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by meteorcloudy** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 6.4.0 RC2](https://releases.bazel.build/6.4.0/rc2/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
