### PR TITLE
[6.2.0]Add test coverage support to android_local_test

### PR DESCRIPTION
**Pull request by ted-xie**
Adding test coverage support to `android_local_test`.

https://github.com/bazelbuild/bazel/issues/15827

Closes #15840.

RELNOTES: Adds coverage metric support to android_local_test
PiperOrigin-RevId: 508549884
Change-Id: I6977efa51ca1c7a6df1f776fe1a326d07989a185

### CODE REVIEW

**Comment by ted-xie** [comment]
@Bencodes @ahumesky 

It would be prudent to cherry-pick the android_local_test coverage fix to 6.1.0.

**Comment by ted-xie** [comment]
Hm, looks like there are some real presubmit failures. I'll take a look.

**Comment by ted-xie** [comment]
I've rebased my branch in the hopes that this PR can pass presubmit. It's weird that there were any failures at all, since it was fine in master branch. I hope that if there are any other cherry-picks necessary that it will be a small number.

**Review by kshyanashree — APPROVED** [review]

**Comment by ted-xie** [comment]
@kshyanashree I think this is still failing presubmit, I will need to discuss internally about next steps.

**Comment by kshyanashree** [comment]
> @kshyanashree I think this is still failing presubmit, I will need to discuss internally about next steps.

Sure @ted-xie!

**Review by kshyanashree — CHANGES_REQUESTED** [review]
Changes requested. Thanks!

**Comment by ted-xie** [comment]
@Bencodes There are unfortunately some integration hurdles with your android_local_test coverage fix into the 6.1.0 branch. The return type of `JavaToolchainProvider.from(ruleContext).getSingleJar()` was changed from `Artifact` to `FilesToRunProvider` some time ago, and it seems nontrivial to refactor this PR to be backwards compatible with the old behavior, especially since the commit that changed the getSingleJar() return type also introduced new behavior with singlejar's runfiles. Any thoughts here?

**Comment by Bencodes** [comment]
@ted-xie I should still have the commits floating around that work with the old implementation before it was refactored over to `FilesToRunProvider` that I can try to find and push.

**Comment by ted-xie** [comment]
I did find Ben's old commits that didn't use `FilesToRunProvider`, but unfortunately they reference `SourceManifestAction`, which does not exist at release-6.1.0 HEAD. It looks like the marginally-cleaner way forward will be to cherry-pick Tiago's FilesToRunProvider changes into 6.1.0.

**Comment by ted-xie** [comment]
OK, I fixed the merge conflicts with Tiago's FIlesToRunProvider/singlejar commit (e0a9081f541baa21d7d9dfad8648692baa274d56), on top of Ben's android_local_test PR. Hopefully presubmit can pass now.

**Comment by ted-xie** [comment]
@kshyanashree Presubmit is passing now.

**Comment by keertk** [comment]
Hi @ted-xie can this wait till the next release (6.2)? We've already created the third release candidate for 6.1 and plan to do the final release on Monday.

**Comment by ted-xie** [comment]
@keertk That should be fine.

**Comment by lukaciko** [comment]
@ted-xie now that 6.1 is released can we expect the PR to make it into the 6.2 branch soon?

**Review by kshyanashree — APPROVED** [review]

**Pull request merged**
