### PR TITLE
Actually check `TEST_SHARD_STATUS_FILE` has been touched

### PR DESCRIPTION
**Pull request by fmeum**
Adds the missing check that a test runner running a sharded test actually declares support for sharding by generating the `TEST_SHARD_STATUS_FILE`. Previously, if it didn't, each shard would silently run all tests. This new behavior is guarded by the new `--incompatible_check_sharding_support` flag.

Closes #18236.

PiperOrigin-RevId: 530259354
Change-Id: If3b01b2c796e66ad7a77e542145efe3ab412eae9

Fixes https://github.com/bazelbuild/bazel/issues/18353

### CODE REVIEW

**Comment by fmeum** [comment]
CC @meteorcloudy @iancha1992

**Comment by meteorcloudy** [comment]
More tests in Bazel are broken: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3028#018823f5-fcb7-42d0-8ef8-7d5087a6a6e7 😅

**Comment by meteorcloudy** [comment]
Please hold on merging this one since we are discovering some issues at https://github.com/bazelbuild/bazel/pull/18354#issuecomment-1549369449

**Comment by keertk** [comment]
@meteorcloudy / @fmeum is this ready to be approved/merged now? Do we need other cherry-picks?

**Comment by meteorcloudy** [comment]
Yes, the fix for the previous issue was cherry picked at https://github.com/bazelbuild/bazel/issues/18474

**Review by meteorcloudy — APPROVED** [review]

**Pull request merged**
