### PR TITLE
Update Guava to 28.1

### PR DESCRIPTION
**Pull request by tetromino**
To allow us to start using Duration with com.google.common.util.concurrent.

### CODE REVIEW

**Comment by tetromino** [comment]
@ahumesky and @jin - it looks like updating to modern Guava will require updating or patching com.android.tools_sdk-common_25.0.0.jar to use CharMatcher.javaLetter() instead of CharMatcher.JAVA_LETTER (a deprecated beta API that got removed from Guava a year ago).

See https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/1a91facd-e9c1-4636-ac2f-828632639479/src/test/java/com/google/devtools/build/android/AndroidDataWriterTest/attempt_1.log

What would you recommend as the least bad way to update the jar? Or maybe we can just patch it?

**Comment by jin** [comment]
(as discussed offline, the simplest way to patch this)

**Comment by aiuto** [comment]
@tetromino  Are you moving forward with this?

**Comment by davido** [comment]
FTR: Upcoming Error Prone release 2.3.5 is also switched to using recent Guava release, so that this [PR](https://github.com/bazelbuild/bazel/pull/11426) is also failing the Andoird tests and waiting for Guava upgrade in Bazel.

Interestingly non Andoird projects can be built and all tests are passing with [PR](https://github.com/bazelbuild/bazel/pull/11426).

**Comment by meisterT** [comment]
@tetromino ping

**Comment by tetromino** [comment]
I'm working on this at the moment. Sorry for the delay. (In other news, rebuilding old android_common jars is unnecessarily difficult.)

**Comment by tetromino** [comment]
@jin @ahumesky - ready for review (RBE in Bazel CI is slow today and has been repeatedly timing out for reasons apparently unrelated to this PR).

The follow-up update to scripts/bootstrap/compile.sh is in https://github.com/tetromino/bazel/commit/7750ea937d0e267c2c1b18239086a447cc860798 (will make a PR from it once this one is committed).

**Comment by tetromino** [comment]
@jin @ahumesky - ping for review? (See comments above about spurious rbe-ubuntu-16-dot-04-openjdk-8 failure.)

**Comment by aiuto** [comment]
Friendly review ping

**Comment by tetromino** [comment]
Rebased since the rbe-ubuntu-16-dot-04-openjdk-8 buildkite failure was worked around by 1a528c827de3a10eb1fd6862670cb5c1391604a5

**Review by jin — APPROVED** [review]
Thanks, and sorry again for the delay.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
Sorry for the delay, I'm merge this PR now!

**Comment by philwo** [comment]
Thank you, Yun! And sorry @ahumesky @tetromino, usually we don't need that long.. 😞 I'll check our processes for this and will see how we can ensure that this doesn't happen again.

**Pull request closed without merging**
