### PR TITLE
 Use .dylib extension for macOS dynamic libraries in XCode toolchain

### LINKED ISSUE #11082: C++ shared libraries generated on OSX get file extension .so instead of .dylib
# Description of the problem / feature request:

`cc_library` rule with `name = 'foo` and `linkstatic=False` attribute generates a shared library. 
On Linux the library is named `libfoo.so` - correct.
On Windows the library is named `foo.dll` - correct.
On MacOS the library is named `libfoo.so` - incorrect! It should be `libfoo.dylib`

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Here is the repo with the minimal example: https://github.com/konste/bazel_repro_shared_lib
Clone it and build it on Mac. You get libbase_shared.so in the output, instead of libbase_shared.dylib

### What operating system are you running Bazel on?

MacOS 10.16

### What's the output of `bazel info release`?

2.2.0

### PR DESCRIPTION
**Pull request by fmeum**
This is a follow-up to #14158.

Fixes #11082.

### CODE REVIEW

**Review by keith — APPROVED** [review]

**Comment by fmeum** [comment]
@oquenchil I forgot about the XCode toolchain in #14158. It's the same change as there.

**Comment by fmeum** [comment]
The tests now pass with only a small change to the `cc_integration_test`.

**Review by oquenchil — APPROVED** [review]
LGTM

**Comment by fmeum** [comment]
@oquenchil I don't see the PR at https://bazel-review.googlesource.com yet, has it been imported with the approval?

**Pull request closed without merging**
