### PR TITLE
Delete jformatstring.

### PR DESCRIPTION
**Pull request by aiuto**
We do not need it any more and it removes a special case license restriction.

### CODE REVIEW

**Comment by fweikert** [comment]
Nice!

**Review by fweikert — APPROVED** [review]

**Comment by sventiffe** [comment]
@fweikert @sgowroji unrelated to the actual PR but related to the process: who is supposed to remove the #awaiting-review label from the PR? The approver? The author? Is one approval enough?

**Comment by aiuto** [comment]
@sgowroji   PRs in third party have special merge requirements.  Only a small group of people can do that.

**Comment by Wyverald** [comment]
Actually @sgowroji _can_ merge PRs to third_party. @meteorcloudy has onboarded gTech for the specific task of merging third_party PRs :)

Could you look into merging this when you have the time, @sgowroji ? Thanks!

**Comment by aiuto** [comment]
It seems like I just merged it.
I used import-third-party-patch.sh, and followed the instructions. It did not create a gerrit review, which I would have expected.

**Comment by aiuto** [comment]
I see the PR at head, and post-submit is running here: https://buildkite.com/bazel/bazel-bazel/builds/20458

**Comment by meteorcloudy** [comment]
@aiuto We never create extra gerrit review for third party change merge. The review is already done here in the Github PR. 

It seems that you forgot to squash the commits together before merging, it's better to do that. That's why I recommend just leave this to @sgowroji to handle it since he's already familiar with the process.

**Comment by aiuto** [comment]
Import patch should rebase to squash the comments. Or at least it should
give those instructions.

**Pull request closed without merging**
