### PR TITLE
Update rule-challenges link #1700

### PR DESCRIPTION
**Pull request by Devinsuit**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by davidzchen** [comment]
LGTM. Thanks!

**Comment by laszlocsomor** [comment]
Importing change into internal depot. Will update thread when done.

**Comment by laszlocsomor** [comment]
@davidzchen : how do I import this change into the internal depot? The rule-challenges.md is now a redirect.

**Comment by davidzchen** [comment]
The link will not be a problem because https://bazel.io/docs/rule-challenges.html will automatically redirect to https://bazel.io/versions/master/docs/rule-challenges.html.

Though, the link should be `/docs/rule-challenges.html` rather than `docs/rule-challenges.html`.

**Comment by laszlocsomor** [comment]
Thanks! Never mind though, this PR has either been imported already, or someone else fixed it without pinging this thread.

**Comment by davidzchen** [comment]
Got it. Thanks!

**Pull request closed without merging**
