### PR TITLE
Build chocolatey package within docker container (doesn't work yet)

### LINKED ISSUE #4049: Integrate chocolatey package publishing into release process
### Description of the problem / feature request / question:

At present, publishing the chocolatey package for Windows is a manual process

0. hear about an RC or release
0. run (on Windows)
    ```powershell
    pushd "scripts/packages/chocolatey"
      ./build.ps1 -version <version> -mode <rc or release> -rc <rc number>
      ./test.ps1 -version <version>
      & choco.exe push # this assumes the secret for the chocolatey API key is present in the user's profile
    popd
    ```
0. reply to the release ticket saying that the package has been pushed and the URL it's available from.

I'd like to eliminate this manual process from the release.

#### Dependencies:
0. choco.exe - binary only available for Windows, but [apparently choco.exe can be compiled and run on Linux](https://github.com/chocolatey/choco#other-platforms). So, try that out.
0. chocolatey API key secret - bazel team should sign up to chocolatey and I'll invite that account to become a package maintainer
0. sha256 of the bazel zip file that the chocolatey package downloads and installs - so, access to either that file, or the release binaries directly to calculate that.
0. actually verifying that the package installs on Windows

Having talked to @damienmg and @dslomov the simplest thing to do is to create a Dockerfile for a (ubuntu, probably) container that contains 
* the choco binary
* the packaging script
* the API key secret
* the build output

and then runs the steps (probably, rewritten into bash) to publish the package.

So, I'll have a go at this.

I need to know where to put what I create - I'm going to assume within bazelbuild/continuous-integration somewhere?

Also note dependency (4) - this approach does not satisfy that requirement. Doing that would, I suppose, require shifting this left to become an artifact that is built and tested within CI, as opposed to just within the release process.

I don't intend to address that within this work. Sounds like to do so we'd want to create some `pkg_chocolatey` rule akin to [deb and rpm](https://docs.bazel.build/versions/master/be/pkg.html).

### PR DESCRIPTION
**Pull request by petemounce**
Attempts to fix #4049.

Don't merge yet; hasn't worked, so far. The `docker run ...` hangs.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by petemounce** [comment]
@damienmg + @laszlocsomor: here's something I've thrown together. It's not working yet, but feedback welcome.

**Comment by laszlocsomor** [comment]
Whoa nice, thanks!
Damien is no longer working on the team, let me assign to @philwo who currently maintains all things CI.

**Comment by petemounce** [comment]
@laszlocsomor ah, hold praise 'til it actually, you know, works ;)

@philwo inside #4049 I've asked that the bazel team create a chocolatey.org account so that that user can be used to publish packages. Is that something you could take care of, please?

**Comment by petemounce** [comment]
@laszlocsomor if I could get a bit of help to integrate this into the bazel release process, I'd appreciate it. It doesn't work yet for the Linuturk/mono-choco#8 issue, but I've made a bit of progress. Who should I ask for pointers into which parts of the release automation?

**Comment by laszlocsomor** [comment]
@petemounce , it should be @philwo , let me ping him!

**Comment by philwo** [comment]
@petemounce I've created the "bazel" account on chocolatey.org.

Is there anything I could do / help with at the moment? FYI, we do have Docker installed and usable on all Linux CI machines now and we also have working Windows VMs again.

**Comment by petemounce** [comment]
@philwo perfect, I'll invite that account as a maintainer.

Oh, there are Windows VMs again? That makes things more easy. Please elaborate? Core, GUI, Nano? If you can let me know details I can adjust the chocolatey build, and retain the test. Wouldn't have been able to retain the test for non-Windows.

**Comment by laszlocsomor** [comment]
Pete, it's Server 2016 Core:
```
PS C:\Users\laszlocsomor> [System.Environment]::OSVersion

Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.16299.0 Microsoft Windows NT 10.0.16299.0
```

**Comment by philwo** [comment]
We're running the latest & greatest version of Windows Server on GCE, which is currently: "Windows Server version 1709 Datacenter Core". Does that work for you?

**Comment by petemounce** [comment]
Perfect. I see chocolatey is already installed (https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/setup-windows.ps1#L71-L76) so my question then just becomes where to put the build/test/publish scripts that the chocolatey package will want to run, and where to hook those in to invoke them.

Inputs necessary:
* `VERSION` - bazel version being released (e.g. `0.11.1`, `0.11.1-rc3`)
* `BAZEL_WINDOWS_ZIP_SHA256` need to calculate the sha256 of the zip artifact
* `CHOCOLATEY_API_KEY` secret, presumably configured via buildkite
* `BAZEL_RELEASE_NOTES_URL` - can be inferred from version, above, being a final release or an RC
* `BAZEL_WINDOWS_ZIP_URL` as release notes URL

**Comment by lfpino** [comment]
Hi all, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by philwo** [comment]
Hi @petemounce,

just to make sure that I understand what this does: This automatically builds a Chocolatey package for Bazel releases and RCs and uploads it to chocolatey.org, is that right? So this should run as part of the release pipeline after build and test have succeeded?

I think it's fine to just put it somewhere into the scripts folder of Bazel.

**Comment by petemounce** [comment]
@philwo that's the intent, yes, with the extra that it installs Bazel via the package as well and assets success.

My question really is where to invoke this from such that the inputs (see my last comment?) are satisfied?

(I've only had sporadic opportunity to make progress)

**Comment by irengrig** [comment]
@philwo friendly ping from the Bazel sheriff. What is the status of this?

**Comment by petemounce** [comment]
This is now unnecessary because #4049.

**Pull request closed without merging**
