### PR TITLE
Minor Bash improvements

### PR DESCRIPTION
**Pull request by Androbin**
Based on output of static analysis tool.

https://github.com/koalaman/shellcheck/wiki/SC2166
https://github.com/koalaman/shellcheck/wiki/SC2207
https://github.com/koalaman/shellcheck/wiki/SC2145
https://github.com/koalaman/shellcheck/wiki/SC2001
https://github.com/koalaman/shellcheck/wiki/SC2129
https://github.com/koalaman/shellcheck/wiki/SC2128
https://github.com/koalaman/shellcheck/wiki/SC2004
https://github.com/koalaman/shellcheck/wiki/SC2048

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
@damienmg OK to make these changes?

**Comment by meteorcloudy** [comment]
@ulfjack I guess we can merge this as well?

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by damienmg** [comment]
I haven't had time to triple check yet but so far it LGTM. please have
another review first :)

**Comment by meteorcloudy** [comment]
This PR is causing some test failures, see http://ci.bazel.io/job/PR/job/bazel-tests/22/

**Comment by Androbin** [comment]
Could it be this line?
Original: `files+=($(bazel query $file))`
Current: `IFS=" " read -r -a files <<< "$(bazel query $file)"`
I think `bazel query` should be split at newline instead of whitespace?

**Comment by ulfjack** [comment]
bazel query outputs one label per line, so that sounds like it.

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by meteorcloudy** [comment]
Jenkins, test this please

**Comment by Androbin** [comment]
Could someone please comment on the intention of the following?

```
# Query for the associated buildables
buildables=$(bazel query \
    --keep_going \
    --noshow_progress \
    "kind(.*_binary, rdeps(//..., set(${files[@]})))")
```

If the intention is to concatenate all the array elements into one argument, use $*. This concatenates based on IFS. If the intention is to provide each array element as a separate argument, put the array expansion in its own argument.

**Comment by damienmg** [comment]
Jenkins: retest this please

**Comment by Androbin** [comment]
@damienmg Any thoughts on my last comment?

**Comment by damienmg** [comment]
@Androbin: replacing with files[*] is the right thing to do, the initial code is bogus.

**Comment by damienmg** [comment]
(there are still several test failures, I have no time to investigate right now)

**Comment by Androbin** [comment]
Since the test results are "inconsistent", I think it is probably this change:
`- echo "$lines" | sed 's/^/     /'`
`+ echo "${lines//^/     }"`

I know that `^` is a special character in regular expressions.
But if it worked before, it should work now just as well?

**Comment by damienmg** [comment]
Jenkins retest this please

**Comment by damienmg** [comment]
Btw:
```
$ lines="abc"
$ echo "${lines//^/ }"
abc
$ echo "$lines" | sed 's/^/ /'
 abc
```

These are not semantically equivalent.

**Comment by Androbin** [comment]
Okay, seems like `"${variable//search/replace}"` treats `^` als literal.
I reverted this particular change.
The original version just prefixes each line with 5 spaces.
Isn't there a simpler more obvious way of doing this?
If this is the only issue with the PR, we can leave it like that.

**Comment by damienmg** [comment]
Jenkins: retest this please.

I have no idea, I would be happy to find a better way to do it.

**Comment by Androbin** [comment]
Seems like a subtle discrepancy in quoting was an issue.
* Revert `$* -> "$@"` in `src/test/shell/testenv.sh`
which caused failures in:
`src/test/shell/bazel/apple:bazel_apple_test`
`src/test/shell/bazel:bazel_example_test`

**Comment by damienmg** [comment]
Jenkins: retest this please

**Comment by damienmg** [comment]
Remaining failures are in python test, this PR is good to merge, @mhlopko will take care of the rest

**Comment by mhlopko** [comment]
Importing...

**Pull request closed without merging**
