### PR TITLE
[6.3.0] Teach DexMapper to not separate synthetic classes from their context …

### LINKED ISSUE #16368: D8 dex merger fails when a synthetic class is placed on a different shard than its container class
### Description of the bug:

 a desugared lambda is packed in a different shard than the one
from its original class D8 will fail with the following message:

`Attempt at compiling intermediate artifact without its context
`
e.g.

I'm encountering an issue when compiling my app with the following classes:
`org/chromium/base/MemoryPressureListener
``org/chromium/base/MemoryPressureListener$$ExternalSyntheticLambda0`

bazel fails with the following message 

```
Error in bazel-out/k8-fastbuild/bin/apps/hermosa/hermosa-services/realtime/mirroring-sample-app/dexsplits/apk/9.shard.zip:org/chromium/base/MemoryPressureListener$$ExternalSyntheticLambda0.class.dex:
Attempt at compiling intermediate artifact without its context
Merge failed: Compilation failed to complete, origin: bazel-out/k8-fastbuild/bin/apps/hermosa/hermosa-services/realtime/mirroring-sample-app/dexsplits/apk/9.shard.zip:org/chromium/base/MemoryPressureListener$$ExternalSyntheticLambda0.class.dex
Exception in thread "main" com.android.tools.r8.CompilationFailedException: Merge failed: Compilation failed to complete, origin: bazel-out/k8-fastbuild/bin/apps/hermosa/hermosa-services/realtime/mirroring-sample-app/dexsplits/apk/9.shard.zip:org/chromium/base/MemoryPressureListener$$ExternalSyntheticLambda0.class.dex
at com.google.devtools.build.android.r8.DexFileMerger.main(DexFileMerger.java:389)
Target //apps/hermosa/hermosa-services/realtime/mirroring-sample-app:apk failed to build
```
Here the container class is in shard #8 and the lambda class is in shard #9

Running with d8 dexmerger and native multidex.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Its hard to provide a small reproducible example since it needs to be an app large enough to exceed the size of a dex file and the sharding has to result in a lambda class ending up in a different shard than the container class.

### Which operating system are you running Bazel on?

Linux/Mac

### What is the output of `bazel info release`?

Internal build merged with master at commit https://github.com/bazelbuild/bazel/commit/b6803a2a8367e0a6748256d2e1f162ceb5451636

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by ahumesky**
…classes when sharding dexes, like DexFileSplitter in https://github.com/bazelbuild/bazel/commit/9092303c358b87c1e027abafe135c44a27531b36. Fixes #16368

Cherrypick into bazel 6.3.0.

RELNOTES: None
PiperOrigin-RevId: 546041575
Change-Id: I12fa8cff15b13534ca9a5682b7e9b43e6c860ef8

### CODE REVIEW

**Review by iancha1992 — APPROVED** [review]

**Comment by ahumesky** [comment]
It looks like this depends on another change, I'll go looking for that and cherrypick it in

**Comment by ahumesky** [comment]
I believe the additional cherrypick is 773cfbadc6ef8e7c6ac866bab6617b2d339afa94 which I've added, let's see if the tests pass now

**Comment by ahumesky** [comment]
I'm not sure why `test_bazel_bin_is_not_a_package` in `//src/test/shell/integration:loading_phase_tests keeps` failing. It seems like it should be a transient issue ("Unknown host: github.com"), but it's happened 3 times in a row. I can't reproduce the issue locally either. Maybe there's another cherrypick that's needed (e.g. for the test infrastructure) but I'm not seeing what it could be.

**Comment by ahumesky** [comment]
With a partial cherrypick of e9929afa3de4595c52b466d3a9831a1afa2969a4 the tests are now failing with a couple timeouts instead... which is maybe an improvement... trying the tests again

**Comment by ahumesky** [comment]
bazel_hermetic_sandboxing_test is failing because its size is `small` still on the 6.3.0 branch (https://github.com/bazelbuild/bazel/blob/6fd3bc199d8d6c9de4c6b602eea00a5db64e96c8/src/test/shell/bazel/BUILD#L971) and it was bumped to medium in 3f0b223116f103807fdaf3d47f09079b0c6c9c80, but it appears to have passed on the 3rd try...

**Pull request merged**
