### PR TITLE
fix readme error in `bazel-and-java-md`

### PR DESCRIPTION
**Pull request by jamesma100**

### CODE REVIEW

**Comment by sgowroji** [comment]
Hi @jamesma100, Could you please sign the  Google CLA. Thanks!

**Comment by jamesma100** [comment]
> Hi @jamesma100, Could you please sign the Google CLA. Thanks!

done :)

**Review by sgowroji — APPROVED** [review]

**Comment by jamesma100** [comment]
why was this approved then closed? it hasn't been merged yet.

**Comment by sgowroji** [comment]
Hi @jamesma100, PR is merged at aedeb3c3133fb358013c2219b47b66eb54c8df6d, Sorry for the confusion.

**Pull request closed without merging**
