### PR TITLE
Document source of truth for `rctx.download*` cache key

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
Documenting the default caching behaviour for `rctx.download` and `rctx.download_and_extract`.
 
Related to #22652

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
Friendly ping @Wyverald

**Review by meteorcloudy — APPROVED** [review]

**Comment by iancha1992** [comment]
@fmeum @Silic0nS0ldier could you please take a look at the conflicts in the file? Thanks!

**Comment by Silic0nS0ldier** [comment]
Conflicts resolved.

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.3.0rc1`. Thanks!

**Pull request closed without merging**
