### PR TITLE
Python is unnecessary dependency

### PR DESCRIPTION
**Pull request by petemounce**
See #8794, cc @laszlocsomor.

While I'm here, do you know if less ancient msys2 versions work?

### CODE REVIEW

**Comment by laszlocsomor** [comment]
> \o/
> Could you please create PR for this?

Duh, I thought I commented on your commit... :)
Nice!

**Comment by laszlocsomor** [comment]
> While I'm here, do you know if less ancient msys2 versions work?

Absolutely. There's no requirement about the MSYS2 version. Latest release works.

**Comment by laszlocsomor** [comment]
Do you want to change that in this PR or keep it focused on python?

**Comment by petemounce** [comment]
Is prefer to keep this focused on python.

**Pull request closed without merging**
