### PR TITLE
[Bazel] Improve Mobile-Install Incremental Manifest Generating by applying multi-thread 

### PR DESCRIPTION
**Pull request by ThomasCJY**
**Background**
While using `mobile-Install`, we noticed that it constantly takes more to run on incremental build. Take our app for example, the incremental build metrics for a single line kotlin code change looks like this:

| Command                   | Time |
|---------------------------|------|
| bazel build + adb install | 63s  |
| mobile-install            | 91s  |

After digging into it, I found that the bottleneck is the "Incremental Manifest Generating" action which takes a lot of time (35+ sec) for multidex build. The time is spent on the checksum calculation for all dex files. The SHA256 checksum for each dex file takes around 1-2 sec. Currently in our app we have 10 dex shards and each dex zip contains 2-3 dex files, processing them sequentially takes more than 30 seconds. 

**Change**
In this PR, I added multithread support for this script so that the checksum calculation can be done concurrently and it improved the "Incremental Manifest Generating" to be done in 6 second (80%+ improvement).

**Result & Test**
After applying this change, the total incremental build time has been reduced to 43 seconds, with a 30s+ improvement from `Incremental Manifest Generating` step. 
Before:

After:

You can also easily verify this from command line:
```
jchen tmp % time python ../build_incremental_dexmanifest.py ../output/outmanifest.txt shard1.dex.zip  shard10.dex.zip shard2.dex.zip  shard3.dex.zip  shard4.dex.zip  shard5.dex.zip  shard6.dex.zip  shard7.dex.zip  shard8.dex.zip  shard9.dex.zip
python ../build_incremental_dexmanifest.py ../output/outmanifest.txt           0.70s user 0.72s system 31% cpu 4.583 total
jchen tmp % time python ../build_incremental_dexmanifest_before.py ../output/outmanifest.txt shard1.dex.zip  shard10.dex.zip shard2.dex.zip  shard3.dex.zip  shard4.dex.zip  shard5.dex.zip  shard6.dex.zip  shard7.dex.zip  shard8.dex.zip  shard9.dex.zip
python ../build_incremental_dexmanifest_before.py ../output/outmanifest.txt    0.65s user 0.64s system 3% cpu 37.908 total
```

### CODE REVIEW

**Comment by ThomasCJY** [comment]
@googlebot I consent

**Comment by ThomasCJY** [comment]
@ahumesky mind taking a look when available?

**Comment by ThomasCJY** [comment]
ping @ahumesky again can you take a look?

**Comment by ThomasCJY** [comment]
Seems like @ahumesky is not available? @laurentlb @gregestren is there anyone else who can help review this PR?

**Comment by gregestren** [comment]
I'll poke around to see...

**Comment by ahumesky** [comment]
Thank you for the thorough analysis, and sorry for the delay here!
I'll import this now, should be able to have it merged tomorrow or so.

**Review by ahumesky — APPROVED** [review]

**Comment by ThomasCJY** [comment]
@ahumesky not sure why this PR got closed? Can we reopen and merge it?

**Pull request closed without merging**
