### PR TITLE
Update rules_license to 0.0.3

### PR DESCRIPTION
**Pull request by aiuto**
Updates to the newest release so we can pick up the generic "notice" and "restricted" license types.

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Can you also update our MODULE.bazel file to add rules_license and fix our Bazel Bzlmod build?
https://buildkite.com/bazel/bazel-bazel-with-bzlmod/builds/177

**Comment by aiuto** [comment]
> Can you also update our MODULE.bazel file to add rules_license and fix our Bazel Bzlmod build? 

How do we run a presubmit against https://buildkite.com/bazel/bazel-bazel-with-bzlmod?

**Comment by aiuto** [comment]
I updated MODULE.

**Comment by aiuto** [comment]
Nevermind the question about how to do the presubmit. Florian opened up buildkite so the Bazel team can do their own runs.  With the update MODULE.bazel the bzlmod queue  should go green again. https://buildkite.com/bazel/bazel-bazel-with-bzlmod/builds/180

**Pull request closed without merging**
