### PR TITLE
Make `genquery` work in external repos

### PR DESCRIPTION
**Pull request by fmeum**
Previously, some parts of the `query` implementation would evaluate labels relative to the main repo in all cases.

RELNOTES: Fixed an issue where `genquery` in external repos would evaluate labels as if they were in the main repo.

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]
nice!

**Comment by Wyverald** [comment]
Could you please rebase this?

**Comment by iancha1992** [comment]
@fmeum could you please resolve the conflicts? Thanks!

**Comment by fmeum** [comment]
@iancha1992 Fixed

**Comment by fmeum** [comment]
@bazel-io fork 8.5.0

**Pull request closed without merging**
