### PR TITLE
Add CLion project directory to .gitignore

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by cpsauer** [comment]
Saw this and smiled. @fmeum, any chance you'd also be down to add the following?

1. .aswb (parallel, but for Android Studio)
2. .cache (for clangd support)

**Comment by aiuto** [comment]
stiffe is triage rotation this week. That post usually handles merging the trivial PRs, but this will only take a second.  I'll do the merge.
I can add the other two lines as well.

**Review by aiuto — APPROVED** [review]

**Comment by cpsauer** [comment]
(Did this change land? Not trying to be annoying--just trying to help catch if GitHub didn't detect the merge or something.)

**Comment by aiuto** [comment]
It did not land yet. The PR would autoclose once it does. It looks like I sent it back to @oquenchil for the second approve, but they must not have seen it yet.

**Comment by cpsauer** [comment]
Ah, sorry. Won't do again. (Intentions were good, though. Didn't know about second approve, and thought, maybe, it might not have auto-matched given changes bigger than the original, esp given google's close-and-reimport system.)

**Pull request closed without merging**
