### PR TITLE
fix a sh comparison to use strings to work with large numbers

### PR DESCRIPTION
**Pull request by johnynek**
partial fix to #5413.

Change-Id: I6c691a6048444b7e4bea6b497cd98670192ec9cb

### CODE REVIEW

**Comment by oscar-stripe** [comment]
cc @cushon is this an appropriate fix for part of the bug?

**Comment by cushon** [comment]
I think the underlying problem is that `seq` on macs defaults to formatting with `%g`, which starts using floating point, and bash doesn't want to evaluate e.g. `((1.3167e+06 == 0))`.

Can you check whether using `seq 0 71 -f "%.0f" ${#CLASSPATH_LINE}` fixes the problem you're seeing? It'd be nice to keep the numeric comparison instead of comparing formatted strings.

**Comment by johnynek** [comment]
```
#!/bin/sh

for i in `seq -f "%.0f" 0 71 1316701`; do
    PREFIX=" "
    if (($i == 0)); then
      PREFIX=""
    fi
    echo "good! $i"
done
```
works, but isn't this actually worse? this numeric comparison is just being used to catch the first iteration. Won't the string comparison be faster in general since you don't have to parse the numbers to see that it is not equal to `"0"`?

**Comment by cushon** [comment]
> isn't this actually worse?

I'm not sure. I ran this by a colleague and we came up with e3650359bd82dc50c6d4776ae260b6cd15d85efc, can you check if that fix works for you?

**Comment by johnynek** [comment]
the example seems to work fine in that case, so I guess it will work (testing the whole file isn't quite as easy at the moment).

Side note: it's a bummer to send PRs that fix the issue and then be asked to verify a fix for an already merged slightly different implementation. I don't know how important growing contributors is to the team, but this makes me less likely to send PRs since it seems to confirm the idea that the real development happens privately.

**Pull request closed without merging**
