### PR TITLE
Headermaps Take 2

### PR DESCRIPTION
**Pull request by ob**
### NOT READY, DO NOT MERGE

I've been playing with #3712 and as a first pass rebased it on top of a current master and incorporated all the feedback given in that PR. I also added an integration test. 

I need to add a way to expose the generated header map files to skylark so that other rules (e.g. `swift_library`) can use the header maps, but I thought I'd post this here since #3712 seemed pretty close as it was.

[Design Document](https://docs.google.com/document/d/1fGGLO6vXFHN_kQlvlcA-v_XQ2hc07N6hT0kyUwCSDws/edit?usp=sharing)

### CODE REVIEW

**Comment by ob** [comment]
@jerrymarino, I think you need to confirm you're okay contributing my rebased commit to make the @googlebot happy.

**Comment by jerrymarino** [comment]
@ob wow - great to see this updated. I'm not sure how to verify author consent - cc @googlebot

**Comment by mhlopko** [comment]
Hi Oscar, I'm sorry for the radio silence, there's nothing I can say in my defense. I'll take a thorough look first thing in the morning.

**Comment by ob** [comment]
No worries. The PR is still incomplete and I got distracted for a week. 

The design doc has some open questions and I also have a few implementation questions if you have the bandwidth. I’ll also be on Google Hangouts chat. 

Thank you for looking at this.

**Comment by ob** [comment]
This is no longer being pursued in this form

**Pull request closed without merging**
