### PR TITLE
file_test: add integration tests

### PR DESCRIPTION
**Pull request by laszlocsomor**
Pre-work for https://github.com/bazelbuild/bazel/issues/6122

Change-Id: I0de521a2e4cce23f843b19ade83dab7c1276b976

### CODE REVIEW

**Comment by ulfjack** [comment]
As a general note: we want to unbundle all .bzl rules from Bazel. Second, don't we have a Java integration test framework now?

Otherwise looks ok.

**Comment by laszlocsomor** [comment]
Thanks for looking!

> As a general note: we want to unbundle all .bzl rules from Bazel.
What does that mean for this PR?

> Second, don't we have a Java integration test framework now?
@irengrig : what's the status of that?

**Comment by ulfjack** [comment]
Unbundling means moving elsewhere. As long as we don't already have a copy, it's fine to make fixes here.

**Comment by irengrig** [comment]
> Thanks for looking!
> 
> > As a general note: we want to unbundle all .bzl rules from Bazel.
> 
> What does that mean for this PR?
> 
> > Second, don't we have a Java integration test framework now?
> 
> @irengrig : what's the status of that?

Not ready... Is that only for Bazel? Than we can try to write it in Java.

**Pull request closed without merging**
