### PR TITLE
Do not recommend `shallow_since` for `git_repository`

### LINKED ISSUE #10292: shallow_since appears to be broken
### Description of the problem / feature request:

`shallow_since` appears to be broken.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Try to build `//:BUILD.boost` from https://github.com/nelhage/rules_boost/commit/df908358c605a7d5b8bbacde07afbaede5ac12cf. You'll receive a recommendation for `shallow_since`. Insert that recommendation, and suddenly Bazel fails to find that commit at all.

### What operating system are you running Bazel on?

Windows

### What's the output of `bazel info release`?

release 1.1.0

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Create an empty `BUILD.bazel` alongside the following `WORKSPACE`:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
git_repository(name="rules_boost", commit="df908358c605a7d5b8bbacde07afbaede5ac12cf", remote="https://github.com/nelhage/rules_boost")
```

Now run `bazel --ignore_all_rc_files query "deps(@rules_boost//:BUILD.boost)"`:

```
bazel --ignore_all_rc_files query "deps(@rules_boost//:BUILD.boost)"
@bazel --ignore_all_rc_files clean --expunge
```

It outputs something like the following (after formatting/redactions):

```
INFO: Writing tracer profile to 'command.profile.gz'
DEBUG: Rule 'rules_boost' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1569511515 +0200"
DEBUG: Call stack for the definition of repository 'rules_boost' which is a git_repository (rule definition at external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - WORKSPACE:2:1
ERROR: no such target '@rules_boost//:BUILD.boost': target 'BUILD.boost' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["BUILD.boost"])' to /BUILD?) defined by external/rules_boost/BUILD
Loading: 1 packages loaded
```

Now add `shallow_since="1569511515 +0200"` as recommended and re-run the query:

```
INFO: Writing tracer profile to 'command.profile.gz'
INFO: Call stack for the definition of repository 'rules_boost' which is a git_repository (rule definition at external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - WORKSPACE:2:1
ERROR: An error occurred during the fetch of repository 'rules_boost':
error running 'git reset --hard df908358c605a7d5b8bbacde07afbaede5ac12cf' while working with @rules_boost:
fatal: Could not parse object 'df908358c605a7d5b8bbacde07afbaede5ac12cf'.
ERROR: no such package '@rules_boost//'
Loading: 0 packages loaded
```

Suddenly Bazel seems to be unable to find the commit altogether.

### LINKED ISSUE #12857: shallow_since appears to be a trap when used with commit, debug line should be removed
### Description of the problem / feature request:

The `shallow_since` option to `new_git_repository` appears to be a trap, at least when used with the `commit` option. When shallow_since is provided, instead of using `depth 1` to check out only the relevant commit, the entire repo state since some timestamp is cloned. On one of our repos, this causes a *25x* difference in clone time (7s -> 175s) and presumably a large size disparity as well.

Now that we have removed shallow_since, bazel emits a debug line encouraging us to add it back.
```
DEBUG: Rule 'foo' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1611092265 -0800"
```

This seems wrong -- as far as I understand, the repo at a specific commit hash _is_ a canonical reproducible form, so it seems like bazel should not be suggesting this change.

### Feature requests: what underlying problem are you trying to solve with this feature?

Bazel should not recommend adding shallow_since since it is dramatically slower in some cases, and seems generally unnecessary to obtain a snapshot of the repository.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a `new_git_repository` rule for a large git repository at a commit that is not close to HEAD. Providing shallow_since will slow down the clone substantially.

### What operating system are you running Bazel on?

Linux, Ubuntu 20.04

### What's the output of `bazel info release`?

```
INFO: Invocation ID: 6c8f5dce-cf89-4b6f-a335-93ff77612968
release 3.7.1
```

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

n/a

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

n/a (private repo)

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

n/a

### PR DESCRIPTION
**Pull request by fmeum**
Git's `--shallow-since` feature can lead to broken checkouts and a fix isn't likely to happen:
https://public-inbox.org/git/CAPSG9dZV2EPpVKkOMcjv5z+NF7rUu=V-ZkZNx47rCv122HsiKg@mail.gmail.com/T/#u

This commit removes `shallow_since` from the canonical reproducible form of `git_repository` unless the attribute is provided explicitly. In cases where Bazel's attempt at fetching with `--depth=1` fail, e.g. if there is no server support for shallow fetches of arbitrary commits, the progress message is now used to inform the user about this potential for fetch time optimizations.

Fixes #10292
Fixes #12857

### CODE REVIEW

**Comment by asuffield** [comment]
It's certainly an improvement over the status quo. To fully unbreak it we should also retry without shallow when reset fails - that's when we discover that shallow has "succeeded" and fetched junk.

**Comment by fmeum** [comment]
> It's certainly an improvement over the status quo. To fully unbreak it we should also retry without shallow when reset fails - that's when we discover that shallow has "succeeded" and fetched junk.

I was thinking of proposing something more radical as a follow-up (but not cherry-pickable into Bazel 6): Deprecating `shallow_since` and always removing it from the canonical representation. Assuming the user has control over the Git server, they can always enable lookups by SHA if a full fetch is too costly. If they don't control it, it's very likely that the server is GitHub/GitLab/... which all seem to have this feature enabled. 

@asuffield Do you think `shallow_since` is worth keeping around and "fixing"? If so, are there use cases in which it is clearly better than the other options?

**Comment by asuffield** [comment]
Yes, for some future bazel version we should drop it entirely and always pull commits by hash at depth 1, when an exact commit hash is given. This does require a relatively recent version of git, since depth 1 by hash was only added a couple of years ago, but that doesn't seem unreasonable. Of course that needs the usual deprecation dance, since it'll break any current users; the best cherry pick I can think of is to retry when reset fails and just pull a full clone, since that prevents any existing builds from being surprisingly broken in the future.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
> I was thinking of proposing something more radical as a follow-up

Thanks for the improvement! +1 if we can do the follow up change in a backwards compatible way.

**Comment by fmeum** [comment]
@meteorcloudy Do you think the current PR should be cherry-picked?

**Comment by meteorcloudy** [comment]
Sure, I'm fine with cherry-picking it.

**Comment by meteorcloudy** [comment]
Sure, I'm fine with cherry-picking it.

**Comment by fmeum** [comment]
@bazel-io flag

**Pull request closed without merging**
