### PR TITLE
[7.1.0] Exclude convenience symlinks after changing the output base

### LINKED ISSUE #10653: Change of --output_base causes subsequent builds to fail
### Description of the problem / feature request:

Change in --output_base parameter causes the build to break with very obscure error messages. 

### Feature requests: what underlying problem are you trying to solve with this feature?

When build is done using some IDEs (VSCode or IntelliJ) they tend to set their own --output_base, different from the one configured by the user for the command line builds. This should not cause any problems, but unfortunately it appears that after --output_base changes the build is broken.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Select any simplest Bazel project. Build it with `bazel --output_base=C:/blah1 build ...` so it builds successfully. Then try to build it with `bazel --output_base=C:/blah2 build ...` this time it breaks with the error messages which don't make any sense.

### What operating system are you running Bazel on?

The problem does not seem to be OS dependent.

### What's the output of `bazel info release`?

2.0.0

### Any other information, logs, or outputs that you want to share?

I figured that the problem is must probably caused by the stale "courtesy" symlink in WORKSPACE folder. After the first build Bazel creates "courtesy" symlink such as `bazel-<workspace_name>` in the workspace folder and it points inside output_base. When we issue second build command with the different output_base Bazel is smart enough to realize that and spawn second build server process, but unfortunately that stale `bazel-<workspace_name>` symlink still stays and points inside the old output_base which seems to confuse Bazel. Running `bazel clean` between builds or simply deleting of that symlink fixes the problem. It looks like when Bazel discovers the change in startup parameters which warrants spawning new build server it should at the same time remove existing courtesy symlinks as they are not valid anymore and cause the build to fail.

### LINKED ISSUE #13951: Changing output base results in failed builds due to parsing the contents of the convenience symlinks
### Description of the problem / feature request:

When changing the output base. Bazel no longer recognizes the `bazel-*` symlinks as it's own and parses the contents resulting in build failues

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Example repo at https://github.com/adamporich/simple-bazel-test just consists of a single passing test.

```
> bazel --output_base=/tmp/bazel_1 test //...
INFO: Invocation ID: bda33659-6dbb-4d03-9f8f-fb273b5bafa9
INFO: Analyzed target //:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //:test up-to-date:
  bazel-bin/test
INFO: Elapsed time: 0.075s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//:test                                                         (cached) PASSED in 0.0s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action

> bazel --output_base=/tmp/bazel_2 test //...
Starting local Bazel server and connecting to it...
INFO: Invocation ID: bb24dd33-6bbb-4c47-a943-ed4bfc65a34a
ERROR: error loading package 'bazel-bazel_symlink_test/external/bazel_tools/tools/cpp': in /home/gimo/dev/bazel_symlink_test/bazel-bazel_symlink_test/external/bazel_tools/tools/cpp/compiler_flag.bzl: Label '//tools/cpp:toolchain_utils.bzl' is invalid because 'tools/cpp' is not a package; perhaps you meant to put the colon here: '//:tools/cpp/toolchain_utils.bzl'?
INFO: Elapsed time: 1.998s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded)
FAILED: Build did NOT complete successfully (8 packages loaded)
```

### What operating system are you running Bazel on?

Above output is from Linux but occurs on Windows as well

### What's the output of `bazel info release`?

```
> bazel info release
INFO: Invocation ID: 4d53a63f-daf5-43a2-b0ff-f3ab4927c52c
release 4.2.1
```

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/11875 is a similar issue but in this case we don't need a root level glob to trigger

### Any other information, logs, or outputs that you want to share?

I did try and use the https://docs.bazel.build/versions/4.2.1/command-line-reference.html#flag--experimental_convenience_symlinks option but it didn't seem to have an effect.

### PR DESCRIPTION
**Pull request by bazel-io**
When the output base is changed after the convenience symlinks have been created, queries such as `//...` try to traverse into them and load them as packages since they are only excluded based on whether the resolved location is in the output base. This adds some heuristics to determine if a symlink is a convenience symlink:

1. The symlink name has an appropriate suffix.
2. An ancestor of the symlink target at the appropriate level is called `execroot`.
3. The `execroot` directory contains a file called `DO_NOT_BUILD_HERE`.

These heuristics should work if both the output base and the symlink prefix change while being quite robust to false positives.

This is important for IDE integration, where the [output base is often changed](https://bazel.build/run/scripts#output-base-option) for queries, to prevent concurrent builds from blocking them. An example of this is the vscode-bazel extension.

Fixes #10653
Fixes #13951

Closes #21005.

Commit https://github.com/bazelbuild/bazel/commit/8f74acef5f394e2b4cbcbed9ea73ad2b4fbaede7

PiperOrigin-RevId: 610667735
Change-Id: I1869c9a2063f7f526950e48c0b1ee6efa89fd202

### CODE REVIEW

**Review by lberki — APPROVED** [review]

**Comment by cameron-martin** [comment]
The test that is failing on CI passes for me locally. Is there any way of seeing the test logs on CI?

**Comment by cameron-martin** [comment]
It looks like the failing tests on CI are a network issue:

```
ERROR: Error computing the main repository mapping: in module dependency chain <root> -> bazel_tools@_ -> rules_cc@0.0.9: Error accessing registry https://bcr.bazel.build/: Unknown host: bcr.bazel.build
```

**Comment by iancha1992** [comment]
One of the tests is failing now. Could you please take a look? @lberki 

cc: @bazelbuild/triage

**Comment by cameron-martin** [comment]
@iancha1992 this looks like a network issue. See my comment above.

**Comment by lberki** [comment]
It does look like a network issue. It looks like this has already been merged, but had it not been, I'd have asked you to use `sh_library` instead of `py_library`: I could imagine that this test doesn't have network access and thus can't fetch `rules_python`. But it appears that it does, given that it's been submitted and CI is not very red?

**Comment by cameron-martin** [comment]
> It does look like a network issue. It looks like this has already been merged, but had it not been, I'd have asked you to use `sh_library` instead of `py_library`: I could imagine that this test doesn't have network access and thus can't fetch `rules_python`. But it appears that it does, given that it's been submitted and CI is not very red?

Yeah this passed in the original PR so I'm not sure why this wouldn't. It also passes locally for me so it can't be that networking it disabled via the sandbox.

**Comment by cameron-martin** [comment]
Seems like this might fix it: https://github.com/bazelbuild/bazel/pull/21529

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/pull/21547 should fix the remaining presubmit failures.

**Pull request merged**
