### PR TITLE
[7.3.0] Clean up build after update to 7.2.0

### PR DESCRIPTION
**Pull request by bazel-io**
Closes #22400.

PiperOrigin-RevId: 642564375
Change-Id: I1326aa33ddd30d29a51b928adcea0def42304fe9

Commit https://github.com/bazelbuild/bazel/commit/2758f55c1d4a11a296c0d9649880300d20ae96f9

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@fmeum Can you take a look at the failure?

**Comment by fmeum** [comment]
@meteorcloudy It looks like Bazel 7.3.0 doesn't build with 7.2.0 yet: https://github.com/bazelbuild/bazel/blob/release-7.3.0/.bazelversion

I don't know which commit updated this at HEAD, but cherry-picking it would be a prerequisite for this change.

**Comment by meteorcloudy** [comment]
Oh, right. @keertk and @Wyverald did the upgrade for HEAD

**Comment by Wyverald** [comment]
https://github.com/bazelbuild/bazel/pull/22726

**Comment by keertk** [comment]
Tracked here - https://github.com/bazelbuild/bazel/pull/22728

**Pull request closed without merging**
