### PR TITLE
Java runfiles: delete @bazel_tools//tools/runfiles

### PR DESCRIPTION
**Pull request by laszlocsomor**
This change deletes the Java runfiles target from
@bazel_tools//tools/runfiles:java-runfiles, as its
deprecation message said Bazel 0.19.0 would.

The new target to use is
@bazel_tools//tools/java/runfiles

Fixed https://github.com/bazelbuild/bazel/issues/5803

Change-Id: I8faebb9dc3759d4732d3a53e236e315e58147545

### CODE REVIEW

**Comment by laszlocsomor** [comment]
We could, but that would be inconvenient to use. Also, there's already plenty of code even outside of Bazel that use these libraries.

**Comment by laurentlb** [comment]
If you're moving the code anyway, it might be better to put it in a location where we can update it.

**Comment by laszlocsomor** [comment]
It's been moved already. This patch just cleans up the BUILD file from the old location.

**Comment by laszlocsomor** [comment]
Thanks for the comments, your arguments make sense.
That said, moving the code will require people to migrate their BUILD files to use the new location.

Do you think moving it to a new repo (e.g. "bazelbuild/runfiles-java"), and adding an alias rule or a forwarding java_library rule to `@runfiles-java` would be sufficient? The code would move out of `@bazel_tools` and only a referencing rule (with a deprecation message) would remain, and IIUC the code would no longer fall under this policy.

**Comment by laurentlb** [comment]
The goal is to let users migrate independently from Bazel.
`bazelbuild/runfiles-java` sounds very specific. It's probably easier to maintain if we put multiple related files in the same repository (like skylib).

**Comment by laszlocsomor** [comment]
I'm fine with per-language runfiles-repos or just one runfiles repo.
The question is, is adding a layer of indirection (a rule in `@bazel_tools` that just references the sources that are in another repo) enough to make the code not fall under the incompatible changes policy?

**Comment by laurentlb** [comment]
I don't think it's a good idea to hard-code in Bazel binary the location of another repository. But it doesn't help much: you need to specify with version (release or commit hash) of the repository you want to use. So either you point always to the same version (so no update at all), or you occasionally update the version (and then it becomes a breaking change).

**Pull request closed without merging**
