### PR TITLE
[Skylint] Do not crash ControlFlowChecker on nested functions.

### LINKED ISSUE #4511: Skylint crashes when invoked on a file with a nested function.
### Description of the problem / feature request:

> Skylint crashes with an error below when analyzing a .bzl file with a nested function. A file with
```
def yo():
  def bar():
    pass
```
will cause Skylint crash:
```
Exception in thread "main" java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:485)
	at com.google.devtools.skylark.skylint.ControlFlowChecker.visit(ControlFlowChecker.java:159)
	at com.google.devtools.build.lib.syntax.FunctionDefStatement.accept(FunctionDefStatement.java:78)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visit(SyntaxTreeVisitor.java:28)
	at com.google.devtools.skylark.skylint.ControlFlowChecker.visitBlock(ControlFlowChecker.java:86)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visit(SyntaxTreeVisitor.java:141)
	at com.google.devtools.skylark.skylint.ControlFlowChecker.visit(ControlFlowChecker.java:161)
	at com.google.devtools.build.lib.syntax.FunctionDefStatement.accept(FunctionDefStatement.java:78)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visit(SyntaxTreeVisitor.java:28)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visitAll(SyntaxTreeVisitor.java:34)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visitBlock(SyntaxTreeVisitor.java:47)
	at com.google.devtools.skylark.skylint.ControlFlowChecker.visitBlock(ControlFlowChecker.java:75)
	at com.google.devtools.build.lib.syntax.SyntaxTreeVisitor.visit(SyntaxTreeVisitor.java:62)
	at com.google.devtools.skylark.skylint.ControlFlowChecker.check(ControlFlowChecker.java:68)
	at com.google.devtools.skylark.skylint.Linter.lint(Linter.java:122)
	at com.google.devtools.skylark.skylint.Skylint.main(Skylint.java:48)
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> run Skylint on file with content described above

### Any other information, logs, or outputs that you want to share?

> Technically nested functions are already covered by Skylint linter, because EventHandler errors that happen during build file parsing are recorded as parse-error, but CFChecker does not know about this, so either CFChecker should be made resilient to this issue, or parse errors should prevent other checkers from running. I have a patch for the first option, but believe that second option may be a better one.

### PR DESCRIPTION
**Pull request by ttsugriy**
ControlFlowChecker has a precondition check that assumes nested functions do not occur. While this assumption is reasonable for a valid Skylark syntax, linter can actually be invoked on malformed files and users would get a stack trace instead of a human-readable linter error.

Alternative and possibly a better strategy would to not run CFChecker in case parse errors are detected.
fixes #4511

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by iirina** [comment]
jenkins test this please

**Comment by laurentlb** [comment]
Looks reasonable, thanks!

Assigning to Jon to take a look and merge the PR.

**Comment by philwo** [comment]
Ping @brandjon

**Comment by brandjon** [comment]
Sorry, I'll give it a proper look when my traveling slows down on
Monday/Tuesday.

On Sat, Feb 3, 2018 at 6:01 AM, Philipp Wollermann <notifications@github.com

**Comment by brandjon** [comment]
Looks good, importing.

**Pull request closed without merging**
