### PR TITLE
Remove java_tools_javac14 (releases and dependencies) from Bazel.

### PR DESCRIPTION
**Pull request by comius**
Java_tools_javac14 is a binary equivalent to java_tools_javac11. It was split from java_tools_javac 11 in order to be able to provide specific support for Java 14.

As a result a release of java_tools_javac* we now need 6 binaries and fix of dependencies and their hashes in Bazel on cca. 18 different places. Adding another Java version (e.g. Java 15) will add additional 3 binaries and 9 places to fix (total 9/27).

Also JDK 14 has reached EOL.

It makes sense to have only one release until we actually have some specific support for Java 14 or newer.

This is a partial revert of commits fe291f7dcadc20eb85cff07b2cd4d899d79fba71 and 693c88a8f897b6764b98c7d9da922ffc96c6d890:
- Add support for toolchain java 14
- Add unit test against released java_tools_javac14

### CODE REVIEW

**Comment by comius** [comment]
cc @davido, @Jonpez2

**Comment by comius** [comment]
related to https://github.com/bazelbuild/bazel/pull/12168

**Comment by davido** [comment]
SGTM.

Though, I would rather change the justificatin in the commit message to just: "JDK 14 is reached EOL", instead of bringing obscure math counting places needed to change in Bazel code base to add supprot for new `java_toolchain_jdk_xyz`.

**Review by philwo — APPROVED** [review]
Thanks!

**Pull request closed without merging**
