### PR TITLE
macOS compatibility in build.ps1.

### PR DESCRIPTION
**Pull request by petemounce**
Apparently powershell on macOS is a thing now...

However, chocolatey does not yet seem to be...

cc @dslomov

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by petemounce** [comment]
I tried this with powershell v6.0.0-beta9 on Sierra - change was necessary because the commands were resolving down to the native binaries instead of the powershell aliases.

**Comment by ulfjack** [comment]
I'll import this.

**Comment by ulfjack** [comment]
I get a bunch of lint errors on import.

```
ERROR: Lint errors found:
Use single quotes for non-interpolated string './*.nupkg'. See http://go/powershell-style#single_double.
	scripts/packages/chocolatey/build.ps1:38
Incorrect function capitalization: 'remove-item'. See http://go/powershell-style#function_naming.
	scripts/packages/chocolatey/build.ps1:38
...
Use single quotes for non-interpolated string './tools/*.orig'. See http://go/powershell-style#single_double.
...
Use single quotes for non-interpolated string './tools/params.*'. See http://go/powershell-style#single_double.
...
```

**Comment by dslomov** [comment]
@ulfjack Ignore Google's Powershell style violations.

**Comment by ulfjack** [comment]
"All functions, scripts, and Cmdlets should be named using the same Verb-Noun format used by standard PowerShell Cmdlets. For code readability and consistency, please select verbs from [...]."

**Pull request closed without merging**
