### PR TITLE
More Shell Cleaning - Part Two

### PR DESCRIPTION
**Pull request by Androbin**
@damienmg Here are a few more changes. (`third_party` only)

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by laszlocsomor** [comment]
I'll import this PR, but since parts of the source tree are mirrored in our internal VCS, and parts of it aren't, and this PR touches both parts, I'll import/merge it in chunks.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by laszlocsomor** [comment]
Good news: I managed to fully merge this PR.
Bad news: I forgot to edit the merge commit notes, so it has my name not yours :( sorry about that.
Silver lining: the previous commits are also yours, and do have your name properly.

**Comment by Androbin** [comment]
@laszlocsomor No deal, thanks anyway!

**Pull request merged**
