### PR TITLE
Support persistent worker for generating java ABI from source

### PR DESCRIPTION
**Pull request by oliviernotteghem**
Incremental build time on XL projects shows that using ABI jar generated from full jar (ijar) is faster than generating ABI jar from source (hjar), which is counter-intuitive as hjar should allow pipelining. This could be attributed to the lack of persistent worker support for generating ABI jar from source. This diff enables it, i.e you can build now with `--java_header_compilation --strategy=Turbine=worker` to generate ABI jar from source using workers.

Unfortunately, due to bugs in Turbine, build time couldn't be benchmarked. Verification was done only on simple project (Javalib1-> Javalib2 -> Javalib3 -> Javalib4) via build traces : 

before

after

UPDATE: we were able to build our XL apps with source ABI persistent workers. The win for incremental scenario (the ones we care the most about) are only 2-4%. Also, using ABI generated from full jar is still faster for us...

Screen Shot 2022-09-01 at 7 12 19 PM

### CODE REVIEW

**Comment by cushon** [comment]
> due to bugs in Turbine, build time couldn't be benchmarked

Which bugs?

**Comment by oliviernotteghem** [comment]
@cushon : at Uber, we use our own annotation processor for dependency injection ([motif](https://github.com/uber/motif)). When switching from `--nojava_header_compilation` to `--java_header_compilation` on our driver app, I noticed more files than expected are generating by the AP with Turbine, and therefore heading compilation may fail because of these extra java file getting compiled and sometimes needed additional (missing) entry on classpath.

Also, a second issue I noticed, is that *sometimes* the AP-generated files from Motif are simply missing from the hjar (this could be specific to kotlin android targets).

I could possibly investigate further, however it's not clear how to build Turbine as I don't see any build files within project?

**Comment by cushon** [comment]
> I could possibly investigate further, however it's not clear how to build Turbine as I don't see any build files within project?

The source is at https://github.com/google/turbine, the jars checked in to bazel are produced by the maven build in the turbine repo

**Comment by oliviernotteghem** [comment]
Got it - didn't realize the pom.xml file before. Any idea what could be wrong here? Are we the only one to experience this? If so, this could be an issue with our AP..

**Comment by cushon** [comment]
Does the AP use any internal javac APIs? Otherwise I don't know of any open issues here, but I've seen APs depend on javac implementation details (e.g. the order of elements returned by APIs), or it could be a turbine or javac bug. I can try to help investigate if it's possible to provide a repro.

**Comment by benjaminp** [comment]
(Let me link an old issue about this: https://github.com/bazelbuild/bazel/issues/8006)

**Comment by arunkumar9t2** [comment]
> Also, a second issue I noticed, is that sometimes the AP-generated files from Motif are simply missing from the hjar (this could be specific to kotlin android targets).


@oliviernotteghem I suspect this could be related to https://github.com/bazelbuild/bazel/issues/16087 and especially Kotlin. We noticed sometimes when using kt_android_library, even transitive plugins appear as direct plugins in the processor classpath. Not sure if that causes issues like annotations processors running twice or generated files not getting picked up correctly. A possible angle to investigate.

**Comment by oliviernotteghem** [comment]
@cushon : I could narrow down the issue we were facing when using Turbine Vs generating ABI from full jar. 
- First, the issue occurs only with kotlin rules, which register the java compile action [here](https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/compile.bzl#L690).
- Second, it happens only with our (internal) optimization to skip KAPT and perform annotation processing on kotlin classes during java compilation - see (*) for a quick explanation of how this is done. 

In this situation, the classes generated from annotation processor (from kotlin classes) are not included in the hjar output. This is a bit of a special situation, so I am not sure if this is something generic enough to fix in Turbine?

(*)
We registered a custom javac plugin, that adds target's kotlin compiled classes to the list of classes on which AP needs to be run (see abbreviated source below). The plugin is registered via the `javac_opts` argument of the java_common.compile call (`javac_opts.append('-Xplugin:"Kaptish %s"' % kt_runtime_jar.path)`)

```
@AutoService(Plugin::class)
class KotlinClassInjectorPlugin : Plugin {
  override fun getName() = "Kaptish"

  override fun init(task: JavacTask, vararg args: String?) {

    if (task is BasicJavacTask) {
      if (Options.instance(task.context).get(Option.PROC) == "none") {
        return
      }

      val classes =
          if (args.isNotEmpty()) getClassesFromJar(args.first()) else getClasses(task.context)
      Arguments.instance(task.context).classNames.addAll(classes)
    }
  }
```

**Comment by cushon** [comment]
> ```
> Arguments.instance(task.context).classNames.addAll(classes)
> ```

Is that `com.sun.tools.javac.main.Arguments`? Turbine only implements the JSR-269 APIs, anything that relies on javac implementation details isn't going to be supported.

**Comment by oliviernotteghem** [comment]
@cushon : yes, it is com.sun.tools.javac.main.Arguments

**Comment by arunkumar9t2** [comment]
After importing this we saw `too many open files` error on a large Android project during Turbine action. We saw similar error in `KotlinKapt` which is fixed [here](https://github.com/bazelbuild/rules_kotlin/pull/848).

Increasing shell limit and `-XX:-MaxFDLimit` would ideally fix it but I realized both JavaBuilder and Turbine does not add user specified jvm flags to their command line. I opened [this](https://github.com/bazelbuild/bazel/issues/16486) to track that. 

Manually fixing the JVM flags allows us to compile just fine.

**Comment by comius** [comment]
Hi @oliviernotteghem! Thank you for contributing to the Bazel repository. We appreciate your time and effort. It seems the review of this PR has stalled, so I will close it. Please feel free to reopen if you'd like to discuss anything further.

**Pull request closed without merging**
