### PR TITLE
Add zstd-jni to //third_party.

### PR DESCRIPTION
**Pull request by philwo**
Extracted from #11968, as I have to merge this separately from the rest
of that PR.

### CODE REVIEW

**Comment by philwo** [comment]
Will merge when presubmits pass.

**Comment by philwo** [comment]
Merged in https://github.com/bazelbuild/bazel/commit/941fe0a4b8a31a75ffa047cfcd59065793b38a72

**Comment by keith** [comment]
FYI when building on macOS this results in dozens of warnings:

```
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstd_compress_literals.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstd_compress.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstd_fast.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstd_double_fast.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstd_compress_sequences.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/huf_compress.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_zdict.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:28:9: warning: variable 'size' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    if (!samples_buffer) {
        ^~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:55:12: note: uninitialized use occurs here
E1: return size;
           ^~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:28:5: note: remove the 'if' if its condition is always false
    if (!samples_buffer) {
    ^~~~~~~~~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:14:9: warning: variable 'size' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    if (!samples_sizes) {
        ^~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:55:12: note: uninitialized use occurs here
E1: return size;
           ^~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:14:5: note: remove the 'if' if its condition is always false
    if (!samples_sizes) {
    ^~~~~~~~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:44:16: note: initialize the variable 'size' to silence this warning
    size_t size;
               ^
                = 0
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:74:9: warning: variable 'size' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    if (sample_sizes_array == NULL) goto E2;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:89:12: note: uninitialized use occurs here
E1: return size;
           ^~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:74:5: note: remove the 'if' if its condition is always false
    if (sample_sizes_array == NULL) goto E2;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:68:9: warning: variable 'size' is used uninitialized whenever 'if' condition is true [-Wsometimes-uninitialized]
    if (!samples_sizes) {
        ^~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:89:12: note: uninitialized use occurs here
E1: return size;
           ^~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:68:5: note: remove the 'if' if its condition is always false
    if (!samples_sizes) {
    ^~~~~~~~~~~~~~~~~~~~~
external/com_github_luben_zstd_jni/src/main/native/jni_zdict.c:80:16: note: initialize the variable 'size' to silence this warning
    size_t size;
               ^
                = 0
5 warnings generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_outputstream_zstd.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_directbufferdecompress_zstd.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/dictBuilder/divsufsort.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/legacy/zstd_v06.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/compress/zstdmt_compress.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_directbuffercompress_zstd.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_inputstream_zstd.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
INFO: From Compiling com_github_luben_zstd_jni/src/main/native/jni_fast_zstd.c:
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]
1 warning generated.
```

**Comment by keith** [comment]
Fix here https://github.com/bazelbuild/bazel/pull/12443

**Pull request closed without merging**
