### PR TITLE
Remove dead ConvertPathList

### PR DESCRIPTION
**Pull request by rongjiecomputer**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by iirina** [comment]
jenkins test this please

**Comment by meteorcloudy** [comment]
LGTM, thanks for the contribution!

**Comment by rongjiecomputer** [comment]
CI test failed at git fetching step. Please re-trigger CI test again.

**Comment by meteorcloudy** [comment]
jenkins test this please

**Pull request closed without merging**
