### PR TITLE
Update to Error Prone 2.3.2

### PR DESCRIPTION
**Pull request by cushon**

### CODE REVIEW

**Comment by ulfjack** [comment]
Let me try my new import script for third-party changes...

**Comment by ulfjack** [comment]
Merged as cffe0e30e4949dbf2a68fb6f2747ffe14333c8a7.

**Comment by cushon** [comment]
> Let me try my new import script for third-party changes...

Looks like it worked! Is it documented somewhere?

**Comment by ulfjack** [comment]
It isn't checked in yet. I also had to completely rewrite it since it wasn't working, but it seems to work now. Ideally, there'd be a way to also attach the original PR id, but, unfortunately, the script was a bit too quick and pushed the changes before I had figured out that part.

**Pull request closed without merging**
