### PR TITLE
Document `--experimental_output_paths`

### PR DESCRIPTION
**Pull request by fmeum**

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by iancha1992** [comment]
@fmeum @gregestren I can submit a CL for this one if this is ready for merge. Let me know.

**Comment by iancha1992** [comment]
@gregestren Is this good to be merged?

**Comment by aiuto** [comment]
Greg is OOO for a few more days. Although this is probably correct, I'll wait a few days for him to decide if it is ready to be documented, or if there is more work to go in first.

**Comment by fmeum** [comment]
> Greg is OOO for a few more days. Although this is probably correct, I'll wait a few days for him to decide if it is ready to be documented, or if there is more work to go in first.

It's been mentioned throughout our BazelCon talk and we even have the first users reporting on their experience. Would be great if we could merge this now to prevent confusion about which version has this flag.

**Comment by Wyverald** [comment]
This flag was discussed in both the BazelCon talk and extensively in the remote execution BoF, so I think some documentation is warranted.

**Review by Wyverald — APPROVED** [review]

**Pull request closed without merging**
