### PR TITLE
REST Cache Improvements

### PR DESCRIPTION
**Pull request by jgavris**
Discovered while implementing a REST cache for bazel using the Kitura web server. I plan to also change the server to be more lenient and allow accessing the request data even if content type is not specified. This makes the client a little more well behaved. 

https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/bodyParser/BodyParser.swift#L51

I've also added support for automatic content compression for GET / PUT operations (seeing ~25% compression rate, which is 🔥  for the more remote developers).

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by jgavris** [comment]
Any feedback on this?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by philwo** [comment]
@jgavris It seems like ContentEncodingHttpClient is deprecated in favor of DecompressingHttpClient, but I don't know enough about Apache HTTP Client to understand the implications of that: http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/ContentEncodingHttpClient.html

I just guess we don't want to introduce the usage of a deprecated class in new code. What do you think?

**Comment by jgavris** [comment]
@philwo Heh, that is also deprecated. They recommend switching to the builder, which may be a few extra lines of code. I'll give that a shot.

**Comment by jgavris** [comment]
@philwo Apache HTTP Client 4.3 introduced `HttpClientBuilder`, would it be ok to bump the jar? `DecompressingHttpClient` is also deprecated anyway.

**Comment by philwo** [comment]
@jgavris Thanks, that would be very helpful! I just checked and we do have Apache HTTP Client 4.5 internally in our Google repo as a newer version available, too, so there won't be any issues. :)

**Comment by jgavris** [comment]
@philwo Ok, I've bumped it.

**Comment by philwo** [comment]
Thanks! I'll give the merge a try on Tuesday when I'm back in the office.

**Comment by ulfjack** [comment]
Ping @philwo

**Comment by philwo** [comment]
Merging this now.

**Pull request closed without merging**
