### PR TITLE
Add uniquify parameter to TemplateDict.add_joined

### PR DESCRIPTION
**Pull request by fmeum**
The behavior is analogous to that of Args.add_joined.

### CODE REVIEW

**Comment by fmeum** [comment]
@hvadehra With this change, it would among other things become possible to collect the unique user link flags for a hypothetical `cc_static_library` in a memory efficient way (see #1920 and in particular [@oquenchil's example code](https://gist.github.com/oquenchil/3f88a39876af2061f8aad6cdc9d7c045)). Do you think it's worth the additional API in `TemplateDict`?

**Comment by fmeum** [comment]
@hvadehra I rebased onto master, this is ready for review again.

**Comment by fmeum** [comment]
@oquenchil In case @hvadehra should unavailable, could you perhaps review this PR? It's not something that needs to go into 6.0.

**Comment by hvadehra** [comment]
So sorry, this dropped off my radar somehow. Reviewing today.

**Review by hvadehra — APPROVED** [review]
I think it does make sense to have this, so thanks! Java rules might start using this for jvm_flags as well

**Pull request closed without merging**
