### PR TITLE
Make bazel_tools work again

### PR DESCRIPTION
**Pull request by meteorcloudy**
This PR address two problems:
- Partially rolledback https://github.com/bazelbuild/bazel/commit/ef1a21fd05e061a7bb7cb75c9c909af6b3adbbb1 to restore android tools extension to avoid breaking older rules_jvm_external and rules_kotlin versions: https://github.com/bazel-contrib/rules_jvm_external/issues/1270
- Add protobuf in MODULE.tools to ensure a Bazel 8 compatible version gets selected. (related https://github.com/bazelbuild/bazel/pull/23908)

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]

**Review by fmeum — APPROVED** [review]

**Comment by ahumesky** [comment]
We had a goal of removing all android-related code from the bazel 8 binary, and breaking changes can happen in major versions of bazel. Related to the discussions in https://github.com/bazel-contrib/rules_jvm_external/issues/1270, how far back do we need to support rules_jvm_external? We're working to make rules_android 0.6.0 work with rules_jvm_external and rules_kotlin, blocked on a few issues including the protobuf issue here.

**Comment by Wyverald** [comment]
that's a good point -- let's fix the protobuf thing first and let the whole android thing pan out, before deciding whether to do the partial //tools/android rollback? I acknowledge the tension between major Bazel versions making breaking changes and rulesets wanting to support older Bazel versions; we should make a conscious decision here before 8.0 release.

**Comment by Wyverald** [comment]
ow. @ahumesky, are you okay with us getting this PR submitted as-is, and then you guys can try to resolve the situation with rules_jvm_external, and _then_ we could maybe roll forward the //tools/android deletion?

**Comment by ted-xie** [comment]
An important question here is what Bazel RC's the rollbacks/rollforwards would occur in. It would be extra painful to have to wait for RCs to be cut in order for changes to be reflected.

**Comment by Wyverald** [comment]
If necessary, we can push RCs out very quickly for testing, no problem. (I'm talking multiple in a day.) cc @keertk @iancha1992

**Comment by ahumesky** [comment]
I think it's just an accident that `android_extensions.bzl` is still in the bazel repo (or we just hadn't gotten to deleting it yet. we were primarily concerned with removing things from the bazel binary before the bazel 8 cut).

Also if we do have to restore `android_extensions.bzl` in `@bazel_tools`, think we also have to restore these targets:
https://github.com/bazelbuild/bazel/blob/3f70ca11ca0f33f71544b1ea43e59995d6cc5f01/tools/android/android_extensions.bzl#L119-L123

> The new protobuf version depends on rules_jvm_external now, so I actually cannot bump it without fixing the rules_jvm_external issue first.

Do you mean update protobuf to work with bazel 8?

rules_jvm_external has a goal of being compatible with N-2 versions of bazel (e.g. https://github.com/bazel-contrib/rules_jvm_external/pull/1268#issuecomment-2432035205), but it's not clear that we need to ensure old versions of rules_jvm_external work with new versions of bazel (the compatibility matrix is already very difficult).

Would it work to first land adding the protobuf dep (https://github.com/bazelbuild/bazel/pull/23908) which is required for rules_android 0.6.0, then we can update rules_jvm_external for rules_android 0.6.0 (revert https://github.com/bazel-contrib/rules_jvm_external/pull/1215 / restore https://github.com/bazel-contrib/rules_jvm_external/commit/ba7310ce4a1d8fb14434597fbc7440a4074f7695, and also this I think https://github.com/bazel-contrib/rules_jvm_external/pull/1268), then we can update rules_kotlin (https://github.com/bazelbuild/rules_kotlin/pull/1205, probably others). Or are there more circular dependencies that prevent all this from working?

**Review by Henrryxdjr — APPROVED** [review]

**Comment by ahumesky** [comment]
After discussing this, because of the various circular dependencies we'll need to restore android_extensions.bzl to update all the rulesets for bazel 8

**Review by ahumesky — APPROVED** [review]

**Comment by Wyverald** [comment]
@bazel-io fork 8.0.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 8.0.0 RC2](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc2). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.0rc2`. Thanks!

**Pull request closed without merging**
