### PR TITLE
ijar: read Code attribute

### PR DESCRIPTION
**Pull request by Yannic**
JVMS 4.7.3: "If the method is either native or abstract, its method_info
structure must not have a Code attribute. Otherwise, its method_info structure
must have exactly one Code attribute."

As hack around this, we instead emit a (dummy) Code attribute that does not
depend on the actual implementation of the method. This should fix compatibility
with tools like https://spotbugs.github.io which seem to care about the Code
attribute of dependencies and currently fail with ijar enabled.

Since there are some performance concerns about emitting a code attribute at
all, we start with only reading the Code attribute in this PR and add the code
to emit the dummy attributes in a follow-up to make benchmarking easier.

Progress on https://github.com/bazelbuild/bazel/issues/13546

### CODE REVIEW

**Comment by Yannic** [comment]
@cushon PTAL

**Comment by cushon** [comment]
> Since there are some performance concerns about emitting a code attribute at
all, we start with only reading the Code attribute in this PR and add the code
to emit the dummy attributes in a follow-up to make benchmarking easier.

I don't understand why would need to read code attributes.

If it ever supports writing them, I'd expect it to write a code attribute that did something like unconditionally throw for non-void methods, which doesn't require inspecting the original real code attribute.

**Comment by cushon** [comment]
> This should fix compatibility with tools like https://spotbugs.github.io/ which seem to care about the Code attribute of dependencies and currently fail with ijar enabled.

Can you add context in #13546?

**Comment by keertk** [comment]
Hi there! Thank you for contributing to the Bazel repository. We appreciate your time and effort. We're doing a clean up of old PRs and will be closing this one since it seems to have stalled. Please feel free to reopen if you’re still interested in pursuing this or if you'd like to discuss anything further. We’ll respond as soon as we have the bandwidth/resources to do so.

**Pull request closed without merging**
