### PR TITLE
Sort recorded inputs in lockfile entries of module extensions

### PR DESCRIPTION
**Pull request by fmeum**
Order doesn't matter for these inputs and sorting them can only help decrease merge conflicts in the lockfile.

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald Do you happen to understand why https://github.com/bazelbuild/bazel/pull/24363 saw changes to the recorded inputs section? They were kept in `HashMap`, but last time I looked into this, I thought that `HashMap` ordering was still a deterministic function of the series of operations on a given instance.

**Comment by fmeum** [comment]
@bazel fork 8.0.0

**Review by meteorcloudy — APPROVED** [review]
Thanks!

**Comment by Wyverald** [comment]
> I thought that `HashMap` ordering was still a deterministic function of the series of operations on a given instance.

I've always been told not to rely on any sort of ordering from hash containers, so either way it's good to get some guaranteed deterministic behavior here.

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 8.0.0 RC3](https://github.com/bazelbuild/bazel/releases/tag/8.0.0rc3). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=8.0.0rc3. Thanks!

**Pull request closed without merging**
