### PR TITLE
Create incompatible flags to remove pkg_deb and pkg_rpm

### PR DESCRIPTION
**Pull request by aiuto**
Create incompatible flags to remove pkg_deb and pkg_rpm on a different schedule from pkg_tar.
   //tools/build_defs/pkg:incompatible_no_build_defs_pkg_deb
   //tools/build_defs/pkg:incompatible_no_build_defs_pkg_rpm

The process of removing pkg_tar is blocked on switching from a dummy internal rules_python to the external rules_python, so that may not happen in time for the next major Bazel release.

Splitting removal of  deb and rpm packaging rules out let's us flip that flag earlier.

Track removal in #11217 and #11218

### CODE REVIEW

**Comment by aiuto** [comment]
Ping

**Comment by aiuto** [comment]
friendly ping

**Review by philwo — APPROVED** [review]

**Comment by philwo** [comment]
Don't see anything problematic with this, so from my side please go ahead.

**Comment by aiuto** [comment]
I don't think it will help.   From looking at the CI scripts, I think this kind of flag will never be used.
bazelisk --migration might, but CI won't detect anything that does not begin with the prefix --incompatible.

**Comment by philwo** [comment]
@aiuto Can we close this?

**Comment by aiuto** [comment]
Yes. I think the best path forward is to simply delete the code without a flag. The version in rules_pkg is still backwards compatible so people can easily migrate to that.

**Pull request closed without merging**
