### PR TITLE
SolibSymlinkAction does not need exec platform or properties

### PR DESCRIPTION
**Pull request by glukasiknuro**
https://github.com/bazelbuild/bazel/issues/14826

### CODE REVIEW

**Comment by jlaxson** [comment]
@bazel-io flag 

I'd like to suggest this should be a blocker for the 5.x series.  It is a regression from 4.2, appears to have a viable fix ready, and the underlying issue doesn't seem to have a workaround.

**Comment by jlaxson** [comment]
@bazel-io flag

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by ckolli5** [comment]
@bazel-io fork 5.2.0

**Review by oquenchil — APPROVED** [review]
LGTM

**Pull request closed without merging**
