### PR TITLE
Add helper for Markdown inline code escaping

### PR DESCRIPTION
**Pull request by fmeum**
The helper adds escaping to a string so that it can be embedded in a Markdown inline code segment delimited by backticks.

### CODE REVIEW

**Review by tetromino — CHANGES_REQUESTED** [review]
I agree with the PR in principle, but I would ask for some changes.

1. Terminology nit: GH-flavored-markdown's official name for this is ["code span"](https://github.github.com/gfm/#code-spans), so let's rename the method to `markdownCodeSpan`
2. Please include the outermost backticks in the function's output. The *only* reason to not include them would be to allow concatenating multiple strings within a single span, e.g.  to have`` `${util.markdownCodeSpanEscape(foo)}${util.markdownCodeSpanEscape(bar)}` `` in a template - but that is impossible to do safely (consider what happens when `${util.markdownCodeSpanEscape(foo)}` outputs a string with a terminal sequence of `` ` ``-s). Omitting the outermost onion layer of backticks is therefore a footgun for careless template writers.
3. We'd want a unit test in ~src/test/java/com/google/devtools/build/skydoc/SkydocTest.java~ on second thought, let's create a src/test/java/com/google/devtools/build/skydoc/MarkdownUtilTest.java

**Comment by tetromino** [comment]
I agree with the PR in principle, but I would ask for some changes.

1. Terminology nit: GH-flavored-markdown's official name for this is ["code span"](https://github.github.com/gfm/#code-spans), so let's rename the method to `markdownCodeSpanEscape`
2. Please include the outermost backticks in the function's output. The *only* reason to not include them would be to allow concatenating multiple strings within a single span, e.g.  to have`` `${util.markdownCodeSpanEscape(foo)}${util.markdownCodeSpanEscape(bar)}` `` in a template - but that is impossible to do safely (consider what happens when `${util.markdownCodeSpanEscape(foo)}` outputs a string with a terminal sequence of `` ` ``-s). Omitting the outermost onion layer of backticks is therefore a footgun for careless template writers.
3. We'd want a unit test in ~src/test/java/com/google/devtools/build/skydoc/SkydocTest.java~ on second thought, let's create a src/test/java/com/google/devtools/build/skydoc/MarkdownUtilTest.java

**Comment by tetromino** [comment]
Note that I'm in the process of moving the renderer code from Bazel into the Stardoc repo; if you don't have time to make those changes, I can do them myself before the move (to avoid merge complications).

**Review by tetromino — APPROVED** [review]
Thanks. Looks good. I took the liberty of adding the  missing srcs filegroup and fixing some stylistic nits / linter suggestions.

**Comment by fmeum** [comment]
@tetromino Thanks! Looks like there is a visibility issue with that though.

**Pull request closed without merging**
