### PR TITLE
[6.3.0] Let `common` ignore unsupported options

### LINKED ISSUE #3054: bazelrc: Allow "common" lines to always accept any legal Bazel options
### Description of the problem / feature request / question:

Currently, if a bazelrc file contains a `common` line, then all of the specified options are passed to every bazel command that is run. I propose that the `common` line *always allow all legal options that can apply to any command, but silently ignore the ones that don't apply to the current command.*

The current behavior can easily lead to unnecessary error messages, and greatly hampers the usefulness of the `common` feature.

For one thing, there are very few Bazel options that are actually common across every command.

Also, although bazelrc supports inheritance (e.g. `test` and `run` will automatically inherit from any `build` lines), that inheritance isn't always enough. For example, suppose I want to have a custom `--package_path` for every Bazel command that supports that flag. It's not sufficient to write

    build --package_path ...

because that will apply to `build`, `test`, and `run`, but not to `fetch`, `info`, and `query`, which do _not_ inherit from `build` but _do_ support the `--package_path` option.

I could write

    build --package_path ...
    fetch --package_path ...
    info --package_path ...
    query --package_path ...

But that is (a) messy, (b) requires me to do a lot of research to carefully figure out which commands support `--package_path`, and (c) could break in the future if I upgrade to a newer version of Bazel that supports `--package_path` for additional commands.

What I really want is to write

    common --package_path ...

but I can't, because that breaks any command that doesn't support that flag, such as `bazel help`.

I think probably the best way to address this is what I proposed above: The `common` line always allows all legal options that can apply to any command, but silently ignores the ones that don't apply to the current command.

So `common --package_path ...` would never cause an error, but `common --invalid_flag` would cause an error.

### Environment info
* Operating System:

OS X

* Bazel version (output of `bazel info release`):

0.4.5

### PR DESCRIPTION
**Pull request by iancha1992**
Fixes #3054

RELNOTES: Options specified on the pseudo-command `common` in `.rc` files are now ignored by commands that do not support them as long as they are valid options for *any* Bazel command. Previously, commands that did not support all options given for `common` would fail to run. These previous semantics of `common` are now available via the new `always` pseudo-command.

Closes #18130.

Commit https://github.com/bazelbuild/bazel/commit/44d395338ab9a27596b0796c14076641f4cb2093

PiperOrigin-RevId: 534940403
Change-Id: I2ae268ae84de3f2b07ff3d1e36bf382bce714968

### CODE REVIEW

**Review by justinhorvitz — APPROVED** [review]

**Comment by iancha1992** [comment]
@justinhorvitz @fmeum Looks like the checks are failing. Do you think we need any additional commit to pass the checks?

**Comment by fmeum** [comment]
The commit depends on a minor change to a BUILD file introduced by https://github.com/bazelbuild/bazel/commit/3dc69515210897c00d645e323dff23dfd178970c. @kkress Would you say that your commit qualifies for a cherry pick to Bazel 6.3.0?

**Comment by kkress** [comment]
I don't know what the Cherry-pick requirements are for 6.3 so I can't say if it qualifies. That said it's a backwards compatible change to a single flag that probably no one uses, so should be safe to apply to older code. 

Alternatively just adding the dep to the build file in it own commit is also probably harmless.

**Comment by fmeum** [comment]
@iancha1992 Could you try to cherry-pick https://github.com/bazelbuild/bazel/commit/3dc69515210897c00d645e323dff23dfd178970c first?

**Pull request closed without merging**
