### PR TITLE
Starlark: Add dict union operators | and |=

### PR DESCRIPTION
**Pull request by fmeum**
Implements the Starlark spec addition of https://github.com/bazelbuild/starlark/pull/215.

Work towards #12457

### CODE REVIEW

**Comment by aiuto** [comment]
Is there an issue for this? 
It seems like we shouljd have discussed it first, so the other Starlark implementations can more easily stay in sync.

**Comment by fmeum** [comment]
@aiuto Sorry for the confusion, I created this as a draft PR specifically because I first wanted to ask about the proper procedure at https://github.com/bazelbuild/starlark/issues/14. I found that issue to convey positive signal towards whether this should be implemented, so I thought that having one concrete implementation including test cases would aid the final discussion. If you prefer to keep the open PR count low, I can close the PR until I have gotten a reply over at https://github.com/bazelbuild/starlark/issues/14.

**Comment by aiuto** [comment]
No need to close the issue. But let's finish the discussion in the original FR bug.  So, maybe just convert to draft, so it stays around.

**Comment by fmeum** [comment]
> No need to close the issue. But let's finish the discussion in the original FR bug. So, maybe just convert to draft, so it stays around.

It's been a draft all along, but I agree that we should continue the discussion on the other repo.

**Comment by fmeum** [comment]
The spec has been updated, so this is now ready for review.

**Review by laurentlb — APPROVED** [review]
lgtm

(import is pending @brandjon or @tetromino 's approval)

**Pull request closed without merging**
