### PR TITLE
Call FindMissingBlobs before BES artifact upload. Fixes #8673, #7630

### LINKED ISSUE #8673: RE combined with BES is slow with large output artifacts
### Description of the problem / feature request:

When BES is used in conjunction with remote-execution, output artifacts tagged `no-remote` and `no-cache` are uploaded to the CAS. When these outputs are large in size, this can result in significant performance penalties.

More concretely, we have seen significant performance penalities when BES is used in conjunction with RE, but *not* when each was used in isolation.

It would be beneficial to introduce a bazel command line flag which would disable BES artifact upload for output artifacts corresponding to targets that are marked `no-remote` and `no-cache`. The paths for output files corresponding to these targets should be local (or none at all) and not bytestream:/// pathnames.

### What operating system are you running Bazel on?

macOS 10.14.x

### What's the output of `bazel info release`?

release 0.25.3

###  Have you found anything relevant by searching the web?

https://github.com/bazelbuild/bazel/issues/8249 refers to how file URIs are automatically translated to bytestream:/// paths in remote execution/remote cache contexts

### PR DESCRIPTION
**Pull request by buchgr**
Bazel unconditionally uploads files referenced by BEP events to the remote cache. This change makes it so that Bazel calls FindMissingBlobs() before uploading a file.

This should drastically improve BES performance for when files already exist remotely (i.e. when using remote execution).

A side effect of this change is that it also moves calls to potentially blocking Path#getDigest() on the thread pool.

### CODE REVIEW

**Comment by buchgr** [comment]
@arlyon can you review please? Ideally, test it our for your use case?

**Comment by arlyon** [comment]
> @arlyon can you review please? Ideally, test it our for your use case?

I'll run some checks on it and review. Aiming for 4pm UTC.

**Comment by arlyon** [comment]
Code looks good, local testing with smaller builds show no immediate issues. Currently running a larger build that should take around 30-60 mins so I'll update as that runs.

**Comment by buchgr** [comment]
@arlyon can you please reply with `@googlebot I consent.` as the @googlebot god wants from us?

**Comment by arlyon** [comment]
Hey @buchgr, having some problems (unrelated to the patch) in our test env. What is the latest you need this done by?

**Comment by buchgr** [comment]
@arlyon I believe we'll cut tomorrow end-of-day. the earlier the better :).

**Comment by buchgr** [comment]
@arlyon can you please reply with the googlebot command anyway? Else I won't be able to credit you with this change.

**Comment by arlyon** [comment]
@googlebot I consent.

**Comment by arlyon** [comment]
Hey, we're happy on our end. Thanks for helping us get this through.

**Comment by buchgr** [comment]
Thanks @arlyon!

**Comment by buchgr** [comment]
@arlyon has signed the cla according to https://github.com/bazelbuild/bazel/pull/9031. I also manually looked up the author's e-mail in the CLA list. He also responded with `@googlebot I consent` but the googlebot did not recognize it.

**Pull request closed without merging**
