### PR TITLE
Add pprof proto.

### PR DESCRIPTION
**Pull request by tomlu**
Sourced from https://github.com/google/pprof. Will be used to
output pprof-compatible profiling data from bazel.

### CODE REVIEW

**Comment by damienmg** [comment]
Please add a LICENSE file.

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
test this please

**Comment by tomlu** [comment]
I added a LICENSE file as requested. I can't see the actual test failure in the logs, as far as I can tell everything did in fact succeed. Nor do I understand how anything could possibly fail.

**Comment by damienmg** [comment]
Merged :)

**Pull request closed without merging**
