### PR TITLE
Update coverage output generator to include 3b75bc7d7aee7bcdbb51a1522…

### PR DESCRIPTION
**Pull request by meisterT**
…df8efb3121bb4e5.

RELNOTES[NEW]: Support code coverage with GCC 9.

### CODE REVIEW

**Comment by meisterT** [comment]
cc @helaan

**Comment by helaan** [comment]
In case you were CC'ing me because the build is failing: I see it is trying to download a file from `https://mirror.bazel.build/bazel_coverage_output_generator/releases/coverage_output_generator-v2.2.zip`, which it can't find. Is the new release uploaded properly or does it just need some time to propagate?

**Comment by meisterT** [comment]
No, I was just cc'ing you to keep you in the loop.

The file is now in the right place and I triggered a rebuild. So let's hope that it'll come back clean.

**Comment by meisterT** [comment]
Well, no luck, some coverage tests are broken.

I don't have time to look into them today, so you may want to do so. Easiest is to patching in my PR and then run `bazel test //src/test/shell/bazel:bazel_coverage_java_test`.

**Comment by helaan** [comment]
Hmm, looked into it for a bit, I can reproduce the issue on my machine when I perform the steps myself, is it possible that a change different to the one we are integrating is responsible for the breakage? As spotted in #11585 the previous release of COG did not include commit 21f633ca, nor the 6 other commits that have been made since then.

**Comment by meisterT** [comment]
955a4fd seems to be the culprit, but I haven't yet looked why

**Comment by meisterT** [comment]
This is the fix: https://github.com/bazelbuild/bazel/pull/11605

**Pull request closed without merging**
