### PR TITLE
ijar: Widen some size types.

### PR DESCRIPTION
**Pull request by benjaminp**
This is a follow up to https://github.com/bazelbuild/bazel/commit/ac10bac23bd138f64b071749e10b03fe22df333e.

### CODE REVIEW

**Comment by hvadehra** [comment]
Is it possible to add a test for this?

**Comment by benjaminp** [comment]
It's hard to write on that doesn't take up GBs of memory. I was mostly fixing up the signedness compiler warnings triggered by https://github.com/bazelbuild/bazel/commit/ac10bac23bd138f64b071749e10b03fe22df333e.

**Review by hvadehra — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 7.0.0

**Comment by iancha1992** [comment]
A fix for this issue has been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. Thanks!

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
