### PR TITLE
Expose documented function return values in stardoc

### PR DESCRIPTION
**Pull request by segiddins**
Closes https://github.com/bazelbuild/stardoc/issues/58

### CODE REVIEW

**Comment by segiddins** [comment]
Ping on getting this reviewed?

**Comment by thomasvl** [comment]
@c-parsons @laurentlb

**Comment by alandonovan** [comment]
The code change seems fine to me, but @c-parsons is the expert.

**Comment by segiddins** [comment]
@thomasvl would that show up in the templates basically the same way `Returns:` does?

**Comment by thomasvl** [comment]
That would be my guess.

**Comment by segiddins** [comment]
Added deprecations as a new commit

**Comment by segiddins** [comment]
@c-parsons I'd appreciate a review when you get a chance!

**Comment by c-parsons** [comment]
This looks good to me. I'll submit this upstream. Thank you so much!

**Pull request closed without merging**
