### PR TITLE
Flip the default value of --experimental_remote_discard_merkle_trees to true

### PR DESCRIPTION
**Pull request by moroten**

### CODE REVIEW

**Comment by moroten** [comment]
@EdSchouten here it is!

**Comment by EdSchouten** [comment]
Then I suppose we should also drop the `experimental_` prefix?

**Comment by coeuvre** [comment]
Thanks! Can you also check why tests are failing?

**Comment by coeuvre** [comment]
> Then I suppose we should also drop the `experimental_` prefix?

As we discussed offline, let's keep the prefix because maybe it's possible to restructure the code so that the flag is no longer necessary and can be removed.

**Review by coeuvre — APPROVED** [review]

**Pull request closed without merging**
