### PR TITLE
Upgrade absl-py from 0.1.1 to 1.3.0

### PR DESCRIPTION
**Pull request by fweikert**
Should fix https://github.com/bazelbuild/bazel/issues/16975

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Looks like we have to bump https://cs.opensource.google/bazel/bazel/+/master:src/test/shell/integration/minimal_jdk_test.sh;l=45 again..

**Review by meteorcloudy — APPROVED** [review]

**Comment by fweikert** [comment]
Yeah, I guess that's the long term plan.

**Comment by meteorcloudy** [comment]
which means we have to split this PR to merge the changes..

**Comment by fweikert** [comment]
Arg, I forgot :( will do

**Pull request closed without merging**
