### PR TITLE
Download the sha1 of the jar file from maven in generate_workspace.

### PR DESCRIPTION
**Pull request by wjywbs**
The sha1 is not calculated yet for local jars.

### CODE REVIEW

**Comment by kchodorow** [comment]
Thanks for the patch!  Could you add a test (maybe just a line [here](https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/generate_workspace_test.sh#L121))?

**Comment by wjywbs** [comment]
Test added, thanks.

**Comment by kchodorow** [comment]
Sorry about the delay getting this in, our automatic script is designed to handle a single commit (sigh).  I'll manually merge it tomorrow.

**Comment by damienmg** [comment]
This was merged :)

**Pull request closed without merging**
