### PR TITLE
[6.4.0] Add visionOS support

### PR DESCRIPTION
**Pull request by keith**
This cherry picks https://github.com/bazelbuild/bazel/pull/18905 and https://github.com/bazelbuild/bazel/pull/19133

### CODE REVIEW

**Comment by meteorcloudy** [comment]
I remember there were some breakages caused by this change at Bazel@HEAD, will this cherry pick introduce the same breakages into 6.4?

**Comment by keith** [comment]
the issue is that folks have to have platforms >= 0.0.7, which would apply for this too

**Comment by meteorcloudy** [comment]
Is it possible to only trigger the breakage when visonos config is actually used? I'm a bit reluctant to merge this since it'll cause breakages for users who haven't adopted Bzlmod (which is still the majority of Bazel users).

**Comment by brentleyjones** [comment]
If we do that, we should get that into 7.0 as well.

**Comment by keith** [comment]
maybe we should just toss the cc_test behavior for this? I can't think of a case where a `cc_test` target would be built for visionOS

**Comment by keith** [comment]
same with other platforms like watchOS, but I just added this config in the existing places. these tests won't pass (unless google has something internal for this) since they need to be hosted in simulators which is managed by rules_apple

**Comment by googlewalt** [comment]
It seems practical to drop support for visionos in cc_test for the time being.  Even internally we don't have many uses of cc_test for ios, tvos, and watchos.

**Comment by keith** [comment]
Done.

**Comment by brentleyjones** [comment]
Can/should we do that at HEAD as well, so people have an easier time upgrading to Bazel 7?

**Comment by meteorcloudy** [comment]
Yes, I would also recommend to make the same change at HEAD and backport it to 6.4

**Comment by keith** [comment]
should be good to include it here still but here's the PR for main https://github.com/bazelbuild/bazel/pull/19488

**Comment by iancha1992** [comment]
@nglevin @lberki @ted-xie @googlewalt Is this good to be merged to release-6.4.0? Or are we still waiting?

**Comment by keith** [comment]
doing it on 6.4 first should be fine, even if it never lands on main that will just mean main has a feature that 6.4 doesn't for this which i think is fine

**Pull request merged**
