### PR TITLE
Remove javac.jar as a dependency of java tools

### PR DESCRIPTION
**Pull request by meteorcloudy**
We no longer need the javac.jar for building java tools if we're building with JDK11.

This helps remove javac.jar as a dependency of the Debian build, which
is a part of OpenJDK and won't be able to be packaged in Debian.

However, the javac jar will still exist in third_party because some tests depend on it.

Working towards: #9408

### CODE REVIEW

**Comment by meteorcloudy** [comment]
@cushon Looks like we are able to remove javac.jar if we build the java tools with JDK 11.

I have to add extra `--javabase` option to the build script to make sure we use JDK 11, which is not what is said at https://docs.bazel.build/versions/master/bazel-and-java.html#configuring-the-jdk:
> Bazel’s default flags essentially look like this:
> ...
> `    --javabase=@bazel_tools//tools/jdk:remote_jdk11 \`
> ...

**Comment by meteorcloudy** [comment]
OK.. it broken many targets if we have openJDK 8 installed..

**Comment by meteorcloudy** [comment]
@olekw I think this will stay a patch on the Debian side until we totally give up JDK 8 on Bazel CI.

**Comment by olekw** [comment]
Ok, I'll add this to my queue for Debian changes. Thanks!

**Pull request closed without merging**
