### PR TITLE
Pass --system path to Javac when the target JDK admits it.

### PR DESCRIPTION
**Pull request by benjaminp**

### CODE REVIEW

**Comment by cushon** [comment]
Thanks!

> JDK 11 distributions at least do not contain the `release` file.

Which ones? This may be something vendor-specific that we shouldn't be relying on, but https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz appears to contain `release`

**Comment by benjaminp** [comment]
> > JDK 11 distributions at least do not contain the `release` file.
> 
> Which ones? This may be something vendor-specific that we shouldn't be relying on, but https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu11.56.19-ca-jdk11.0.15-linux_x64.tar.gz appears to contain `release`

Good question. It turns the file wasn't actually missing; it just wasn't included in the relevant JDK `BUILD` globs.

**Comment by benjaminp** [comment]
Relatedly, I noticed turbine supports `--system`, but Bazel always uses `--bootclasspath`. Is it worth matching the logic for selecting JavaBuilder flags?

**Comment by cushon** [comment]
> Relatedly, I noticed turbine supports `--system`, but Bazel always uses `--bootclasspath`. Is it worth matching the logic for selecting JavaBuilder flags?

Good question. I think it might make sense to keep using `--bootclasspath` in turbine:

* it doesn't do any of the module encapsulation checking javac does, and it doesn't need a modularized bootclasspath--it just tries to be fast and produce correct output for correct input, and relies on javac to reject incorrect input
* the implementation of `--system` relies on the Java implementation of the `jrtfs` filesystem, which at least the last time I tried, made it harder to use a GraalVM native-image with turbine

**Pull request closed without merging**
