### PR TITLE
Fix additional outputs in BEP when remote_download_minimal is used

### PR DESCRIPTION
**Pull request by exoson**
Injects optional test outputs when using --remote_download_minimal and
uses the list of injected artifacts to list them in BEP TestResult.

### CODE REVIEW

**Comment by exoson** [comment]
Will be fixing the tests later. Would appreciate comments on if a change along these lines would make sense.

**Comment by coeuvre** [comment]
Thanks for your PR!

Since this PR is mainly about test strategy and is already beyond my limited understanding of it, I will try to find an appropriate reviewer.

Out of my head, are these additional outputs already referenced in BEP for normal build / remote build?

**Comment by exoson** [comment]
@coeuvre Any updates on finding a reviewer?

**Comment by coeuvre** [comment]
I went another way (#16123) to fix this issue. It requires no changes outside remote module and allow us to remove the hack in `StandaloneTestStrategy`. That is also the way how we solve similar problems internally.

**Pull request closed without merging**
