### PR TITLE
[6.3.0] Update java_tools to v12.5

### PR DESCRIPTION
**Pull request by keertk**
Update java_tools to v12.5

Issue: https://github.com/bazelbuild/bazel/issues/18774 + https://github.com/bazelbuild/bazel/pull/18868#issuecomment-1631063300
java_tools release: https://github.com/bazelbuild/java_tools/releases/tag/java_v12.5
Original PR: https://github.com/bazelbuild/bazel/pull/18902

Note: The original commit (TBD) can not be cherry-picked due to the recent changes to the java_tools release process (these updates are in the master branch but not in the release branch). This PR updates java_tools in 6.3.0 using the old process.

cc @meteorcloudy

### CODE REVIEW

**Comment by keertk** [comment]
Do other updates need to be made to 6.3 to fix these bazel_determinism_test [failures](https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/01893e63-c8bc-48c3-b52f-023f86a2d8c9/src/test/shell/bazel/bazel_determinism_test/test_attempts/attempt_1.log), or is it safe to merge as is?

**Comment by hvadehra** [comment]
The failures look like an instance of https://github.com/google/error-prone/issues/3895

I suppose we should update our error prone version to >= 2.19.1

**Comment by iancha1992** [comment]
@cushon looks like 4 tests are still failing. Can you please take a look?

**Comment by cushon** [comment]
> @cushon looks like 4 tests are still failing. Can you please take a look?

The failing test logs contain

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.19.0
     BugPattern: (see stack trace)
     Stack Trace:
     java.lang.NoSuchMethodError: 'com.sun.tools.javac.util.List com.sun.tools.javac.code.Symbol$ClassSymbol.getEnclosedElements()'
```

I'm not sure where 2.19.0 is coming from? Does that java_tools version include db7bd58272d2b967665020b85fdad64b8676032d?

**Comment by keertk** [comment]
@cushon it doesn't. I didn't realize we'd need another java tools release for this. 
Will try to do this today.

**Comment by keertk** [comment]
Checks are finally passing after the new java_tools release (12.5). Also cherry-picked https://github.com/bazelbuild/bazel/commit/cafa3cb1f2754a92fc4085f95d1fd19324df0e38 and https://github.com/bazelbuild/bazel/commit/09188a906a8cb5237e6336f81eb5677c9d478621 to fix additional failures.

Please review, @hvadehra @cushon.

**Review by cushon — APPROVED** [review]

**Pull request merged**
