### PR TITLE
Provide `--broadcom_instrumentation_filter_fragment` cli option

### PR DESCRIPTION
**Pull request by tsiddharth**
This option is similar to `--instrumentation_filter` option. The difference is this option can be used multiple times.

If this option is provided --instrumentation_filter has no effect.

Multiple uses of `--instrumentation_filter` are not accumulated. This makes it difficult to have short hand config for a combination of coverage flags in a bazelrc file. e.g.,
```
build:covA --flagA --instrumentation_filter=afoo/abar,-afoo/abaz
build:covB --flagB --instrumentation_filter=bfoo/bbar,-bfoo/bbaz
\# Filters list need to be listed again
build:covAB --flagA --flagB --instrumentation_filter=afoo/abar,-afoo/abaz,bfoo/bbar,-bfoo/bbaz
```

`--broadcom_instrumentation_filter_fragment` option can accumulate multiple uses. Thus with this option having coverage for a combination of flags will be simple as,
```
build:covAB --config covA --config covB
```

Add tests for --broadcom_instrumentation_filter_fragment cli to verify that its multiple uses are accumulated and --instrumentation_filter has no effect when --broadcom_instrumentation_filter_fragment is used.

https://github.com/bazelbuild/bazel/issues/22959 is the upstream issue.

Testing Done:
* Specify multiple `--broadcom_instrumentation_filter_fragment`. gcno files are generated for matching labels (excluding those starting with "-").
```
$ export GOBUILD_CAYMAN_BAZEL_ROOT=/dbc/sc-dbc2163/stuli/cayman_bazel/build/component
$ vbazel run --config={esx,obj} \
--collect_code_coverage \
--//bora/esx/bazel:coverage_vmkernel \
--broadcom_instrumentation_filter_fragment=//bora/vmkernel:backdoor,//bora/vmkernel:cityhash  \
--broadcom_instrumentation_filter_fragment=//bora/vmkernel:bootConfigLineParse,-//bora/vmkernel:backdoor \
--broadcom_instrumentation_filter_fragment=//bora/vmkernel:cpuidInfo \
//bora/vmkernel
$ find -L bazel-out/ | grep gcno$
bazel-out/k8-dbg-obj-ST-666afe520531/bin/bora/vmkernel/_objs/cityhash/cityHash.pic.gcno
bazel-out/k8-dbg-obj-ST-666afe520531/bin/bora/vmkernel/_objs/cpuidInfo/cpuidInfo.pic.gcno
bazel-out/k8-dbg-obj-ST-666afe520531/bin/bora/vmkernel/_objs/bootConfigLineParse/bootConfigLineParse.pic.gcno
```
* --instrumentation_filter has not effect when --broadcom_instrumentation_filter_fragment is used. Add `--instrumentation_filter=//bora/vmkernel:lfqueue` cli to above `vbazel run` command. No additional gcno files are created.

* --instrumentation_filter works as-is.
```
$ find -L bazel-out/ | grep gcno$ | xargs rm
$ vbazel run --config={esx,obj} \
--collect_code_coverage \
--//bora/esx/bazel:coverage_vmkernel \
--instrumentation_filter=//bora/vmkernel:lfqueue \
//bora/vmkernel
$ find -L bazel-out/ | grep gcno$
bazel-out/k8-dbg-obj-ST-666afe520531/bin/bora/vmkernel/_objs/lfqueue/lfqueue.pic.gcno
bazel-out/k8-dbg-obj-ST-666afe520531/bin/bora/vmkernel/_objs/lfqueue/slfqueue.pic.gcno
```
* Apply this patch on upstream bazel.git and execute `bazel test`.
```
$ bazelisk  test src/test/java/com/google/devtools/build/lib/starlark:all
INFO: Analyzed 4 targets (0 packages loaded, 0 targets configured).
INFO: Found 1 target and 3 test targets...
INFO: Elapsed time: 242.197s, Critical Path: 216.72s
INFO: 27 processes: 1 internal, 25 darwin-sandbox, 1 worker.
INFO: Build completed successfully, 27 total actions
//src/test/java/com/google/devtools/build/lib/starlark:BindTest (cached) PASSED in 7.5s
//src/test/java/com/google/devtools/build/lib/starlark:StarlarkRuleClassFunctionsTest (cached) PASSED in 78.0s
  Stats over 5 runs: max = 78.0s, min = 59.8s, avg = 73.9s, dev = 7.1s
//src/test/java/com/google/devtools/build/lib/starlark:StarlarkTests     PASSED in 121.1s
  Stats over 25 runs: max = 121.1s, min = 24.8s, avg = 88.6s, dev = 32.1s

Executed 1 out of 3 tests: 3 tests pass.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

### CODE REVIEW

**Comment by sgowroji** [comment]
Hi @tsiddharth, Could you please sign the CLA?

**Comment by katre** [comment]
Why the name `broadcom_instrumentation_filter`? Please explain this.

I can discuss the flag parsing machinery (I do not think that `BuildConfigurationValue` is the right place for this), but let's sort out the actual flag semantics.

Looks like this is related to https://github.com/bazelbuild/bazel/issues/22959, so I am assigning to @c-mita to review further.

**Comment by c-mita** [comment]
I have a few issues:

1. The name makes no sense?
2. I think the interaction with `--instrumentation_filter` is exactly wrong. If `--instrumentation_filter` is set, I think it should override everything else.
3. I am really against adding more complexity and additional flags.

But fundamentally, I'm struggling with imagining the use case motivating this.

Further, I still have questions about how filters like `//foo` and `-//foo` interact when combined and what the correct approach should be.

**Comment by tsiddharth** [comment]
> Why the name `broadcom_instrumentation_filter`? Please explain this.

This was unintentional. I'll update the patch to use `experimental_instrumentation_filter` instead.

> I can discuss the flag parsing machinery (I do not think that `BuildConfigurationValue` is the right place for this), but let's sort out the actual flag semantics.

Sure, thanks.

> Looks like this is related to #22959, so I am assigning to @c-mita to review further.

Thanks !

**Comment by tsiddharth** [comment]
> I have a few issues:
> 
> 1. The name makes no sense?

This was not intentional. Please take a look at https://github.com/bazelbuild/bazel/pull/23623

> 2. I think the interaction with `--instrumentation_filter` is exactly wrong. If `--instrumentation_filter` is set, I think it should override everything else.
> 3. I am really against adding more complexity and additional flags.
> 
> But fundamentally, I'm struggling with imagining the use case motivating this.
> 
> Further, I still have questions about how filters like `//foo` and `-//foo` interact when combined and what the correct approach should be.

I've updated the description in https://github.com/bazelbuild/bazel/pull/23623 to reflect the use case I'm solving. Please take a look. Thanks.

**Pull request closed without merging**
