### PR TITLE
Update footer.html

### PR DESCRIPTION
**Pull request by kgdev**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by kchodorow** [comment]
IIRC, there was some reason we couldn't update the copyright date.  Damien?

**Comment by mhlopko** [comment]
I created the same cl on my first day on Bazel :) Good times :) I think it's not that we cannot, more like we don't have to. Similarly how we don't have to update the year in copyrights in our file comments.

**Comment by kchodorow** [comment]
Fair enough.

**Pull request closed without merging**
