### PR TITLE
[8.0.0-pre.20240325.5] Cherry pick commits to fix CI

### PR DESCRIPTION
**Pull request by fweikert**
https://buildkite.com/bazel/bazel-bazel/builds/27480

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Can you run `bazel mod deps` to update the lockfile?

**Comment by fweikert** [comment]
```
$ bazel mod deps --lockfile_mode=update
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/sgammon/rules_graalvm/releases/download/v0.11.1/rules_graalvm-0.11.1.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_java/releases/download/7.5.0/rules_java-7.5.0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
<root> (bazel@_)

```

**Comment by meteorcloudy** [comment]
That's just warning messages, the lockfile should haven been updated. We can mirror those two artifacts to remove the warning message.

**Comment by meteorcloudy** [comment]
I mirrored the two artifacts.

**Comment by meteorcloudy** [comment]
Maybe try https://github.com/bazelbuild/bazel/commit/0662df0506507d872e1243c243719aeba72e6a3e

**Comment by fweikert** [comment]
More problems - I don't think it's worth it, given that there has been a new Blaze release today.

**Pull request closed without merging**
