### PR TITLE
Add support for strip_prefix to {new_}git_repository skylark rules

### PR DESCRIPTION
**Pull request by edbaunton**
An approach at supporting `strip_prefix` with the `git` skylark rules.

This approach unfortunately uses symlinks since you cannot clone a subset of a git repository. It creates a `tmp` directory which is the 'real' clone and then provides a link in place of the expected location of the repository to the path of the required prefix.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by edbaunton** [comment]
I have just noticed the following paragraph in the workspace rules [documentation](https://docs.bazel.build/versions/master/be/workspace.html#git_repository):

> If you are using a private repository, prefer the Skylark git repository rules, which will use your system's git install (instead of jGit). These rules are built into Bazel and have the same API as the native rules.

This patch would cause the API of the skylark rules to be extended beyond those documented in the workspace rules. I opened this thread https://groups.google.com/forum/#!topic/bazel-discuss/E4jlTLvspp4 to discuss whether we could consider deprecating the built-in rules.

**Comment by edbaunton** [comment]
Will also add a test at https://github.com/bazelbuild/bazel/blob/master/src/test/shell/bazel/skylark_git_repository_test.sh if this approach is deemed reasonable.

**Comment by MarkusTeufelberger** [comment]
I would prefer the skylark rules to be pulled out into their own repository (e.g. "rules_scm" or "rules_sourcecode" or similar, so also svn or cvs or bazaar or mercurial rules can go in there) actually.

Imho the native rules should be deprecated and only the skylark ones supported, the java git stuff can't do some things that git can do (e.g shallow clones...) which would be very useful to have.

**Comment by edbaunton** [comment]
Closing this for now actually since the tests are not passing.

**Pull request closed without merging**
