### PR TITLE
Document best practice of avoiding extensions directly specifying repository names

### PR DESCRIPTION
**Pull request by rickeylev**
Starting with a GH pr for external feedback. I'll resend as an internal CL once approved.

### CODE REVIEW

**Review by fmeum — APPROVED** [review]
This explains the point pretty well.

Two aspects you could (but don't have to) cover:
1. Root modules may not remain root modules forever, so it may make sense to prefer toolchain resolution to explicit toolchain repo references even for them.
2. A module extension could postprocess the `name` attribute per module, so just having two tags with identical names in different modules doesn't guarantee a collision. However, distinguishing between the two would require caller-dependent macros (e.g. using `native.module_name`), which is pretty complex and best avoided (although something as complex as `rules_nixpkgs` will probably need it).

**Review by Wyverald — APPROVED** [review]
sorry, I somehow completely missed this one. LGTM!

**Comment by brentleyjones** [comment]
@bazel-io fork 7.1.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.1.0 RC1](https://releases.bazel.build/7.1.0/rc1/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
