### PR TITLE
Add implementation deps support for Objective-C

### PR DESCRIPTION
**Pull request by ivan-golub**
Implements feature https://github.com/bazelbuild/bazel/issues/17646

### CODE REVIEW

**Comment by ivan-golub** [comment]
FYI: @xiemotongye @yongjincho92

**Comment by xiemotongye** [comment]
It seems that rules_xcodeproj has fixed the bugs.
May I make so bold as to ask when this pull request would be merged?
I can't wait to use this.

**Comment by BalestraPatrick** [comment]
We also would like to use this. Maybe we can turn this PR into "Ready for review" and get someone from the Bazel team to give it a look?

**Comment by xiemotongye** [comment]
@keith 
Could you review this PR?

**Review by keith — APPROVED** [review]

**Review by gregestren — APPROVED** [review]

**Comment by sgowroji** [comment]
Hi @ivan-golub, Could you please address the build-kite failures so that the PR above can be merged. Thanks!

**Comment by ivan-golub** [comment]
@sgowroji sorry for that, my last documentation commit had issues, not all should be good. @gregestren @sgowroji PTAL again

**Comment by gregestren** [comment]
@sgowroji does your import have the latest commits that the last comment mentions?

**Comment by sgowroji** [comment]
Hi @gregestren, I have reimported it after that last and recent commit and shared it with you. Thanks!

**Comment by brentleyjones** [comment]
We should get this into 6.x

**Comment by brentleyjones** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 6.2.0

**Comment by keertk** [comment]
Hi @brentleyjones @gregestren @ivan-golub if we want this in 6.2, could you submit a PR against the `release-6.2.0` branch please? There are some conflicts and looks like additional commits may need to be cherry-picked first.

**Comment by keertk** [comment]
Since we're quite far along the 6.2 release process, we're moving this one to 6.3.

**Comment by ivan-golub** [comment]
Sounds good. Will work on cherry-pick to 6.3

**Comment by ivan-golub** [comment]
@keertk looks like release-6.3.0 is not yet available. What would be the best target branch to choose for cherry-pick of this change?

**Comment by keertk** [comment]
Hey @ivan-golub the 6.3 branch isn't ready yet. We'll create it once 6.2 is out in a few days. I'll keep you posted.

**Comment by keertk** [comment]
The `release-6.3.0` branch is now ready and open for PR submissions.

**Pull request closed without merging**
