### PR TITLE
Update `@rules_java` v7.6.1

### PR DESCRIPTION
**Pull request by hvadehra**

### CODE REVIEW

**Comment by hvadehra** [comment]
@Wyverald looks like this needs updating the lockfile on all platforms?

**Comment by hvadehra** [comment]
@bazel-io fork 7.2.0

**Comment by Wyverald** [comment]
Unfortunately yes. If this PR is otherwise ready, I can start importing and fix the lockfiles on my side.

**Comment by hvadehra** [comment]
> Unfortunately yes. If this PR is otherwise ready, I can start importing and fix the lockfiles on my side.

Yes this is good to import , thanks!

**Review by Wyverald — APPROVED** [review]

**Pull request closed without merging**
