### PR TITLE
Add supplemental support for JDK 11, 17 and 19 on cpu s390x

### LINKED ISSUE #17381: Add support for JDK 18 on cpu s390x
### Description of the bug:

The recent releases of Bazel have already supported JDK 11 and 17 on cpu s390x. Please consider to add support for JDK 18 on cpu s390x as well.

Thanks!

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

_No response_

### Which operating system are you running Bazel on?

Ubuntu Linux 18.04+

### What is the output of `bazel info release`?

release 6.0.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

https://github.com/bazelbuild/bazel.git
0cc6bcdd1aed4dc3c5b8e5ed698b0cecc5a7c548
06deebfb5b73f848de5a0ea0e00fcfaa26788d1f

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by kun-lu20**
Recent releases of Bazel have already supported JDK 11 and 17 on cpu s390x. This PR aims to add support for JDK 18 and supplement the support for JDK 11 and 17 on cpu s390x.

The code changes have been verified on s390x and won't cause any regressions on other archs.

Fixes #17381 .

commit https://github.com/bazelbuild/bazel/commit/19b2e2f448bdd50c42d53c3b3d1c45a95eaadd44 has replaced JDK 18 with JDK 19, so this PR was updated as well to add support for JDK 19 on s390x.

Signed-off-by: Kun-Lu <kun.lu@ibm.com>

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @kshyanashree ,

I think the test failures in PR checks (such as the `presubmit` check) are not related to this PR. Could you please change `awaiting-user-response` tag to `awaiting-review`?

Thanks!

**Comment by kshyanashree** [comment]
> Hi @kshyanashree ,
> 
> I think the test failures in PR `presubmit` checks are not related to this PR. Could you please change `awaiting-user-response` tag to `awaiting-review`?
> 
> Thanks!

sure, Done!

**Comment by kshyanashree** [comment]
> > Hi @kshyanashree ,
> > I think the test failures in PR `presubmit` checks are not related to this PR. Could you please change `awaiting-user-response` tag to `awaiting-review`?
> > Thanks!
> 
> Sure, done!

**Comment by kun-lu20** [comment]
Hi @kshyanashree ,

Could you please help to assign someone to review this PR?

Thank you very much!

**Comment by hvadehra** [comment]
Hi @kun-lu20 , this looks fine to me, but we currently don't have any way to test such changes. 

In the earlier change that added the embedded jdk11 for s390x, it [was mentioned that it may be possible to have access to a VM](https://github.com/bazelbuild/bazel/pull/11965#issuecomment-696728143) for testing. Is this still a possibility?

**Comment by kun-lu20** [comment]
Hi @hvadehra ,

Thanks for reviewing this PR!

Yes, for sure we can provide s390x VMs for testing. Let me check the latest process for requesting VMs and I'll get back to you later.

**Comment by kun-lu20** [comment]
Hi @hvadehra ,

Please use the following form to request s390x VMs for testing: https://www.ibm.com/community/z/open-source/virtual-machines-request/ . Feel free to let me know if you run into any problems. 

Thank you very much!

**Comment by kun-lu20** [comment]
Hi @hvadehra ,

Recent commits on this PR solves the conflicts from master branch and replaces the support for JDK 18 with JDK 19 on s390x as per the change introduced by commit https://github.com/bazelbuild/bazel/commit/19b2e2f448bdd50c42d53c3b3d1c45a95eaadd44. Please take a look when you have a chance.

Although some PR checks failed because the `OpenJDK19U-jdk_s390x_linux_hotspot_19.0.2_7.tar.gz` couldn't be downloaded, the downloading worked fine on our local s390x VMs and the build completed successfully.

Also please feel free to let me know if there is anything I can help with the s390x VMs request.

Thank you very much!

**Comment by hvadehra** [comment]
Hi, I've gotten the account and created an instance. I will spend some time today setting it up and testing this PR.

**Review by hvadehra — APPROVED** [review]

**Comment by kun-lu20** [comment]
Hi @comius ,

Yes sure, I'll raise a PR in [bazelbuild/rules_java](https://github.com/bazelbuild/rules_java) to update it.

Thanks!

**Pull request closed without merging**
