### PR TITLE
third_party condition for ppc64le dyn lib

### PR DESCRIPTION
**Pull request by clnperez**
Pick up the `third_party` portion of PR #9346

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by clnperez** [comment]
@jin @gregestren  PTAL

**Comment by gregestren** [comment]
I don't think I have permissions to fully import this. I've reached out to @buchgr , who I believe can help with this.

**Comment by jin** [comment]
@gregestren I can do it.

**Comment by jin** [comment]
Done: https://github.com/bazelbuild/bazel/commit/27612bb1f6131cd86b42306c80037946b686c9c7

**Comment by clnperez** [comment]
thanks!

**Pull request closed without merging**
