### PR TITLE
Update third_party/protobuf to 3.6.0

### PR DESCRIPTION
**Pull request by rongjiecomputer**
Notable changes:

- Update `src/test/java/com/google/devtools/build/lib/rules/cpp/BUILD` to not hard-code version number.
- Update version number in `src/main/protobuf/BUILD` and `src/test/shell/testenv.sh`.
- Use `proto_library` rules for well known types provided by Protobuf https://github.com/google/protobuf/pull/3594.
- Fix `_path_ignoring_repository` in `third_party/grpc/build_defs.bzl` to work with generated proto files.
- More reminders in `third_party/protobuf/README.md`.

/cc @buchgr #5351

### CODE REVIEW

**Comment by rongjiecomputer** [comment]
@buchgr 

`//src/test/shell/bazel:srcs_test` test failure is definitely caused by this PR ([See test log][0]).  It is complaining that `third_party/protobuf/3.6.0/examples` is not included in `srcs` filegroup. I just copied the `filegroup` declaration from old proto to the new one and change `"//third_party/protobuf/3.4.0/util/python:srcs"` to `"//third_party/protobuf/3.6.0/util/python:srcs"`. Not sure why it works for 3.4.0 but not 3.6.0.

```
filegroup(
    name = "srcs",
    srcs = glob(
        [
            "**",
            "protobuf.bzl",
            "python/google/protobuf/**/*.py",
            "src/google/protobuf/**/*.proto",
        ],
    ) + [
        "//third_party/protobuf/3.6.0/util/python:srcs",
    ],
    visibility = ["//visibility:public"],
)
```

Any idea?

`//src/test/shell/integration:bazel_command_log_test` also fails, but I don't think it is related to protobuf.

[0]: https://source.cloud.google.com/results/invocations/fdf2f5e8-0eca-4ba7-b998-91f790a24872/targets/%2F%2Fsrc%2Ftest%2Fshell%2Fbazel:srcs_test/log

**Comment by buchgr** [comment]
@rongjiecomputer in protobuf 3.6, the examples directory is its own package (it contains a BUILD file). That was not so in 3.4. So you will need to a srcs filegroup to examples/BUILD and then add that filegroup to the above filegroup.

**Comment by rongjiecomputer** [comment]
@buchgr Thanks for the tips! Added `filegroup` and `licenses` for the package and rebase. I can't test it locally because the test does not work on Windows. Please trigger CI build again.

**Comment by rongjiecomputer** [comment]
@buchgr `//src/test/shell/bazel:srcs_test` no longer failed, hooray!

However, `test_batch_mode` and `test_batch_mode_with_logging_flag` in `//src/test/shell/integration:bazel_command_log_test` still failed (see [log](https://source.cloud.google.com/results/invocations/3b371026-b01b-4108-b493-82102fc2e8b2/targets/%2F%2Fsrc%2Ftest%2Fshell%2Fintegration:bazel_command_log_test/tests)). In the same test, `test_client_server_mode` and `test_client_server_mode_with_logging_flag` subtests passed.

It might be related to #5442 (also about `--batch`). What worries me is the JVM warning in `com.google.protobuf.UnsafeUtil`. I am not seeing this warning in my local build when running with `--batch`, probably because I am still using JDK8 instead of JDK9.
```
-- Test log: -----------------------------------------------------------
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/install/9e99da4240f2bae5b4b171fa2158d02f/_embedded_binaries/A-server.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
bazel-bin: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/execroot/main/bazel-out/k8-fastbuild/bin
bazel-genfiles: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/execroot/main/bazel-out/k8-fastbuild/genfiles
bazel-testlogs: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/execroot/main/bazel-out/k8-fastbuild/testlogs
character-encoding: file.encoding = ISO-8859-1, defaultCharset = ISO-8859-1
command_log: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/command.log
committed-heap-size: 1983MB
execution_root: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/execroot/main
gc-count: 2
gc-time: 86ms
install_base: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/install/9e99da4240f2bae5b4b171fa2158d02f
java-home: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/install/9e99da4240f2bae5b4b171fa2158d02f/_embedded_binaries/embedded_tools/jdk
java-runtime: OpenJDK Runtime Environment (build 9.0.7.1+1) by Azul Systems, Inc.
java-vm: OpenJDK 64-Bit Server VM (build 9.0.7.1+1, mixed mode) by Azul Systems, Inc.
max-heap-size: 31687MB
output_base: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059
output_path: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/30b706702cc08e1213b248db618b0059/execroot/main/bazel-out
package_path: %workspace%
release: development version
repository_cache: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/root/cache/repos/v1server_pid: 552
used-heap-size: 27MB
workspace: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/9dd292985c15213116adfbd4ceb1867f/sandbox/linux-sandbox/1768/execroot/io_bazel/_tmp/bf89598a54a896b6604732eca0b954fe/workspace
------------------------------------------------------------------------
FAILED: terminated because this command returned a non-zero status:
```

**Comment by buchgr** [comment]
@rongjiecomputer I think these tests were fixed in the meantime. Can you please rebase your change on Bazel master and retrigger CI?

**Comment by rongjiecomputer** [comment]
@buchgr Rebased on Bazel master. Please retrigger CI.

**Comment by buchgr** [comment]
Hmm. The test should always use the embedded JDK9 and it should have been fixed recently: https://github.com/bazelbuild/bazel/issues/5314

I am quite busy atm and don't have time to take a detailed look right now :(.

**Comment by rongjiecomputer** [comment]
@buchgr I think https://github.com/bazelbuild/bazel/pull/5439/commits/b30cc7b2d6614a84c7c24dd404e002ded3ac06f3 should fix the failures. Can you trigger CI test again?

**Comment by buchgr** [comment]
Awesome everything passes!

**Comment by rongjiecomputer** [comment]
Is this still being reviewed internally?

**Comment by buchgr** [comment]
triggered CI one more time to ensure it works with latest sync. will then import

**Comment by rongjiecomputer** [comment]
Nevermind. CLA test suddenly just passed on its own. Weird.

**Comment by buchgr** [comment]
I ll import it again tomorrow morning. Unfortunately we'll have to break the build for a ~15 minutes when importing it and so I want to do it when the least amount of devs are effected.

**Comment by buchgr** [comment]
Imported as `0399f38a163c76a7c3fe9c5be25dbd89fd4717cb` thanks @rongjiecomputer

**Pull request closed without merging**
