### PR TITLE
Fallback to download with HttpDownloader if assets not found in remote cache

### LINKED ISSUE #12417: Remote Downloader: No retry after receiving a CacheNotFoundException
### Description of the problem / feature request:

Using `--experimental_remote_downloader` with a https://github.com/buchgr/bazel-remote remote cache, the build failed with the following error, upon encountering a CacheNotFoundException.

I expected Bazel to fallback to fetching the artifact in the event of a cache miss.

```
INFO: Repository build_bazel_rules_nodejs instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/gitlab/.cache/bazel/_bazel_gitlab/856f582f3053cc7df99ab29b906d93f4/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'build_bazel_rules_nodejs':
   com.google.devtools.build.lib.remote.common.CacheNotFoundException: Missing digest: 0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3/1000820
ERROR: no such package '@build_bazel_rules_nodejs//': com.google.devtools.build.lib.remote.common.CacheNotFoundException: Missing digest: 0f2de53628e848c1691e5729b515022f5a77369c76a09fbe55611e12731c90e3/1000820
INFO: Elapsed time: 35.390s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Job failed: command terminated with exit code 1
```

### Feature requests: what underlying problem are you trying to solve with this feature?

More reliable builds.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Unsure.

### What operating system are you running Bazel on?

Linux Ubuntu 18.04

### What's the output of `bazel info release`?

release 3.4.1

### If `bazel info release` returns "development version" or "(@non-git)", tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin ; git rev-parse master ; git rev-parse HEAD` ?

N/A

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

Here are all the remote-related configs:
```
common:ci-remote-cache --remote_cache=grpc://bazel-remote-cache.bazel-remote-cache.svc.cluster.local:9092
common:ci-remote-cache --experimental_remote_downloader=grpc://bazel-remote-cache.bazel-remote-cache.svc.cluster.local:9092
common:ci-remote-cache --remote_local_fallback
common:ci-remote-cache --remote_max_connections=50
common:ci-remote-cache --remote_retries=1
common:ci-remote-cache --remote_timeout=60
common:ci-remote-cache --experimental_guard_against_concurrent_changes
```

### LINKED ISSUE #16264: Remote Downloader: Does not honor --remote_local_fallback
### Description of the bug:

We have `--experimental_remote_downloader` flag enabled with bazel-remote cache, however it does not honor `--remote_local_fallback`. When the remote cache shuts down unexpected,  the following error is observed:

```
INFO: Repository io_bazel_rules_go instantiated at:
  /home/circleci/figma/WORKSPACE.bazel:278:13: in <toplevel>
Repository rule http_archive defined at:
  /home/circleci/.cache/bazel/_bazel_circleci/a6e8cb0ce75ceb1ea1faa0cca0b0ae0d/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_go':
   Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/a6e8cb0ce75ceb1ea1faa0cca0b0ae0d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
ERROR: /home/circleci/figma/WORKSPACE.bazel:278:13: fetching http_archive rule //external:io_bazel_rules_go: Traceback (most recent call last):
	File "/home/circleci/.cache/bazel/_bazel_circleci/a6e8cb0ce75ceb1ea1faa0cca0b0ae0d/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
ERROR: no such package '@io_bazel_rules_go//go': io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
INFO: Elapsed time: 13.460s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
FAILED: Build did NOT complete successfully (0 packages loaded)
```

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

1. start bazel-remote with `--experimental_remote_asset_api` enabled
2. build a target with `--experimental_remote_downloader` and  `--remote_local_fallback` enabled (can use a build target that uses rules_go, but any repo should work)
3. as soon as you begin to observe remote downloads in bazel-remote logs, send a SIGTERM to the bazel-remote process
4. build will fail with above error

### Which operating system are you running Bazel on?

Linux / Macos

### What is the output of `bazel info release`?

release 5.2.0

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

N/A

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

N/A

### Have you found anything relevant by searching the web?

Similar issue as https://github.com/bazelbuild/bazel/issues/12417#issuecomment-741639582
Relevant PR discussion: https://github.com/bazelbuild/bazel/pull/12528

### Any other information, logs, or outputs that you want to share?

Agree with [this comment](https://github.com/bazelbuild/bazel/pull/12528#issuecomment-732392535), would love to see the option of fall back to local download as a configurable option, regardless of what the default is. Using a separate flag for this (like `--experimental_remote_downloader_http_fallback`) is reasonable too if the concern is around overloading the existing `--remote_local_fallback` feature.

### PR DESCRIPTION
**Pull request by coeuvre**
Fixes #12417.

Fixes #16264.

### CODE REVIEW

**Comment by philwo** [comment]
If I understand correctly, the design doc of this feature says as one reason for why people use it: „Some organizations would like to enforce policies on use of third-party code, and a build tool that directly downloads external dependencies will bypass technical controls that implement these policies.“ (https://github.com/bazelbuild/proposals/blob/master/designs/2020-01-14-remote-downloads.md)

By falling back to downloading via HTTP we would circumvent that. So maybe we should make this configurable? Maybe by turning the downloaders into a list of strategies, people who want both could use „grpc,http“ and people who want to enforce grpc-only would remove http from it? 🤔

OTOH I can also see the use case where people use this just as an additional cache - in which case maybe even printing a warning on cache miss is too much noise as it would happen frequently.

WDYT? (Also @jmillikin-stripe)

**Comment by coeuvre** [comment]
Sorry for missing the design doc.

Making this configurable sounds reasonable. How about using flag `--experimental_remote_downloader_http_fallback`? (like we had `--remote_local_fallback` for falling back to local execution)

**Comment by jmillikin-stripe** [comment]
The linked issue indicates a bug in the remote downloader _server_, not in Bazel. The server responded that it had successfully resolved the download request and had put the content into the remote cache, but then when Bazel went and tried to fetch it, the cache said that key wasn't found.

This is roughly the same behavior as what you'd get if a remote executor said it had finished an action, but didn't write the action results into the cache. Bazel doesn't automatically fall back to local execution in that case, and similarly, the download code shouldn't fall back to the local HTTP downloader with ambient authority.

More generally, I think a fallback doesn't make sense because the purpose of the remote downloader is to fully override Bazel's access to external resources. It's not just an optional lookup into the remote cache, it's a proxy that has a role in the security of a build. As one example, if a company wants to forbid downloading assets without a checksum, this fallback would bypass the remote downloader that enforces the policy.

**Comment by coeuvre** [comment]
I am agree with you that automatically fall back to http downloader without asking explicitly is not good. But I can optionally enable this could benefit other user cases e.g providing cache for the CI workers.

If this fallback is only enabled by a flag, I don't think this introduces a security issue since users can always disable remote downloader and use HTTP downloader instead if they have access to Bazel command line options.

**Comment by jmillikin-stripe** [comment]
> I am agree with you that automatically fall back to http downloader without asking explicitly is not good. But I think optionally enable this could benefit other user cases e.g providing cache for the CI workers.

The current code in Bazel works fine for caching between CI workers -- we've been using it in that mode for several months.

I strongly recommend that you file a bug against the download server you're using, because it sounds like that server is returning incorrect responses. I do not think it's a good idea for Bazel to try working around buggy implementations of the remote APIs.

**Comment by mostynb** [comment]
IMO it would feel more consistent with the other cache operations if this were to fall back to downloading locally. But as long as this is made configurable, I don't think it matters too much what the default is.

**Pull request closed without merging**
