### PR TITLE
Use toolchain env for strip action

### LINKED ISSUE #14270: C++: strip action ignores environment passed through toolchain features
### Description of the problem / feature request:

When passing custom environment variables to compile actions using `env_sets` parameter of a `feature`, stripping action ignores it.

I found this while using [bazel_rules_cc_toolchain](https://github.com/silvergasp/bazel_rules_cc_toolchain), which passes path to the compiler into the wrapper script using  environment variables. While most of the compilation works ok, it seems to fail with stripping step, because bazel does not pass the expected variable `STRIP_TOOL_PATH`, which is set by a feature.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

```bash
git clone -b strip https://gitlab.com/DCNick3/bazel_rules_cc_toolchain_repro.git
bazel build '//main:hello-world.stripped'
```

### What operating system are you running Bazel on?

GNU/Linux

### What's the output of `bazel info release`?

`release 4.2.1`

###  Have you found anything relevant by searching the web?

Nope

### Any other information, logs, or outputs that you want to share?

I took a glance at the source code surrounding the potential problem and found a suspicious difference between the stripping and usual compilation: while `CppCompileActions` gets the provided environment from `featureConfiguration` (through [compileCommandLine.getEnvironment()](https://github.com/bazelbuild/bazel/blob/f5196e2ce4e8e45ca49c271053dad8dd32be5080/src/main/java/com/google/devtools/build/lib/rules/cpp/CppCompileAction.java#L817)), I can't see it being called by code creating the strip action, and it has even more suspicious call to [useDefaultShellEnvironment](https://github.com/bazelbuild/bazel/blob/33f7648fbaa875f73416be47f0b3c10ed93f30d6/src/main/java/com/google/devtools/build/lib/rules/cpp/CppHelper.java#L676).

It also seems that other actions in the `CppHelper` class may be affected.

While I am completely unsure if this analysis is 100% correct, I hope it helps to find the underlying issue and fix it.

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #14270

### CODE REVIEW

**Comment by fmeum** [comment]
@pzembrod The best way to test this would be a starlark analysis test, but those aren't open-source yet. Could you maybe add one to the internal test suite?

**Comment by pzembrod** [comment]
> @pzembrod The best way to test this would be a starlark analysis test, but those aren't open-source yet. Could you maybe add one to the internal test suite?

Sorry, took me a while to get to this. Will check tomorrow how that could go.

**Comment by fmeum** [comment]
@pzembrod The library for writing tests (rules_testing) is open-source, but the tests themselves are not. I don't think that there is any Starlark analysis test in Bazel outside the special builtins tests for `cc_shared_library`.

**Comment by pzembrod** [comment]
As discussed on Slack, let's merge this now, and I'll open a tracking bug for me so we can see next quarter how to best test this.

**Review by pzembrod — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io fork 7.3.0

**Pull request closed without merging**
