### PR TITLE
Update Java 17 to zulu17.32.13

### PR DESCRIPTION
**Pull request by davido**
This also harmonizes the JDK versions used for testing and releases.

Change-Id: I571019afe74edc46b24f61184993a2e1f013e668

### CODE REVIEW

**Comment by davido** [comment]
//CC @comius @meteorcloudy 

Can we please add new JDK artifacts to Bazel mirror? Thanks.

**Comment by cushon** [comment]
I think I missed that those JDK references in `WORKSPACE` weren't covered by https://github.com/bazelbuild/bazel/commit/b74111671713f132869b94cf3686cc427c67663a, it would be nice if everything could be consolidated in `distdir_deps.bzl`

**Comment by davido** [comment]
> I think I missed that those JDK references in WORKSPACE weren't covered by b741116, it would be nice if everything could be consolidated in distdir_deps.bzl

Indeed. That way the versions wouldn't diverge in different locations.

**Comment by meteorcloudy** [comment]
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-linux_x64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-macosx_x64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-macosx_aarch64.tar.gz
https://mirror.bazel.build/cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-win_x64.zip
are now available.

**Review by comius — APPROVED** [review]

**Review by comius — CHANGES_REQUESTED** [review]
Can you add Bazel mirrors as well?

**Comment by comius** [comment]
>>I think I missed that those JDK references in WORKSPACE weren't covered by b741116, it would be nice if everything could be consolidated in distdir_deps.bzl

>Indeed. That way the versions wouldn't diverge in different locations.

I agree. There is no reason to do so. I just missed those JDKs.

**Comment by davido** [comment]
> Can you add Bazel mirrors as well?

Done.

**Review by comius — APPROVED** [review]

**Pull request closed without merging**
