### PR TITLE
Add src/main/native/windows files required by ijar on Windows in the Java tools archive

### PR DESCRIPTION
**Pull request by iirina**
Progress on #6316.

### CODE REVIEW

**Comment by lfpino** [comment]
Maybe @laszlocsomor should also review this?

**Comment by laszlocsomor** [comment]
How does ijar depend on these files?

**Comment by iirina** [comment]
@laszlocsomor That's a great question:) As a note: the dependency graph for ijar on windows is different than the other platforms. Here is the path for windows:

```
//third_party/ijar:ijar ->
//third_party/ijar:zip ->
//src/main/cpp/util:filesystem ->
//src/main/native/windows:lib-file 
```

**Comment by laszlocsomor** [comment]
Consider adding a filegroup to each package on that dependency path, to hold the required source, so `//third_party/ijar:ijar` wouldn't know (or care) that `//src/main/cpp/util:filesystem` depends on `//src/main/native/windows:lib-file`.

**Comment by laszlocsomor** [comment]
Clarification for the record: I meant adding pkg_tar rules, but adding them so the pkg_tar in `//third_party/ijar` depends on the pkg_tar in `//src/main/cpp/util` (because `//third_party/ijar:zip` depends directly on `//src/main/cpp/util:filesystem` and should not care about the transitive dependency on `//src/main/native/windows:lib-file`), and the pkg_tar in `//src/main/cpp/util` depends on the pkg_tar in `//src/main/native/windows` (because `//src/main/cpp/util:filesystem` depends on `//src/main/native/windows:lib-file`).

This way the pkg_tar rulers would mirror the direct-dependency relations between the cc_libraries, not the transitive ones, yielding less coupling between the rules. (E.g. `//src/main/cpp/util:filesystem` may be changed more easily in the future not to depend on `//src/main/native/windows:lib-file`.)

**Comment by iirina** [comment]
Thanks for the clarifications and for your input! One of the problems I was facing with the approach you suggested was that I couldn't preserve the directory structure. Every `pkg_tar` places the content of `pkg_tar` dependencies under its own package directory. For example instead of having

```
src/main/native/windows
src/main/cpp/util
```

I ended up having

```
src/main/cpp/util/src/main/native/windows
```

I fixed this by adding intermediate `pkg_tar` targets with no sources and no `package_dir` specified with the sole purpose of merging the content of two other `pkg_tar`.

**Comment by iirina** [comment]
`third_party` changes not merged yet

**Comment by iirina** [comment]
`third_party/BUILD` changes merged in 0b1ad3d30d46348c82108bc7f9638b494261dcb0

**Pull request closed without merging**
