### PR TITLE
update google-auth library. Fixes #7259

### LINKED ISSUE #7259: remote: update grpc and google auth library to latest

### PR DESCRIPTION
**Pull request by buchgr**

### CODE REVIEW

**Comment by laszlocsomor** [comment]
Please add "Fixes: http://github.com/bazelbuild/bazel/issues/7259" to the PR description.
I'll wait until CI is complete before reviewing.

**Comment by buchgr** [comment]
@laszlocsomor it's in the title.

**Comment by laszlocsomor** [comment]
Yes I know. :)
Is that enough for GitHub to close the bug when the PR is merged?

**Comment by buchgr** [comment]
@laszlocsomor yes. github first and foremost cares about what's in the commit message. title and description is just fancy ui stuff :)

**Comment by buchgr** [comment]
Merged

**Pull request closed without merging**
