### PR TITLE
Prevent git filegroup from choking on gitk temporary files.

### PR DESCRIPTION
**Pull request by abergmeier**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by ulfjack** [comment]
I'm not sure why we have a git filegroup in the first place, but it seems reasonable to exclude [ files.

**Comment by damienmg** [comment]
Jenkins: test this please

**Comment by abergmeier** [comment]
> I'm not sure why we have a git filegroup in the first place, but it seems reasonable to exclude [ files.

Well you know - the more reasonable thing would be to support characters like `[` in target paths - but I will not touch that can of worms ;)

**Comment by ulfjack** [comment]
@abergmeier I have a change for that - I just need to get it to work. :-P

**Comment by ulfjack** [comment]
@damienmg I'm not sure what you're seeing from these results.

**Comment by damienmg** [comment]
There is a failure to report the result to GitHub (first time I see that). let's retry: Jenkins retest this please.

**Comment by damienmg** [comment]
And now something killed all the darwin slaves so the job is pending artifact retrieval. however everything from bazel succeeded so it should be good to merge.

**Pull request closed without merging**
