### PR TITLE
BazelTestRunner: exit with 137 on OOMs

### PR DESCRIPTION
**Pull request by saraadams**
Motivation: Make it easier to detect whether a test failed due to an OutOfMemoryException

Current behavior:
The test runner exited with a code 1 on any test failure. This can make it hard to programmatically differentiate whether a test failed due to an actual test failure, or because the test was aborted due to an OutOfMemoryException.

Proposed change:
If a run of a test suite fails, the failures are checked for any OOMs. If at least one failure was caused by an OOM, the program exits with a code 137, rather than 1. Additionally, this is also the exit code if the test runner itself OOMs.

This distinction can help with automatically detecting OOMs and then retrying the execution with more memory available, and is especially helpful in the context of remote execution, where the action may be retried on a larger executor.

### CODE REVIEW

**Comment by hvadehra** [comment]
This seems reasonable to me. Any chance we could add a test for this?

**Comment by saraadams** [comment]
> This seems reasonable to me. Any chance we could add a test for this?

I had looked, but didn't see where I could easily add a test. Do you have guidance on where/how I could add a test for this?

**Comment by saraadams** [comment]
Added a test - is that the right way to do it?

**Comment by hvadehra** [comment]
Thanks for adding the tests. Could you maybe separate out the new test into a different class? It would be preferable to not modify existing tests so we can be sure we're not inadvertently affecting something else.

**Comment by saraadams** [comment]
> Thanks for adding the tests. Could you maybe separate out the new test into a different class? It would be preferable to not modify existing tests so we can be sure we're not inadvertently affecting something else.

Just so I head in the right direction:

1. Do you want me to add a separate Java test class for the OOM test case? If I keep the current change and reverted the changes to `junit4_testbridge_integration_tests.sh` that should still pass.
2. Do you want me to add a separate test case in the existing `src/java_tools/junitrunner/javatests/com/google/testing/junit/runner/junit4_testbridge_integration_tests.sh` or do you want me to add a separate `.sh`? It looks to me like adding a separate test function would be sufficient.

**Comment by hvadehra** [comment]
A separate java test class and new test case in the same sh file SG.

**Comment by saraadams** [comment]
> A separate java test class and new test case in the same sh file SG.

PTAL.

**Comment by hvadehra** [comment]
Thanks!

**Review by hvadehra — APPROVED** [review]

**Comment by saraadams** [comment]
May I also ask how the release of this would work? If I understand correctly, this code is not included in the Bazel releases, but rather in the `java_tools` releases: https://github.com/bazelbuild/java_tools

Is there a particular release schedule? (I didn't find one, but may have not looked in the right place.)

**Comment by hvadehra** [comment]
Yes, this will need a java_tools release, and then a release of rules_java with that. Once this is submitted, you can request a new release at https://github.com/bazelbuild/rules_java/issues/new/choose

(sorry about the delay, we ran into some challenges with the import, and now people are away for Thanksgiving)

**Comment by saraadams** [comment]
> Yes, this will need a java_tools release, and then a release of rules_java with that. Once this is submitted, you can request a new release at https://github.com/bazelbuild/rules_java/issues/new/choose
> 
> (sorry about the delay, we ran into some challenges with the import, and now people are away for Thanksgiving)

Thanks - so I should request a new release via https://github.com/bazelbuild/rules_java/issues/new/choose when this PR has been closed? Will that trigger both a `java_tools` release and a `rules_java` release (if I add that to the release request, referencing this PR)?

**Comment by hvadehra** [comment]
> so I should request a new release via https://github.com/bazelbuild/rules_java/issues/new/choose when this PR has been closed?

Yes, just make sure to reference this PR and mention we also want a java_tools update.

> Will that trigger both a java_tools release and a rules_java release

I'm afraid it's not _that_ automated just yet. Someone will make the release(s).

**Pull request closed without merging**
