### PR TITLE
add more support for Arm

### PR DESCRIPTION
**Pull request by lubinszARM**
Signed-off-by: Bin Lu <bin.lu@arm.com>

### CODE REVIEW

**Comment by mhlopko** [comment]
Is this PR obsoleted by https://github.com/bazelbuild/bazel/pull/5457?

**Comment by mhlopko** [comment]
Please comment if it's not, I'll close this issue now, but will gladly reopen if I'm wrong. Thanks!

**Comment by lubinszARM** [comment]
Hi @mhlopko 
The modification is different with #5457 
Please check the changed file between them.
Thanks.

**Comment by mhlopko** [comment]
I see, thanks! Importing.

**Pull request closed without merging**
