### PR TITLE
sandbox: Allow UNIX sockets on macOS even when block-network is used.

### PR DESCRIPTION
**Pull request by philwo**

### CODE REVIEW

**Comment by ittaiz** [comment]
Amazing!!! The test passes, thanks :)
There isn't a real chance this will be cherry picked right?
Asking in hope (but without real anticipation).
This is a blocker for us but we'll be willing to use the commit it goes in until 0.6.0

**Comment by ittaiz** [comment]
Scratch that. Take the time for the API you think is appropriate. Didn't
mean to stress it.

**Comment by philwo** [comment]
@ulfjack On macOS we don't have network virtualization, so "block-network" on that platform is used to block access to external networks in order to not accidentally depend on non-hermetic resources. We do allow networking with non-virtualized localhost though.

I'd argue that just allowing UNIX sockets fits into the current philosophy and that we don't need a special flag for this. What do you think?

**Comment by philwo** [comment]
Thanks! Importing and sending for internal review now.

**Comment by philwo** [comment]
Fix merged internally.

**Comment by ittaiz** [comment]
Yay! Thanks.
So if it went that smoothly then any chance this will be cherry picked?

**Comment by philwo** [comment]
I'll kindly ask @buchgr, but I don't know in what state we currently are with the 0.5.3 release :)

**Comment by philwo** [comment]
@ittaiz This was cherry-picked and will be part of the next Bazel 0.5.3 release candidate.

**Comment by buchgr** [comment]
Just triggered the creation of the next release candidate with this change :)

**Comment by ittaiz** [comment]
Thanks!

**Pull request closed without merging**
