### PR TITLE
Release 0.5.0

### PR DESCRIPTION
**Pull request by jayanti-prasad**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by iirina** [comment]
Hi @jayanti-prasad, I don't really understand what's the purpose of this PR, can you explain? For releases we have a separate process and is done by a release manager (you can follow the progress [here](https://github.com/bazelbuild/bazel/issues/2692)).

**Comment by jayanti-prasad** [comment]
my apologies .. that was by  a mistake.

regards
jayanti

**Comment by iirina** [comment]
No worries

**Pull request closed without merging**
