### PR TITLE
Enable query sync by default in IntelliJ

### PR DESCRIPTION
**Pull request by tpasternak**
Description of the query sync: https://github.com/bazelbuild/intellij/blob/master/docs/querysync.md

### CODE REVIEW

**Comment by tpasternak** [comment]
cc @mai93

**Review by meteorcloudy — APPROVED** [review]

**Comment by tpasternak** [comment]
Please hold on with the merge until the current beta version of the intellij plugin becomes stable. It fixes some annoying stuff with query sync

**Comment by tpasternak** [comment]
@iancha1992 it's mostly about some annoyances, but I'd recommend to help. In the meantime - may I ask you to try it and decide if this is indeed a good change? Query Sync completely changes the behavior of IntelliJ, so it might look weird initially, but on the other hand it outperforms the legacy mode by orders of magnitude

**Comment by iancha1992** [comment]
> @iancha1992 it's mostly about some annoyances, but I'd recommend to help. In the meantime - may I ask you to try it and decide if this is indeed a good change? Query Sync completely changes the behavior of IntelliJ, so it might look weird initially, but on the other hand it outperforms the legacy mode by orders of magnitude

cc: @mai93

**Comment by tpasternak** [comment]
well, let's close it, users can switch if they need

**Pull request closed without merging**
