### PR TITLE
Cherrypicks for experimental cc_shared_library

### PR DESCRIPTION
**Pull request by oquenchil**
Includes various bug fixes and improvements to experimental_cc_shared_library. Copied from:
PiperOrigin-RevId: 410579009
PiperOrigin-RevId: 412008374
PiperOrigin-RevId: 425857199
PiperOrigin-RevId: 408879871
PiperOrigin-RevId: 409139665
PiperOrigin-RevId: 410579009
PiperOrigin-RevId: 407799825

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Looks like there are some test failures: https://buildkite.com/bazel/bazel-bazel/builds/18671#b452c78f-43e6-4882-b79d-4bbc76b67b5c

**Comment by oquenchil** [comment]
They don't look very related to the change here and I don' t see how it could be caused by it. Not discarding completely that this is the culprit but my change mostly just adds new APIs and lots of changes to a rule that is experimental and not widely used, the rule is certainly not used within those tests.

Also every presubmit passed before merging.

**Comment by Wyverald** [comment]
Indeed -- the build is green now: https://buildkite.com/bazel/bazel-bazel/builds?branch=release-5.1.0

Maybe it was flaky?

**Comment by meteorcloudy** [comment]
I see, probably a flake.

**Pull request merged**
