### PR TITLE
Remove useless methods from CcToolchainProviderApi.

### PR DESCRIPTION
**Pull request by benjaminp**
All these *_executable methods were shadowed by the toolchain fields given to the provider.

### CODE REVIEW

**Comment by mhlopko** [comment]
Hi Benjamin,

thanks for catching this. But I don't think we can just remove these methods, especially since I advertised the wrong ones in the migration docs. We'll need to follow the incompatible flag process. Are you up to creating an issue for the change and updating this PR?

**Comment by benjaminp** [comment]
sigh. I think at the time I wrote this I thought it wasn't actually a user-visible change. But, I clearly forgot Starlark has bizarre semantics where `cc_toolchain.compiler_executable` can be a string and `cc_toolchain.compiler_executable()` can be a method call that returns a string simultaneously.

**Comment by benjaminp** [comment]
Deprecation of this APIs wouldn't share much code, so I withdraw this PR.

**Comment by mhlopko** [comment]
Ack, let me close the PR.

**Pull request closed without merging**
