### PR TITLE
Add -v, --version flag

### PR DESCRIPTION
**Pull request by akirabaruah**
Attempts to resolve issue #3599 by adding conventional `-v` and `--version` flags to the Bazel client, calling `bazel version` under the hood.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by philwo** [comment]
I guess this is fine. @ulfjack WDYT?

**Comment by ulfjack** [comment]
I don't have any objections. Unfortunately, we can't merge it without the CLA. :-(

**Comment by akira-baruah** [comment]
I signed it!

**Comment by mhlopko** [comment]
Can I merge this now?

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by akira-baruah** [comment]
@mhlopko I'm not sure if you were asking other reviewers or me, but it's ready for merge from my end!

**Comment by mhlopko** [comment]
I meant reviewers, but you know what, I'll merge this and let them object in the internal review :) Thanks!

**Comment by akira-baruah** [comment]
Thanks, SGTM!

**Comment by akira-baruah** [comment]
@mhlopko did you want to merge this?

**Comment by mhlopko** [comment]
I did import it, but @jmmv had strong concerns. Pinging him to reiterate here.

**Comment by jmmv** [comment]
Apologies. I should have pasted my comment here earlier. Here is what I said when this was imported:

> Err... but why is this the right thing to do?
>
> Adding this "--version" flag breaks the command-line interface that we have as it's disguising a command under a flag. In other words: this flag is not really a flag because it does not specify optional behavior: the presence of --version changes the behavior of the whole program -- which is what commands are intended to do.
>
> Plus I have to question the claims of "conventional" in the original bug. --version is a GNU thingy that some tools support, but many tools that accept subcommands (like Blaze) do not because of orthogonality issues.
>
> What about making this a "blaze version --short" (whose format is short, maybe GNU-compatible, _and_ machine-parseable)? Or what about making "blaze version" default to this short output and adding a new "blaze version --full" that provides the verbose details?

**Comment by akira-baruah** [comment]
@jmmv Thanks for the feedback! I see your point about separating the behavioral semantics between subcommands and flags.

Just to play devil's advocate, why then does bazel currently [support `--help`, `-help`, and `-h` flags](https://github.com/bazelbuild/bazel/blob/b29a75265882aa15bc02c5ff3e3ddc3a32b80ec2/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java#L103)? It seems like `--version` and `-v` flags are very similar. I also figure that if @drigz and [other developers](https://github.com/bazelbuild/bazel/issues/3599) (including myself) commonly run `bazel --version` for version information, why not "[be gentle to users](https://github.com/bazelbuild/bazel/blob/b29a75265882aa15bc02c5ff3e3ddc3a32b80ec2/src/main/java/com/google/devtools/build/lib/runtime/BlazeCommandDispatcher.java#L289)?"

Regardless, I agree that it might be a good idea to implement a `bazel version --full` option and to make the default `bazel version` output a bit more concise. Any internal decisions on that?

**Comment by jbduncan** [comment]
@jmmv And just to play devil's advocate even further, why not at least follow the convention that most other command line programs I know of follow (that is, allowing `--version`, `-v`, or heck even `-version` as a means to query the version of a program), which is even recommended by the GNU people themselves in their [CLI guidelines](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html#Command_002dLine-Interfaces)? :)

**Comment by drigz** [comment]
> Err... but why is this the right thing to do?

If a user has run `bazel --version`, their intent is clear, and the current behaviour is unhelpful.

> Adding this "--version" flag breaks the command-line interface ...

I don't see the downside to this change. The implementation in this PR seems clean as the `--help` flag has similar behaviour.

Are you concerned about the behaviour when the user runs eg `bazel --version query`?

> Plus I have to question the claims of "conventional" in the original bug.

Some evidence for conventionality:

```
> systemctl --version
systemd 215
[SNIP]
> git --version
git version 2.1.4
> npm --version
4.1.2
> gcloud --version
Google Cloud SDK 176.0.0
[SNIP]
> apt-get --version
apt 1.2.14 (amd64)
```

The only other subcommand-based tools I found that don't support `--version` are kubectl and hugo.

> What about making this a "blaze version --short"

That doesn't help users who run `bazel --version`.

**Comment by jmmv** [comment]
I still think that the `--version` flag is a bad idea. But... given that we already have `--help` (for no good historical reasons, I'm willing to bet), I won't object to adding `--version` as well.

*However*, if we are going to add the `--version` flag, we better make sure its output is compatible with what all other tools do in this regard. And currently, the output of `bazel version` is *not*.

See https://www.gnu.org/prep/standards/standards.html#g_t_002d_002dversion for what would be necessary to make this happen, as that's where the `--version` tradition originates.

**Comment by ulfjack** [comment]
IMO we should merge this change.

**Comment by jin** [comment]
I agree with @jmmv - if we are to go with `--version`, then we should make it as unixy as possible by printing the standard output format.

**Comment by laszlocsomor** [comment]
ping -- are there any updates? can we merge or close this PR?

**Comment by drigz** [comment]
IMO this PR is an improvement on the current behaviour. A more concise format for `bazel --version` could be implemented as a followup PR.

**Comment by ittaiz** [comment]
+1
I’ve ran “bazel —version” tens of times and still haven’t gotten it through
my head

**Comment by jmmv** [comment]
A more concise format **cannot** be implemented as a followup PR. If implemented, the output of `bazel --version` should be machine parseable to respect widespread expectations. Which means that changing it after-the-fact would break backwards compatibility. So I don't agree that this is a net improvement as is.

**Comment by lfpino** [comment]
Hi @ulfjack and @philwo, Bazel sheriff here, what's the status of this pull request? It hasn't been updated for more than a week so it'd be good to understand if it's still ongoing or safe to close. Thanks.

**Comment by akirabaruah** [comment]
I'd like to complete this feature,  since there seems to be a reasonable amount of interest. If it helps move this PR forward, I can propose a standardized version format based on previous suggestions by tomorrow.

**Comment by akirabaruah** [comment]
To address concerns regarding compatibility with other tools, `bazel --version` and `bazel -v` can alias to something like `bazel version --gnu_format` which can follow the GNU style version output:
```sh
Bazel 0.11.1
Copyright 2018 The Bazel Authors. All rights reserved.
License Apache version 2.0: <http://www.apache.org/licenses/LICENSE-2.0>
```
The version number is present only in release builds at the moment, so we'll probably have to use a placeholder version number for dev builds.

**Comment by jmmv** [comment]
@jin see the latest replies from @akirabaruah where he expressed interest to continue working on this.

I think the last proposal of aliasing `bazel --version|-v` to `bazel version --gnu_format` is a good one. I didn't realize we already had an implementation for the "standard" output of this flag.

**Comment by ulfjack** [comment]
Do you want to update this to specify --gnu_format?

**Comment by jbduncan** [comment]
I understand after reading https://github.com/bazelbuild/bazel/issues/3599#issuecomment-408202602 that `bazel info release` also prints out the version, something like:

```text
release 0.15.0
```

Does the output of this command follow the GNU format?

**Comment by jmmv** [comment]
Ah, so I read things wrong. We do *not* yet have `bazel version --gnu_format` :-/ But having it and having the alias seems like a good compromise.

@jbduncan: Regarding your latest question, no, that's not appropriate. See https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html for how things should look like.

**Comment by ulfjack** [comment]
I have a patch to add --gnu_format to bazel version.

**Comment by ulfjack** [comment]
Redirecting to --gnu_format is tricky. I'd love to switch the default, but that'll take some time - possibly up to 6 months :-(

**Comment by ulfjack** [comment]
(I suppose we could switch Google to the old default and everyone else to the new default. I can do that once we have the next release out at Google.)

**Comment by jin** [comment]
Closing this, implemented in https://github.com/bazelbuild/bazel/commit/371a2e343199ee799404fd2bb8319d990a2ad572. `--version` now works without starting a Bazel server.

**Pull request closed without merging**
