### PR TITLE
Preserve --experimental_allow_unresolved_symlinks in exec cfg

### PR DESCRIPTION
**Pull request by fmeum**
See https://github.com/bazelbuild/bazel/issues/10298#issuecomment-1097097541

Work towards https://github.com/bazelbuild/bazel/issues/10298

### CODE REVIEW

**Comment by fmeum** [comment]
@lberki Could you take a look?

**Comment by lberki** [comment]
/cc @katre 

I can't imagine you not wanting this change, so I'll go ahead and approve it.

**Review by lberki — APPROVED** [review]
Thanks! You even added a test case :)

**Review by katre — APPROVED** [review]

**Comment by katre** [comment]
@lberki Will you merge, or shall I?

**Comment by lberki** [comment]
@katre I thought that that's what the "awaiting-PR-merge" label is for and that gTech is taking care of it now. That said, if it's urgent I can merge it myself (tomorrow)

**Comment by katre** [comment]
I had no idea that label existed. The future is now!

**Comment by brentleyjones** [comment]
@bazel-io flag

**Pull request closed without merging**
