### PR TITLE
Add more license attestations for third_party pacakges with BUILD files.

### PR DESCRIPTION
**Pull request by aiuto**
Do a few interesting ones that have multiple licenses. This is mostly to have a better examples and establish a pattern.

### CODE REVIEW

**Comment by aiuto** [comment]
This is going to need a merge from the green team.  It is //third_party.

**Review by meteorcloudy — APPROVED** [review]

**Comment by sgowroji** [comment]
Hello @aiuto, Can you help me in importing this PR by squashing all the above commits into one . Thanks!

**Comment by aiuto** [comment]
It should be squashed now, to head as of 11:50AM US eastern time.

**Comment by aiuto** [comment]
done

**Comment by sgowroji** [comment]
Merged at 1620b17ccfc1167e66c4888488d272ad1a2022f4

**Pull request closed without merging**
