### PR TITLE
Update go tools to release 1.6

### PR DESCRIPTION
**Pull request by laramiel**
This updates the golang tools to release 1.6 from 1.5.1

### CODE REVIEW

**Comment by gorakhargosh** [comment]
Can this please be merged?

**Comment by davidzchen** [comment]
+@kchodorow

We have just moved the Skylark rule sets out of the main repo and into separate repos. The Go rules are now in [bazelbuild/rules_go](https://github.com/bazelbuild/rules_go). Perhaps this PR should be re-opened there?

**Comment by kchodorow** [comment]
I can manually merge it into the rules_go repo, no need to move it over.

**Comment by kchodorow** [comment]
Merged in as https://github.com/bazelbuild/rules_go/commit/655d11c450060170eeb12c009fdac01c44e79d16.

**Pull request closed without merging**
