### PR TITLE
Update to go1.6 relesase

### PR DESCRIPTION
**Pull request by laramiel**
This updates the go tools to the 1.6 release

### CODE REVIEW

**Comment by laramiel** [comment]
Updated email. Try again, googlebot.

**Comment by kchodorow** [comment]
Hmm, our system still doesn't think you've signed it.

**Comment by damienmg** [comment]
Your email (the one in the git author) is not in the database. You have to amend the commits or sign the cla with your gmail for googlebot to be happy.

**Comment by laramiel** [comment]
Yeah, I have to figure out how to ammend the commit. Haven't looked up that
yet.

**Comment by kchodorow** [comment]
Maybe http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit?

**Comment by laramiel** [comment]
Try again, googlebot.

**Comment by laramiel** [comment]
Hm. In my repository I think that I have changed the author on both commits, but it didn't get transferred here. I'll start over.

**Pull request closed without merging**
