### PR TITLE
Add JaCoCo to v0.8.9-SNAPSHOT and remove v0.8.7

### PR DESCRIPTION
**Pull request by somethingvague**
Related to #16412

PR 1 of 3 as described in [README](https://github.com/bazelbuild/bazel/blob/master/third_party/java/jacoco/README.md)

### CODE REVIEW

**Review by cushon — CHANGES_REQUESTED** [review]
Based on https://github.com/bazelbuild/bazel/issues/16412#issuecomment-1481365757, I think we should try removing the remaining patch at this point.

Would you be willing to update this to use the published 0.8.9-SNAPSHOT release and delete the patch, instead of rebuilding with it applied?

**Comment by somethingvague** [comment]
> Based on [#16412 (comment)](https://github.com/bazelbuild/bazel/issues/16412#issuecomment-1481365757), I think we should try removing the remaining patch at this point.

This PR removes the patch, confirmed this works against a test project with updated java tools

**Review by cushon — APPROVED** [review]

**Comment by sgowroji** [comment]
Merged at 11dc7de3bcbc400bf94e06af271fbe4f0992e7cb

**Comment by davidhsv** [comment]
The Jacoco snapshot of Bazel is from 30/03/2023, but the current snapshot available is from 31/03/2023. This difference in build dates is causing issues because our tests with coverage are running with the 0.8.9-snapshot(31/03), while Bazel is weaving the classes using a Jacoco agent from the 30/03 snapshot.

This mismatch is leading to a bug, cause the hash in org.jacoco.agent.rt.internal_(hash) is dependent on the Jacoco agent build.

Is there a way to downgrade in runtime to 0.8.8 version of Jacoco in my local project, or to align the Bazel environment with the current snapshot?

**Comment by cushon** [comment]
> The Jacoco snapshot of Bazel is from 30/03/2023, but the current snapshot available is from 31/03/2023. This difference in build dates is causing issues because our tests with coverage are running with the 0.8.9-snapshot(31/03), while Bazel is weaving the classes using a Jacoco agent from the 30/03 snapshot.
> 
> This mismatch is leading to a bug, because the hash in org.jacoco.agent.rt.internal_(hash) is dependent on the Jacoco agent build.
> 
> Is there a way to downgrade in runtime to 0.8.8 version of Jacoco in my local project, or to align the Bazel environment with the current snapshot?

Can you file a bug for this? Probably we should update Bazel to a newer non snapshot Jacobo release

**Comment by davidhsv** [comment]
I was able to do a workaround downloading the jacoco used in bazel and creating a lib for it:

// BUILD.bazel
```java_import(
    name = "jacocoagent",
    jars = ["jacocoagent-0.8.9-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],  # Make it available to other packages
```)

//libs/jacoco/jacocoagent-0.8.9-SNAPSHOT.jar
[jacocoagent-0.8.9-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16791255/jacocoagent-0.8.9-SNAPSHOT.jar.zip)

And use it like this in the weaving:
```
_aspectj_weave(
        name = name,
        aspects = aspects,
        jar = jar,
        runtime_deps = ["//maven:org_aspectj_aspectjrt", "//libs/jacoco:jacocoagent"] + runtime_deps,
        **kwargs
    )
 ```
 
 The error was: /private/var/tmp/_bazel_davidvieira/52af286067236843f81b50b2c41f19c6/execroot/mono/bazel-out/darwin_arm64-fastbuild/bin/[OMITTED]/identity/libidentity-raw.jar [error] can't determine superclass of missing type org.jacoco.agent.rt.internal_43a39aa.Offline
when weaving type com.[OMITTED].SyncedUserService
when weaving classes
when weaving
when batch building BuildConfig[null] #Files=0 AopXmls=#1
 [Xlint:cantFindType]
(no source information available)
	[Xlint:cantFindType]

**Comment by davidhsv** [comment]
In newer versions of Bazel, we already have a non-snapshot version of Jacoco. I think we are fine, at least we have a workaround for now, before updating Bazel.

Thank you 🙏

**Pull request closed without merging**
