### PR TITLE
Switch to new builtin cc proto rules for protobuf.

### PR DESCRIPTION
**Pull request by abergmeier-dsfishlabs**
We no longer need to use the custom rules.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by buchgr** [comment]
OK to test

**Comment by abergmeier-dsfishlabs** [comment]
@damienmg Friendly ping.

**Comment by damienmg** [comment]
Sorry importing right now. FTR @cgrushko go/bazel has the command to import a change...

**Comment by abergmeier-dsfishlabs** [comment]
Should I fix the conflict first?

**Comment by damienmg** [comment]
Nope I fixed it during import.

**Pull request closed without merging**
