### PR TITLE
Remove pre-compiled Protobuf jars

### PR DESCRIPTION
**Pull request by Yannic**
Checking them in is no longer necessary after #10638

### CODE REVIEW

**Comment by Yannic** [comment]
@philwo This is the third-party part of #10638 and cannot stand on its own. Please merge soon after #10638 lands.

**Comment by philwo** [comment]
@Yannic Can you rebase this so that we can test this change on CI with #10638 included?

**Comment by philwo** [comment]
Ah, I managed to do it in a personal branch - tests running here: https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/5295.

If they're green, I'll merge this PR. :)

**Comment by Yannic** [comment]
Tests are failing because of https://github.com/bazelbuild/bazel/commit/d5d39449a100cfc6b29938b6973051f7aff0f5fb#r37117155. Looks like it got lost during import and export.

**Comment by philwo** [comment]
I fixed the bad merge via https://github.com/bazelbuild/bazel/commit/aa742182a608c1e4551a5a28acb108f39b723828. Thanks for noticing that.

Tests are green now: https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/5298

**Comment by philwo** [comment]
Merged and pushed in https://github.com/bazelbuild/bazel/commit/69092ef6b169ca9a11db1237852aefdd606b8cab.

**Pull request closed without merging**
