### PR TITLE
Expose proto bindings to Python, too.

### PR DESCRIPTION
**Pull request by abergmeier**

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by meteorcloudy** [comment]
@buchgr Can you review this change?

**Comment by abergmeier-dsfishlabs** [comment]
> What are you using these for, if I may ask? Are you depending on bazel?

Exactly. Specifically I am implementing `compile_commands.json` support for Sublime.

**Comment by abergmeier** [comment]
Had to add fixes to `.bzl`, too.

**Comment by abergmeier** [comment]
*sigh* Apparently `py_proto_library` does not yet work with the `ProtoSourcesProvider`. And you cannot use it anyway because of name collisions with `proto_library` :cry:

**Comment by buchgr** [comment]
> sigh Apparently py_proto_library does not yet work with the ProtoSourcesProvider. And you cannot use it anyway because of name collisions with proto_library

cc: @cgrushko

**Pull request closed without merging**
