### PR TITLE
fix: export constraints.bzl file from @local_config_platform so it can be used in downstream bzl_library targets

### PR DESCRIPTION
**Pull request by gregmagolan**
Same as https://github.com/bazelbuild/bazel/commit/4959d34e844714b793b2c6fa05016a9a6eaa7044 but for release-6.0.0 branch. See https://github.com/bazelbuild/bazel/issues/16159#issuecomment-1307519558.

### CODE REVIEW

**Review by kshyanashree — APPROVED** [review]

**Comment by gregmagolan** [comment]
v0.16.0 Aspect CLI Pro release with brew install support is out. 

Closing this epic. Will make new tickets for remaining work.

**Comment by gregmagolan** [comment]
Whooops. Unintentional close. Thought I was looking at a different PR.

**Review by meteorcloudy — APPROVED** [review]

**Comment by meteorcloudy** [comment]
@gregmagolan Can you rebase with the release-6.0.0 HEAD?

**Comment by gregmagolan** [comment]
Oh. Looks like this has already been landed on the release-6.0.0 branch https://github.com/bazelbuild/bazel/commit/e9a931f7e8647f8e0b9b2d47c750eedd26dd53bf

**Comment by gregmagolan** [comment]
Looks like this has already been landed on the release-6.0.0 branch https://github.com/bazelbuild/bazel/commit/e9a931f7e8647f8e0b9b2d47c750eedd26dd53bf

**Pull request closed without merging**
