### PR TITLE
Support collecting coverage for C-only targets

### PR DESCRIPTION
**Pull request by th0br0**
*NOTE*: It appears that `master` is lagging behind the latest release `0.19.0`; not sure which branch this PR should target or if `master` will be updated. Please tell me and I will rebase/amend accordingly.

Currently (and also prior to 0.19.0) `bazel coverage` fails for C-only targets as the coverage collector can't find the correct gcov files. gcov apparently doesn't create `.gcda` files for such targets, as such the output filename of the actual gcov file differs.

This PR (only commit 7faad59) adds another file exists check to the coverage collector to take C targets into account.
I can provide a sample repo for reproducing the bug, alternatively there's https://github.com/iotaledger/entangled where `bazel coverage -c dbg --experimental_cc_coverage //common/... --verbose_failures` fails on 0.19.0

### CODE REVIEW

**Comment by th0br0** [comment]
FWIW, I do have a valid CLA on file for the `andreas@osowski.de` address, id: 117988078752316293185 - not sure why the bot can't find it.

**Comment by th0br0** [comment]
The `-w` was something I had planned to remove once know the right merge target (it's equivalent to `--verbose`), but I've removed it now (new commit is 7faad59)

**Comment by ulfjack** [comment]
This patch no longer applies cleanly, and I can't tell whether head still requires changes to work with C-only targets or not. I'm therefore closing this PR. Feel free to reopen if you have an updated version. Also, please use master as the base in the future, not the release branch (I can import individual patches, but it's easier that way).

**Comment by ulfjack** [comment]
(You can ping me personally if you have a new patch and you're not getting timely replies from the reviewer.)

**Pull request closed without merging**
