### PR TITLE
convert rules using pkg_tar in //third_party to rules_pkg

### PR DESCRIPTION
**Pull request by aiuto**
Part of the extraction of packaging rules from Bazel.
See https://docs.google.com/document/d/1GAbAiW0nVbxGlwsdXhFIcn3owlZJkMJiXBt-ttA9z_k/edit?ts=5cc6f473#

### CODE REVIEW

**Comment by jin** [comment]
Has this been merged yet?

**Comment by iirina** [comment]
I couldn't find it on bazel's history, so I don't think so. I just sent Tony how to merge third-party changes. Make sure you don't try to merge it both.

**Comment by aiuto** [comment]
Not yet. I just tried to merge, but the git push failed. I'll keep trying.

**Comment by iirina** [comment]
Merged in 0ebf8e29713dbf9d0a71ff9d6a6ced14b2383b11.

**Comment by aiuto** [comment]
Thanks.

**Pull request closed without merging**
