### PR TITLE
Remove idle GC.

### PR DESCRIPTION
**Pull request by benjaminp**
If a Bazel server was idle for 10 seconds, it would trigger a full-scale Java GC
via `System.gc()`. This behavior didn't have clear benefits and caused Bazel to
steal resources from whatever the user did after invoking Bazel.

Fixes https://github.com/bazelbuild/bazel/issues/5589.

### CODE REVIEW

**Comment by buchgr** [comment]
+1, though @lberki might now better :-)

**Comment by lberki** [comment]
Bouncing to @meisterT and @tomlu  -- they have been dabbling into GC so they know better whether this is doable.

The GC-after-ten-seconds rule is probably a bigger boon to our internal builds which are much bigger; it's conceivable that Bazel can do without it.

**Comment by buchgr** [comment]
I think it's not clear that this helps at all (internal or external) and it sounds unlikely too. How would we be able to keep expensive GC work to after a build has finished? I can imagine that this was added with the rational to clean up dead objects after a build, however in Java's GCs throwing away dead objects is mostly free and thus this idle timer seems unlikely to help?

**Comment by benjaminp** [comment]
I'm happy to send a CL to add an option to toggle idle GC, my original suggestion in #5589. Another intermediate step would be to add logging of heap usage before and after the GC to see how much is actually being collected.

The heart of the problem is that `System.gc()` is a very heavy operation. It would be different if HotSpot had a V8-style API to say, "I'm probably idle for the next N milliseconds, so do some incremental GC work if you think it would be useful." I believe the usecases of `System.gc()` are limited to profiling (`info used-heap-size-after-gc`) and handling requests where the user expects all state to be dropped (`clean`).

The problem I mention in the ticket of Bazel stealing resources from other processes is more severe after the recent `run` command changes. In particular, since `run` no longer blocks in the server, there's nothing preventing Bazel from executing a full GC while some long-running `run` operation is in progress.

**Comment by tomlu** [comment]
I did some investigation on a certain infamous internal target to see what the GC buys us.

The memory usage during the heaviest part of the build ranged between 12.8GB-16GB. The latter value is simply because that's the Xmx I granted the build, so with a larger Xmx you'd see a greater range.

The GC drops this to 10.5GB, indicating that in this case there is about 2.3GB worth of objects that are no longer needed after the build is complete. But of course then it all depends on when the last GC was performed during the build.

I don't know what the right solution is. Having 3+GB of unused memory sit around in each client doesn't seem great, but then again the current situation isn't great either.

**Comment by meisterT** [comment]
I also looked into this the day before. One of the differences is that we use CMS for GC which can be convinced to release unused heap space back to the kernel, unlike ParallelOldGC. So with default OpenJDK settings the gc call makes the JVM consume more (not less) memory from the view of the kernel :-/

So I see the following options:
- either add the toggle (and default it to be off and turn it on where it makes sense) or
- use ProcMeminfoParser (see https://source.bazel.build/bazel/+/master:src/main/java/com/google/devtools/build/lib/unix/ProcMeminfoParser.java;l=91?q=ProcMeminfoparser&ss=bazel) to check whether there's actually memory pressure from the kernel point of view.

**Comment by benjaminp** [comment]
Okay, sounds like we'll want to go with something like #5628 for the time being.

**Pull request closed without merging**
