### PR TITLE
Update java_tools v13.8 / rules_java 7.11.0

### PR DESCRIPTION
**Pull request by iancha1992**
https://github.com/bazelbuild/java_tools/issues/91

### CODE REVIEW

**Comment by iancha1992** [comment]
@hvadehra I am currently on step 6/7. After I've modified the `MODULE.bazel` and `workspace_deps.bzl`, I tried to update the lockfile. But it's giving me this following error:

```
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_java/archive/b52393a1f6860901e95d5fa88de3cfc81129b58e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: For repository 'abseil-cpp', the root module requires module version abseil-cpp@20230802.1, but got abseil-cpp@20240116.2 in the resolved dependency graph.
ERROR: Error computing the main repository mapping: Direct dependency check failed.
Computing main repo mapping: 
```

Can you please advise? thanks

cc: @bazelbuild/triage

**Comment by iancha1992** [comment]
@hvadehra looks like we're getting a couple presubmit errors. Could you please take a look?

cc: @bazelbuild/triage

**Comment by hvadehra** [comment]
Looks like a repeat of https://github.com/bazelbuild/bazel/pull/23237#issuecomment-2274824831

**Comment by iancha1992** [comment]
> Looks like a repeat of [#23237 (comment)](https://github.com/bazelbuild/bazel/pull/23237#issuecomment-2274824831)

Thanks!

**Comment by iancha1992** [comment]
@hvadehra looks like the presubmits are failing. Could you please take a look? Thanks!

**Comment by hvadehra** [comment]
For one, the abseil-cpp version might be problematic. It was deliberated downgraded from this version in https://github.com/bazelbuild/bazel/commit/651294b4c8141b3964d0ce6c7a4b2a5b988e979c . @meteorcloudy What can we do here? I tried pinning the version with `single_version_override` but that seems to break distfile tests as well. 

Additionally, re: the cpython download failures, I think because of these changes, the lockfile might need to be updated on all platforms.

**Comment by hvadehra** [comment]
I downgraded the abseil-cpp version in rules_java and released `v7.11.1`. Lets use that instead once https://github.com/bazelbuild/bazel-central-registry/pull/2749 is merged.

**Comment by meteorcloudy** [comment]
@Wyverald How close are we to upgrading protobuf and abseil-cpp for Bazel itself?

**Comment by hvadehra** [comment]
@iancha1992 I've gone ahead and created https://github.com/bazelbuild/bazel/pull/23571 which is looking proimising, I guess we can close this.

**Comment by hvadehra** [comment]
https://github.com/bazelbuild/bazel/pull/23571 was merged, closing as obsolete.

**Comment by iancha1992** [comment]
@bazel-io fork 7.4.0

**Pull request closed without merging**
