### PR TITLE
Forward `@bazel_tools//tools/sh:toolchain_type` to `rules_shell`

### PR DESCRIPTION
**Pull request by fmeum**
This is required for compatibility with modules that rely on the auto-registered `sh_toolchain` to obtain a shebang, e.g. `rules_js`.

Also remove implementations and toolchain registrations in favor of forwarders.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @comius

**Comment by fmeum** [comment]
@bazel-io fork 8.0.1

**Comment by fmeum** [comment]
FYI @alexeagle as this may break `rules_{,node}js` users with Bazel 8.0.0

**Comment by alexeagle** [comment]
Thank you! I don't think we saw that report yet but perhaps the problem is unreachable due to other Bazel 8 errors.

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 8.0.1 RC1](https://github.com/bazelbuild/bazel/releases/tag/8.0.1rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=8.0.1rc1`. Thanks!

**Pull request closed without merging**
