### PR TITLE
[coverage] Parsing file log level to DEBUG

### PR DESCRIPTION
**Pull request by mortenmj**
https://github.com/bazelbuild/bazel/pull/17499 was closed as stale. This logging is still very noisy, so it would be great to get this merged.

Fixes https://github.com/bazelbuild/bazel/issues/17492

### CODE REVIEW

**Comment by mortenmj** [comment]
CI is failing; I guess `Level.Debug` doesn't exist. What would be reasonable here?

**Comment by fmeum** [comment]
> CI is failing; I guess `Level.Debug` doesn't exist. What would be reasonable here? Does this need to be logged at all?

This is a standalone Java program, not part of the Bazel server. We can't just inherit the same logging settings, so we'll have to come up with some other setting to gate this behind.

@c-mita Is the output used at Google?

**Comment by mortenmj** [comment]
@c-mita if you'd like to make changes to this PR, please feel free

**Comment by c-mita** [comment]
Looking at https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/logging/Level.html - it looks like the "correct" setting would be `Level.FINE`?

But the issue is that I don't actually know if, when Bazel runs this program, if the desired log level can be specified. I don't want to lose the ability to see these messages because they can be helpful when there are problems with the coverage output, but I appreciate that they can generate a lot of noise in some cases. I suspect we'll have to wire in a configuration switch somewhere.

**Comment by mortenmj** [comment]
Fixed by https://github.com/bazelbuild/bazel/pull/22257

**Pull request closed without merging**
