### PR TITLE
Force use of Clang over C++ modules with `use_module_maps`

### PR DESCRIPTION
**Pull request by fmeum**
With `-std=c++20`, Clang defaults to using C++ modules rather than Clang modules, which can result in failures when using `layering_check` and thus `use_module_maps`.

Fixes https://github.com/bazel-contrib/toolchains_llvm/issues/334

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io flag

**Review by oquenchil — APPROVED** [review]

**Comment by fmeum** [comment]
@oquenchil The flag unfortunately requires clang-14: https://github.com/llvm/llvm-project/commit/0556138624edf48621dd49a463dbe12e7101f17d

I will add version detection logic.

**Comment by keertk** [comment]
@bazel-io fork 7.3.0

**Comment by fmeum** [comment]
I added feature detection.

**Review by oquenchil — APPROVED** [review]

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.3.0 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.3.0rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.3.0rc1`. Thanks!

**Pull request closed without merging**
