### PR TITLE
Add exec transition to lcov_merger in Java version of py_test

### LINKED ISSUE #17568: Running coverage on a py_test fails when --java_runtime_version is Java 8
### Description of the bug:

The tools in `@remote_coverage_tools` require a JRE 11 or higher. When running coverage on `java_test`, the JRE from `--tool_java_runtime_version` will be used, which enables running the tests themselves with a different JRE. However, when running coverage on `py_test`, the JRE from `--java_runtime_version` will be used, so Bazel will fail if `--java_runtime_version` is a JRE 8.

### What's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Minimal workspace: [testrepo.zip](https://github.com/bazelbuild/bazel/files/10818569/testrepo.zip)

```
% cd testrepo
% bazel coverage :all
INFO: Invocation ID: 3c462964-cab1-4263-97cb-56fda85d9a68
INFO: Using default value for --instrumentation_filter: "^//".
INFO: Override the above default with --instrumentation_filter
INFO: Analyzed 2 targets (52 packages loaded, 1107 targets configured).
INFO: Found 2 test targets...
FAIL: //:PyTest (see /private/var/tmp/_bazel_tkaplan/5d75f57112c098c59880ccf1af5eecda/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/PyTest/test.log)
INFO: Elapsed time: 35.944s, Critical Path: 6.98s
INFO: 21 processes: 10 internal, 8 darwin-sandbox, 3 worker.
INFO: Build completed, 1 test FAILED, 21 total actions
//:JavaTest                                                              PASSED in 1.0s
//:PyTest                                                                FAILED in 1.0s
  /private/var/tmp/_bazel_tkaplan/5d75f57112c098c59880ccf1af5eecda/execroot/__main__/bazel-out/darwin_arm64-fastbuild/testlogs/PyTest/test.log
```

### Which operating system are you running Bazel on?

macOS 13.2.1

### What is the output of `bazel info release`?

6.1.0rc1

### If `bazel info release` returns `development version` or `(@non-git)`, tell us how you built Bazel.

_No response_

### What's the output of `git remote get-url origin; git rev-parse master; git rev-parse HEAD` ?

_No response_

### Have you found anything relevant by searching the web?

_No response_

### Any other information, logs, or outputs that you want to share?

_No response_

### PR DESCRIPTION
**Pull request by thirtyseven**
Fixes #17568

### CODE REVIEW

**Review by c-mita — APPROVED** [review]
LGTM

**Comment by thirtyseven** [comment]
Any chance this can be included in 6.1.0?

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by keertk** [comment]
@bazel-io fork 6.1.0

**Pull request closed without merging**
