### PR TITLE
17173 improve error message

### PR DESCRIPTION
**Pull request by tbaing**
Creating a new PR after updating my GitHub account's settings to show my @google.com email address in my commit header. This should have identical content to https://github.com/bazelbuild/bazel/pull/17323, other than my email address.

### CODE REVIEW

**Comment by tbaing** [comment]
Hmm, given the merge conflict it looks like maybe these changes already merged under https://github.com/bazelbuild/bazel/pull/17323 but the PR was still open due to the missing CLA (since the commit listed my GitHub email rather than my Google email as the author)?

It looks like this can be abandoned, but I'd appreciate confirmation of that from a maintainer since I hadn't thought https://github.com/bazelbuild/bazel/pull/17323 had been merged.

**Comment by coeuvre** [comment]
#17323 wasn't merged into 6.1. The merge conflict is because this PR is comparing against `master` branch not [release-6.1.0](https://github.com/bazelbuild/bazel/tree/release-6.1.0). Can you please update the PR?

**Review by kshyanashree — APPROVED** [review]

**Comment by tbaing** [comment]
Just updating the PR to target the 6.1.0 branch didn't work because then it tries to pull in other commits. Might the best solution be for @kshyanashree to update the author email in the cherrypick commit in https://github.com/bazelbuild/bazel/pull/17323 to use my Google email (tbain@google.com)?

**Comment by kshyanashree** [comment]
Closing this PR because it’s already merged in the master.

**Pull request closed without merging**
