### PR TITLE
Make Bash runfiles library repo mapping aware

### LINKED ISSUE #16713: [6.0.0] Make Bash runfiles library repo mapping aware
Forked from #16693

### PR DESCRIPTION
**Pull request by fmeum**
Work towards #16124

Closes #16713.

PiperOrigin-RevId: 487811689
Change-Id: Iec5ef01ae09394372b87e5cb697ceb728563d2dc

### CODE REVIEW

**Comment by fmeum** [comment]
@Wyverald

**Review by kshyanashree — APPROVED** [review]

**Comment by kshyanashree** [comment]
Hello @fmeum, Could you please resolve the conflicts? Thanks!

**Comment by fmeum** [comment]
@kshyanashree I rebased the PR and resolved the conflicts.

**Comment by kshyanashree** [comment]
> @kshyanashree I rebased the PR and resolved the conflicts.



> @kshyanashree I rebased the PR and resolved the conflicts.

Thanks @fmeum! It is merged now.

**Pull request merged**
