### PR TITLE
Allow Bazel's Debian package to install with headless JDK.

### PR DESCRIPTION
**Pull request by jmillikin-stripe**
Fixes https://github.com/bazelbuild/bazel/issues/3761

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by damienmg** [comment]
Sorry this drop out of my radar. Thanks for your contribution!

**Comment by jmillikin-stripe** [comment]
It looks like this didn't merge automatically -- do I need to do anything to get it moving?

**Comment by damienmg** [comment]
You need to do nothing, the automatic submission failed due to a flake in the internal presubmit sorry, retriggering submissionn now and it should be merged in a couple of hours max.

**Pull request closed without merging**
