### PR TITLE
jvm.bzl: Load Java rules from @rules_java

### LINKED ISSUE #10046: Prepare {java|jvm}_import_external for --incompatible_load_java_rules_from_bzl option flip
See #8746 for details.

### PR DESCRIPTION
**Pull request by beasleyr-vmw**
Resolves #10046.

### CODE REVIEW

**Comment by beasleyr-vmw** [comment]
cc @jin

**Comment by jin** [comment]
This will incur a breaking change on all downstream users of jvm_import_external, since we have not flipped the incompatible change on `@rules_java`. Users do not need to add `@rules_java` now, so if we merge this, projects will break.

This would be better coordinated with someone on the server rules team (@iirina?).

**Comment by beasleyr-vmw** [comment]
I'm confused. Hasn't Bazel implicitly satisified rules_java since 0.29 via jdk.WORKSPACE? (AFAIK, jdk.WORKSPACE is magically appended to the user's WORKSPACE file, so all users automatically have a rules_java repo.)

https://github.com/bazelbuild/bazel/blob/55c75ed16e8c456d92510df13da4ffe01e0b998d/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE#L260-L269

**Comment by jin** [comment]
Oh, hum, my bad! LGTM.

**Pull request closed without merging**
