### PR TITLE
Add `--incompatible_merge_fixed_and_default_shell_env`

### LINKED ISSUE #12049: `PATH` not propagated to many darwin actions
This is a wider reaching version of https://github.com/bazelbuild/bazel/issues/8425

In the linked issue I did some investigation around default PATH variables for actions that at the time I thought only affected `py_*` targets but it turns out that many other actions on darwin do not inherit any `PATH` and therefore fallback to macOS's default shell env of `/usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:.` which can allow leakage of `/usr/local/*` binaries (which is specifically an issue because of homebrew).

While the default PATH may be ok for some use cases, if you actually try to restrict it using `--action_env=PATH=something` or by executing bazel with `env -i PATH=something bazel ...`, neither of these are applied to these actions.

For example any action that is executed in the context of Xcode is executed with these environment variables:

```
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    XCODE_VERSION_OVERRIDE=11.5.0.11E608c \
  external/local_config_cc/wrapped_clang ...
```

Some actions that don't require Xcode are executed with no environment variables:

```
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool ...
```

This is not the behavior of some other rules like `genrule` where if you build this target with `--action_env=/usr/bin:/bin` it hits the "Valid path":

```bzl
genrule(
    name = "foo",
    outs = ["foo.txt"],
    cmd = """
if [[ "$$PATH" != "/usr/bin:/bin" ]]; then
  echo "error: path not propagated: $$PATH"
  exit 1
else
  echo "Valid path! $$PATH"
  exit 1
fi
""",
)
```

I think that either all actions should get a very conservative default PATH like `/usr/bin:/bin`, or the flags like `--action_env` should be able to add env vars to these actions (I believe the latter is likely the more flexible path, but I'm not sure about the implementation implications).

For native actions it seems that this can be resolved by adding:

```java
.setInheritedEnvironment(ImmutableSet.of("PATH"));
```

to this logic https://github.com/bazelbuild/bazel/blob/8f678923ebea788fc1e03ba8c6359b51edafe0df/src/main/java/com/google/devtools/build/lib/rules/objc/ObjcRuleClasses.java#L140-L144

But for starlark actions they inherit this environment:

https://github.com/bazelbuild/bazel/blob/8f678923ebea788fc1e03ba8c6359b51edafe0df/tools/osx/crosstool/cc_toolchain_config.bzl#L4546-L4557

When accessing the environment variables for an action with the [`cc_common` api](https://docs.bazel.build/versions/master/skylark/lib/cc_common.html#get_environment_variables). There doesn't seem to be a way to craft an `env_entry` that doesn't impose a value. So I could add `/usr/bin:/bin` there, but it wouldn't allow overrides via `--action_env=PATH=foo`

I'm happy to make a change here but I'm hoping for some guidance on the right path!

### What operating system are you running Bazel on?

macOS

### Bazel version?

8f678923ebea788fc1e03ba8c6359b51edafe0df

### PR DESCRIPTION
**Pull request by fmeum**
With the new flag, Starlark actions that specify both `env` and `use_default_shell_env` will no longer have `env` ignored. Instead, the values of `env` will override the default shell environment.

This allows Starlark actions to both pick up user-configured variables such as `PATH` from the shell environment as well as set variables to fixed values required for the action, e.g., variables provided by the C++ toolchain.

Rationale for having `env` override the default shell env: The rules know best which values they have to set specific environment variables to in order to successfully execute an action, so a situation where users break an action by a globally applied `--action_env` is prevented. If users really do have to be able to modify an environment variables fixed by the rule, the rule can always make this configurable via an attribute.

Work towards #5980
Fixes #12049

### CODE REVIEW

**Comment by fmeum** [comment]
@comius I thought more about #5980 and found this to be the only approach that made sense to me, so I went ahead and created a PR. Let me know if you think this deserves more design work.

**Comment by fmeum** [comment]
Cc @oquenchil as this fixes an issue with `cc_import`

**Comment by gregestren** [comment]
I think @comius could best triage?

**Comment by fmeum** [comment]
Learned from @keith that this may end up fixing https://github.com/bazelbuild/bazel/issues/12049.

**Comment by keith** [comment]
bump, this would be super nice to have

**Comment by fmeum** [comment]
@comius It would be great if you could take a look or reassign to someone else. Flipping this flag is required for my ongoing work on the all Starlark `cc_static_library` rule.

**Comment by fmeum** [comment]
@comius Friendly ping, could you take a look or assign to someone else?

**Comment by brentleyjones** [comment]
@bazelbuild/triage

**Comment by iancha1992** [comment]
> @bazelbuild/triage

@comius will try and review this tmrw

cc: @fmeum @brentleyjones

**Review by comius — APPROVED** [review]

**Comment by fmeum** [comment]
> Since this is behind a flag, you think it's cherry-pickable @fmeum?

It would be if it applies cleanly. I recall some merge conflicts, but we can give it a try.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
@fmeum @brentleyjones @keith @gregestren @comius 
I think we may need another commit(s) before we can cherry-pick this one.

From ```src/main/java/com/google/devtools/build/lib/analysis/actions/SpawnAction.java```

In the current release-6.4.0 branch, we have
```
ActionEnvironment env =
          actionEnvironment != null
              ? actionEnvironment
              : useDefaultShellEnvironment
                  ? configuration.getActionEnvironment()
                  : ActionEnvironment.create(environment, inheritedEnvironment);
      return buildSpawnAction(
          owner, commandLines, configuration.getCommandLineLimits(), configuration, env);
```
but it really should be 
```
ActionEnvironment env =
          useDefaultShellEnvironment
              ? configuration.getActionEnvironment()
              : ActionEnvironment.create(environment);
```
before the change.

**Pull request closed without merging**
