### PR TITLE
Optimize RepoMappingManifestAction

### PR DESCRIPTION
**Pull request by fmeum**
The following optimizations reduce the time spent writing the repo mapping manifest from >6s to <80ms for a test referencing each of ~4,000 repos created by a module extension:

* The set of repository names appearing in runfiles paths is only constructed once rather than for each repo by moving the `build()` call out of a closure.
* The relevant entries per repository are now sorted after filtering out those for repos that don't contribute runfiles.
* Crucially, the relevant mapping entries per repository are now cached per instance of `RepositoryMapping#entries()`. Since extension repos all share the same instance due to interning, this reduces the complexity from quadratic to linear in the number of extension repos.

### CODE REVIEW

**Comment by fmeum** [comment]
Turns out that the action itself is really fast now, but the key computation is still slow. I will see whether that can be fixed without memory overhead.

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by fmeum** [comment]
I pushed a commit that also caches the key computation. The first computation is actually still a bit slower than running the action, but subsequent evaluations are much faster (~1-2ms), leveraging both the nested set fingerprint cache as well as the new repo mapping fingerprint cache.

Here is a profile of the reproducing repo (https://github.com/DavidZbarsky-at/repo-mapping-manifest-repro) with `//:slow_test` duplicated 20 times: 
[after.json.gz](https://github.com/bazelbuild/bazel/files/13297280/after.json.gz)

**Comment by keertk** [comment]
@bazel-io fork 7.0.0

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.0.0 RC5](https://releases.bazel.build/7.0.0/rc5/index.html). Please test out the release candidate and report any issues as soon as possible. If you're using Bazelisk, you can point to the latest RC by setting USE_BAZEL_VERSION=last_rc.
Thanks!

**Pull request closed without merging**
