### PR TITLE
Update to latest remote-execution proto

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by EdSchouten** [comment]
Cc @coeuvre @philwo

**Comment by coeuvre** [comment]
@meteorcloudy Please help merge this.

**Comment by philwo** [comment]
Merging this now.

**Comment by philwo** [comment]
Merged in https://github.com/bazelbuild/bazel/commit/1fcb18a0b455bfcb8e9940778f37d8c82c5ed5a0

**Pull request closed without merging**
