### PR TITLE
Fix up some tests for Arm64

### PR DESCRIPTION
**Pull request by ArielleA**
This is the first PR for my Arm64 test cleanup.

### CODE REVIEW

**Comment by mhlopko** [comment]
Are there tests that don't pass yet? 

@buchgr can we get arm64 machine on our CI so this doensn't regress in the future?

**Comment by buchgr** [comment]
@mhlopko I don't think so.

**Comment by ArielleA** [comment]
This isn't a regression as such, as the arm64 support was only introduced in the code-base last week.

It may be a little early to think about CI, however the Bazel project could always reach out to www.Workonarm.com which is an organization providing equipment for CI/CD to various projects for Datacenter strength Arm64 support. Golang is listed on their site as a user.

**Comment by vielmetti** [comment]
Thanks @ArielleA - for access to the Works on Arm cluster open up an issue at https://github.com/worksonarm/cluster - we have a variety of resources for CI needs.

**Pull request closed without merging**
