### PR TITLE
Update to Turbine 0.8.0

### PR DESCRIPTION
**Pull request by cushon**
https://github.com/google/turbine/releases/tag/v0.8.0

```
REPIN=1 bazelisk run @maven//:pin && bazelisk mod deps --lockfile_mode=update
```

https://github.com/bazelbuild/bazel/issues/24138

### CODE REVIEW

**Comment by vinnybod** [comment]
Is it possible to cherry-pick this to 7.4.1 ?

**Comment by fmeum** [comment]
@hvadehra It would be great to have a rules_java release with this that is compatible with Bazel 7.4.1.

**Comment by hvadehra** [comment]
@bazel-io flag

**Comment by iancha1992** [comment]
@Wyverald @meteorcloudy Should this be included in 7.4.1? If so, then we'll need rc2.

cc: @bazelbuild/triage

**Comment by hvadehra** [comment]
What we really need is https://github.com/bazelbuild/bazel/pull/24143 but I think it's optional for 7.4.1 (users can always update rules_java independently). Would be good to have in 8.0.0.

**Comment by iancha1992** [comment]
@bazel-io fork 8.0.0

**Pull request closed without merging**
