### PR TITLE
Allow adding prefix path when unpacking HTTP repos.

### PR DESCRIPTION
**Pull request by inazarenko**
Motivation: https://github.com/bazelbuild/bazel/issues/16136

### CODE REVIEW

**Review by Wyverald — APPROVED** [review]
thanks!

**Comment by rdesgroppes** [comment]
wasn't merged?

**Comment by brentleyjones** [comment]
It was merged into master/6.0.

**Comment by rdesgroppes** [comment]
Thanks, @brentleyjones!

**Pull request closed without merging**
