### PR TITLE
Fix broken link to cc_binary

### PR DESCRIPTION
**Pull request by wisechengyi**
Invalid url https://docs.bazel.build/versions/master/tutorial/docs/be/c-cpp.html#cc_binary
Valid url: https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary

Hence changed relative path `docs/be/c-cpp.html#cc_binary` to abs path `/be/c-cpp.html#cc_binary`.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by wisechengyi** [comment]
not sure how to verify exactly, since I'm just picking up bazel. but should be easy to enough to eye ball it?

**Comment by wisechengyi** [comment]
I signed it!

**Comment by mhlopko** [comment]
Thanks for the pr! I'll add a tiny polish and merge it. Welcome to Bazel :)

**Pull request closed without merging**
