### PR TITLE
Report the config id with the failing target during toolchain resolution

### PR DESCRIPTION
**Pull request by katre**

### CODE REVIEW

**Review by gregestren — APPROVED** [review]

**Comment by fmeum** [comment]
@bazel-io flag

**Comment by katre** [comment]
Why is this flagged for a cherrypick to the next release? It's a nice feature for debugging but it's not related to any actual issues that I am aware of.

**Comment by iancha1992** [comment]
@bazel-io fork 6.4.0

**Comment by iancha1992** [comment]
@katre @fmeum @gregestren @sdtwigg 
As per @meteorcloudy, it looks like it's nice to include and cherry-pick this, while waiting for other PR's. But there was one conflict because the "src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainException.java" is currently missing in the release-6.4.0 branch. Think it's because it was renamed from "src/main/java/com/google/devtools/build/lib/skyframe/ToolchainException.java" (currently in release-6.4.0) to "src/main/java/com/google/devtools/build/lib/skyframe/toolchains/ToolchainException.java" (currently in master). Please advise or create a PR. Thank you!

cc: @bazelbuild/triage @meteorcloudy

**Comment by katre** [comment]
Sounds good, I'll be happy to check a PR.

**Comment by fmeum** [comment]
I tried to cherry-pick this, but it depends on 2a923f1, which in turn doesn't deal with the host configuration. I will give up.

**Pull request closed without merging**
