### PR TITLE
Ignore try import failure on Windows

### PR DESCRIPTION
**Pull request by andrewkatson**
Fixes:

https://github.com/bazelbuild/bazel/issues/13443#event-4951673487

### CODE REVIEW

**Comment by meteorcloudy** [comment]
Thanks!  Can you reference the issue report in your PR description?

**Comment by meteorcloudy** [comment]
I wonder if there is a more clean solution, this looks like a lot of changes.

**Comment by andrewkatson** [comment]
Im open to suggestions of how to make it cleaner. Not sure how though.

**Comment by meteorcloudy** [comment]
I guess you can try to deal with the error in ConvertPath instead of calling BAZEL_DIE unconditionally: https://cs.opensource.google/bazel/bazel/+/master:src/main/cpp/util/path_windows.cc;l=73

See Lukacs's suggestion here: https://github.com/bazelbuild/bazel/issues/13443#issuecomment-855765933

**Comment by andrewkatson** [comment]
This is invalid and I will open a better one

**Pull request closed without merging**
