### PR TITLE
Fix double encoding of inputs in worker request

### PR DESCRIPTION
**Pull request by fmeum**
Since `WorkRequest` encodes strings as UTF-8, Bazel's internal string encoding of file paths needs to be undone before passing them to the protobuf builder.

### CODE REVIEW

**Comment by fmeum** [comment]
@bazel-io fork 8.0.0

**Comment by fmeum** [comment]
@bazel-io fork 7.4.0

**Comment by meisterT** [comment]
How did this not show up as problematic before?

**Comment by fmeum** [comment]
> How did this not show up as problematic before?

The only worker supplied with Bazel (Javac) doesn't read the field. I don't know whether any worker does. Multiplex sandboxing would probably be a better way to do that.

**Comment by iancha1992** [comment]
The changes in this PR have been included in [Bazel 7.4.1 RC1](https://github.com/bazelbuild/bazel/releases/tag/7.4.1rc1). Please test out the release candidate and report any issues as soon as possible.
If you're using Bazelisk, you can point to the latest RC by setting `USE_BAZEL_VERSION=7.4.1rc1`. Thanks!

**Pull request closed without merging**
