### PR TITLE
Update Windows Install Instructions

### PR DESCRIPTION
**Pull request by spomorski**
Updating Windows install instructions together with David.

### CODE REVIEW

**Comment by laszlocsomor** [comment]
FYI: https://github.com/davidstanke/bazel/pull/1

**Comment by spomorski** [comment]
I know about this one, I made some edits on top of Dave's work last week.
Can we somehow merge them into a single PR?

**Comment by iirina** [comment]
What is the status of this PR?

**Comment by laszlocsomor** [comment]
Waiting for @spomorski to address the conflict errors -- rebase or resolve.

**Comment by spomorski** [comment]
Too many edits are happening around these files simultaneously. Will
revisit once we have cleared up the mess.

**Pull request closed without merging**
